Feature/pipeline generator GitHub
devonfw/hangar pull request #105
Opened 2022-05-20 10:50 UTC by ultymatom

This PR is for the creation of the pipeline generator for github actions.

This also include changes in the pipeline generator for azure, as some funcitons are common I created a lib file

2022-05-20 10:59 UTC, ultymatom commented on scripts/pipelines/github/pipeline_generator.sh
> +        -l | --language)          language=$2; shift 2;;
@sonatype-lift ignore

2022-05-20 10:59 UTC, ultymatom commented on scripts/pipelines/github/pipeline_generator.sh
> +        --sonar-token)            sonarToken=$2; shift 2;;
@sonatype-lift ignore

2022-05-20 10:59 UTC, ultymatom commented on scripts/pipelines/github/pipeline_generator.sh
> +        -u | --registry-user)     dockerUser=$2; shift 2;;
@sonatype-lift ignore

2022-05-20 11:00 UTC, ultymatom commented on scripts/pipelines/github/pipeline_generator.sh
> +        --resource-group)         resourceGroupName=$2; shift 2;;
@sonatype-lift ignore

2022-05-20 11:00 UTC, ultymatom commented on scripts/pipelines/github/pipeline_generator.sh
> +        --storage-container)      storageContainerName=$2; shift 2;;
@sonatype-lift ignore

2022-05-20 11:00 UTC, ultymatom commented on scripts/pipelines/github/pipeline_generator.sh
> +        --s3-bucket)              s3Bucket=$2; shift 2;;
@sonatype-lift ignore

2022-05-20 11:00 UTC, ultymatom commented on scripts/pipelines/github/pipeline_generator.sh
> +        --dockerfile)             dockerFile=$2; shift 2;;
@sonatype-lift ignore

2022-05-20 11:00 UTC, ultymatom commented on scripts/pipelines/github/pipeline_generator.sh
> +        -c | --config-file)       configFile=$2; shift 2;;
@sonatype-lift ignore

2022-05-20 13:03 UTC, ultymatom commented on scripts/pipelines/github/pipeline_generator.sh
> +        --sonar-url)              sonarUrl=$2; shift 2;;
@sonatype-lift ignore

2022-05-20 13:04 UTC, ultymatom commented on scripts/pipelines/github/pipeline_generator.sh
> +        --storage-account)        storageAccountName=$2; shift 2;;
@sonatype-lift ignore

2022-05-20 13:04 UTC, ultymatom commented on scripts/pipelines/github/pipeline_generator.sh
> +        --cluster-name)           clusterName=$2; shift 2;;
@sonatype-lift ignore

2022-05-20 13:04 UTC, ultymatom commented on scripts/pipelines/github/pipeline_generator.sh
> +        --aws-access-key)         awsAccessKey="$2"; shift 2;;
@sonatype-lift ignore

2022-05-20 13:04 UTC, ultymatom commented on scripts/pipelines/github/pipeline_generator.sh
> +        --aws-region)             awsRegion="$2"; shift 2;;
@sonatype-lift ignore

2022-05-20 13:05 UTC, ultymatom commented on scripts/pipelines/github/pipeline_generator.sh
> +        sed -i '/# mark to insert additional artifact input #/d' "${localDirectory}/${pipelinePath}/${yamlFile}"
@sonatype-lift ignore

2022-05-20 13:07 UTC, ultymatom commented on scripts/pipelines/github/pipeline_generator.sh
> +        --aws-secret-access-key)  awsSecretAccessKey="$2"; shift 2;;
@sonatype-lift ignore

2022-05-20 13:07 UTC, ultymatom commented on scripts/pipelines/github/pipeline_generator.sh
> +commonTemplatesPath="scripts/pipelines/github/templates/common"
@sonatype-lift ignore

2022-05-20 13:07 UTC, ultymatom commented on scripts/pipelines/github/pipeline_generator.sh
> +        sed -i '/# mark to insert additional artifact input #/d' "${localDirectory}/${pipelinePath}/${yamlFile}"
@sonatype-lift ignore

2022-05-20 13:08 UTC, ultymatom commented on scripts/pipelines/github/pipeline_generator.sh
> +        grep "    inputs:" ${localDirectory}/${pipelinePath}/${yamlFile} > /dev/null && textArtifactPathInput="      artifactPath:\n       required: false\n       default: ${artifactPath//\//\\/}"
@sonatype-lift ignore

2022-05-20 13:08 UTC, ultymatom commented on scripts/pipelines/github/pipeline_generator.sh
> +        echo -e "${green}No branch specified to do the Pull Request, changes left in the ${sourceBranch} branch."
@sonatype-lift ignore

2022-05-20 13:09 UTC, ultymatom commented on scripts/pipelines/github/pipeline_generator.sh
> +. "$hangarPath/scripts/pipelines/common/pipeline_generator.lib"
@sonatype-lift ignore

2022-05-20 13:09 UTC, ultymatom commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +. "$hangarPath/scripts/pipelines/common/pipeline_generator.lib"
@sonatype-lift ignore

2022-05-20 13:12 UTC, ultymatom commented on scripts/pipelines/github/pipeline_generator.sh
> +        -p | --registry-password) dockerPassword=$2; shift 2;;
@sonatype-lift ignore

2022-05-23 13:29 UTC, ultymatom commented on scripts/pipelines/github/pipeline_generator.sh
> +        -u | --registry-user)     dockerUser=$2; shift 2;;
@sonatype-lift ignore

2022-05-23 13:29 UTC, ultymatom commented on scripts/pipelines/github/pipeline_generator.sh
> +        --resource-group)         resourceGroupName=$2; shift 2;;
@sonatype-lift ignore

2022-05-23 13:29 UTC, ultymatom commented on scripts/pipelines/github/pipeline_generator.sh
> +        --storage-container)      storageContainerName=$2; shift 2;;
@sonatype-lift ignore

2022-05-23 13:29 UTC, ultymatom commented on scripts/pipelines/github/pipeline_generator.sh
> +        --storage-account)        storageAccountName=$2; shift 2;;
@sonatype-lift ignore

2022-06-10 07:10 UTC, ultymatom commented on scripts/pipelines/gitlab/pipeline_generator.sh
> +        --sonar-token)            sonarToken=$2; shift 2;;
@sonatype-lift ignore

2022-06-10 07:10 UTC, ultymatom commented on scripts/pipelines/gitlab/pipeline_generator.sh
> +        --resource-group)         resourceGroupName=$2; shift 2;;
@sonatype-lift ignore

2022-06-15 14:00 UTC, albertdb requested changes

2022-06-15 14:00 UTC, albertdb commented on scripts/pipelines/gitlab/templates/build/quarkus-build.sh
> +#!/bin/bash
This does not belong to this PR.

2022-06-15 14:00 UTC, albertdb commented on scripts/pipelines/gitlab/templates/build/build-pipeline.cfg
> +# Mandatory flags.
This does not belong here nor to this PR.

2022-06-15 14:00 UTC, albertdb commented on scripts/pipelines/gitlab/pipeline_generator.sh
> +#!/bin/bash
This does not belong to this PR and it is a copy-paste from GitHub one.

2022-06-15 14:00 UTC, albertdb commented on scripts/pipelines/github/pipeline_generator.sh
> +function help {
Can't we move help and flag parsing to common? We can create provider specific section and parsing if needed, right?

2022-06-16 07:56 UTC, ultymatom commented on scripts/pipelines/github/pipeline_generator.sh
> +function help {
The problem is that the help function is supposed to be executed before anything if the user ask for it

2022-06-16 08:06 UTC, ultymatom commented on scripts/pipelines/github/pipeline_generator.sh
> +function help {
my bad we can do it, and it's done

2022-06-16 09:48 UTC, albertdb approved these changes

2022-06-20 14:18 UTC, albertdb approved these changes

2022-06-20 14:18 UTC, merged