Feature/create-repo-github
devonfw/hangar pull request #109
Opened 2022-05-25 10:53 UTC by mcerverc

2022-05-25 10:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw/hangar?pullRequest=109) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/devonfw/hangar?pullRequest=109) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw/hangar?pullRequest=109) it.</sub>

2022-05-26 13:59 UTC, ultymatom commented on scripts/repositories/common/create-repo.sh
> +      fi
Are you sure it is better to do policy by policy and inside them checking the target ?
and not better to do one big block for azure with all the policies, another one for github ?
because for example in azure you have a paremeter which allows you to enable or not this policy, so it would be less lines and I think easier to read.
Also I think it is easier to update for a new provider if you just have to add a block for that provider, instead of adding many mini blocks for that new provider

Also your switching between using $7 and $target  (but this I think I also did it a lot^^)

2022-06-23 14:45 UTC, ultymatom approved these changes

2022-06-23 16:04 UTC, ultymatom submitted a review, later dismissed

2022-06-23 16:23 UTC, albertdb requested changes

2022-06-23 16:23 UTC, albertdb commented on documentation/github/setup-repository-script.asciidoc
> +
```suggestion
* A GitHub user.

```

2022-06-23 16:23 UTC, albertdb commented on documentation/github/setup-repository-script.asciidoc
> +* Limit merge types: OFF
```suggestion
* Require a pull request before merging: ON
** Require approvals: 1
** Dismiss stale pull request approvals when new commits are pushed: ON
* Require conversation resolution before merging: ON
```

2022-06-23 16:23 UTC, albertdb commented on documentation/github/setup-repository-script.asciidoc
> +You can find more information about branch policies in the https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops[official documentation].
```suggestion
You can find more information about branch protection rules in the https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches[official documentation].
```

2022-06-23 16:23 UTC, albertdb commented on documentation/github/setup-repository-script.asciidoc
> +NOTE: This is the bare minimum standard for any project. We do not prohibit the most recent pusher from approving their own changes, although being more than recommendable, because if we do, it will
```suggestion
NOTE: This is the bare minimum standard for any project.
```

2022-06-23 16:23 UTC, albertdb commented on documentation/github/setup-repository-script.asciidoc
> +It is possible to protect important branches against bad practices using branch policies.
```suggestion
It is possible to protect important branches against bad practices using branch protection rules.
```

2022-06-23 16:23 UTC, albertdb commented on documentation/github/setup-repository-script.asciidoc
> +The following branch policies are applied to `master` and `develop` branches:
```suggestion
The following branch protection rules are applied to `master` and `develop` branches:
```

2022-06-23 16:27 UTC, albertdb approved these changes

2022-06-23 16:27 UTC, merged