Feature/Test pipeline for Github
devonfw/hangar pull request #110
Opened 2022-05-26 14:36 UTC by jbellver99

2022-05-26 15:11 UTC, ultymatom commented on scripts/pipelines/github/templates/test/test-pipeline.yml.template
> +  build_pipeline: ${{ github.event.name == 'workflow_run' && format('$buildPipelineName') || github.event.inputs.build_pipeline }}
Here you don't need to define the env variable with conditions, because it is not an input for manual execution

2022-05-26 15:12 UTC, ultymatom commented on scripts/pipelines/github/templates/test/test-pipeline.yml.template
> +  build_pipeline: ${{ github.event.name == 'workflow_run' && format('$buildPipelineName') || github.event.inputs.build_pipeline }}
because in case of manual execution the var will be empty

2022-05-26 15:13 UTC, ultymatom commented on scripts/pipelines/github/templates/test/test-pipeline.yml.template
> +
```suggestion

    # mark to insert step for additonal artifact #
```

For adding the step exactly here to upload addtional artifact

2022-06-10 12:35 UTC, ultymatom commented on scripts/pipelines/github/templates/test/test-pipeline.yml.template
> +    types: completed
with the ci_pipeline we need to change this trigger
```suggestion
  workflow_call:
```

2022-06-10 12:42 UTC, ultymatom commented on scripts/pipelines/github/templates/test/test-pipeline.yml.template
> +          uses: andymckay/cancel-action@0.2
```suggestion
```

Not needed anymore as we use the CI_pipeline

2022-06-10 12:42 UTC, ultymatom commented on scripts/pipelines/github/templates/test/test-pipeline.yml.template
> +      if: ${{ github.event.workflow_run.conclusion == 'success' }}
```suggestion
```

not needed anymore as we use the CI_pipeline

2022-06-10 12:43 UTC, ultymatom commented on scripts/pipelines/github/templates/test/test-pipeline.yml.template
> +    on-success:
maybe name to be change as we use the ci_pipeline and does do a on success/on failure

2022-06-14 09:12 UTC, ultymatom commented on scripts/pipelines/github/templates/test/test-pipeline.yml.template
> +          files: '**/TEST-*.xml'
I confirm, indentation must be changed (everything under step needs 2 more spaces
except the mark for the additional artifact that needs to be without any indentation

2022-06-15 09:34 UTC, ultymatom commented on documentation/github/setup-test-workflow.asciidoc
> +In this section we will create a test workflow on Github Actions for running project test cases. This workflow will be configured in order to be triggered every time the build workflow is executed su
Maybe change the triggering part, as now it is configured to be executed manually or inside or ci pieline

2022-06-15 09:34 UTC, ultymatom commented on documentation/github/setup-test-workflow.asciidoc
> +  --build-pipeline-name <build pipeline name> \
now build pipeline name is not used anymore

2022-06-15 09:34 UTC, ultymatom commented on documentation/github/setup-test-workflow.asciidoc
> +    --build-pipeline-name   [Required] Build pipeline name.
build pipeline name not used anymore

2022-06-15 09:35 UTC, ultymatom commented on documentation/github/setup-test-workflow.asciidoc
> +    --build-pipeline-name   [Required] Build pipeline name.
```suggestion
```

2022-06-15 09:35 UTC, ultymatom commented on documentation/github/setup-test-workflow.asciidoc
> +In this section we will create a test workflow on Github Actions for running project test cases. This workflow will be configured in order to be triggered every time the build workflow is executed su
```suggestion
In this section we will create a test workflow on Github Actions for running project test cases. This workflow will be configured in order to be executed manually or  inside a CI workflow (see documentation about the CI workflow for more info: <link to it when it will be done>), and consumes the artifact produced by the build workflow.

```

2022-06-15 09:36 UTC, ultymatom commented on documentation/github/setup-test-workflow.asciidoc
> +In this section we will create a test workflow on Github Actions for running project test cases. This workflow will be configured in order to be triggered every time the build workflow is executed su
not totally sure for the suggestion

2022-06-15 09:36 UTC, ultymatom commented on scripts/pipelines/github/templates/test/test-pipeline.cfg
> +mandatoryFlags="$pipelineName,$localDirectory,$language,$buildPipelineName,"
```suggestion
mandatoryFlags="$pipelineName,$localDirectory,$language,"
```

2022-06-15 09:44 UTC, ultymatom commented on scripts/pipelines/github/templates/test/test-pipeline.yml.template
> +  build_pipeline: 'build-pipeline.yml'
```suggestion
  build_pipeline: 'build-pipeline.yml'
  ciPipelineYamlName: 'ci-pipeline.yml'
```

for the download part

2022-06-30 13:33 UTC, ultymatom submitted a review, later dismissed

2022-07-06 11:30 UTC, albertdb requested changes

2022-07-06 11:36 UTC, albertdb commented on documentation/src/common_templates/setup-test-pipeline.asciidoc
> +./pipeline_generator.sh -c ./templates/test/test-pipeline.cfg -n node-project-test -l node -a ./.pipelines/target/ -d C:/Users/$USERNAME/Desktop/node-project {extra_args_node} -b develop -w
```suggestion
./pipeline_generator.sh -c ./templates/test/test-pipeline.cfg -n node-project-test -l node -d C:/Users/$USERNAME/Desktop/node-project {extra_args_node} -b develop -w
```

2022-07-06 11:36 UTC, albertdb commented on documentation/src/common_templates/setup-test-pipeline.asciidoc
> +./pipeline_generator.sh -c ./templates/test/test-pipeline.cfg -n angular-project-test -l angular -a ./.pipelines/target/ -d C:/Users/$USERNAME/Desktop/node-project {extra_args_angular} -b develop -w
```suggestion
./pipeline_generator.sh -c ./templates/test/test-pipeline.cfg -n angular-project-test -l angular -d C:/Users/$USERNAME/Desktop/node-project {extra_args_angular} -b develop -w
```

2022-07-06 12:45 UTC, merged