Feature/quality pipeline GitHub
devonfw/hangar pull request #111
Opened 2022-05-26 15:01 UTC by ultymatom

Adding the quality workflow for github

2022-05-26 15:05 UTC, ultymatom commented
Draft for two reason:

- Waiting for github pipeline generator PR to be merged
- waiting for the quality for devon4node PR to be merged also

2022-07-06 13:31 UTC, albertdb requested changes

2022-07-06 13:31 UTC, albertdb commented on documentation/src/azure-devops/setup-quality-pipeline.asciidoc
> +:provider: Azure Devops
```suggestion
:provider: Azure DevOps

```

2022-07-06 13:31 UTC, albertdb commented on documentation/src/github/setup-quality-pipeline.asciidoc
> +:provider: Github
```suggestion
:provider: GitHub

```

2022-07-06 13:31 UTC, albertdb commented on documentation/src/github/setup-quality-pipeline.asciidoc
> +:trigger_sentence: This workflow will be configured to be executed inside a CI pipeline after the test or build workflow
```suggestion
:trigger_sentence: This workflow will be configured to be executed inside a CI pipeline after the test (or build, if no test) workflow

```

2022-07-06 13:31 UTC, albertdb commented on documentation/src/github/setup-quality-pipeline.asciidoc
> +:pipeline_type2: Github action
```suggestion
:pipeline_type2: GitHub action

```

2022-07-06 13:31 UTC, albertdb commented on scripts/pipelines/github/templates/quality/quality-pipeline.yml.template
> +      - name: Download artifact from this workflow
```suggestion
      - name: Download artifact from build job (current workflow)
```

2022-07-06 13:31 UTC, albertdb commented on scripts/pipelines/github/templates/quality/quality-pipeline.yml.template
> +      - name: Download artifact from build pipeline
```suggestion
      - name: Download artifact from build workflow
```

2022-07-06 13:31 UTC, albertdb commented on scripts/pipelines/github/templates/quality/quality-pipeline.yml.template
> +      - name: Download artifact from ci pipeline
```suggestion
      - name: Download artifact from CI workflow
```

2022-07-06 13:33 UTC, albertdb commented on documentation/src/azure-devops/setup-quality-pipeline.asciidoc
> +
```suggestion
```

2022-07-06 14:10 UTC, albertdb commented on documentation/src/github/setup-quality-pipeline.asciidoc
> +
```suggestion
```

2022-07-06 14:10 UTC, albertdb commented on documentation/src/github/setup-quality-pipeline.asciidoc
> +
```suggestion
```

2022-07-06 14:12 UTC, albertdb approved these changes

2022-07-06 14:14 UTC, merged