suppressed maven logs
devonfw/hangar pull request #140
Opened 2022-06-17 10:01 UTC by BenjaminE98

Closes #131 

simple output-log cleanup (suppresses unnecessary logs)

2022-06-22 07:54 UTC, shiftwolf commented on scripts/pipelines/azure-devops/templates/test/quarkus-test.sh
> +mvn test -B -Dmaven.install.skip=true -Pnative
Is there a reason to not set this to --quiet unlike the others?

2022-06-27 15:51 UTC, albertdb requested changes
`--quiet` is too quiet.

2022-06-27 15:51 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/build/quarkus-build.sh
> +mvn package --quiet -B -Pnative
```suggestion
mvn package -B -Pnative
```

2022-06-27 15:51 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/build/quarkus-jvm-build.sh
> +mvn package --quiet -B
```suggestion
mvn package -B
```

2022-06-27 15:51 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/library-package/java-library-package.sh
> +mvn deploy --quiet -B -Dmaven.install.skip=true -Dmaven.test.skip=true --settings $settings_path
```suggestion
mvn deploy -B -Dmaven.install.skip=true -Dmaven.test.skip=true --settings $settings_path
```

2022-06-27 15:51 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/test/quarkus-jvm-test.sh
> +mvn test --quiet -B -Dmaven.install.skip=true
```suggestion
mvn test -B -Dmaven.install.skip=true
```

2022-06-27 15:52 UTC, albertdb approved these changes

2022-06-27 15:52 UTC, merged