Feature/block3
devonfw/hangar pull request #16
Opened 2021-10-21 13:56 UTC by ultymatom

2021-11-04 11:04 UTC, jbellver99 requested changes
Check the document for spelling mistakes and capital letters in order for it to be more consistent.
Add more explanations about the part on creating the required branches in order to keep the workflow of gitflow. Remember that what this is trying to achieve is to clone a reference repo, create the necessary branches and push them into Azure.

2021-11-04 12:00 UTC, albertdb commented on documentation/guide-azure-script_repository-creation.asciidoc
> +== II. Commands used in this script
Maybe some parts  could be reused for the manual guide o some explanation reused for the scripts (although it's 
 probably already verbose enough).

2021-11-04 12:01 UTC, albertdb commented on documentation/guide-azure-script_repository-creation.asciidoc
> +=== A. 1st case
Yes, as long as the script tells the user what is doing, there's no need to explain step by step what the script does. User dig into the script code if interested in knowing the internals.

2021-11-05 09:06 UTC, jbellver99 requested changes

2021-11-05 09:06 UTC, jbellver99 commented on documentation/tutorial-azure-manual-repository-creation.asciidoc
> +All the actions will be done manually with the web interface, if you want to use command line or a script that automatize these steps, check this documentation: *'guide-azure-script-repository-creati
```suggestion
All the actions will be done manually with the web interface, if you want to use command line or a script that automatize these steps, check the following guide.

```

Add link to the other guide.

2021-11-05 09:06 UTC, jbellver99 commented on documentation/tutorial-azure-manual-repository-creation.asciidoc
> +When you create a new project, an empty repository already exists. +
```suggestion
When you create a new project, an empty repository is created. +

```

2021-11-05 09:06 UTC, jbellver99 commented on documentation/tutorial-azure-manual-repository-creation.asciidoc
> +To acces it, click on `Repos` on the left pannel of the home page and will get this page:
```suggestion
To access it, click on `Repos` on the left panel of the home page and will get this page:

```

2021-11-05 09:06 UTC, jbellver99 commented on documentation/tutorial-azure-manual-repository-creation.asciidoc
> +Now you are on this page, 4 possibilities are available.
```suggestion
Now that you are on this page, 4 possibilities are available.

```

2021-11-05 09:06 UTC, jbellver99 commented on documentation/tutorial-azure-manual-repository-creation.asciidoc
> +  B: You can push an existing local repository to your project
```suggestion
  B: You can push an existing local repository to your project.

```

2021-11-05 09:06 UTC, jbellver99 commented on documentation/tutorial-azure-manual-repository-creation.asciidoc
> +  C: You can import an existing online repository with the url
```suggestion
  C: You can import an existing online repository with the url.

```

2021-11-05 09:06 UTC, jbellver99 commented on documentation/tutorial-azure-manual-repository-creation.asciidoc
> +  D: You can initialize your repository with a 'main' branch
```suggestion
  D: You can initialize your repository with a 'main' branch.

```

2021-11-05 09:06 UTC, jbellver99 commented on documentation/tutorial-azure-manual-repository-creation.asciidoc
> +Your folder has now been converted into a git repository and you have your first branch
```suggestion
Your folder has now been converted into a git repository and you have your first branch.

```

2021-11-05 09:06 UTC, jbellver99 commented on documentation/tutorial-azure-manual-repository-creation.asciidoc
> +WARNING: As it just imports the content, modification made on your azure repository will not affect the initial git repository you imported
```suggestion
WARNING: As it just imports the content, modifications made on your azure repository will not affect the initial git repository you imported.

```

2021-11-05 09:06 UTC, jbellver99 commented on documentation/tutorial-azure-manual-repository-creation.asciidoc
> +First you need to get the url of your repository (here is an example with a repository from github)
```suggestion
First you need to get the url of your repository (here is an example with a repository from github).

```

2021-11-05 09:06 UTC, jbellver99 commented on documentation/tutorial-azure-manual-repository-creation.asciidoc
> +Then you can import it in your azure project
```suggestion
Then  import it in your azure project.

```

2021-11-05 09:06 UTC, jbellver99 commented on documentation/tutorial-azure-manual-repository-creation.asciidoc
> +You can now see the that all your branches and files have been imported
```suggestion
You can now see the that all your branches and files have been imported.

```

2021-11-05 09:06 UTC, jbellver99 commented on documentation/tutorial-azure-manual-repository-creation.asciidoc
> +The `gitignore` file list all type of file that needs to be ignore when commiting, for example if there are artefacts generated by builds you do not want to commit
```suggestion
The `gitignore` file list all type of file that needs to be ignore when committing, for example if there are artefacts generated by builds you do not want to commit.

```

2021-11-05 09:06 UTC, jbellver99 commented on documentation/tutorial-azure-manual-repository-creation.asciidoc
> +NOTE: You can modify/delete the two files after initializing your repository
```suggestion
NOTE: You can modify/delete the two files after initializing your repository.

```

2021-11-05 09:06 UTC, jbellver99 commented on documentation/tutorial-azure-manual-repository-creation.asciidoc
> +If you untick this box, it will create an empty repository, in this case you can follow the steps of A, B, C or D of the part I. because your repository will be in the same state as what we saw previ
```suggestion
If you untick this box, it will create an empty repository, in this case you can follow the steps of A, B, C or D of part I. because your repository will be in the same state as what we saw previously.

```

2021-11-05 09:06 UTC, jbellver99 commented on documentation/tutorial-azure-manual-repository-creation.asciidoc
> +Then you just need to put the URL of the repository you want to import qnd choose the name of the repository that will be created.
```suggestion
Then you just need to put the URL of the repository you want to import and choose the name of the repository that will be created.

```

2021-11-05 10:31 UTC, ultymatom commented on documentation/guide-azure-script-repository-creation.asciidoc
> +This Guide is made to be able to create repository with command line and automatically, if you prefer using the Azure web interface, you can follow the guide under the name: *'tutorial-azure-manual-r
It is because I'm doing reference about the other guide, in the other guide I'm making reference with this one

2021-11-05 10:38 UTC, ultymatom commented on documentation/guide-azure-script-repository-creation.asciidoc
> +==== Additional information
It is additional informations for the arguments, that's why I put it with 4 =

2021-11-05 10:43 UTC, ultymatom commented on documentation/guide-azure-script-repository-creation.asciidoc
> +This command has created a repository on Azure, it imported a sample repository of an application and then created the branches and policies.
It does not always import a sample repository, depends if the user ask it or no.

2021-11-05 11:47 UTC, ultymatom commented on documentation/guide-azure-script-repository-creation.asciidoc
> +This command has created a repository on Azure, it imported a sample repository of an application and then created the branches and policies.
sorry i misrode, you re right^^

2021-11-08 08:49 UTC, jbellver99 requested changes

2021-11-08 08:49 UTC, jbellver99 commented on documentation/guide-azure-script-repository-creation.asciidoc
> +This Guide is made to be able to create repository with command line and automatically, if you prefer using the Azure web interface, you can follow this guide link:tutorial-azure-manual-repository-cr
Check link, it is not working.

2021-11-08 08:49 UTC, jbellver99 commented on documentation/tutorial-azure-manual-repository-creation.asciidoc
> +All the actions will be done manually with the web interface, if you want to use command line or a script that automatize these steps, check this documentation: *'guide-azure-script-repository-creati
Add the link to the other documentation

2021-11-11 12:48 UTC, albertdb requested changes
Rework use cases as discussed on meeting.

2021-11-11 12:48 UTC, albertdb commented on documentation/azure-devops/setup-repository-script.asciidoc
> +  - 3rd case: Convert a local folder into a git repository, then push this repository to your Azure project, works also if your folder is already a git repository, if it is just a local git repositor
```suggestion
1. Create an empty repository with just a README file and clone it to your computer into the directory you set (you can also use a sample application instead of an empty repository).

2. Import an existing git repository into your project, then clone this repo on your computer into the directory you set.

3. Convert a local folder into a git repository, then push this repository to your Azure project, works also if your folder is already a git repository, if it is just a local git repository it will add the remote origin url, if your git repository already has one configured, it will ask a confirmation to change it.
```

Please use proper Asciidoc syntax, and use uppercase when writing product names. Also, Azure is not the same as Azure DevOps.

2021-12-14 15:24 UTC, jbellver99 requested changes

2021-12-14 15:24 UTC, jbellver99 commented on documentation/azure-devops/setup-repository-script.asciidoc
> +  /path/to/script/create_repo.bash -a 'create' -d /path/to/directory -o https://dev.azure.com/azure_organization -p azure_project -n repository_azure -s
```suggestion
  ./create_repo.bash -a 'create' -d <path to directory> -o https://dev.azure.com/<organization> -p <azure project> -n <repository name> -s

```

2021-12-14 15:24 UTC, jbellver99 commented on documentation/azure-devops/setup-repository-script.asciidoc
> +NOTE: Importing a Git repository into Azure DevOps just imports the content (branchs, files ...), but once the repository is imported there is no link between them , any modification made on the orig
```suggestion
===== Subcase a +
  ./create_repo.bash -a 'import' -d <path to directory> -o  https://dev.azure.com/<organization> -p <project name> -n <repository name> -g <git url>

This will import all the content of the repository stored at that URL `<git url>` under the name *<repository name>*, if no name is set, the repository will be imported under the name *repository* (it uses the URL to know the name). +
Then the repository is cloned inside the folder *<path to directory>*. +

NOTE: Importing a Git repository into Azure DevOps just imports the content (branchs, files ...), but once the repository is imported there is no link between them, any modification made on the original repo will not apply on your Azure DevOps project (and the other way around is also true). +

```

2021-12-14 15:24 UTC, jbellver99 commented on documentation/azure-devops/setup-repository-script.asciidoc
> +
```suggestion
===== Subcase c: +
  ./create_repo.bash -a 'import' -d <path to directory> -o https://dev.azure.com/<organization> -p <project name> -n <repository name>

If your folder *<path to directory>* is just a folder, it will convert it into a Git repository, push it to your Azure DevOps project and create *master* and *develop* branches. +
If your folder is a local Git repository, it will just push it to your Azure DevOps project. +
If your folder is an online Git repository, it will change the remote URL so that future commits will be pushed into your Azure DevOps repository but not on the one already configured, and it will push all your branches at the new URL. +


```

2021-12-14 15:24 UTC, jbellver99 commented on documentation/azure-devops/setup-repository-script.asciidoc
> +
```suggestion
```

2022-03-16 18:26 UTC, albertdb requested changes
Please review in deep all the comments and suggestions to have an overall idea, there are quite a few changes to be taken to the script.

2022-03-16 18:26 UTC, albertdb commented on documentation/azure-devops/setup-repository-script.asciidoc
> +NOTE: You should never commit directly on *develop* or *master*, modifications on *develop* should only come from merge of feature branches and modifications on *master* should only come from merge o
```suggestion
=== Gitflow

This is not an explanation of Gitflow (there are plenty of them on the web), but the actions performed by the script to help you start using this worflow.

==== Branches

* `master` is the initial (seed) branch. 
* `develop` branch is created from `master` branch.

Any other branch part the strategy (feature, release, and hotfix branches) will be created by developers during the lifecycle of the project.
```

We should not create the example feature branch, could be annoying for the user if a dozen a repos are created.

2022-03-16 18:26 UTC, albertdb commented on documentation/azure-devops/setup-repository-script.asciidoc
> +https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops&tabs=browser
```suggestion
==== Policies

You can define policies on your branches so you can secure them from commits not following certain rules. For example you can block squash merge.

Here are the policies we use as templates.

For the *develop* and *master* branch we have limited the type of merge that can be done.

==== master

image::master_policy.PNG[]

==== develop

image::develop_policy.PNG[]

==== Additional link

There are many other parameters you can use to define your branches policy, if you need to modify it, here is a link with more information about it. +
https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops&tabs=browser

```
This is VERY opinionated, we should discuss which "consensual" policies to apply. It is a shame that Azure DevOps does not support restricting which branches can merge to others.

2022-03-22 11:20 UTC, ultymatom commented on documentation/azure-devops/setup-repository-script.asciidoc
> +  -o (for organization) : URL of your Azure DevOps organization (mandatory)
done, need test to validate

2022-03-22 11:20 UTC, ultymatom commented on documentation/azure-devops/setup-repository-script.asciidoc
> +  -b (for branch) :       If you mention this parameter it will be used in the case you used the action 'import, it will import your repository as is but will create a master and develop branch from
develop created only when -s is provided, need test before resolve

2022-03-22 11:21 UTC, ultymatom commented on documentation/azure-devops/setup-repository-script.asciidoc
> +  -r (for remove) :       If you gave a branch as reference when importing an existing git repository, it will delete all other branches (except master and develop).
done but still need test

2022-03-22 11:21 UTC, ultymatom commented on documentation/azure-devops/setup-repository-script.asciidoc
> +  -s (for strategy) :     Set this flag if you want the script to create branch policies with the template this script uses.
done but need test

2022-03-22 11:31 UTC, ultymatom commented on documentation/azure-devops/setup-repository-script.asciidoc
> +
code behind changed, need to validate

2022-03-22 11:33 UTC, ultymatom commented on documentation/azure-devops/setup-repository-script.asciidoc
> +NOTE: `-r` and `-s` are independent, you can use one without the other it will not affect their use, but they are both dependent to `-b`.
with "NOTE: Same command could also be used with a local directory, but then using `-b` and `-r` would be redundant." did you mean if we gave a giturl instead of lecal repo instead ?

2022-03-22 11:35 UTC, ultymatom commented on documentation/azure-devops/setup-repository-script.asciidoc
> +https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops&tabs=browser
I created policies as template but yes sure we should so a meeting about it to define them

2022-03-22 16:40 UTC, albertdb commented on documentation/azure-devops/setup-repository-script.asciidoc
> +NOTE: `-r` and `-s` are independent, you can use one without the other it will not affect their use, but they are both dependent to `-b`.
No, I mean passing a local (not yet Git) directory instead of local Git repository, those flags wouldn't do anything.

2022-03-29 09:56 UTC, albertdb requested changes

2022-03-29 09:56 UTC, albertdb commented on scripts/repositories/azure-devops/create_repo.bash
> +  echo -e "${blue}Here are all the information about the repository you just created, you can save it in a json file if you feel the need."
```suggestion
```

2022-03-29 09:56 UTC, albertdb commented on scripts/repositories/azure-devops/create_repo.bash
> +  MSG_ERROR  "Importing sample repository"  $?
Sample?

2022-03-29 09:56 UTC, albertdb commented on scripts/repositories/azure-devops/create_repo.bash
> +        echo 'Your input is not valid, Press Y to confirm and N to cancel:'
```suggestion
        echo 'Your input is not valid, Press Y to confirm or N to cancel:'
```

2022-03-29 09:56 UTC, albertdb commented on scripts/repositories/azure-devops/create_repo.bash
> +        echo "Type 'Y' to validate and 'N' to exit the script. (You can use -f flag to skip user confirmation on next executions)"
```suggestion
        echo "Type 'Y' to validate or 'N' to exit the script. (You can use -f flag to skip user confirmation on next executions)"
```

2022-03-29 09:56 UTC, albertdb commented on scripts/repositories/azure-devops/create_repo.bash
> +# When using git init, the branch created will be the one you definie with this command 'git config --global init.defaultBranch <branch>', we checkout to master in case the default one of the user is
```suggestion
# When using git init, the branch created will be the one you defined with this command 'git config --global init.defaultBranch <branch>', we checkout to master in case the default one of the user is different

```

2022-03-29 09:56 UTC, albertdb commented on scripts/repositories/azure-devops/create_repo.bash
> +    echo "There is already a URL set for the remote repository ($giturl_azure_repo), this script will change this URL so that all the next commits you will push will be done on the azure repository b
```suggestion
    echo "There is already a remote origin configured for this repository: ($giturl_azure_repo). This will be change by the new Azure DevOps repository. Press Y to confirm or N to cancel:"

```

2022-03-29 09:56 UTC, albertdb commented on scripts/repositories/azure-devops/create_repo.bash
> +    echo -e "${red}You chose the action 'create' but one of these parameters is null but they are mandatory: -n, -d, -o, -p"
```suggestion
    echo -e "${red}You chose the action 'create' but one of these mandatory flags is missing: -n, -d, -o, -p."

```

2022-03-29 09:56 UTC, albertdb commented on scripts/repositories/azure-devops/create_repo.bash
> +    echo "you can type -h to get more information about the script"
```suggestion
    echo "Use -h or --help flag to display help."

```

2022-03-29 09:56 UTC, albertdb commented on scripts/repositories/azure-devops/create_repo.bash
> +    echo -e "${white}you can type -h to get more information about the script"
```suggestion
    echo -e "${white}Use -h or --help flag to display help."
```

2022-03-29 09:56 UTC, albertdb commented on scripts/repositories/azure-devops/create_repo.bash
> +    echo -e "${red}You chose the action 'import' but one of these parameters is null but they are mandatory: -d, -o, -p, -g"
```suggestion
    echo -e "${red}You chose the action 'import' but one of these mandatory flags is missing: -d, -o, -p, -g"

```

2022-03-29 09:56 UTC, albertdb commented on scripts/repositories/azure-devops/create_repo.bash
> +  echo -e "${white}you can type -h to get more information about the script"
```suggestion
  echo -e "${white}Use -h or --help flag to display help."

```

2022-03-29 09:56 UTC, albertdb commented on scripts/repositories/azure-devops/create_repo.bash
> +  echo -e "${red}The parameter -a is not set or not set correctly, its value can be 'import' or 'create'"
```suggestion
  echo -e "${red}The flag -a is not set or invalid. Accepted values are 'import' and 'create'."

```

2022-03-29 09:56 UTC, albertdb commented on scripts/repositories/azure-devops/create_repo.bash
> +  echo -e "${blue}As you put the 's' flag we set the branch policies corresponding to $5."
```suggestion
  echo -e "${blue}According to -s flag we set the branch policies corresponding to $5."

```

2022-03-29 09:56 UTC, albertdb commented on scripts/repositories/azure-devops/create_repo.bash
> +  echo -e "Charging the properties for the strategy you choose."
```suggestion
  echo -e "Loading the properties for the strategy you chose."

```

2022-03-29 10:28 UTC, ultymatom commented on scripts/repositories/azure-devops/create_repo.bash
> +  az repos update --organization ${1} --project "$2" --repository "$4" --default-branch master &> /dev/null
it is just that I replace all "> /dev/null", and I did not think of that^^, my bad, Iam correcting that

2022-03-29 10:29 UTC, ultymatom commented on scripts/repositories/azure-devops/create_repo.bash
> +  az repos import create --git-url $1 --organization ${2} --project "$3" --repository $4 &> /dev/null
I replaced all "> /dev/null", but I forgot that it did not have to be like this for everything

2022-03-29 10:30 UTC, ultymatom commented on scripts/repositories/azure-devops/create_repo.bash
> +  MSG_ERROR  "Importing sample repository"  $?
forgot to delete that line, it was from before where there was an option to import a sample repo but we removed that

2022-03-29 10:39 UTC, ultymatom commented on scripts/repositories/azure-devops/create_repo.bash
> +      git branch -D $i &> /dev/null
I was hiding it because before I was doing a git "branch -a", to get the list of the branches, and so remotes branches appeared, but as we changed before the remote URL, they did not exist anymore on the new URL, so I redirected stderr to don't show it, but I can remove it now

2022-03-29 10:40 UTC, ultymatom commented on scripts/repositories/azure-devops/create_repo.bash
> +  git rev-parse --git-dir &> /dev/null
Here it makes sense, because this command return an error if this is not a git repository, and that why I am executing this command, to know if this is already a git repo or not (I get the return code the line just after), but I don't want the error message to appear

2022-03-29 10:45 UTC, ultymatom commented on scripts/repositories/azure-devops/create_repo.bash
> +  git config --get remote.origin.url &> /dev/null
I thought that as for the command to check if it is repo, there would be an erro I put it, but apparently no

2022-03-29 10:47 UTC, ultymatom commented on scripts/repositories/azure-devops/create_repo.bash
> +    echo "There is already a URL set for the remote repository ($giturl_azure_repo), this script will change this URL so that all the next commits you will push will be done on the azure repository b
I'm commiting a changes after adding it to the batch:
"This will be changed to the"

2022-03-29 10:47 UTC, ultymatom commented on scripts/repositories/azure-devops/create_repo.bash
> +            if echo $line  | grep $SECTION &> /dev/null ; then
same as the one before, I am removing it

2022-03-29 11:54 UTC, albertdb requested changes

2022-03-29 11:54 UTC, albertdb commented on documentation/azure-devops/setup-repository-script.asciidoc
> +      [-n <name of the repo>] \
```suggestion
      [-n <repository name>] \
```

2022-03-29 11:54 UTC, albertdb commented on documentation/azure-devops/setup-repository-script.asciidoc
> +  -f, --force        Skips any user confirmation.
Fix indentation and style (required instead of mandatory, within brackets and as prefix)

2022-03-29 11:54 UTC, albertdb commented on documentation/azure-devops/setup-repository-script.asciidoc
> +  -f, --force        Skips any user confirmation.
Also, remove spaces at the beggining.

2022-03-29 13:04 UTC, albertdb requested changes
Sorry for being picky, but this is introduced in last commit.

2022-03-29 13:04 UTC, albertdb commented on documentation/azure-devops/setup-repository-script.asciidoc
> +-f, --force                             Skips any user confirmation.
Fix double space between Required and flag description.

2022-03-29 13:25 UTC, albertdb commented on documentation/azure-devops/setup-repository-script.asciidoc
> +-o, --org                   [Required] Name of the Azure DevOps organization (mandatory).
```suggestion
-o, --org                   [Required] Name of the Azure DevOps organization.

```

2022-03-31 09:51 UTC, albertdb requested changes

2022-03-31 09:51 UTC, albertdb commented on documentation/azure-devops/setup-repository-script.asciidoc
> +
```suggestion
```

2022-03-31 09:51 UTC, albertdb commented on documentation/azure-devops/setup-repository-script.asciidoc
> +https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops&tabs=browser
```suggestion
In Azure DevOps it is possible to protect important branches against bad practices using branch policies.

The following branch policies are applied to `master` and `develop` branches:

* Require a minimum number of reviewers: ON
** Minimum number of reviewers: 1
** Allow requestors to approve their own changes: ON
** Prohibit the most recent pusher from approving their own changes: OFF
** Allow completion even if some reviewers vote to wait or reject: OFF
** When new changes are pushed: Reset all approval votes (does not reset votes to reject or wait)
* Check for linked work items: OFF
* Check for comment resolution: REQUIRED
* Limit merge types: OFF

The above policies are defined in a configuration file located at `/scripts/repositories/azure-devops/config/strategy.cfg`. Feel free to adapt it to your needs.

NOTE: This is the bare minimum standard for any project. We do not prohibit the most recent pusher from approving their own changes, although being more than recommendable, because if we do, it will block the auto-approval of Pull Requests generated during pipelines creation on the following guides.

You can find more information about branch policies in the https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops[official documentation].
```

2022-03-31 09:51 UTC, albertdb commented on documentation/azure-devops/setup-repository-script.asciidoc
> += Setting up a repository on Azure DevOps using script
```suggestion
= Setting up a repository on Azure DevOps
```

2022-04-01 09:09 UTC, albertdb requested changes

2022-04-01 09:09 UTC, albertdb commented on scripts/repositories/azure-devops/create-repo.sh
> +   cd "$old_path"
What's the point of this? When you exit a script, the path remains the same as before running it.

2022-04-01 09:09 UTC, albertdb commented on scripts/repositories/azure-devops/create-repo.sh
> +    git checkout -b $i
```suggestion
    git checkout -b "$i"
```

2022-04-01 09:09 UTC, albertdb commented on scripts/repositories/azure-devops/create-repo.sh
> +    git push --set-upstream origin $i
```suggestion
    git push --set-upstream origin "$i"
```

2022-04-01 09:09 UTC, albertdb commented on scripts/repositories/azure-devops/create-repo.sh
> +  az repos update --organization ${1} --project "$2" --repository "$4" --default-branch master > /dev/null
```suggestion
  az repos update --organization "$1" --project "$2" --repository "$4" --default-branch master > /dev/null
```

2022-04-01 09:13 UTC, ultymatom commented on scripts/repositories/azure-devops/create-repo.sh
> +   cd "$old_path"
no when we exit a script we stay in the repo we have done the cd in the script

2022-04-01 09:13 UTC, ultymatom commented on scripts/repositories/azure-devops/create-repo.sh
> +    git checkout -b $i
hecho ya

2022-04-01 09:18 UTC, ultymatom commented on scripts/repositories/azure-devops/create-repo.sh
> +    git push --set-upstream origin $i
ya hecho

2022-04-01 09:26 UTC, albertdb requested changes

2022-04-01 09:26 UTC, albertdb commented on scripts/repositories/azure-devops/create-repo.sh
>  #We save the path from where the script is executing to cd there back at the end of the script
Remove comment

2022-04-01 10:06 UTC, albertdb approved these changes

2022-04-01 10:22 UTC, jbellver99 approved these changes

2022-04-01 10:24 UTC, merged