Feature/azure aks provision
devonfw/hangar pull request #175
Opened 2022-07-14 10:28 UTC by prathibhapadma

AKS provisioning pipeline with common variable group in Azure devops

2022-07-14 13:22 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/common/kubernetes/update-variable-group.sh
> +variablegroup=$(az pipelines variable-group list --organization "$1" --project "$2" --group-name "$3" --query '[0].name' -o  json)
@sonatype-lift ignore

2022-07-18 09:05 UTC, albertdb requested changes
You are deleting a lot of files that shouldn't be touched. Please fix.

2022-07-20 12:59 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/aks/aks-pipeline.cfg
> +
```suggestion

```

2022-07-20 12:59 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/aks/aks-pipeline.cfg
> +    az pipelines variable create --name "operation" --pipeline-name $pipelineName --value ${operation}
```suggestion
    az pipelines variable create --name "operation" --pipeline-name $pipelineName --value ${operation}

```

2022-07-21 07:53 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/aks/aks-provisioning.yml.template
> +  k8sVariableGroupName: 'common-k8s-variables'
```suggestion
  k8sVariableGroupName: 'deployment-env-variables'
```

2022-07-21 07:57 UTC, albertdb approved these changes

2022-07-21 08:03 UTC, ultymatom approved these changes

2022-07-21 08:08 UTC, albertdb approved these changes

2022-07-21 08:08 UTC, merged