Feature/block1 Setup Azure DevOps project
devonfw/hangar pull request #18
Opened 2021-10-22 09:14 UTC by prathibhapadma

Azure Devops account setup in Azure cli.

2021-11-03 09:56 UTC, jbellver99 commented on documentation/scripts/account-setup/Azure_Devops.asciidoc
> +   - Create Extensions for external template (Example: EKS).
Take off unnecessary things as we are trying to make a guide not a knowledge base

2021-11-03 09:57 UTC, jbellver99 commented on documentation/scripts/account-setup/Azure_Devops.asciidoc
> +   - Azure {url-dashboard}[Dashboards] are customizable interactive signboards that provide real-time information, and display configurable charts and widgets
Same for things like the explanation of what is the dashboard, boards, etc. Try to keep it as a guide.

2021-11-03 09:58 UTC, jbellver99 commented on documentation/scripts/account-setup/Azure_Devops.asciidoc
> +az --version
No need to add a verification to know which version we are running

2021-11-03 09:59 UTC, jbellver99 commented on documentation/scripts/account-setup/Azure_Devops.asciidoc
> +-  Create Automated script for above process in "myScript.ps1"
If this script does exactly the same as the commands above, it would be better to take off the commands and mention that a script has been created in order to automate this part and give and explanation of how this is script could be used by the users.

2021-11-03 10:41 UTC, albertdb requested changes
In general, when you reference a documentation, you still have to write about what you are trying to achieve, but you take advantage of the detailed step-by-step procedure already available and you don't have to reinvent the wheel.

2021-11-03 10:41 UTC, albertdb commented on documentation/scripts/account-setup/Azure_Devops.asciidoc
> +* Create Azure Devops Project.
I'm missing a reference on how to create a project to
https://docs.microsoft.com/en-us/azure/devops/boards/get-started/sign-up-invite-teammates?view=azure-devops#create-a-project

2021-11-03 10:41 UTC, albertdb commented on documentation/scripts/account-setup/Azure_Devops.asciidoc
> +* Create Azure Devops Project.
Also, although it is out of scope of Hangar (we don't make a specific recommendation) you can also reference https://docs.microsoft.com/en-us/azure/devops/boards/get-started/plan-track-work?view=azure-devops&tabs=agile-process so user can decide what work process is best for the project (and inform/ask his manager about this).

2021-11-03 10:41 UTC, albertdb commented on documentation/scripts/account-setup/Azure_Devops.asciidoc
> +-  Create Automated script for above process in "myScript.ps1"
Also, the script should be verbose about the steps it performs, so user doesn't see it as a black box

2021-11-03 10:41 UTC, albertdb commented on documentation/scripts/account-setup/Azure_Devops.asciidoc
> +-  Create Automated script for above process in "myScript.ps1"
Finally, the script shouldn't be embedded on the guide, but committed separately

2021-11-03 12:41 UTC, jbellver99 requested changes

2021-11-03 12:41 UTC, jbellver99 commented on documentation/Scripts/account-setup/Azure_Devops.asciidoc
> +1. Install the Azure CLI.
Add the links to the installation of these two prerequisities.

2021-11-03 12:41 UTC, jbellver99 commented on documentation/Scripts/account-setup/Azure_Devops.asciidoc
> +[source,asciidoc]
As commented before the script should be committed separately and mention in the guide where to find it and how to execute it

2021-11-05 10:38 UTC, jbellver99 requested changes

2021-11-05 10:38 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +Automated the Azure Devops setup using script, you can find Script in this folder `/Scripts/account-setup/account_create.sh`.
```suggestion
There is a script in order to automate the Azure DevOps setup, you can find this script in `/scripts/account-setup/account_create.sh`.
```

2021-11-05 10:38 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +1. Install the Azure DevOps Extension to manage Azure DevOps Services from the command line .
These part can be deleted as we do not need to explain what the script does, this is done via echos in the script.

2021-11-05 10:38 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +2. Edit *account_create.sh* file to change the organization name `Organization={{Organization-org}}` and project name `project={{project}}`.
Configure the script so that the user inputs the parameters Organization and Project. It would be better than having the user to modify the script.
If you do so here you can explain that they should add parameters and what are these parameters.

2021-11-10 10:59 UTC, jbellver99 requested changes

2021-11-10 10:59 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +1. create Azure devops project manually by {url-az-project}[Following] instructions.
```suggestion
1. Create an Azure DevOps project manually by {url-az-project}[Following] instructions. 
```

2021-11-10 10:59 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +2. Other way using Script to automate the Azure DevOps project setup, you can find this script in `/scripts/account-setup/account_create.sh`.
```suggestion
2. Create an Azure DevOps project using an automated script, you can find this script in `/scripts/account-setup/account_create.sh`.
```

2021-11-10 10:59 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +== *Setup Azure DevOps  using Script*
```suggestion
== *Setup Azure DevOps using Script*
```

2021-11-10 10:59 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +This script is to creates a new project or Configure already existed project. Follow below instructions for further details.
```suggestion
This script will enable you to create a new project or configure an existing one. Follow the instructions below for more details.
```

2021-11-10 10:59 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +Arguments
```suggestion
== Arguments
```

2021-11-10 10:59 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +    -t    PAT token to login Azure Devops
```suggestion
    -p    [Required] Name of the new project.
    -d    [Required] Description for the new project.
    -o    [Required] Name of the organization  for which the project will be configured.
    -v    Accepted values: private, public.
    -t    PAT token to login Azure DevOps.
```

2021-11-10 10:59 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +*Script Usage*
```suggestion
== *Script Usage*
```

2021-11-10 10:59 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +1. create Azure devops project manually by {url-az-project}[Following] instructions.
```suggestion
1. Create an Azure devOps project manually by {url-az-project}[Following] instructions. 
```

2021-11-10 10:59 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +2. Other way using Script to automate the Azure DevOps project setup, you can find this script in `/scripts/account-setup/account_create.sh`.
```suggestion
2. Create an Azure DevOps project using an automated script, you can find this script in `/scripts/account-setup/account_create.sh`.
```

2021-11-10 10:59 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +== *Setup Azure DevOps  using Script*
```suggestion
== *Setup Azure DevOps using Script*
```

2021-11-10 10:59 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +This script is to creates a new project or Configure already existed project. Follow below instructions for further details.
```suggestion
This script enables you to create a new project or configure an existing one. Follow below instructions for further Follow the instructions below for further details.
```

2021-11-10 10:59 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +Arguments
```suggestion
== Arguments
```

2021-11-10 10:59 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +    -t    PAT token to login Azure Devops
```suggestion
    -p    [Required] Name of the new project.
    -d    [Required] Description for the new project.
    -o    [Required] Name of the organization  for which the project will be configured.
    -v    Accepted values: private, public.
    -t    PAT token to login Azure DevOps.
```

2021-11-10 10:59 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +*Script Usage*
```suggestion
== *Script Usage*
```

2021-11-10 10:59 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +5.  Check your logs for Configured list.
Remove unnecessary explanations that already mentioned when executing the script. For example, "1. Install the Azure DevOps Extension to manage Azure DevOps Services from the command line". You already have an echo in the script that will tell the user what it is doing when executed.

2021-11-10 10:59 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +5.  Check your logs for Configured list.
Change the second point as the PAT is now passed through parameters.

2021-11-10 12:30 UTC, jbellver99 requested changes

2021-11-10 12:30 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +    e.  Replace '$pat_token' with pat_token
```suggestion
1.  Edit all the parameters as desired to create an Azure DevOps project

    a.  Replace '$projectname' with Project Name
    b.  Replace '$description' with Description
    c.  Replace '$organization' with organization Name
    d.  Replace '$visibility' with visibility
    e.  Replace '$pat_token' with pat_token
```

2021-11-10 13:26 UTC, albertdb requested changes
The script looks much better now along with the provided suggestions.

2021-11-10 13:26 UTC, albertdb commented on Scripts/account-setup/account_create.sh
> +   echo -e "\t-t Description of what is pat_token"
Parameter description is missing.

2021-11-10 13:26 UTC, albertdb commented on Scripts/account-setup/account_create.sh
> +   echo "Some or all of the parameters are empty";
```suggestion
   echo "ERROR: Some required parameters are missing.";
```

2021-11-10 13:26 UTC, albertdb commented on Scripts/account-setup/account_create.sh
> +	echo "Install the Azure DevOps extension for cli use"
```suggestion
	echo "Installing Azure DevOps extension for CLI use..."
```

2021-11-10 13:26 UTC, albertdb commented on Scripts/account-setup/account_create.sh
> +	echo "Login to Azure Devops With PAT Token"
```suggestion
	echo "Logging in to Azure DevOps with PAT token..."
```

2021-11-10 13:26 UTC, albertdb commented on Scripts/account-setup/account_create.sh
> +	echo "Create project"
```suggestion
	echo "Creating project..."
```

2021-11-10 13:26 UTC, albertdb commented on Scripts/account-setup/account_create.sh
> +	echo "project list"
```suggestion
	echo "Project list:"
```

2021-11-10 13:26 UTC, albertdb commented on Scripts/account-setup/account_create.sh
> +	echo "Configure Organizations and project"
```suggestion
	echo "Configuring default organization and project..."
```

2021-11-10 13:26 UTC, albertdb commented on Scripts/account-setup/account_create.sh
> +	echo "List of Configured Organizations list"
```suggestion
	echo "List of configured organization:"
```

2021-11-10 13:33 UTC, albertdb commented on documentation/scripts/account-setup/Azure_Devops.asciidoc
> +* Create Azure Devops Project.
@prathibhapadma This is still relevant and partially missing. Please check all three comments (including the general above one).

2021-11-11 11:18 UTC, jbellver99 requested changes

2021-11-11 11:18 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +1. Create an Azure DevOps organization to start planning and tracking work. Sign-up process for {url-az-devops}[Azure Devops].
Rephrase this part as something like, you will need to be signed into Azure DevOps in order to follow the steps of this guide.

2021-11-11 11:18 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +2. create an Azure devops project, They are two ways to create an Azure devops project:
```suggestion
2. Create an Azure DevOps project, There are two ways to create an Azure DevOps project:
```

2021-11-11 11:18 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +.. Create an Azure DevOps project manually by {url-az-project}[Following] instructions.
```suggestion
.. Create an Azure DevOps project manually with the web interface following Microsoft's official {url-az-project}[guide]. 
```

2021-11-11 11:18 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +3. Plan and track your work by creating items in {url-az-devops}[Azure Boards], You can follow these instructions when you want to accomplish the followingtasks for best process.
Not quite sure if this should go here, and the url takes you to the same page as the one in step 1

2021-11-11 11:18 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +    .. Replace '$pat_token' with pat_token
This part can be omitted as the arguments are already explained in the Arguments section.

2021-11-11 11:18 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +    .. Replace '$pat_token' with pat_token
It would be better to add an example of how the script should be used and what the parameters could be.

2021-11-15 08:17 UTC, jbellver99 requested changes

2021-11-15 08:17 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +... You need to be Sign up for an {url-az-devops}[Azure Devops] in order to follow the steps of this guide.
```suggestion
... Sign up into {url-az-devops}[Azure DevOps] in order to follow the steps of this guide.
```

2021-11-15 08:17 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +... Install the Azure CLI.
Add link to the CLI installation guide.

2021-11-15 08:17 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +3. Plan and track your work by creating items in {url-az-board}[Azure Boards], You can follow these instructions when you want to accomplish the followingtasks for best process.
```suggestion
2. Plan and track your work by creating items in {url-az-board}[Azure Boards], You can follow these instructions when you want to accomplish the following tasks for best process.
```

2021-11-15 08:17 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +`bash account_create.sh -p 'devon4java' -d 'devon4java_Application' -o 'devon-hangar' -v 'public' -t 'xxxxxxxxxxxxxx'`
Add another more generic example, one of the kind: bash account_create.sh -p 'my_project' ... Using placeholders.

2021-11-16 07:49 UTC, jbellver99 requested changes

2021-11-16 07:49 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +I want to create an devon4java project in `devon-hangar` organization. Edit all the parameters as desired to create an Azure DevOps project.
There is no need to add this if you are using a generic example with placeholders. Delete this part or add an example that suits this case study.

2021-11-17 08:33 UTC, jbellver99 requested changes

2021-11-17 08:33 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +*Prerequisites:*
```suggestion
== *Prerequisites:*
```

2021-11-17 08:33 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +... Sign up into {url-az-devops}[Azure DevOps] in order to follow the steps of this guide.
```suggestion
. Sign up into {url-az-devops}[Azure DevOps].
```

2021-11-17 08:33 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +... Install the Azure {url-az-CLI}[CLI].
```suggestion
. Install the Azure {url-az-CLI}[CLI].
```

2021-11-17 08:33 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +2. Plan and track your work by creating items in {url-az-board}[Azure Boards], You can follow these instructions when you want to accomplish the following tasks for best process.
```suggestion
== *Creating the Azure DevOps project*

The scope of this section is to prepare and activate an Azure DevOps account.

There  are two ways to create an Azure DevOps project:
.  Create an Azure DevOps project manually with the web interface following Microsoft's official {url-az-project}[guide].  
. Create an Azure DevOps project using an automated script, you can find this script in `/scripts/account-setup/account_create.sh`. 

Additionally you are able to plan and track your work by creating items in {url-az-board}[Azure Boards], you can follow these instructions when you want to accomplish the following tasks for best practices.
```

2021-11-17 08:33 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +`bash account_create.sh -p 'my_project' -d 'This_is_an_sample_project' -o 'organization-org' -v 'public' -t 'xxxxxxxxxxxxxx'`
```suggestion
Executing the script:

`bash account_create.sh -p 'my_project' -d 'This_is_a_sample_project' -o 'organization-org' -v 'public' -t 'xxxxxxxxxxxxxx'`

Case study:

I want to create a devon4quarkus project with the description 'This is a quarkus application' in an organization called `devon-hangar` .

`bash account-create.sh -p 'devon4quarkus' -d 'This is a quarkus application' -o 'devon-hangar' -v 'public' -t 'xxxxxxxxxxxxxx'`
```

2021-11-22 05:51 UTC, prathibhapadma commented on documentation/Azure_Devops_Setup.asciidoc
> +3. Plan and track your work by creating items in {url-az-devops}[Azure Boards], You can follow these instructions when you want to accomplish the followingtasks for best process.
It will take to Azure Boards page, please can you check once again.

2021-11-22 07:37 UTC, jbellver99 requested changes

2021-11-22 07:37 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +== Arguments
```suggestion
== Flags
```

2021-11-22 07:37 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +*Executing the script:*
```suggestion
== Usage
```

2021-11-22 07:37 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +*Case study:*
```suggestion
== Examples
```

2021-11-22 07:37 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +I want to create a devon4quarkus project with the description This is a `quarkus` application in an organization called `devon-hangar`.
```suggestion
=== Quarkus project
```

2021-11-22 15:15 UTC, jbellver99 requested changes

2021-11-22 15:15 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +I want to create a devon4quarkus project with the description 'This is a quarkus application' in an organization called `devon-hangar`.
```suggestion
```

2021-11-22 15:15 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +`bash account-create.sh -p 'devon4quarkus' -d 'This_is_a_quarkus_application' -o 'devon-hangar' -v 'public' -t 'xxxxxxxxxxxxxx'`
```suggestion
=== Quarkus project

I want to create a devon4quarkus project with the description 'This is a quarkus application' in an organization called `devon-hangar`.

`bash account-create.sh -p 'devon4quarkus' -d 'This is a quarkus application' -o 'devon-hangar' -v 'public' -t 'xxxxxxxxxxxxxx'`
```

2021-11-23 08:15 UTC, jbellver99 requested changes
Add the suggetions on the script in order to accept blank spaces in the description and the project name.
Add the suggestion on the prerequisites on how to create a PAT.

2021-11-23 08:15 UTC, jbellver99 commented on Scripts/account-setup/account_create.sh
> +	az devops project create --name $projectname --description $description --organization https://dev.azure.com/$organization --visibility $visibility
```suggestion
	az devops project create --name "$projectname" --description "$description" --organization https://dev.azure.com/$organization --visibility $visibility
```

2021-11-23 08:15 UTC, jbellver99 commented on Scripts/account-setup/account_create.sh
> +	az devops configure --defaults organization=https://dev.azure.com/$organization project=$projectname
```suggestion
	az devops configure --defaults organization=https://dev.azure.com/$organization project="$projectname"
```

2021-11-23 08:15 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +. Install the Azure {url-az-CLI}[CLI].
```suggestion
== *Prerequisites:*

. Sign up into {url-az-devops}[Azure DevOps].
. Install the Azure {url-az-CLI}[CLI].
. Create a {url-pat-token}[Personal Access Token (PAT)] in Azure DevOps.
```

2021-11-23 08:15 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +
```suggestion
:url-az-devops: https://docs.microsoft.com/en-us/azure/devops/boards/get-started/sign-up-invite-teammates?view=azure-devops#choose-your-sign-up-option

:url-az-project:  https://docs.microsoft.com/en-us/azure/devops/boards/get-started/sign-up-invite-teammates?view=azure-devops#create-a-project

:url-az-CLI:  https://docs.microsoft.com/en-us/cli/azure/?view=azure-cli-latest

:url-az-board: https://docs.microsoft.com/en-us/azure/devops/boards/get-started/plan-track-work?view=azure-devops&tabs=agile-process

:url-pat-token: https://docs.searchunify.com/Content/Content-Sources/Azure-Generate-Personal-Access-Token.htm
```

2021-11-29 06:15 UTC, sundharakanth reviewed
Sign up into "Azure DevOps" link is pointing to this AzureBoards link - https://docs.microsoft.com/en-us/azure/devops/boards/get-started/sign-up-invite-teammates?view=azure-devops#choose-your-sign-up-option instead of AzureDevOps link - https://docs.microsoft.com/en-us/azure/devops/user-guide/sign-up-invite-teammates?view=azure-devops . Please check and confirm which link to be shown there.

2021-11-29 06:20 UTC, sundharakanth commented
Create a "Personal Access Token (PAT)" in Azure DevOps.
--> You can add few words saying to follow the steps in the link since the link is pointing to documentation with the step by step instructions and not the actual Azure PAT link.

2021-11-29 06:25 UTC, sundharakanth commented
Create an Azure DevOps project using an automated script, you can find this script in "/scripts/account-setup/account_create.sh"
--> Is it possible to add link to the file? If yes, please add and if not possible, please ignore.

2021-11-29 06:28 UTC, sundharakanth commented
Additionally you are able to plan and track your work by creating items in Azure Boards, you can follow these instructions when you want to accomplish the "following tasks" for best practices.
--> The above statement refers to following tasks whereas we have only one command to execute after this step. So, please consider re-phrasing the sentence.

2021-11-29 06:30 UTC, sundharakanth commented
Setup Azure DevOps using Script
This script will enable you to create a new project or configure an existing one. Follow the instructions below for more details.
--> Above statement referring to the instructions whereas we have only one command (account_create.sh) to execute after this. Please consider re-phrasing the sentence.

2021-11-29 06:32 UTC, sundharakanth commented
Usage and Example
--> Please consider showing in multiple lines (instead of current single line command) like the Syntax for better readability.

2021-11-29 06:43 UTC, sundharakanth submitted a review, later dismissed

2021-11-29 06:43 UTC, sundharakanth commented on documentation/Azure_Devops_Setup.asciidoc
> +. Sign up into {url-az-devops}[Azure DevOps].
Sign up into "Azure DevOps"
--> the link is pointing to this AzureBoards link - https://docs.microsoft.com/en-us/azure/devops/boards/get-started/sign-up-invite-teammates?view=azure-devops#choose-your-sign-up-option instead of AzureDevOps link - https://docs.microsoft.com/en-us/azure/devops/user-guide/sign-up-invite-teammates?view=azure-devops . Please check and confirm which link to be shown there.

You can add few words saying to follow the steps in the link since the link is pointing to Microsoft Docs with the step by step instructions.

2021-11-29 06:43 UTC, sundharakanth commented on documentation/Azure_Devops_Setup.asciidoc
> +. Create a  {url-pat-token}[Personal Access Token (PAT)] in Azure DevOps.
Create a "Personal Access Token (PAT)" in Azure DevOps.
--> You can add few words saying to follow the steps in the link since the link is pointing to documentation with the step by step instructions and not the actual Azure PAT link.

2021-11-29 06:43 UTC, sundharakanth commented on documentation/Azure_Devops_Setup.asciidoc
> +. Create an Azure DevOps project using an automated script, you can find this script in `/scripts/account-setup/account_create.sh`.
Create an Azure DevOps project using an automated script, you can find this script in "/scripts/account-setup/account_create.sh"
--> Is it possible to add link to the file? If yes, please add and if not possible, please ignore.

2021-11-29 06:43 UTC, sundharakanth commented on documentation/Azure_Devops_Setup.asciidoc
> +Additionally you are able to plan and track your work by creating items in {url-az-board}[Azure Boards], you can follow these instructions when you want to accomplish the following tasks for best pra
Additionally you are able to plan and track your work by creating items in Azure Boards, you can follow these instructions when you want to accomplish the "following tasks" for best practices.
--> The above statement refers to following tasks whereas we have only one command (account_create.sh) to execute after this step. So, please consider re-phrasing the sentence.

2021-11-29 06:43 UTC, sundharakanth commented on documentation/Azure_Devops_Setup.asciidoc
> +This script will enable you to create a new project or configure an existing one. Follow the instructions below for more details.
This script will enable you to create a new project or configure an existing one. Follow the instructions below for more details.
--> Above statement referring to the instructions whereas we have only one command (account_create.sh) to execute after this. Please consider re-phrasing the sentence.

2021-11-29 06:43 UTC, sundharakanth commented on documentation/Azure_Devops_Setup.asciidoc
> +`bash account_create.sh -p 'my_project' -d 'This_is_a_sample_project' -o 'organization-org' -v 'public' -t 'xxxxxxxxxxxxxx'`
Usage and Example
--> Please consider showing in multiple lines (instead of current single line command) like the Syntax for better readability.

2021-11-29 06:43 UTC, sundharakanth commented on documentation/Azure_Devops_Setup.asciidoc
> +`bash account-create.sh -p 'devon4quarkus' -d 'This is a quarkus application' -o 'devon-hangar' -v 'public' -t 'xxxxxxxxxxxxxx'`
Usage and Example
--> Please consider showing in multiple lines (instead of current single line command) like the Syntax for better readability.

2021-11-29 07:00 UTC, prathibhapadma commented on documentation/Azure_Devops_Setup.asciidoc
> +`bash account-create.sh -p 'devon4quarkus' -d 'This is a quarkus application' -o 'devon-hangar' -v 'public' -t 'xxxxxxxxxxxxxx'`
```suggestion
`bash account-create.sh -p 'devon4quarkus' -d 'This is a quarkus application' -o 'devon-hangar' -v 'public' -t 'xxxxxxxxxxxxxx'`
```
yntax
   account_create.sh
        [-p <String>]
        [-d <String>]
        [-o <String>]
        [-v <String>]
        [-t <String>]
Flags
    -p    [Required] Name of the new project.
    -d    [Required] Description for the new project.
    -o    [Required] Name of the organization  for which the project will be configured.
    -v    [Required] Visibility accepted values: private or public.
    -t    [Required] PAT token to login Azure DevOps.

2021-11-29 07:03 UTC, prathibhapadma commented on documentation/Azure_Devops_Setup.asciidoc
> +`bash account-create.sh -p 'devon4quarkus' -d 'This is a quarkus application' -o 'devon-hangar' -v 'public' -t 'xxxxxxxxxxxxxx'`
Already few lines exist regarding syntax and variables description. so that they can understand how to use it.

2021-11-29 07:29 UTC, prathibhapadma commented on documentation/Azure_Devops_Setup.asciidoc
> +. Sign up into {url-az-devops}[Azure DevOps].
The link which is pointing to create an Azure Devops Account. please re-check once again.

2021-11-29 07:54 UTC, prathibhapadma commented on documentation/Azure_Devops_Setup.asciidoc
> +. Sign up into {url-az-devops}[Azure DevOps].
The link which is pointing is shared by albert.

2021-12-01 08:25 UTC, jbellver99 requested changes

2021-12-01 08:25 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +:url-az-devops: https://docs.microsoft.com/en-us/azure/devops/boards/get-started/sign-up-invite-teammates?view=azure-devops#choose-your-sign-up-option
Specify the section that the user should read. Like this it looks like the user needs to read the whole page and we are only interested in the part about signing in.

2021-12-01 08:25 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +```
```suggestion
```

2021-12-01 08:25 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +Additionally you are able to plan and track your work by creating items in {url-az-board}[Azure Boards], you can follow these instruction when you want to accomplish the following task for best pract
```suggestion
There  are two ways to create an Azure DevOps project:

.  Create an Azure DevOps project manually with the web interface following Microsoft's official {url-az-project}[guide]. 
.. When you create an Azure DevOps project manually, you will need to create its workflow. Learn more about this in the following {url-az-board}[guide].

. Create an Azure DevOps project using an automated script, you can find this script in {url-script-url}[`/scripts/account-setup/project_create.sh`]. 
```

2021-12-01 08:25 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +
```suggestion

By the end of this section you will end up with a new Azure DevOps project.
```

2021-12-01 08:26 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +. Sign up into {url-az-devops}[Azure DevOps].
Specify the section that the user should read. Like this it looks like the user needs to read the whole page and we are only interested in the part about signing in.

2021-12-01 11:52 UTC, jbellver99 submitted a review, later dismissed

2021-12-01 11:52 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +In this section you will create a new Azure DevOps project.
```suggestion
By the end of this guide, a new project in Azure DevOps will be created.
```

2021-12-01 11:52 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +In this section you will create a new Azure DevOps project.
We want to know what is the output of this section, so that the user can read this at the beginning and if he has already and azure project created he can skip this section.

2021-12-01 11:52 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +
```suggestion
== *Prerequisites:*
. Sign up into {url-az-devops}[Azure DevOps] (just follow the section `Sign up with a personal Microsoft account`).
. Install the Azure {url-az-CLI}[CLI].
. Create an Azure Devops {url-pat-token}[Personal Access Token (PAT)].

```

2021-12-01 11:52 UTC, jbellver99 commented on documentation/Azure_Devops_Setup.asciidoc
> +`bash project_create.sh -p 'devon4quarkus' -o 'devon-hangar' -d 'This is a quarkus application' -v 'public' -t 'xxxxxxxxxxxxxx'`
```suggestion
Create a devon4quarkus project with the description 'This is a quarkus application' in an organization called `devon-hangar`.

`./project_create.sh -p 'devon4quarkus' -o 'devon-hangar' -d 'This is a quarkus application' -v 'public' -t 'xxxxxxxxxxxxxx'`
```

2021-12-02 14:52 UTC, albertdb requested changes
Apply suggestions and move files accordingly please.

2021-12-02 14:52 UTC, albertdb commented on Scripts/account-setup/project_create.sh
> +#!/bin/bash
Move and rename script to `scripts/accounts/azure-devops/create-project.sh`

2021-12-02 14:52 UTC, albertdb commented on documentation/Azure_Devops_Setup.asciidoc
> +== Activate and prepare Azure DevOps
```suggestion
== Setup Azure DevOps project
```

Move and rename document to documentation/azure-devops/setup-project.asciidoc`

2021-12-02 14:52 UTC, albertdb commented on documentation/Azure_Devops_Setup.asciidoc
> +. Create an Azure DevOps project using an automated script, you can find this script in {url-script-url}[`/scripts/account-setup/project_create.sh`]
```suggestion
[loweralpha]
.  Create it manually using the web interface following {url-az-project}[Microsoft official guide]. 
 * When done manually, you will need to choose a workflow. Learn more about the different options in the {url-az-board}[official documentation].
. Create it in an automated way using the provided script, as shown below.
```

What workflow is applied by default when using the script? The guide should mention it.

2021-12-02 14:52 UTC, albertdb commented on documentation/Azure_Devops_Setup.asciidoc
> +== *Setup Azure DevOps using Script*
```suggestion
== *Creating Azure DevOps project using provided script*
```

2021-12-02 14:52 UTC, albertdb commented on documentation/Azure_Devops_Setup.asciidoc
> +This script will enable you to create a new project or configure an existing one. Follow the instruction below for more details.
```suggestion
The script located at `scripts/accounts/azure-devops/create-project.sh` enables you to create a new Azure DevOps project or configure an existing one.
```

2021-12-02 14:52 UTC, albertdb commented on documentation/Azure_Devops_Setup.asciidoc
> +```
````suggestion
== Usage

```
create-project.sh \
  -p <name> \
  -d <description> \
  -o <organization> \
  -v <visibility> \
  -t <PAT>
```

== Flags

```
-p    [Required] Name of the new project.
-d    [Required] Description for the new project.
-o    [Required] Name of the organization for which the project will be configured.
-v    [Required] Visibility accepted values: private or public.
-t    [Required] PAT token to login Azure DevOps.
```
````

2021-12-02 14:52 UTC, albertdb commented on documentation/Azure_Devops_Setup.asciidoc
> +
```suggestion
== Example

`./create-project.sh -p "Hello World" -d 'This is a sample application' -o "devon-hangar" -v 'public' -t 'myToken'`
```

2021-12-02 14:52 UTC, albertdb commented on Scripts/account-setup/project_create.sh
> +
```suggestion

echo "Installing Azure DevOps extension for CLI use..."
az extension add --name azure-devops

echo "Logging in to Azure DevOps with PAT token..."
echo $pat_token | az devops login

echo "Creating project..."
az devops project create --name "$projectname" --description "$description" --organization https://dev.azure.com/$organization --visibility "$visibility"

echo "Project list:"
az devops project list  --organization https://dev.azure.com/$organization

echo "Configuring default organization and project..."
az devops configure --defaults organization=https://dev.azure.com/$organization project="$projectname"  

echo "List of configured organization:"
az devops configure --list
```

2021-12-03 13:06 UTC, albertdb commented on documentation/Azure_Devops_Setup.asciidoc
> +There  are two ways to create an Azure DevOps project:
Regression: space introduced between project and :

2021-12-03 13:07 UTC, albertdb commented on Scripts/account-setup/project_create.sh
> +#!/bin/bash
Filename still not the proposed. `Scripts` is not the same as `scripts`.

2021-12-03 13:09 UTC, albertdb commented on documentation/Azure_Devops_Setup.asciidoc
> +. Create an Azure DevOps project using an automated script, you can find this script in {url-script-url}[`/scripts/account-setup/project_create.sh`]
Suggestion partially ignored. Please review.

2021-12-03 13:10 UTC, albertdb commented on documentation/Azure_Devops_Setup.asciidoc
> +```
Suggestion partially ignored. Please review.

2021-12-03 13:12 UTC, albertdb commented
Please accept suggestions instead of manually copying changes and commiting. Otherwise, it makes review process extremely and unnecessarily complex.

2021-12-07 15:06 UTC, albertdb requested changes
Please accept suggestions so I can then approve.

2021-12-07 15:06 UTC, albertdb commented on documentation/azure-devops/setup-project.asciidoc
> +
```suggestion
`./create-project.sh -n "Hello World" -d "This is a sample application" -o devon-hangar -v public -t myToken -p agile`
```

2021-12-07 15:06 UTC, albertdb commented on documentation/azure-devops/setup-project.asciidoc
> +-o    [Required] Name of the organization  for which the project will be configured.
```suggestion
-o    [Required] Name of the organization for which the project will be configured.
```

2021-12-07 15:06 UTC, albertdb commented on documentation/azure-devops/setup-project.asciidoc
> +-v    [Required] Visibility. Accepted values: private or public.
```suggestion
-v    [Required] Visibility. Accepted values: private, public.
```

2021-12-07 15:06 UTC, albertdb commented on scripts/accounts/azure-devops/create-project.sh
> +   echo -e "\t-p            Process that will be used. Accepted values: basic, agile, scrum, cmmi."
```suggestion
   echo -e "\t-w            Process workflow that will be used. Accepted values: basic, agile, scrum, cmmi. Default: basic."
```

2021-12-07 15:06 UTC, albertdb commented on scripts/accounts/azure-devops/create-project.sh
> +      p ) process="$OPTARG" ;;
```suggestion
      w ) process="$OPTARG" ;;
```

2021-12-09 13:50 UTC, albertdb approved these changes

2021-12-10 13:26 UTC, albertdb commented
@isandesh1986 PR needs second approval, could you please quickly check?

2021-12-13 07:50 UTC, jbellver99 approved these changes

2021-12-13 08:57 UTC, isandesh1986 approved these changes
looks good to me

2021-12-13 12:13 UTC, merged