AWS Credentials variable group creation as part of provisioning.
devonfw/hangar pull request #184
Opened 2022-07-20 10:00 UTC by isandesh1986

AWS Credentials variable group creation as part of provisioning.

2022-07-20 10:09 UTC, ultymatom approved these changes

2022-07-20 10:58 UTC, albertdb requested changes

2022-07-20 10:58 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/eks/eks-pipeline.cfg
> +sourceBranch="feature/eks-provision"
```suggestion
sourceBranch="feature/eks-provisioning"
```

Otherwise we need to modify the guide.

2022-07-20 10:58 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/eks/eks-provisioning.yml.template
> +      '$(System.DefaultWorkingDirectory)/.pipelines/scripts/update-variable-group.sh' "$(System.TeamFoundationCollectionUri)" "$(System.TeamProject)" "$(variableGroupName)" "eks-cluster-name" "$(clus
This script needs to be included in the PR and copied as part of setup

2022-07-20 10:58 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/eks/eks-pipeline.cfg
> +    fi
This should somehow informatively fail is the variable group does not exist and the AWS flags are not provided.

2022-07-20 11:00 UTC, isandesh1986 commented on scripts/pipelines/azure-devops/templates/eks/eks-provisioning.yml.template
> +      '$(System.DefaultWorkingDirectory)/.pipelines/scripts/update-variable-group.sh' "$(System.TeamFoundationCollectionUri)" "$(System.TeamProject)" "$(variableGroupName)" "eks-cluster-name" "$(clus
I was actually reusing this script from Prathibha's PR. Will add it.

2022-07-20 11:52 UTC, isandesh1986 commented on scripts/pipelines/azure-devops/templates/eks/eks-pipeline.cfg
> +    fi
Done

2022-07-20 11:53 UTC, isandesh1986 commented on scripts/pipelines/azure-devops/templates/eks/eks-pipeline.cfg
> +sourceBranch="feature/eks-provision"
Done

2022-07-20 11:53 UTC, isandesh1986 commented on scripts/pipelines/azure-devops/templates/eks/eks-provisioning.yml.template
> +      '$(System.DefaultWorkingDirectory)/.pipelines/scripts/update-variable-group.sh' "$(System.TeamFoundationCollectionUri)" "$(System.TeamProject)" "$(variableGroupName)" "eks-cluster-name" "$(clus
Done

2022-07-20 12:37 UTC, albertdb submitted a review, later dismissed

2022-07-20 13:04 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/eks/eks-provisioning.yml.template
> +      '$(System.DefaultWorkingDirectory)/.pipelines/scripts/update-variable-group.sh' "$(System.TeamFoundationCollectionUri)" "$(System.TeamProject)" "$(variableGroupName)" "eks-cluster-name" "$(clus
Is this variable needed? I don't see it in use in the other PRs.

2022-07-20 16:01 UTC, isandesh1986 commented on scripts/pipelines/azure-devops/templates/common/kubernetes/update-variable-group.sh
> +if test -z $groupid
@sonatype-lift ignore

2022-07-20 16:02 UTC, isandesh1986 commented on scripts/pipelines/azure-devops/templates/eks/eks-provisioning.yml.template
> +      '$(System.DefaultWorkingDirectory)/.pipelines/scripts/update-variable-group.sh' "$(System.TeamFoundationCollectionUri)" "$(System.TeamProject)" "$(variableGroupName)" "eks-cluster-name" "$(clus
Needed by Deploy pipeline.

2022-07-21 07:43 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +    echo "      --aws-region            [Required, on first run] AWS Region to provision the resources."
```suggestion
    echo "      --aws-access-key        [Required, on first run] AWS account access key ID."
    echo "      --aws-secret-access-key [Required, on first run] AWS account secret access key."      
    echo "      --aws-region            [Required, on first run] AWS Region to provision the resources."
    echo "      --rancher                          Install Rancher to manage the cluster."
```

2022-07-21 07:44 UTC, albertdb approved these changes

2022-07-21 07:47 UTC, albertdb commented on documentation/azure-devops/setup-eks-provisioning-pipeline.asciidoc
> +    --aws-region                [Required, on first run] AWS Region to provision the resources.
```suggestion
    --aws-region                [Required, on first run] AWS region for provisioning resources.
```

2022-07-21 07:48 UTC, albertdb approved these changes

2022-07-21 07:50 UTC, merged