Documentation & script for block 5
devonfw/hangar pull request #19
Opened 2021-11-02 15:29 UTC by jbellver99

2021-11-02 15:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw/hangar?pullRequest=19) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/devonfw/hangar?pullRequest=19) before we can accept your contribution.<br/><hr/>**Bellver Fernandez** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw/hangar?pullRequest=19) it.</sub>

2021-11-03 15:56 UTC, albertdb requested changes
Good, but we should clearly cover the use case of building the devon4quarkus reference app, so it is more straightforward for the user.

2021-11-03 15:56 UTC, albertdb commented on documentation/guide-setup-build-pipelines.asciidoc
> +As it has been mentioned before, you are able to execute this script in two different ways.
Redundant sentence.

Better use subsections (one per use case) which implicitly means the same.

2021-11-03 15:56 UTC, albertdb commented on documentation/guide-setup-build-pipelines.asciidoc
> +The first way would be if you want to create a new build pipeline based on a `.yaml` file which already exists inside your azure repository. In order to create the pipeline you will need to:
```suggestion
The first way would be if you want to create a new build pipeline based on a `.yaml` file which already exists inside your Azure DevOps repository. In order to create the pipeline you will need to:
```

Azure DevOps spelling. Maybe once using subsections you need to reword other parts of the paragraph.

2021-11-03 15:56 UTC, albertdb commented on documentation/guide-setup-build-pipelines.asciidoc
> +WARNING: If the pipeline does not build properly, check the `.yaml` for errors.
Isn't there any way to know where it failed? At least we can tell the user to validate the yaml using maybe http://www.yamllint.com/

2021-11-03 15:56 UTC, albertdb commented on documentation/guide-setup-build-pipelines.asciidoc
> +. Select the secon option (`[2]`) to edit the `.yaml` file.
```suggestion
. Select the second option (`[2]`) to edit the `.yaml` file.
```

2021-11-03 15:56 UTC, albertdb commented on documentation/guide-setup-build-pipelines.asciidoc
> +. Select wether you want to continue the execution or edit/view the `.yaml` file.
```suggestion
. Select whether you want to continue the execution or edit/view the `.yaml` file.
```

2021-11-03 15:56 UTC, albertdb commented on scripts/pipelines/azure-devops/build_pipeline_generation.ps1
> +param($name, $repository, $branch, $yamlPath)
Please transform it to Bash as per latest project requirements.

`build_pipeline_generator.sh` would be a better naming.

2021-11-03 15:56 UTC, albertdb commented on scripts/pipelines/azure-devops/build_pipeline_generation.ps1
> +  echo "This script is used to create a build pipeline in azure."
```suggestion
  echo "Generates a build pipeline on Azure DevOps."
```

2021-11-03 15:56 UTC, albertdb commented on scripts/pipelines/azure-devops/build_pipeline_generation.ps1
> +    Write-Host "Missing paerameters, name, repository and branch parameters are mandatory." -ForegroundColor Red
```suggestion
    Write-Host "Missing parameters: name, repository and branch parameters are mandatory." -ForegroundColor Red
```

2021-11-03 15:56 UTC, albertdb commented on scripts/pipelines/azure-devops/build_pipeline_generation.ps1
> +    echo "You can type -h to get more information about the script."
```suggestion
    echo "Use -h flag to display help."
```

2021-11-03 15:56 UTC, albertdb commented on scripts/pipelines/azure-devops/build_pipeline_generation.ps1
> +if($args -contains '-yamlPath')
It would be nice if the script supports more parameters that avoid further interaction choosing options.

2021-11-03 15:56 UTC, albertdb commented on scripts/pipelines/azure-devops/build_pipeline_generation.ps1
> +  echo "arguments:"
```suggestion
  echo "Arguments:"
```

2021-11-03 15:56 UTC, albertdb commented on documentation/guide-setup-build-pipelines.asciidoc
> +The other way to execute this script would be if you want to create a new build pipeline but you do not have any `.yaml` file in your repository. In order to create the pipeline and the `.yaml` file,
Be consistent content-wise: "...a new build pipeline **from scratch**, i.e. you do not have any `.yaml` file...".

Maybe once using subsections you need to reword or separate half of the sentence.

2021-11-17 13:39 UTC, albertdb requested changes

2021-11-17 13:39 UTC, albertdb commented on scripts/pipelines/azure-devops/build_pipeline_generator.sh
> +    echo "Generates a build pipeline on Azure DevOps from a yml template according to your programming language"
```suggestion
    echo "Generates a build pipeline on Azure DevOps from a YAML template according to the project programming language or framework."
```

2021-11-17 13:39 UTC, albertdb commented on scripts/pipelines/azure-devops/build_pipeline_generator.sh
> +    echo "  -l    [Required] Language in which your project is programmed."
```suggestion
    echo "  -l    [Required] Language or framework of the project."
```

2021-11-17 13:39 UTC, albertdb commented on scripts/pipelines/azure-devops/build_pipeline_generator.sh
> +    echo "  -d    [Required] Local directory of your project (the path should be using '/' and not '\')."
```suggestion
    echo "  -d    [Required] Local directory of your project (the path should always be using '/' and not '\')."
```

2021-11-17 13:39 UTC, albertdb commented on scripts/pipelines/azure-devops/build_pipeline_generator.sh
> +    echo "Missing parameters, all the flags are mandatory."
```suggestion
    echo "Missing parameters, all flags are mandatory."
```

2021-11-17 13:39 UTC, albertdb commented on scripts/pipelines/azure-devops/build_pipeline_generator.sh
> +echo "Adding the yml template into the repository..."
```suggestion
echo "Copying the YAML template into the repository..."
```

2021-11-17 13:39 UTC, albertdb commented on scripts/pipelines/azure-devops/build_pipeline_generator.sh
> +echo "Adding the yml template into your Azure DevOps repository..."
```suggestion
echo "Committing and pushing to Git remote..."
```

2021-11-17 13:39 UTC, albertdb commented on scripts/pipelines/azure-devops/build_pipeline_generator.sh
> +git commit -m "Added yml file into Azure DevOps repository"
```suggestion
git commit -m "Adding build pipeline source YAML"
```

2021-11-17 13:39 UTC, albertdb commented on scripts/pipelines/azure-devops/build_pipeline_generator.sh
> +echo "Generating the pipeline from the yml template..."
```suggestion
echo "Generating the pipeline from the YAML template..."
```

2021-11-17 13:39 UTC, albertdb commented on documentation/azure-devops/setup-build-pipeline.asciidoc
> +This script will copy the corrsponding yml template into your local repository and push into Azure DevOps, so it is necessary that you have in your local repository all the changes done in your Azure
Is this really required? Azure DevOps seem to end up in single file that is directly editable (https://docs.microsoft.com/en-us/azure/devops/pipelines/customize-pipeline?view=azure-devops), **please confirm**. It can make sense to let Azure CLI hide the complexity of merging the new pipeline into the possibly existing file, but then storing the template somewhere else would be confusing if later someone wants to edit the pipeline.

2021-11-17 13:39 UTC, albertdb commented on scripts/pipelines/azure-devops/build_pipeline_generator.sh
> +cp ${yamlFile} ${directory}
If this is finally required, then using a hidden subdirectory would be better.

2021-11-17 16:14 UTC, jbellver99 commented on documentation/azure-devops/setup-build-pipeline.asciidoc
> +    ./build_pipeline_generator.sh -n 'quarkus-project-build' -l 'quarkus' -d C:/Users/$USERNAME/Desktop/quarkus-project
```suggestion
    ./build_pipeline_generator.sh -n quarkus-project-build -l quarkus -d C:/Users/$USERNAME/Desktop/quarkus-project
```

2021-12-20 09:16 UTC, albertdb requested changes
I'm missing the part of creating the PR in the script using the CLI or instructing the user in the guide to do so. Same for accepting that PR.

2021-12-20 09:16 UTC, albertdb commented on documentation/azure-devops/setup-build-pipeline.asciidoc
> +In this section we will create a build pipeline for compiling project code. This pipeline will be configured in order to be triggered every time a commit to the Azure DevOps repository is done, regar
```suggestion
In this section we will create a build pipeline for compiling project code. This pipeline will be configured in order to be triggered every time there is a commit to the Azure DevOps repository, regardless of which branch it is made on.
```

2021-12-20 09:16 UTC, albertdb commented on documentation/azure-devops/setup-build-pipeline.asciidoc
> +The creation of the pipeline will follow the projets worklfow, with what a new branch called `feature/build-pipeline` will be created and the YAML file for the pipeline will be pushed to  this branch
```suggestion
The creation of the pipeline will follow the project workflow, so a new branch named `feature/build-pipeline` will be created and the YAML file for the pipeline will be pushed to it.
```

2021-12-28 13:31 UTC, albertdb requested changes
Some minor changes requires, but almost good to go.

2021-12-28 13:31 UTC, albertdb commented on documentation/azure-devops/setup-build-pipeline.asciidoc
> +In this section we will create a build pipeline for compiling project code. This pipeline will be configured in order to be triggered every time there is a commit to the Azure DevOps repository, rega
```suggestion
In this section we will create a build pipeline for compiling project code. This pipeline will be configured to be triggered every time there is a commit to the Azure DevOps repository, regardless of which branch it is made on.
```

2021-12-28 13:31 UTC, albertdb commented on documentation/azure-devops/setup-build-pipeline.asciidoc
> +Following the project workflow, a Pull Request will be created in order to merge this new branch (`feature/build-pipeline`) into the specified branch using the `-b` flag. The Pull Request will merge
```suggestion
Then, a Pull Request (PR) will be created in order to merge the new branch into the appropriate branch (provided in `-b` flag). The PR will be automatically merged if the repository policies are met. If the merge is not possible, either the PR URL will be shown as output, or it will be opened in your web browser if using `-p` flag.
```

2021-12-28 13:31 UTC, albertdb commented on documentation/azure-devops/setup-build-pipeline.asciidoc
> +The script located at `/scripts/pipelines/azure-devops/build_pipeline_generator.sh` will automatically create this new branch, create a build pipeline based on a YAML template appropriate for the pro
```suggestion
The script located at `/scripts/pipelines/azure-devops/build_pipeline_generator.sh` will automatically create this new branch, create a build pipeline based on a YAML template appropriate for the project programming language or framework, create the Pull Request and, if it is possible, merge this new branch into the specified branch.
```

2021-12-28 13:31 UTC, albertdb commented on documentation/azure-devops/setup-build-pipeline.asciidoc
> +    ./build_pipeline_generator.sh -n quarkus-project-build -l quarkus -d C:/Users/$USERNAME/Desktop/quarkus-project -b develop -true
```suggestion
    ./build_pipeline_generator.sh -n quarkus-project-build -l quarkus -d C:/Users/$USERNAME/Desktop/quarkus-project -b develop -p
```

2021-12-28 13:31 UTC, albertdb commented on scripts/pipelines/azure-devops/build_pipeline_generator.sh
> +    echo "  -p               Open the Pull Request on the web browser if the merging fails. Accepted values: true, false."
```suggestion
    echo "  -p               Open the Pull Request on the web browser if it cannot be automatically merged. Requires -b flag."
```

2021-12-28 13:31 UTC, albertdb commented on scripts/pipelines/azure-devops/build_pipeline_generator.sh
> +    echo "  -b               Name of the branch for which the Pull Request will be created."
```suggestion
    echo "  -b               Name of the branch to which the Pull Request will target. PR is not created if the flag is not provided."
```

2021-12-28 13:31 UTC, albertdb commented on documentation/azure-devops/setup-build-pipeline.asciidoc
> +    -p               Open the Pull Request on the web browser if the merging fails. Accepted values: true, false.
```suggestion
    -b    [Required] Name of the branch to which the Pull Request will target. PR is not created if the flag is not provided.
    -p               Open the Pull Request on the web browser if it cannot be automatically merged. Requires -b flag.
```

2021-12-28 13:31 UTC, albertdb commented on scripts/pipelines/azure-devops/build_pipeline_generator.sh
> +    pr=$(az repos pr create --source-branch feature/build-pipeline --target-branch $branch --title "Build Merge" --auto-complete true)
```suggestion
    pr=$(az repos pr create --source-branch feature/build-pipeline --target-branch $branch --title "Build Pipeline" --auto-complete true)
```

2021-12-28 13:31 UTC, albertdb commented on scripts/pipelines/azure-devops/build_pipeline_generator.sh
> +    exit
```suggestion
    exit 2
```

Exit code 2 is usually used when user input is invalid. Anyway, it shouldn't be 0 (the default for success).

2021-12-28 13:31 UTC, albertdb commented on scripts/pipelines/azure-devops/build_pipeline_generator.sh
> +        p) openPR=${OPTARG};;
`-p` shouldn't require a value in order to work.

2022-01-07 10:54 UTC, albertdb approved these changes

2022-01-07 10:54 UTC, albertdb requested changes

2022-01-07 10:54 UTC, albertdb commented on .scripts/quarkus-build.sh
> +mvn package
Add shebang

2022-01-07 11:01 UTC, albertdb submitted a review, later dismissed

2022-01-07 11:57 UTC, albertdb approved these changes

2022-01-07 13:17 UTC, albertdb approved these changes

2022-01-07 13:18 UTC, isandesh1986 approved these changes

2022-01-07 13:20 UTC, merged