Feature/gcloud-create-project
devonfw/hangar pull request #236
Opened 2022-09-20 13:02 UTC by mcerverc

2022-09-26 18:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw/hangar?pullRequest=236) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/devonfw/hangar?pullRequest=236) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: mcerverc<br/>:x: abcarcol<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw/hangar?pullRequest=236) it.</sub>

2022-09-26 18:59 UTC, abcarcol submitted a review, later dismissed

2022-10-03 14:55 UTC, albertdb requested changes

2022-10-03 14:55 UTC, albertdb commented on documentation/gcloud/setup-project.asciidoc
> +By the end of this guide a new project in Google Cloud will be created.
We do more things. Try to answer this question: A project with what? Permissions to APIs and such. Try to explain it in plain but concise words.

2022-10-03 14:55 UTC, albertdb commented on documentation/gcloud/setup-project.asciidoc
> +· Install the https://cloud.google.com/sdk/docs/install?hl=en[Google Cloud CLI].
```suggestion
. Install the https://cloud.google.com/sdk/docs/install?hl=en[Google Cloud CLI].
```

2022-10-03 14:55 UTC, albertdb commented on documentation/gcloud/setup-project.asciidoc
> +. Create it manually using the web interface following https://cloud.google.com/resource-manager/docs/creating-managing-projects#console[Google Cloud official guide].
If the user does that, will be missing some APIs, you should mention them for it to be a valid alternative.

2022-10-03 14:55 UTC, albertdb commented on documentation/gcloud/setup-project.asciidoc
> +-o    [Optional] Numeric ID of the organization for which the project will be configured.
Remove [Optional] to be consistent with other guides.

2022-10-03 14:55 UTC, albertdb commented on documentation/gcloud/setup-project.asciidoc
> +-b    [Optional] Billing account. If not specified, won't be able to enable some services.
For me this is a required one, otherwise we won't be able to proceed. (move it below name, then)

2022-10-03 14:55 UTC, albertdb commented on documentation/gcloud/setup-project.asciidoc
> +`./create-project.sh -n "project-test-123" -d "This is a sample application" -f 12345 -o 2048`
Better skip folder and organization (if you want to keep it simple) and put the billing one.

2022-10-03 14:55 UTC, albertdb commented on scripts/accounts/gcloud/create-project.sh
> +   echo "Usage: $0 -n projectName -d description -o organization. "
Better follow this style of help: https://github.com/devonfw/hangar/blob/master/scripts/accounts/aws/create-user.sh

2022-10-03 14:55 UTC, albertdb commented on scripts/accounts/gcloud/create-project.sh
> +   echo -e "\t-d [Optional] Description for the new project. If not specified, name will be used as description"
It seems you forgot to copy full flag description to guide.

2022-10-03 14:55 UTC, albertdb commented on scripts/accounts/gcloud/create-project.sh
> +if [ -z "$projectName" ]
Remember to add billing

2022-10-03 14:55 UTC, albertdb commented on scripts/accounts/gcloud/create-project.sh
> +echo -ne ${white}
Marking as resolved won't stop sonatype complaining XD

2022-10-03 14:55 UTC, albertdb commented on scripts/accounts/gcloud/create-project.sh
> +if ! [ $? -eq 0 ]
Same as before.

2022-10-03 14:55 UTC, albertdb commented on scripts/accounts/gcloud/create-project.sh
> +   echo "Linking project to billing account"
```suggestion
   echo "Linking project to billing account..."
```

2022-10-03 14:55 UTC, albertdb commented on scripts/accounts/gcloud/create-project.sh
> +   echo "Enabling sourcerepo service"
```suggestion
   echo "Enabling Cloud Source Repositories..."
```

2022-10-03 14:55 UTC, albertdb commented on scripts/accounts/gcloud/create-project.sh
> +   echo "Enabling run service"
```suggestion
   echo "Enabling CloudRun..."
```

2022-10-03 14:55 UTC, albertdb commented on scripts/accounts/gcloud/create-project.sh
> +   echo "Enabling artifact registry"
```suggestion
   echo "Enabling Artifact Registry..."
```

2022-10-05 15:09 UTC, albertdb requested changes

2022-10-05 15:09 UTC, albertdb commented on documentation/gcloud/setup-project.asciidoc
> +.. Enable ```Cloud Source Repositories API, Cloud Run Admin API, Artifact Registry API``` following the https://cloud.google.com/endpoints/docs/openapi/enable-api#enabling_an_api[Enablig an API guide
```suggestion
.. Enable `Cloud Source Repositories`, `Cloud Run Admin`, and `Artifact Registry` APIs following https://cloud.google.com/endpoints/docs/openapi/enable-api#console[official guide]
```

2022-10-05 15:09 UTC, albertdb commented on documentation/gcloud/setup-project.asciidoc
> +The script located at `scripts/accounts/gcloud/create-project.sh` enables you to create a new Google Cloud project or configure an existing one.
```suggestion
The script located at `scripts/accounts/gcloud/create-project.sh` enables you to create and configure a new Google Cloud project.
```

It does not allow to configure an existing one

2022-10-05 15:09 UTC, albertdb commented on documentation/gcloud/setup-project.asciidoc
> +```
````suggestion
-o               Numeric ID of the organization for which the project will be configured.
```
````

2022-10-05 15:09 UTC, albertdb commented on scripts/accounts/gcloud/create-project.sh
> +if [ "$1" == "-h" ];
I was meaning the style of the help message, please keep help function as it was, it also avoids Sonatype complaints.

2022-10-05 15:09 UTC, albertdb commented on scripts/accounts/gcloud/create-project.sh
> +   echo -e "\t-o            Numeric ID of the organization for which the project will be configured."
Whitespaces preferred over tabs, check mentioned script in previous review,

2022-10-05 15:09 UTC, albertdb commented on scripts/accounts/gcloud/create-project.sh
> +if ! [ $? -eq 0 ]
@mcerverc Still pending

2022-10-05 15:09 UTC, albertdb commented on scripts/accounts/gcloud/create-project.sh
> +gcloud services enable artifactregistry.googleapis.com --project "$projectName"
Missing error handling.

2022-10-07 07:33 UTC, mcerverc commented on scripts/accounts/gcloud/create-project.sh
> +   case "$opt" in
No problem with invalid flags. The script will just ignore them. We do not handle in any hangar script

2022-10-11 13:50 UTC, abcarcol requested changes

2022-10-11 14:14 UTC, abcarcol commented on scripts/accounts/gcloud/create-project.sh
> +if ! gcloud services enable artifactregistry.googleapis.com --project "$projectName" ; then echo -e "${red}ERROR: Unable to enable Artifact Registry API"; exit 2; fi
```suggestion
echo -e "${white}Creating project $projectName..."
if ! eval "$command"; 
then 
    echo -e "${red}Error while creating the project."; 
    exit 200;
else
    echo -e "${green}Created project $projectName successfully."
fi

echo -e "${white}Linking project to billing account..."
if ! gcloud beta billing projects link "$projectName" --billing-account "$billing" ; 
then 
    echo -e "${red}ERROR: Unable to link project to billing account"; 
    exit 210; 
else
    echo -e "${green}Linked project to billing account successfully"; 
fi
echo -e "${white}Enabling Cloud Source Repositories..."
if ! gcloud services enable sourcerepo.googleapis.com --project "$projectName" ; 
then 
    echo -e "${red}ERROR: Unable to enable Cloud Source Repositories API"; 
    exit 220; 
else
    echo -e "${green}Enabled Cloud Source Repositories API successfully";
fi
echo -e "${white}Enabling CloudRun..."
if ! gcloud services enable run.googleapis.com --project "$projectName" ; 
then 
    echo -e "${red}ERROR: Unable to enable CloudRun API"; 
    exit 221; 
else
    echo -e "${green}Enabled CloudRun API successfully";
fi
echo -e "${white}Enabling Artifact Registry..."
if ! gcloud services enable artifactregistry.googleapis.com --project "$projectName" ; 
then 
    echo -e "${red}ERROR: Unable to enable Artifact Registry API"; 
    exit 222; 
else
    echo -e "${green}Enabled Artifact Registry API successfully";
fi
```

2022-10-12 13:27 UTC, jrodenasCapgemini commented on scripts/accounts/gcloud/create-project.sh
> +   echo -e "${red}Use -h flag to display help." >&2
```suggestion
   echo -e "${red}Use -h flag to display help." >&2
   echo -e "${white}"
   helpFunction
```

2022-10-12 13:30 UTC, jrodenasCapgemini commented on scripts/accounts/gcloud/create-project.sh
> +
```suggestion
# Check if exists a Google Cloud project with that project ID. 
if gcloud projects describe $projectName &>/dev/null ; then
     echo -e "${red}Error: Project ID already exists. Try another Project ID for the project." >&2
     echo -e "${white}"
     exit 2
fi
```

2022-10-12 13:31 UTC, jrodenasCapgemini commented on scripts/accounts/gcloud/create-project.sh
> +if ! eval "$command"; then echo -e "${red}Error while creating the project."; exit 2; fi
```suggestion
if ! eval "$command"
then
    echo -e "${red}Error while creating the project." >&2
    echo -e "${white}"
    exit 2
fi
```

2022-10-13 07:14 UTC, mcerverc commented on scripts/accounts/gcloud/create-project.sh
> +if ! gcloud services enable artifactregistry.googleapis.com --project "$projectName" ; then echo -e "${red}ERROR: Unable to enable Artifact Registry API"; exit 2; fi
Do you think is mandatory to indent the code like that? IMO is more readable with the if short form

2022-10-13 07:15 UTC, mcerverc commented on scripts/accounts/gcloud/create-project.sh
> +if ! gcloud services enable artifactregistry.googleapis.com --project "$projectName" ; then echo -e "${red}ERROR: Unable to enable Artifact Registry API"; exit 2; fi
I modified the exit codes like you suggest

2022-10-13 12:28 UTC, albertdb requested changes

2022-10-13 12:46 UTC, albertdb approved these changes

2022-10-13 15:51 UTC, merged