WIP: 234 investigate if an all in one docker image is viable
devonfw/hangar pull request #239
Opened 2022-09-23 13:14 UTC by lpinon

2022-09-23 13:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw/hangar?pullRequest=239) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/devonfw/hangar?pullRequest=239) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw/hangar?pullRequest=239) it.</sub>

2022-10-05 15:44 UTC, albertdb requested changes

2022-10-05 15:44 UTC, albertdb commented on setup/README.asciidoc
> +. **Build** the image `docker build -t hangar -f .\setup\Dockerfile .`
```suggestion
. **Build** the image `docker build -t hangar -f ./setup/Dockerfile .`
```

Devonfw requires command to be Bash compatible.

2022-10-05 15:44 UTC, albertdb commented on setup/README.asciidoc
> +IMPORTANT: The container is Stateless -- all the information (credentials, configurations, etc.) created inside the session will be lost at the end of the lifecycle of the container.
```suggestion
WARNING: The container is stateless -- all the information (credentials, configurations, etc.) created inside the session will be lost at the end of the lifecycle of the container. 

```

2022-10-05 15:44 UTC, albertdb commented on setup/README.asciidoc
> +## Volumes Configuration
```suggestion
## Running container with persistence

```

2022-10-06 08:35 UTC, albertdb commented on setup/README.asciidoc
> +# All-in-one container image for running Hangar.
```suggestion
# All-in-one container image for running Hangar
```

2022-10-06 08:35 UTC, albertdb commented on setup/README.asciidoc
> +## Included Tools
```suggestion
## Included tools

```

2022-10-06 08:35 UTC, albertdb commented on setup/README.asciidoc
> +Following toolkits are included in the solution:
```suggestion
The following toolkits are included in the solution:
```

2022-10-07 11:47 UTC, albertdb approved these changes

2022-10-11 08:19 UTC, ultymatom commented on setup/README.asciidoc
> +docker run --rm -it -v /Users/$env:UserName/AppData/Roaming/gcloud:/root/.config/gcloud -v /Users/$env:UserName/.aws:/root/.aws -v /Users/$env:UserName/.azure:/root/.azure -v /Users/$env:UserName/.ku
I think there is an error on the paths,
on powershell, it should be :
```suggestion
docker run --rm -it -v C:\Users\$env:UserName\AppData\Roaming\gcloud\:/root/.config/gcloud -v C:\Users\$env:UserName\.aws:/root/.aws -v C:\Users\$env:UserName\.azure:/root/.azure -v C:\Users\$env:UserName\.kube:/root/.kube -v "C:\Users\$env:UserName\AppData\Roaming\GitHub CLI:/root/.config/gh" -v C:\Users\$env:UserName\.ssh:/root/.ssh hangar bash

```

2022-10-11 08:24 UTC, ultymatom commented on setup/Dockerfile
> +RUN apt-get update && apt-get install --no-install-recommends curl unzip git wget -y && apt-get clean && rm -rf /var/lib/apt/lists/*
I needed to install less to be able to make it work
```suggestion
RUN apt-get update && apt-get install --no-install-recommends curl unzip git wget less -y && apt-get clean && rm -rf /var/lib/apt/lists/*

```

2022-10-11 08:59 UTC, lpinon commented on setup/README.asciidoc
> +docker run --rm -it -v /Users/$env:UserName/AppData/Roaming/gcloud:/root/.config/gcloud -v /Users/$env:UserName/.aws:/root/.aws -v /Users/$env:UserName/.azure:/root/.azure -v /Users/$env:UserName/.ku
Added as alternative

2022-10-11 09:00 UTC, ultymatom approved these changes

2022-10-11 09:38 UTC, albertdb approved these changes

2022-10-11 11:06 UTC, merged