Documentation + script
devonfw/hangar pull request #24
Opened 2021-11-15 09:41 UTC by mcerverc

2021-11-15 09:42 UTC, mcerverc commented
I finally have finished my fight versus GitGuardian :)

2021-11-15 14:46 UTC, jbellver99 requested changes

2021-11-15 14:46 UTC, jbellver99 commented on documentation/tutorial-prepare-aws.asciidoc
> +In this section it is going to be created a new user and a new group. Necessary policies to allow permissions will be attached to this group and the user will be added to it.
```suggestion
In this section a new user and an new group will be created. The user will be added to this group and the necessary policies to allow permissions will be attached.
```

2021-11-15 14:46 UTC, jbellver99 commented on documentation/tutorial-prepare-aws.asciidoc
> +Now you have your AWS account ready to use.
As commented in the meeting, try to change this section into something more simple, so it does not look like a repetition of the other section.

2021-11-15 16:00 UTC, mcerverc commented on documentation/tutorial-prepare-aws.asciidoc
> +Now you have your AWS account ready to use.
Solved in the new commit

2021-11-16 08:00 UTC, jbellver99 requested changes

2021-11-16 08:00 UTC, jbellver99 commented on documentation/tutorial-prepare-aws.asciidoc
> +Now you have your AWS account ready to use.
Add a message or warning in order to let the user know that if they have executed the script form the previous section there is no need to do this section.

2021-11-16 08:21 UTC, mcerverc commented on documentation/tutorial-prepare-aws.asciidoc
> +Now you have your AWS account ready to use.
In this final section, the user is configuring his new AWS user in his AWS console. Everyone needs to do this step

2021-11-17 10:10 UTC, jbellver99 requested changes

2021-11-17 15:39 UTC, mcerverc commented on documentation/tutorial-prepare-aws.asciidoc
> +== Configure AWS Cli [[configure-cli]]
In this final section, the user is configuring his new AWS user in his AWS console. Everyone needs to do this step

2021-11-17 17:06 UTC, albertdb requested changes

2021-11-17 17:06 UTC, albertdb commented on scripts/create-user/aws/create-user.sh
> +aws iam create-group --group-name $groupname > /dev/null
Improve group so it supports using an already created group (you will need to check if it exists or blindly try and check if it succeeded)

2021-11-17 17:06 UTC, albertdb commented on scripts/create-user/aws/create-user.sh
> +aws iam attach-group-policy --group-name $groupname --policy-arn arn:aws:iam::aws:policy/AmazonEKSVPCResourceController
It would be better if the policies are provided as a comma separated list with a new flag. This way we can change just the guide later on if new policies are required.

2021-11-17 17:06 UTC, albertdb commented on scripts/create-user/aws/create-user.sh
> +echo $username" is ready. Please store the following access data securely:"
```suggestion
echo "User $username is ready. Please store the following access data securely:"
```

2021-11-22 08:13 UTC, jbellver99 requested changes

2021-11-22 08:13 UTC, jbellver99 commented on documentation/tutorial-prepare-aws.asciidoc
> +First of all, [install AWS CLI for your OS](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html).
```suggestion
First of all, [install AWS CLI for your OS](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html).
```

2021-11-22 08:13 UTC, jbellver99 commented on documentation/tutorial-prepare-aws.asciidoc
> +The script located at `/scripts/accounts/aws/create-user.sh` will assist you in the creation of a user, also enrolling it in a newly created group with the required policies attached.
```suggestion
The script located at `/scripts/accounts/aws/create-user.sh` will automatically create a user, also enrolling it in a newly created group with the required policies attached.
```

2021-11-22 08:13 UTC, jbellver99 commented on documentation/tutorial-prepare-aws.asciidoc
> +In case you do not have an AWS access key (needed to authenticate through API), follow [this guide](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html#Using_CreateAccess
```suggestion
In case you do not have an AWS access key (needed to authenticate through API), follow [this guide](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html#Using_CreateAccessKey) to create it.
```

2021-11-22 08:13 UTC, jbellver99 commented on documentation/tutorial-prepare-aws.asciidoc
> +IMPORTANT: It is mandatory to store the access key ID and the secret access key securely at this point, as *the will not be retrievable again*.
Add a usage example of the type ./create-user.sh -u ...
In order to let the user know how to execute the script and how the flags are inputed.

2021-11-30 16:42 UTC, albertdb requested changes
Move guide file to `documentation/aws/setup-aws-account-iam-for-eks.asciidoc`.

2021-11-30 16:42 UTC, albertdb commented on documentation/tutorial-prepare-aws.asciidoc
> +The scope of this section is to prepare an AWS account to be ready for deployment from Azure DevOps to AWS EKS. By the end of this guide, a new user with the required permissions will be created.
```suggestion
= Setup AWS account IAM for deployment in EKS
The scope of this section is to prepare an AWS account to be ready for deploying in AWS EKS. By the end of this guide, a new IAM user belonging to a group with the required permissions will be created.
```

2021-11-30 16:42 UTC, albertdb commented on documentation/tutorial-prepare-aws.asciidoc
> +
```suggestion
==Prerequisites

* An AWS account with IAM full access permission.
```

2021-11-30 16:42 UTC, albertdb commented on documentation/tutorial-prepare-aws.asciidoc
> +In case you do not have permission to create new IAM users, request it to your AWS administrator asking for the following policies attached. Then go to <<configure-cli>>.
```suggestion
In case you do not have an account or permission to create new IAM users, request it to your AWS administrator asking for the following policies attached. Then go to <<configure-cli>>.
```

2021-11-30 16:42 UTC, albertdb commented on documentation/tutorial-prepare-aws.asciidoc
> +== Using the script to create the user
```suggestion
== Creating IAM user using provided script
```

2021-11-30 16:53 UTC, albertdb commented on documentation/tutorial-prepare-aws.asciidoc
> +
```suggestion
NOTE: If the "DevOps" group does not exist, it will be created.
```

2021-11-30 17:03 UTC, jbellver99 approved these changes

2021-11-30 17:04 UTC, merged

2021-12-07 14:33 UTC, albertdb commented
closes #2