feature/create-repo-gcloud
devonfw/hangar pull request #246
Opened 2022-09-27 11:57 UTC by mcerverc

2022-10-03 15:04 UTC, albertdb commented on documentation/gcloud/setup-repository-script.asciidoc
> += Setting up a repository on Google Cloud
Please refactor documentation, this is a copy of other guides with some keywords replaced.

2022-10-03 15:16 UTC, albertdb submitted a review, later dismissed

2022-10-03 15:16 UTC, albertdb commented on scripts/repositories/common/create-repo.sh
> +  echo "Creates or imports a repository."
You can define a variable on provider script with the provider name instead of making generic.

2022-10-03 15:16 UTC, albertdb commented on scripts/repositories/common/create-repo.sh
> +  echo "  - Import an already existing directory or Git repository into your project giving a path or an URL. Useful for taking to a cloud platform the development of an existing project"
Same for this

2022-10-03 15:16 UTC, albertdb commented on scripts/repositories/common/create-repo.sh
> +  echo "  -n, --name                               Name for the repository. By default, the source repository or directory name (either new or existing, depending on use case) is used."
And this

2022-10-03 15:16 UTC, albertdb commented on scripts/repositories/common/create-repo.sh
> -  echo "  -p, --project           [Azure Required] Name of the Azure DevOps project."
Better conditionally (to the provider) print the [Required] keyword.

2022-10-03 15:16 UTC, albertdb commented on scripts/repositories/gcloud/create-repo.sh
> +    #We redirect the output to a tmp file to be able to parse the content and get the repository Id we will need later
Really?

2022-10-03 15:16 UTC, albertdb commented on scripts/repositories/gcloud/create-repo.sh
> +    nothing=""
Some comment won't hurt.

2022-10-03 15:16 UTC, albertdb commented on scripts/repositories/gcloud/create-repo.sh
> +    ghuser=""
Some comment won't hurt.

2022-10-11 07:12 UTC, ultymatom commented on documentation/azure-devops/setup-build-pipeline.asciidoc
> +[subs="attributes"]
Why this have changed ?

2022-10-11 07:14 UTC, ultymatom commented on documentation/azure-devops/setup-repository-script.asciidoc
> +:provider_name: Azure DevOps
why this file has changed ?

2022-10-11 07:16 UTC, ultymatom commented on documentation/github/setup-build-pipeline.asciidoc
> +[subs="attributes"]
why this file has changed ?

2022-10-11 07:18 UTC, ultymatom commented on scripts/repositories/github/create-repo.sh
> +#!/bin/bash
same than for azure-devops

2022-10-11 07:20 UTC, ultymatom commented on scripts/repositories/gcloud/create-repo.sh
> +    nothing=""
I would not define the function if it does nothing, and when calling it use the type function
as in the pipeline generator:
![image](https://user-images.githubusercontent.com/90399827/195021747-b463d6a9-c549-4212-86e5-627aa007c52e.png)

2022-10-11 07:20 UTC, ultymatom commented on scripts/repositories/gcloud/create-repo.sh
> +    nothing=""
I would not define the function if it does nothing, and when calling it use the type function
as in the pipeline generator:
![image](https://user-images.githubusercontent.com/90399827/195021747-b463d6a9-c549-4212-86e5-627aa007c52e.png)

2022-10-11 07:55 UTC, mcerverc commented on documentation/azure-devops/setup-build-pipeline.asciidoc
> +[subs="attributes"]
I did a full refactor of create-repo documentation. Created a common template and unificated doc style

2022-10-11 07:55 UTC, mcerverc commented on documentation/github/setup-build-pipeline.asciidoc
> +[subs="attributes"]
Explained upper

2022-10-11 07:56 UTC, mcerverc commented on scripts/repositories/azure-devops/create-repo.sh
> +#!/bin/bash
Explained upper

2022-10-11 07:56 UTC, mcerverc commented on scripts/repositories/github/create-repo.sh
> +#!/bin/bash
Explained upper

2022-10-12 14:24 UTC, jrodenasCapgemini commented on scripts/repositories/common/create-repo.sh
> +
```suggestion
# exit when any command fails
set -e
```

2022-10-12 14:28 UTC, jrodenasCapgemini commented on scripts/repositories/common/create-repo.sh
>    echo -e "${blue}Setting policies for the repository. ${white}"
```suggestion
  echo -e "${blue}Setting policies for the repository."
  echo -e "${white}"
```

2022-10-13 09:00 UTC, jrodenasCapgemini commented on scripts/repositories/azure-devops/create-repo.sh
> +    echo "Use -h or --help flag to display help."
```suggestion
    echo "Use -h or --help flag to display help."
    echo -e "${white}"
```

2022-10-13 09:38 UTC, jrodenasCapgemini commented on scripts/repositories/gcloud/create-repo.sh
> +        echo "Use -h or --help flag to display help."
```suggestion
        echo "${white}Use -h or --help flag to display help."
```

2022-10-13 12:54 UTC, albertdb commented on documentation/azure-devops/setup-build-pipeline.asciidoc
> +[subs="attributes"]
@mcerverc right, but this is build pipeline documentation file. Revert changes in src.

2022-10-13 13:38 UTC, jrodenasCapgemini commented on scripts/repositories/common/create-repo.sh
> +  echo "  - Import an already existing directory or Git repository into your project giving a path or an URL. Useful for taking to $provider the development of an existing project"
```suggestion
  echo "  - Import an already existing directory or Git repository into your project giving a path or an URL. Useful for taking to $provider the development of an existing project."
```

2022-10-13 13:38 UTC, jrodenasCapgemini commented on scripts/repositories/common/create-repo.sh
>    MSG_ERROR "Setting 'master' branch as default branch" $?
```suggestion
  MSG_ERROR "Setting 'master' branch as default branch." $?
```

2022-10-13 14:06 UTC, albertdb requested changes

2022-10-13 14:16 UTC, jrodenasCapgemini requested changes
Insert final dot in these lines: 195,197, 218, 242, 247, 250, 252, 254, 398, 425, 432, 434, 436, 443, 449,464,468.
Use capital letter in these lines: 254, 449

2022-10-13 14:47 UTC, albertdb commented
> Insert final dot in these lines: 195,197, 218, 242, 247, 250, 252, 254, 398, 425, 432, 434, 436, 443, 449,464,468. Use capital letter in these lines: 254, 449

You are not specifying which file.

2022-10-13 14:48 UTC, mcerverc commented
> Insert final dot in these lines: 195,197, 218, 242, 247, 250, 252, 254, 398, 425, 432, 434, 436, 443, 449,464,468. Use capital letter in these lines: 254, 449

I thought we were friends.. xD Done.

2022-10-13 15:34 UTC, albertdb requested changes

2022-10-13 15:34 UTC, albertdb commented on scripts/repositories/common/create-repo.sh
> +      echo "  -u, --public                             Repository scope. Private by default"
```suggestion
      echo "  -u, --public                             Sets repository scope to public. Private otherwise."
```

2022-10-13 15:40 UTC, albertdb commented on documentation/src/gcloud/setup-repository-script.asciidoc
> +-p, --project               [Required] Name of the Google Cloud project.
```suggestion
-p, --project               [Required] Short name (ID) of the Google Cloud project.
```

2022-10-13 15:41 UTC, albertdb commented on documentation/src/azure-devops/setup-repository-script.asciidoc
> +    -p <project> \
```suggestion
    -p <project name> \
```

2022-10-13 15:42 UTC, albertdb commented on documentation/src/gcloud/setup-repository-script.asciidoc
> +    -p <project> \
```suggestion
    -p <project id> \
```

2022-10-13 15:43 UTC, albertdb commented on scripts/repositories/common/create-repo.sh
> +      echo "  -p, --project           [Required] Name of the project."
```suggestion
      echo "  -p, --project           [Required] Short name (ID) of the project."
```

2022-10-13 15:44 UTC, albertdb approved these changes

2022-10-13 15:46 UTC, jrodenasCapgemini approved these changes

2022-10-13 16:05 UTC, jrodenasCapgemini approved these changes

2022-10-14 07:02 UTC, merged