Feature/block7 sonarqubeinstance
devonfw/hangar pull request #25
Opened 2021-11-15 13:17 UTC by yildserd

2021-11-15 13:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw/hangar?pullRequest=25) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/devonfw/hangar?pullRequest=25) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw/hangar?pullRequest=25) it.</sub>

2021-11-22 08:43 UTC, jbellver99 requested changes

2021-11-22 08:43 UTC, jbellver99 commented on documentation/sonarqubedoc/sonarqubeinstance.asciidoc
> +== Sonarqube instance in aws
```suggestion
= Setting up a SonarQube instance in AWS
```

2021-11-22 08:43 UTC, jbellver99 commented on documentation/sonarqubedoc/sonarqubeinstance.asciidoc
> +This repository will show you how to deploy a aws instance with sonarqube on it. This script lauch a sonarqube with an embedded database.
```suggestion
The scope of this section is to deploy an AWS instance with SonarQube. A script has been created in order to assist you in the launching of a SonarQube instance with an embedded database.
```

2021-11-22 08:43 UTC, jbellver99 commented on documentation/sonarqubedoc/sonarqubeinstance.asciidoc
> +* https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html[aws cli]
```suggestion
=== Prerequisites
* https://learn.hashicorp.com/collections/terraform/aws-get-started?utm_source=terraform_io&utm_content=terraform_io_footer[Install Terraform].

* https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html[Install the AWS CLI].
```

2021-11-22 08:43 UTC, jbellver99 commented on documentation/sonarqubedoc/sonarqubeinstance.asciidoc
> +== available scripts
```suggestion
== The scripts
```

2021-11-22 08:43 UTC, jbellver99 commented on documentation/sonarqubedoc/sonarqubeinstance.asciidoc
> +* `terraform.tfvars` parameters for the variables (changeable)
```suggestion
* `main.tf` this script will deploy the AWS infrastructure.
* `datascript.sh` this script will install Docker on your EC2 instance, and deploy a container running SonarQube.
* `variables.tf` this script contains the variables for the script main.tf.
* `terraform.tfvars` this script contains the parameters for the variables (changeable).
```

2021-11-22 08:43 UTC, jbellver99 commented on documentation/sonarqubedoc/sonarqubeinstance.asciidoc
> +== Using the script
```suggestion
== Usage
```

2021-11-22 08:43 UTC, jbellver99 commented on documentation/sonarqubedoc/sonarqubeinstance.asciidoc
> +Downloade the files from `...scripts/terrafom/aws/sonarqube`. Open the file `terraform.tfvars` and edit the changes of the parameter you need.
```suggestion
Download the files from `...scripts/terrafom/aws/sonarqube`. Open the file `terraform.tfvars` and edit the needed parameters. 
```

2021-11-22 08:43 UTC, jbellver99 commented on documentation/sonarqubedoc/sonarqubeinstance.asciidoc
> +Downloade the files from `...scripts/terrafom/aws/sonarqube`. Open the file `terraform.tfvars` and edit the changes of the parameter you need.
Add the full path to the scripts.

2021-11-22 08:43 UTC, jbellver99 commented on documentation/sonarqubedoc/sonarqubeinstance.asciidoc
> +IMPORTANT: If you don´t want to chang the Parameters, you will need a Keypair withe the name `sonarqube`.
```suggestion
IMPORTANT: If you do not want to change the parameters, you will need a Keypair with the name `sonarqube`.
```

2021-11-22 08:43 UTC, jbellver99 commented on documentation/sonarqubedoc/sonarqubeinstance.asciidoc
> +Run the following commads on your comand promt.
```suggestion
Run the following commands on your command prompt.
```

2021-11-22 08:43 UTC, jbellver99 commented on documentation/sonarqubedoc/sonarqubeinstance.asciidoc
> +This command run the script and creat ec2 instance with Ubuntu in aws and deploy a docker container with a sonarqube image on it. In the comand promter you will see the Ip-Adress of the ec2 instance.
Create a script with this commands so that the user can execute this script and not execute command by command

2021-11-22 08:43 UTC, jbellver99 commented on documentation/sonarqubedoc/sonarqubeinstance.asciidoc
> +After the succesfull deployment type in your Brwoser `+http://localhost:9000+`(replace localhost with the ec2 instance IP-Adress from the output on the comand promt) and you will have acces to sonarq
```suggestion
Once the deployment has finished type `+http://localhost:9000+`(replace localhost with the ec2 instance IP-Address from the output on the command prompt) in your browser and you will have access to your SonarQube. The default values are :
```

2021-11-22 08:43 UTC, jbellver99 commented on scripts/aws/sonarqubeinstance/datascript.sh
> +                echo "skript end"
```suggestion
                echo "script end"
```

2021-12-07 16:04 UTC, albertdb requested changes
Good but needs some improvements and polishing.

2021-12-07 16:04 UTC, albertdb commented on scripts/aws/sonarqubeinstance/variables.tf
> +
```suggestion
```

Not used.

2021-12-13 09:13 UTC, jbellver99 requested changes

2021-12-13 09:13 UTC, jbellver99 commented on documentation/sonarqubedoc/sonarqubeinstance.asciidoc
> +* `execute.sh` creat the AWS instance with a Docker container wich run SonarQube.
```suggestion
* `execute.sh` create the AWS EC2 instance with a Docker container which run SonarQube. 
```

2021-12-13 09:13 UTC, jbellver99 commented on documentation/sonarqubedoc/sonarqubeinstance.asciidoc
> +According to this, it will create an ec2 instance with Ubuntu in aws and deploy a Docker container with a SonarQube image on it.  On the command line, you will see the IP address of the EC2 instance.
```suggestion
According to this, it will create an EC2 instance with Ubuntu in AWS and deploy a Docker container with a SonarQube image on it.  On the command line, you will see the IP address of the EC2 instance.
```

2021-12-13 09:13 UTC, jbellver99 commented on scripts/aws/sonarqubeinstance/main.tf
> +#creat internet gateway
```suggestion
#create internet gateway
```

2021-12-13 09:13 UTC, jbellver99 commented on scripts/aws/sonarqubeinstance/main.tf
> +#routtable assoiation
```suggestion
#route table association
```

2021-12-14 04:33 UTC, isandesh1986 commented on scripts/aws/sonarqubeinstance/execute.sh
> +terrafrom init
Just stumbled upon this...Please correct "terraform" spelling.

2021-12-16 08:57 UTC, albertdb commented on documentation/sonarqubedoc/sonarqubeinstance.asciidoc
> + password:   *admin*
Still relevant. Terraform command and its explanation should be on the document, not in a separate script. Sorry for not being totally clear.

2021-12-16 08:57 UTC, albertdb commented on scripts/aws/sonarqubeinstance/datascript.sh
> +                echo "script end"
Still relevant. Now the script has comment, but does not `echo` what is doing

2022-01-07 10:59 UTC, jbellver99 requested changes

2022-01-07 10:59 UTC, jbellver99 commented on documentation/sonarqubedoc/sonarqubeinstance.asciidoc
> +* `execute.sh` create the AWS EC2 instance with a Docker container which run SonarQube.
```suggestion
```

2022-01-07 10:59 UTC, jbellver99 commented on scripts/aws/sonarqubeinstance/datascript.sh
> +#getting the long term support version of an sonarqube image. Here it is Version 8.9.3
```suggestion
#getting the long term support version of an sonarqube image.
```

2022-01-07 10:59 UTC, jbellver99 commented on scripts/aws/sonarqubeinstance/main.tf
> +#create costum route table
```suggestion
#create custom route table
```

2022-01-07 10:59 UTC, jbellver99 commented on scripts/aws/sonarqubeinstance/main.tf
> +
```suggestion
resource "aws_route_table" "sqroutetable" {
  vpc_id = aws_vpc.sq_vpc.id

  tags = {
    Name = "sqroutetable"
  }
}

```

2022-01-07 10:59 UTC, jbellver99 commented on scripts/aws/sonarqubeinstance/main.tf
> +  route_table_id         = aws_route_table.sqrouttable.id
```suggestion
  route_table_id         = aws_route_table.sqroutetable.id
```

2022-01-07 10:59 UTC, jbellver99 commented on scripts/aws/sonarqubeinstance/main.tf
> +  route_table_id = aws_route_table.sqrouttable.id
```suggestion
  route_table_id = aws_route_table.sqroutetable.id
```

2022-01-07 10:59 UTC, jbellver99 commented on scripts/aws/sonarqubeinstance/main.tf
> +#create securitygroup
```suggestion
#create security group
```

2022-01-07 10:59 UTC, jbellver99 commented on scripts/aws/sonarqubeinstance/main.tf
> +#networkinterface
```suggestion
#network interface
```

2022-01-07 10:59 UTC, jbellver99 commented on scripts/aws/sonarqubeinstance/main.tf
> +  user_data = file("./datascript.sh")
```suggestion
  user_data = file("./setup_sonarqube.sh")
```

2022-01-07 10:59 UTC, jbellver99 commented on scripts/aws/sonarqubeinstance/main.tf
> +#Get Ubuntu 20.04 AMI for EC Instanz
```suggestion
#Get Ubuntu 20.04 AMI for EC Instance
```

2022-01-07 10:59 UTC, jbellver99 commented on scripts/aws/sonarqubeinstance/terraform.tfvars
> +#Parameter for the privat ip from the nic. Need to be an ip from subnet
```suggestion
#Parameter for the private IP from the nic. Need to be an IP from subnet
```

2022-01-07 10:59 UTC, jbellver99 commented on scripts/aws/sonarqubeinstance/terraform.tfvars
> +#Parameter of the instance type of the ec2 Instance
```suggestion
#Parameter of the instance type of the EC2 Instance
```

2022-01-07 10:59 UTC, jbellver99 commented on scripts/aws/sonarqubeinstance/variables.tf
> +
```suggestion
```

2022-01-13 16:09 UTC, jbellver99 approved these changes

2022-02-03 17:39 UTC, albertdb approved these changes

2022-02-03 17:40 UTC, merged