added script for GCP user management
devonfw/hangar pull request #251
Opened 2022-10-10 07:08 UTC by abcarcol

2022-10-10 07:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw/hangar?pullRequest=251) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/devonfw/hangar?pullRequest=251) before we can accept your contribution.<br/><hr/>**Abel Antonio Carrion Collado** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw/hangar?pullRequest=251) it.</sub>

2022-10-10 07:12 UTC, abcarcol commented on scripts/accounts/gcp/setup-principal-account.sh
> +    case "${flag}" in
Scripts in hangar do not use the "*)" case.

2022-10-12 13:57 UTC, jrodenasCapgemini commented on scripts/accounts/gcp/setup-principal-account.sh
> +#!/bin/bash
```suggestion
#!/bin/bash

# exit when any command fails
set -e

```

2022-10-12 14:06 UTC, jrodenasCapgemini commented on scripts/accounts/gcp/setup-principal-account.sh
> +        echo -e "${green}Current project set to $project_id." >&2
```suggestion
    echo -e "${red}Use -h flag to display help." >&2
    echo -e "${white}"
    exit 2
fi

#Only google_account or service_account allowed
if [ -n "$google_account" ] && [ -n "$service_account" ];
then
    echo -e "${red}Error: Parameters -g or -s are mutually exclusive." >&2
    echo -e "${red}Use -h flag to display help." >&2
    echo -e "${white}"
    exit 2
fi

if { [ "$custom_role_file" ] && [ -z "$custom_role_id" ]; } || { [ -z "$custom_role_file" ] && [ "$custom_role_id" ]; };
then
    echo -e "${red}Error: -c and -i parameters must be used together." >&2
    echo -e "${red}Use -h flag to display help." >&2
    echo -e "${white}"
    exit 2
fi

#Check if GCP CLI is installed
if ! [ -x "$(command -v gcloud)" ]; then
  echo -e "${red}Error: GCP CLI is not installed." >&2
  echo -e "${white}"
  exit 127
fi

#Check if Python is installed
if ! [ -x "$(command -v python)" ]; then
  echo -e "${red}Error: Python is not installed." >&2
  echo -e "${white}"
  exit 127
fi

#Check if the provided project_id exists and in that case set it as working project
echo -e "${white}Checking provided project $project_id..."
if ! gcloud projects describe "$project_id" &> /dev/null;
then
    echo -e "${red}Error: The provided project ID does not exist. Please, create it first." >&2
    echo -e "${white}"
    exit 2
else
    echo -e "${white}Setting current project to $project_id..."
    if ! gcloud config set project "$project_id" &> /dev/null;
    then
        echo -e "${red}Error: Could not set current project to $project_id." >&2
        echo -e "${white}"
	exit 2
    else
        echo -e "${green}Current project set to $project_id." >&2
        echo -e "${white}"
```

2022-10-12 14:09 UTC, jrodenasCapgemini commented on scripts/accounts/gcp/setup-principal-account.sh
> +            echo -e "${green}Attached role $role_to_check to $memberValue in project $project_id."
```suggestion
	    echo -e "${red}Error: Attaching role $role_to_check to $memberValue in project $project_id." >&2
	    echo -e "${white}"
	    exit 2
	else
            echo -e "${green}Attached role $role_to_check to $memberValue in project $project_id."
            echo -e "${white}"
```

2022-10-12 14:11 UTC, jrodenasCapgemini commented on scripts/accounts/gcp/setup-principal-account.sh
> +        echo -e "${green}Attached custom role $custom_role_id to $memberValue in project $project_id successfully."
```suggestion
        echo -e "${red}Error: Creating custom role $custom_role_id for project $project_id." >&2
        echo -e "${white}"
	exit 2
    else
	echo -e "${green}Created custom role $custom_role_id for project $project_id successfully."
	echo -e "${white}"
    fi
    echo -e "${white}Binding role $custom_role_id to principal $memberValue in project $project_id..."
    if ! gcloud projects add-iam-policy-binding "$project_id" --member="$memberValue" --role=projects/$project_id/roles/$custom_role_id &> /dev/null;
    then
        echo -e "${red}Error: Attaching custom role $custom_role_id to $memberValue in project $project_id." >&2
        echo -e "${white}"
	exit 2
    else
        echo -e "${green}Attached custom role $custom_role_id to $memberValue in project $project_id successfully."
        echo -e "${white}"
```

2022-10-13 10:25 UTC, abcarcol commented on scripts/accounts/gcp/verify-principal-roles-and-permissions.sh
> +    case "${flag}" in
We do not use *) in Hangar

2022-10-13 12:37 UTC, albertdb requested changes
Wrong directories, we agreed gcloud naming. Cannot proceed with the rest of the review until this is addressed (suggestions won't be applicable on renaming)

2022-10-13 12:37 UTC, albertdb commented on scripts/demo_takeoff/example_folder/README.md
> +Testing gcloud repositories
This should not have been pushed.

2022-10-13 13:24 UTC, jrodenasCapgemini commented on scripts/accounts/gcloud/setup-principal-account.sh
> +        echo -e "${green}Attached custom role $custom_role_id to $memberValue in project $project_id successfully."
```suggestion
        echo -e "${red}Error: Creating custom role $custom_role_id for project $project_id." >&2
        echo -e "${white}"
	exit 2
    else
	echo -e "${green}Created custom role $custom_role_id for project $project_id successfully."
	echo -e "${white}"
    fi
    echo -e "${white}Binding role $custom_role_id to principal $memberValue in project $project_id..."
    if ! gcloud projects add-iam-policy-binding "$project_id" --member="$memberValue" --role=projects/"$project_id"/roles/"$custom_role_id" &> /dev/null;
    then
        echo -e "${red}Error: Attaching custom role $custom_role_id to $memberValue in project $project_id." >&2
        echo -e "${white}"
	exit 2
    else
        echo -e "${green}Attached custom role $custom_role_id to $memberValue in project $project_id successfully."
        echo -e "${white}"
```

2022-10-13 13:28 UTC, jrodenasCapgemini commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +	echo -e "${green}Current project set to $project_id." >&2
```suggestion
    echo -e "${red}Use -h flag to display help." >&2
    echo -e "${white}"
    exit 2
fi

#Only google_account or service_account allowed
if [ -n "$google_account" ] && [ -n "$service_account" ];
then
    echo -e "${red}Error: Parameters -g or -s are mutually exclusive." >&2
    echo -e "${red}Use -h flag to display help." >&2
    echo -e "${white}"
    exit 2
fi

#Check if GCP CLI is installed
if ! [ -x "$(command -v gcloud)" ]; then
  echo -e "${red}Error: GCP CLI is not installed." >&2
  echo -e "${white}"
  exit 127
fi

#Check if Python is installed
if ! [ -x "$(command -v python)" ]; then
  echo -e "${red}Error: Python is not installed." >&2
  echo -e "${white}"
  exit 127
fi

#Check if the provided project_id exists and in that case set it as working project
echo -e "${white}Checking provided project $project_id..."
if ! gcloud projects describe "$project_id" &> /dev/null;
then
    echo -e "${red}Error: The provided project ID does not exist. Please, create it first." >&2
    echo -e "${white}"
    exit 2
else
    echo -e "${white}Setting current project to $project_id..."
    if ! gcloud config set project "$project_id" &> /dev/null;
    then
        echo -e "${red}Error: Could not set current project to $project_id." >&2
        echo -e "${white}"
	exit 2
    else
	echo -e "${green}Current project set to $project_id." >&2
	echo -e "${white}"
```

2022-10-13 13:29 UTC, jrodenasCapgemini commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +            echo -e "${red}FAILED      $role_to_check"
```suggestion
            echo -e "${red}FAILED      $role_to_check"
            echo -e "${white}"
```

2022-10-13 13:30 UTC, jrodenasCapgemini commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +            echo -e "${red}FAILED      $role_to_check"
```suggestion
            echo -e "${green}OK        $role_to_check"
            echo -e "${white}"
        else
            echo -e "${red}FAILED      $role_to_check"
            echo -e "${white}"
```

2022-10-13 13:32 UTC, jrodenasCapgemini commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +            echo -e "${red}FAILED      $permission_to_check"
```suggestion
	    echo -e "${green}OK        $permission_to_check"
	    echo -e "${white}"
	else
	    echo -e "${red}FAILED      $permission_to_check"
	    echo -e "${white}"
	    exit 1;
	fi
    done
fi

#Check permissions (From file)
if [ -n "$permissions_file" ];
then
    echo -e "${white}Checking permissions in file..."
    IFS=$'\r\n' GLOBIGNORE='*' command eval  'permissions_file_array=($(cat ${permissions_file}))'
    for permission_to_check in "${permissions_file_array[@]}"
    do
        if [[ " ${all_permissions_array[*]} " =~ " ${permission_to_check} " ]];
	then
	    echo -e "${green}OK        $permission_to_check"
	    echo -e "${white}"
	else
            echo -e "${red}FAILED      $permission_to_check"
            echo -e "${white}"
```

2022-10-13 13:52 UTC, albertdb requested changes

2022-10-13 13:52 UTC, albertdb commented on documentation/gcp/setup-gcp-account-for-gke.asciidoc
> +:toc: macro
rename to `setup-account-iam.asciidoc`

2022-10-13 13:52 UTC, albertdb commented on scripts/accounts/gcloud/gke-custom-role.yaml
> +title: My Custom Role
rename to `custom-role-example.yaml`

2022-10-13 13:52 UTC, albertdb commented on scripts/accounts/gcloud/gke-predefined-roles.txt
> +roles/viewer
Rename to `predefined-roles.txt`. We will evaluate if we have separate lists for CloudRun and GKE later.

2022-10-13 13:52 UTC, albertdb commented on scripts/accounts/gcloud/gke-required-permissions.txt
> +source.repos.list
rename to `required-permissions-example.txt`

2022-10-13 16:00 UTC, albertdb requested changes

2022-10-13 16:00 UTC, albertdb commented on scripts/accounts/gcloud/setup-principal-account.sh
> +    echo "  -i     Custom Role ID"
```suggestion
    echo "  -g     [Required] Google Account of an end user. Mutually exclusive with -s."
    echo "  -s     [Required] Service Account name. Mutually exclusive with -g."
    echo "  -p     [Required] Short project name (ID) to which the principal will be enrolled."
    echo "  -r               Roles (basic or predefined) to be attached to the principal in the project, splitted by comma."
    echo "  -f               Path to a file containing the roles (basic or predefined) to be attached to the principal in the project."
    echo "  -c               Path to a YAML file containing the custom role to be attached to the principal in the project. Requires -i."
    echo "  -i               ID to be set to the custom role provided in -c."
```

2022-10-13 16:08 UTC, albertdb requested changes

2022-10-13 16:08 UTC, albertdb commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +    echo "Checks if a Principal has the specified roles and permissions in a given project."
```suggestion
    echo "Checks if a Principal (end user or service account) has the specified roles and permissions in a given project."
```

2022-10-13 16:08 UTC, albertdb commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +    echo "  -i     Path to a file containing the permissions to be checked for the principal in the project."
```suggestion
    echo "  -g     [Required] Google Account of an end user. Mutually exclusive with -s."
    echo "  -s     [Required] Service Account name. Mutually exclusive with -g."
    echo "  -p     [Required] Short project name (ID) where the roles and permissions will be checked."
    echo "  -r                Roles to be checked, splitted by comma."
    echo "  -f                Path to a file containing the roles to be checked."
    echo "  -e                Permissions to be checked, splitted by comma."
    echo "  -i                Path to a file containing the permissions to be checked."
```

Update documentation accordingly.

2022-10-13 18:46 UTC, abcarcol commented on scripts/accounts/gcloud/setup-principal-account.sh
> +    case "${flag}" in
We do not use the *) case in Hangar

2022-10-13 18:52 UTC, abcarcol commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +    case "${flag}" in
We do not use the *) case in Hangar.

2022-10-14 07:31 UTC, albertdb commented on documentation/gcp/setup-gcp-account-for-gke.asciidoc
> +:toc: macro
@abcarcol still pending file rename

2022-10-14 08:23 UTC, jrodenasCapgemini commented on scripts/accounts/gcloud/setup-principal-account.sh
> +	    echo -e "${white}"
```suggestion
    echo -ne "${white}"
    exit 2
fi

#Only google_account or service_account allowed
if [ -n "$google_account" ] && [ -n "$service_account" ];
then
    echo -e "${red}Error: Parameters -g or -s are mutually exclusive." >&2
    echo -e "${red}Use -h flag to display help." >&2
    echo -ne "${white}"
    exit 2
fi

if { [ "$custom_role_file" ] && [ -z "$custom_role_id" ]; } || { [ -z "$custom_role_file" ] && [ "$custom_role_id" ]; };
then
    echo -e "${red}Error: -c and -i parameters must be used together." >&2
    echo -e "${red}Use -h flag to display help." >&2
    echo -ne "${white}"
    exit 2
fi

#Check if GCP CLI is installed
if ! [ -x "$(command -v gcloud)" ]; then
  echo -e "${red}Error: GCP CLI is not installed." >&2
  echo -ne "${white}"
  exit 127
fi

#Check if Python is installed
if ! [ -x "$(command -v python)" ]; then
  echo -e "${red}Error: Python is not installed." >&2
  echo -ne "${white}"
  exit 127
fi

#Check if the provided project_id exists and in that case set it as working project
echo -e "${white}Checking provided project $project_id..."
if ! gcloud projects describe "$project_id" &> /dev/null;
then
    echo -e "${red}Error: The provided project ID does not exist. Please, create it first." >&2
    echo -ne "${white}"
    exit 2
else
    echo -e "${white}Setting current project to $project_id..."
    if ! gcloud config set project "$project_id" &> /dev/null;
    then
        echo -e "${red}Error: Could not set current project to $project_id." >&2
        echo -ne "${white}"
	exit 2
    else
        echo -e "${green}Current project set to $project_id." >&2
        echo -ne "${white}"
    fi
fi


#Check if the service account exists and if not, create it
if [ -n "$service_account" ];
then
    service_account_email="$service_account@$project_id.iam.gserviceaccount.com"
    echo -e "${white}Checking if service account $service_account_email already exists..."
    if ! gcloud iam service-accounts describe $service_account_email &> /dev/null;
    then
	echo -e "${white}Creating new service account: $service_account_email..."
	if ! gcloud iam service-accounts create "$service_account" --display-name="$service_account" &> /dev/null;
	then
	     echo -e "${red}Error: Cannot create service account with display name $service_account." >&2
	     echo -ne "${white}"
	     exit 2
	else
	     echo -e "${green}Service account $service_account created successfully."
	     echo -ne "${white}"
	fi
	echo -e "${white}Creating service-account keys for service account $service_account_email..."
	if ! gcloud iam service-accounts keys create ./key.json --iam-account="$service_account_email" &> /dev/null;
	then      
	    echo -e "${red}Error: Service account key could not be created." >&2
	    echo -ne "${white}"
	    exit 2
	else
	    echo -e "${green}Service account key creation ended successfully."
	    echo -ne "${white}"
```

2022-10-14 08:28 UTC, jrodenasCapgemini commented on scripts/accounts/gcloud/setup-principal-account.sh
> +        echo -e "${white}"
```suggestion
	    echo -ne "${white}"
            exit 2
	else
	    echo -e "${green}Attached role $role_to_check to $memberValue in project $project_id."
	    echo -ne "${white}"
	fi
    done
fi

#Attach roles to principal in project (From file)
if [ -n "$roles_file" ];
then
    echo "Attaching provided roles in file $roles_file to principal in project $project_id..."
    IFS=$'\r\n' GLOBIGNORE='*' command eval  'roles_file_array=($(cat ${roles_file}))'
    for role_to_check in "${roles_file_array[@]}"
    do
        if ! gcloud projects add-iam-policy-binding "$project_id" --member="$memberValue" --role="$role_to_check" &> /dev/null;
	then
	    echo -e "${red}Error: Attaching role $role_to_check to $memberValue in project $project_id." >&2
	    echo -ne "${white}"
	    exit 2
	else
            echo -e "${green}Attached role $role_to_check to $memberValue in project $project_id."
            echo -ne "${white}"
        fi
    done
fi

#Create and attach custom role to principal in project (From YAML file)
if [ -n "$custom_role_file" ];
then	
    echo -e "${white}Creating role $custom_role_id defined in $custom_role_file for project $project_id..."
    if ! gcloud iam roles create "$custom_role_id" --project="$project_id" --file="$custom_role_file" &> /dev/null;
    then
        echo -e "${red}Error: Creating custom role $custom_role_id for project $project_id." >&2
        echo -ne "${white}"
	exit 2
    else
	echo -e "${green}Created custom role $custom_role_id for project $project_id successfully."
	echo -ne "${white}"
    fi
    echo -e "${white}Binding role $custom_role_id to principal $memberValue in project $project_id..."
    if ! gcloud projects add-iam-policy-binding "$project_id" --member="$memberValue" --role=projects/"$project_id"/roles/"$custom_role_id" &> /dev/null;
    then
        echo -e "${red}Error: Attaching custom role $custom_role_id to $memberValue in project $project_id." >&2
        echo -ne "${white}"
	exit 2
    else
        echo -e "${green}Attached custom role $custom_role_id to $memberValue in project $project_id successfully."
        echo -ne "${white}"
```

2022-10-14 08:31 UTC, jrodenasCapgemini commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +	echo -e "${white}"
```suggestion
    echo -ne "${white}"
    exit 2
fi

#Only google_account or service_account allowed
if [ -n "$google_account" ] && [ -n "$service_account" ];
then
    echo -e "${red}Error: Parameters -g or -s are mutually exclusive." >&2
    echo -e "${red}Use -h flag to display help." >&2
    echo -ne "${white}"
    exit 2
fi

#Check if GCP CLI is installed
if ! [ -x "$(command -v gcloud)" ]; then
  echo -e "${red}Error: GCP CLI is not installed." >&2
  echo -ne "${white}"
  exit 127
fi

#Check if Python is installed
if ! [ -x "$(command -v python)" ]; then
  echo -e "${red}Error: Python is not installed." >&2
  echo -ne "${white}"
  exit 127
fi

#Check if the provided project_id exists and in that case set it as working project
echo -e "${white}Checking provided project $project_id..."
if ! gcloud projects describe "$project_id" &> /dev/null;
then
    echo -e "${red}Error: The provided project ID does not exist. Please, create it first." >&2
    echo -ne "${white}"
    exit 2
else
    echo -e "${white}Setting current project to $project_id..."
    if ! gcloud config set project "$project_id" &> /dev/null;
    then
        echo -e "${red}Error: Could not set current project to $project_id." >&2
        echo -ne "${white}"
	exit 2
    else
	echo -e "${green}Current project set to $project_id." >&2
	echo -ne "${white}"
```

2022-10-14 08:32 UTC, jrodenasCapgemini commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +        echo -e "${white}"
```suggestion
        echo -ne "${white}"
```

2022-10-14 08:32 UTC, jrodenasCapgemini commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +        echo -e "${white}"
```suggestion
            echo -ne "${white}"
            exit 1;
        fi
        echo -ne "${white}"
```

2022-10-14 08:34 UTC, jrodenasCapgemini commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +            echo -e "${white}"
```suggestion
            echo -ne "${white}"
        else
            echo -e "${red}FAILED      $role_to_check"
            echo -ne "${white}"
            exit 1;
        fi
     done
fi

#Inline permissions check
if [ -n "$permissions" ];
then
    echo -e "${white}Checking inline permissions provided ..."
    IFS=',' read -ra permissions_array <<< "$permissions"
    for permission_to_check in "${permissions_array[@]}"; do
        if [[ " ${all_permissions_array[*]} " =~ " ${permission_to_check} " ]];
        then
	    echo -e "${green}OK        $permission_to_check"
	    echo -ne "${white}"
	else
	    echo -e "${red}FAILED      $permission_to_check"
	    echo -ne "${white}"
	    exit 1;
	fi
    done
fi

#Check permissions (From file)
if [ -n "$permissions_file" ];
then
    echo -e "${white}Checking permissions in file..."
    IFS=$'\r\n' GLOBIGNORE='*' command eval  'permissions_file_array=($(cat ${permissions_file}))'
    for permission_to_check in "${permissions_file_array[@]}"
    do
        if [[ " ${all_permissions_array[*]} " =~ " ${permission_to_check} " ]];
	then
	    echo -e "${green}OK        $permission_to_check"
	    echo -ne "${white}"
	else
            echo -e "${red}FAILED      $permission_to_check"
            echo -ne "${white}"
```

2022-10-14 09:12 UTC, albertdb requested changes

2022-10-14 09:15 UTC, albertdb commented on documentation/gcp/setup-gcp-account-for-gke.asciidoc
> +:toc: macro
@abcarcol please

2022-10-14 11:00 UTC, albertdb requested changes
It is not removing the exit, but exiting when all roles or permission are checked, with proper exit code (not 0 if some role or permission missing)

2022-10-14 11:38 UTC, albertdb commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +    echo "${white}Checking roles in file..."
```suggestion
    echo -e "${white}Checking roles in file..."
```

2022-10-14 11:40 UTC, albertdb requested changes

2022-10-14 11:40 UTC, albertdb commented on scripts/accounts/gcloud/setup-principal-account.sh
> +	if ! gcloud iam service-accounts keys create ./key.json --iam-account="$service_account_email" &> /dev/null;
Should create key even if service account exists.

2022-10-14 11:47 UTC, albertdb requested changes

2022-10-14 11:47 UTC, albertdb commented on scripts/accounts/gcloud/setup-principal-account.sh
> +if [ "$1" == "-h" ];
Put as help function as in https://github.com/devonfw/hangar/blob/master/scripts/accounts/gcloud/create-project.sh#L3

2022-10-14 11:47 UTC, albertdb commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +if [ "$1" == "-h" ];
Put as help function as in https://github.com/devonfw/hangar/blob/master/scripts/accounts/gcloud/create-project.sh#L3

2022-10-14 11:47 UTC, albertdb commented on scripts/accounts/gcloud/setup-principal-account.sh
> +    esac
Missing help flag.

2022-10-14 11:47 UTC, albertdb commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +    esac
Missing help flag.

2022-10-14 12:16 UTC, albertdb commented on scripts/accounts/gcloud/predefined-roles.txt
> +roles/editor
```suggestion
```

We should add more fine grain editor roles

2022-10-17 07:40 UTC, albertdb requested changes

2022-10-17 07:40 UTC, albertdb commented on scripts/accounts/gcloud/setup-principal-account.sh
> +while getopts g:s:p:r:f:c:i: flag
```suggestion
while getopts g:s:p:r:f:c:i:h: flag
```

2022-10-17 07:40 UTC, albertdb commented on scripts/accounts/gcloud/setup-principal-account.sh
> +	h ) helpFunction; exit ;;
```suggestion
	h) helpFunction ;;
```

Help function already exits

2022-10-17 07:40 UTC, albertdb commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +while getopts g:s:p:r:f:e:i: flag
```suggestion
while getopts g:s:p:r:f:e:i:h: flag
```

2022-10-17 07:40 UTC, albertdb commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +	h ) helpFunction; exit ;;
```suggestion
	h) helpFunction ;;
```

Help function already exits

2022-10-17 07:40 UTC, albertdb commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +exitCode = 0
```suggestion
exitCode=0
```

2022-10-25 11:18 UTC, albertdb commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +        if [[ " ${all_roles_array[*]} " =~ " ${role_to_check} " ]];
@abcarcol Isn't this relevant?

2022-10-25 11:20 UTC, albertdb commented on documentation/gcp/setup-gcp-account-for-gke.asciidoc
> +:toc: macro
@abcarcol please please please, this is waiting for 12 days!

2022-10-25 11:41 UTC, abcarcol commented on documentation/gcp/setup-gcp-account-for-gke.asciidoc
> +:toc: macro
done at last!

2022-10-25 12:20 UTC, abcarcol commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +        if [[ " ${all_roles_array[*]} " =~ " ${role_to_check} " ]];
@sonatype-lift ignore

2022-10-25 14:22 UTC, albertdb requested changes
Documentation reworked.

2022-10-25 14:22 UTC, albertdb commented on documentation/gcloud/setup-account-iam.asciidoc
> +NOTE: Required permissions for using GKE are located at `/scripts/accounts/gcloud/gke-required-permissions.txt`
````suggestion
= Setup Google Cloud account IAM
The scope of this section is to prepare a Google Cloud account to be ready for setting up a Cloud Dev & Run environment later on. By the end of this guide, a Principal (existing end user account or new/existing service account) will be enrolled to an existing project with the required roles attached.

== Prerequisites

* Have a Google Cloud project already setup and Google Cloud CLI installed and configured. If it is not the case, please go back to corresponding guide.
* A Google Cloud account with owner privileges on the project.

=== Alternative

In case you do not have an account or it does not have owner privileges on the project, request a service account to your Google Cloud administrator asking for the following roles being attached. Then go to <<check-roles-and-permissions-of-a-principal>>.

==== Required predefined roles

Find them on `/scripts/accounts/gcloud/predefined-roles.txt`.

== Setting up a principal using provided script

The script located at `/scripts/accounts/gcloud/setup-principal-account.sh` will automatically attach the required roles to the principal, in the context of the provided project.

=== Usage
```
setup-principal-account.sh \
  -g <google account> \
  -s <service account name> \
  -p <project id> \
  [-r <roles...>] \
  [-f <roles file path>] \
  [-c <custom role file path>] \
  [-i <custom role id>]
```

=== Flags
```
-g      [Required] Google Account of an end user. Mutually exclusive with -s.
-s      [Required] Service Account name. Mutually exclusive with -g.
-p      [Required] Short project name (ID) to which the principal will be enrolled.
-r                 Roles (basic or predefined) to be attached to the principal in the project, splitted by comma.
-f                 Path to a file containing the roles (basic or predefined) to be attached to the principal in the project.
-c                 Path to a YAML file containing the custom role to be attached to the principal in the project. Requires -i.
-i                 ID to be set to the custom role provided in -c.
```

=== Example
```
./setup-principal-account.sh -s ExampleServiceAccount -p ExampleProject -f ./predefined-roles.txt
```

NOTE: Required roles are located at `/scripts/accounts/gcloud/predefined-roles.txt`.

TIP: You can find an example of a custom role at `/scripts/accounts/gcloud/custom-role-example.yaml`.

=== After execution
On success and in case of creating a new service account (as in the example), a `key.json` file containing credentials will be generated. It will be used on further steps for authenticating with Google Cloud without human intervention.

IMPORTANT: It is mandatory to store the `key.json` file securely at this point, as *it will not be retrievable again*.

== Check roles and permissions of a principal

The script located at `/scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh` will automatically check that the necessary roles and permissions are bound to the principal, in the context of the provided project.

=== Usage
```
verify-principal-roles-and-permissions.sh \
  -g <google account> \
  -s <service account name> \
  -p <project id> \
  [-r <roles...>] \
  [-f <roles file path>] \
  [-e <permissions...>] \
  [-i <permissions file path>]
```

=== Flags
```
-g      [Required] Google Account of an end user. Mutually exclusive with -s.
-s      [Required] Service Account name. Mutually exclusive with -g.
-p      [Required] Short project name (ID) where the roles and permissions will be checked.
-r                 Roles to be checked, splitted by comma.
-f                 Path to a file containing the roles to be checked.
-e                 Permissions to be checked, splitted by comma.
-i                 Path to a file containing the permissions to be checked.
```

=== Example
```
./verify-principal-roles-and-permissions.sh -s ExampleServiceAccount -p ExampleProject -f ./predefined-roles.txt
```

After execution, provided policies will be shown preceded by an `OK` or `FAILED` depending on the attachment status.

NOTE: Required roles are located at `/scripts/accounts/gcloud/predefined-roles.txt`

TIP: You can find a non-comprehensive example of required permisions at `/scripts/accounts/gcloud/required-permissions-example.txt`.
````

2022-10-26 13:20 UTC, albertdb approved these changes

2022-10-28 08:27 UTC, mcerverc approved these changes

2022-10-28 09:17 UTC, abcarcol commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +        if [[ " ${all_permissions_array[*]} " =~ " ${permission_to_check} " ]]; # Searches right literal in left array. More info: https://stackoverflow.com/a/15394738
@sonatype-lift ignore

2022-10-28 09:18 UTC, abcarcol commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +        if [[ " ${all_roles_array[*]} " =~ " ${role_to_check} " ]]; # Searches right literal in left array. More info: https://stackoverflow.com/a/15394738
@sonatype-lift ignore

2022-10-28 09:28 UTC, abcarcol commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +        if [[ " ${all_roles_array[*]} " =~ " ${role_to_check} " ]]; #Treats right side as a regular expression to avoid looping over the array elements (actually it is not more efficient, only more r
@sonatype-lift ignore

2022-10-28 09:28 UTC, abcarcol commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +    for role_to_check in "${roles_file_array[@]}"
@sonatype-lift ignore

2022-10-28 09:29 UTC, abcarcol commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +    all_roles_array=($all_roles)
@sonatype-lift ignore

2022-10-28 09:45 UTC, abcarcol commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +        if [[ " ${all_roles_array[*]} " =~ " ${role_to_check} " ]]; # Searches right literal in left array. More info: https://stackoverflow.com/a/15394738
@sonatype-lift ignore

2022-10-28 09:46 UTC, albertdb commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +    all_roles_array=($all_roles)
@sonatype-lift ignore

2022-10-28 09:50 UTC, merged