GCLOUD- pipeline generator and build pipeline
devonfw/hangar pull request #255
Opened 2022-10-13 09:16 UTC by ultymatom

2022-10-13 09:30 UTC, ultymatom commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +        -c | --config-file)       configFile=$2; shift 2;;
@sonatype-lift ignore

We call it in the lib file

2022-10-13 09:30 UTC, ultymatom commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +        [[ "$subsitutionVariable" == "" ]] && artifactPathSubStr="_ARTIFACT_PATH=${artifactPath}" || artifactPathSubStr=",_ARTIFACT_PATH=${artifactPath}"
@sonatype-lift ignore
variable set in the cnfig file

2022-10-13 09:36 UTC, ultymatom commented on scripts/pipelines/gcloud/templates/build/build-pipeline.yml.template
> +    location: gs://${PROJECT_ID}_cloudbuild/pipelinesArtifacts/${pipelineName}/end_time_$(date +%Y-%m-%d_%Hh%M)_commit_${SHORT_SHA}
I just have an issue with the date, the timezone is an issue, should we choose one by default ? or use the one from the local of the user ?

2022-10-13 09:39 UTC, ultymatom commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +    gcloud beta builds triggers create cloud-source-repositories --repo="$gCloudRepo" --branch-pattern="$branchTrigger"  --build-config="${pipelinePath}/${yamlFile}" --project="$gCloudProject" --name
@sonatype-lift ignore

2022-10-13 09:39 UTC, ultymatom commented on scripts/pipelines/gcloud/templates/build/build-pipeline.yml.template
> +    location: gs://${PROJECT_ID}_cloudbuild/pipelinesArtifacts/${pipelineName}/end_time_$(date +%Y-%m-%d_%Hh%M)_commit_${SHORT_SHA}
knowing that the handling of timezone is different between git bash and a regular bash

2022-10-13 10:28 UTC, mcerverc commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +if [[ "$help" == "true" ]]; then help; fi
```suggestion
if [[ "$help" == "true" ]]; then help; exit; fi
```

2022-10-13 10:34 UTC, mcerverc commented
Better use -n "$varname" instead of ! -z "$varname" to check if a variable is filled.
Here (I cannot suggest changes as this code is not from this commit):
https://github.com/devonfw/hangar/blob/16be53b08b8376bc8f90672cb3ca3ac0a87596a8/scripts/pipelines/common/pipeline_generator.lib#L176

2022-10-13 10:36 UTC, mcerverc commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +if [[ "$help" == "true" ]]; then help; fi
Also here(not from this commit) :
https://github.com/ultymatom/hangar/blob/16be53b08b8376bc8f90672cb3ca3ac0a87596a8/scripts/pipelines/github/pipeline_generator.sh#L128
and here:
https://github.com/ultymatom/hangar/blob/16be53b08b8376bc8f90672cb3ca3ac0a87596a8/scripts/pipelines/azure-devops/pipeline_generator.sh#L145

2022-10-13 10:51 UTC, ultymatom commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +if [[ "$help" == "true" ]]; then help; fi
the exit command is already inside the help function

2022-10-13 11:49 UTC, mcerverc approved these changes

2022-10-14 12:24 UTC, jrodenasCapgemini commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +        exit
```suggestion
        echo -e "${green}No branch specified to do the merge, changes left in the ${sourceBranch} branch."
        echo -ne "${white}"
        exit
```

2022-10-17 11:54 UTC, albertdb requested changes

2022-10-17 11:54 UTC, albertdb commented on documentation/src/common_templates/setup-build-pipeline.asciidoc
> +
```suggestion
```

2022-10-17 11:54 UTC, albertdb commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +      echo -e "${green}Bucket ${gCloudProject}_cloudbuild already existing.${white}"
```suggestion
      echo -e "${green}Bucket ${gCloudProject}_cloudbuild already exists.${white}"
```

2022-10-17 13:33 UTC, albertdb approved these changes

2022-10-17 13:36 UTC, merged