Initial Draft
devonfw/hangar pull request #26
Opened 2021-11-25 05:29 UTC by sundharakanth

2021-11-25 05:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw/hangar?pullRequest=26) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/devonfw/hangar?pullRequest=26) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw/hangar?pullRequest=26) it.</sub>

2022-01-11 16:19 UTC, jbellver99 requested changes
Change the naming of the files, make them the same structure as in the other block documentations.

2022-01-11 16:19 UTC, jbellver99 commented on documentation/ContainerRegistry.asciidoc
> +----
```suggestion

=== Example

In a project we will normally execute the following commands:

[source,shell]
----
   docker pull <hostname>/<project-id>/<image>
   docker tag <source-image> <hostname>/<project-id>/<image>
   docker push <hostname>/project-id>/<image>
----

. Pull the desired images to our local repository with *docker pull*.

. After making the necessary changes, tag the image using the *docker tag* command.

. After tagging our image, use *docker push* to push the changes into the Docker Hub.

. Going back to our Docker Hub account, we can see the new tag is stored in our private repository [https://hub.docker.com/u/devonfw].
```

2022-01-11 16:19 UTC, jbellver99 commented on documentation/ContainerRegistry.asciidoc
> +* First step, we need to login to our AWS Account using the following command (please replace *<aws_account_id>* and *<region>* as appliable).
```suggestion

The first step is to login to your AWS account with the following command:
```

2022-01-11 16:19 UTC, jbellver99 commented on documentation/ContainerRegistry.asciidoc
> +       --password-stdin <aws_account_id>.dkr.ecr.<region>.amazonaws.com
```suggestion
       --password-stdin <aws-account-id>.dkr.ecr.<region>.amazonaws.com
```

2022-01-11 16:19 UTC, jbellver99 commented on documentation/ContainerRegistry.asciidoc
> +The following create-repository example creates a repository inside the specified namespace in the default registry for an account.
```suggestion

Create a repository inside the specified namespace in the default registry for an account like in the example below:
```

2022-01-11 16:19 UTC, jbellver99 commented on documentation/ContainerRegistry.asciidoc
> +       --region us-west-2
```suggestion
       --region us-west-1
```

2022-01-11 16:19 UTC, jbellver99 commented on documentation/ContainerRegistry.asciidoc
> +* Output:
```suggestion

Output:
```

2022-01-11 16:19 UTC, jbellver99 commented on documentation/ContainerRegistry.asciidoc
> +           "repositoryArn": "arn:aws:ecr:us-west-2:123456789012:repository/project-a/nginx-web-app"
```suggestion
           "repositoryArn": "arn:aws:ecr:us-west-1:123456789012:repository/project-a/nginx-web-app"
```

2022-01-11 16:19 UTC, jbellver99 commented on documentation/ContainerRegistry.asciidoc
> +Here are some optional commands which we would follow in any of our Docker projects.
```suggestion
=== Pulling and Pushing images

Here are some optional commands which we would follow in any of our Docker projects.
```

2022-01-11 16:19 UTC, jbellver99 commented on documentation/ContainerRegistry.asciidoc
> +* To pull the hello-world container to our local (or server from where we run this command), use this.
```suggestion
* Pull the hello-world image:
```

2022-01-11 16:19 UTC, jbellver99 commented on documentation/ContainerRegistry.asciidoc
> +    docker pull <aws_account_id>.dkr.ecr.<region>.amazonaws.com/hello-world:latest
```suggestion
    docker pull <aws-account-id>.dkr.ecr.<region>.amazonaws.com/hello-world:latest
```

2022-01-11 16:19 UTC, jbellver99 commented on documentation/ContainerRegistry.asciidoc
> +* After making the necessary code changes, we need to tag the container using this command (before pushing it to the regitry).
```suggestion

* After making the necessary changes, tag the image using the following command:
```

2022-01-11 16:19 UTC, jbellver99 commented on documentation/ContainerRegistry.asciidoc
> +    docker tag hello-world:latest <aws_account_id>.dkr.ecr.<region>.amazonaws.com/hello-world:latest
```suggestion
    docker tag hello-world:latest <aws-account-id>.dkr.ecr.<region>.amazonaws.com/hello-world:latest
```

2022-01-11 16:19 UTC, jbellver99 commented on documentation/ContainerRegistry.asciidoc
> +* After tagging the container, use this command to push the code changes to the registry.
```suggestion

* After tagging our image, use this command to push the changes to the repository:
```

2022-01-11 16:19 UTC, jbellver99 commented on documentation/ContainerRegistry.asciidoc
> +    docker push <aws_account_id>.dkr.ecr.<region>.amazonaws.com/hello-world:latest
```suggestion
    docker push <aws-account-id>.dkr.ecr.<region>.amazonaws.com/hello-world:latest
```

2022-01-17 11:34 UTC, sundharakanth commented on documentation/ContainerRegistry.asciidoc
> +----
Too many changes in this and need to discuss some of them before changing. Also, would like to see Albert's review comments before making these changes, if any.

2022-01-17 11:55 UTC, sundharakanth commented
> Change the naming of the files, make them the same structure as in the other block documentations.

This is done, please check and revert in case, changes required

2022-01-18 11:55 UTC, albertdb commented on documentation/ContainerRegistry.asciidoc
> +----
Review changes look good to me, the suggestion is more concise, clear and correct (you are handling images here, not containers). I would only remove the reference to https://hub.docker.com/u/devonfw and use 'code` instead of *bold* for commands in the explanation.

There's a typo in docker push command (missing `<`).

 Anyway, I need to review the PR in full.

2022-01-18 11:57 UTC, albertdb commented on documentation/ContainerRegistry.asciidoc
> +* First step, we need to login to our AWS Account using the following command (please replace *<aws_account_id>* and *<region>* as appliable).
Can be even more concise:

First, login to your AWS account with the following command:

2022-01-19 10:05 UTC, sundharakanth commented on documentation/ContainerRegistry.asciidoc
> +* First step, we need to login to our AWS Account using the following command (please replace *<aws_account_id>* and *<region>* as appliable).
ok, this is done

2022-01-19 10:17 UTC, sundharakanth commented on documentation/ContainerRegistry.asciidoc
> +----
**ok, all these changes are done. Please provide review comments in Review PR form to complete the task. Thank you Joan and Albert.**

2022-01-19 10:18 UTC, sundharakanth commented
Hi @albertdb , @jbellver99 and @isandesh1986 ,
     Please do PR Review and share review comments, if any.
Thanks,
Sundhar

2022-01-21 09:49 UTC, sundharakanth commented
Review Comment (from Albert) - Provide Wikipedia type of references with superscripts or subscripts for the content taken from other websites like Stack Overflow, Docker hub, etc in Appendix Document

2022-01-21 09:50 UTC, sundharakanth commented
Review Comment (from Albert and Sandesh) - Separate out the Managed and Hosted list of registries in Appendix document (list of 10 items given)

2022-01-21 09:56 UTC, sundharakanth commented
Review Comment (from Albert) - Add some Scope or Intro (refer Azure DevOps, EKS, etc) as first section in Main Doc

2022-01-21 10:02 UTC, sundharakanth commented
Review Comment (from Albert) - Docker hub has no registry reference since it is default whereas AWS, Azure, etc will have references like ecr.io, azr.io, gcr.io, etc. Mention this in the Main Doc and remove duplication of Docker Pull/Push commands.

2022-01-21 10:12 UTC, sundharakanth commented
Review Comment (from Albert) - Provide example of region and others in AWS Section to make the use understand better (of course, except for the AWS Account ID which is unique)

2022-02-02 12:27 UTC, sundharakanth commented
> Review Comment (from Albert) - Provide Wikipedia type of references with superscripts or subscripts for the content taken from other websites like Stack Overflow, Docker hub, etc in Appendix Document.
> 
> Also, especially if it’s official documentation, reference it instead of copying and quoting the content.

Done in both the documents. @albertdb - Please check and confirm.

2022-02-02 12:27 UTC, sundharakanth commented
> Review Comment (from Albert and Sandesh) - Separate out the Managed and Hosted list of registries in Appendix document (list of 10 items given)

Updated. @albertdb - Please check and confirm.

2022-02-02 12:28 UTC, sundharakanth commented
> Review Comment (from Albert) - Add some Scope or Intro (refer Azure DevOps, EKS, etc) as first section in Main Doc

Updated. @albertdb - Please check and confirm.

2022-02-03 11:49 UTC, sundharakanth commented
> Review Comment (from Albert) - Provide example of region and others in AWS Section to make the user, understand better (of course, except for the AWS Account ID which is unique)

Updated. @albertdb - Please check and confirm.

2022-02-09 05:26 UTC, sundharakanth commented
Opening Pull Request newly after closing the old Pull Request

2022-02-09 08:37 UTC, isandesh1986 commented on documentation/setup-container-repository.asciidoc
> +   aws ecr get-login-password \
Setting up AWS CLI should be a part of the prerequisite for the user to run these commands.

2022-02-09 09:12 UTC, isandesh1986 approved these changes
looks fine for me

2022-02-15 09:58 UTC, albertdb requested changes
This is a partial review, please address requested changes. For the rest of the review I'm going to directly commit changes, as it will be way easier.

2022-02-15 09:58 UTC, albertdb commented on documentation/container-repository-appendix.asciidoc
> +This section contains the additional content about Container Registry.
```suggestion
This section contains additional content about container registries, container repositories and managing container images. 
```

2022-02-16 05:49 UTC, sundharakanth commented
> This is a partial review, please address requested changes. For the rest of the review, you will be pinged by Sneha.

Hi @albertdb and @ssarmokadam, the changes request are accepted. Please share the additional review comments here in this Pull Request rather than sharing it offline. Thanks!

2022-02-16 07:16 UTC, ssarmokadam commented
Hi @sundharakanth , as per discussion with @albertdb please find some more review comments:

This block mainly focuses on creating package repository. So this document mainly should address 3 points:
1. User should be able to understand aim of this document- so may be 2-3 lines for giving this context
2. How to create image/package repo - in that we just need 3 options : Dockerhub, Azure(ACR) and Aws(ECR). This part should only focus on creating image repositories and not on pulling or pushing of images. If you add pull or push of images please restrict it to 2-3 liner.
3. Next part will explain format of image name. Please refer diagram below , you need to explain different part of image name and its meaning.
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAksAAAEUCAYAAAA7jXK9AAAgAElEQVR4Ae2di7XquA5AqYuCUg/V0MxtYjrILH9kS44/gSSQHPZbax4htvXZkm3hcDm3mf9BAAIQgAAEIAABCFQJ/Pfff/Ot2sJNCEAAAhCAAAQgAIGZYokkgAAEIAABCEAAAh0CFEsdODRBAAIQgAAEIACBF4qlf/PjfpunJ9BWE3hO8+02zWdE9pxuJ7Ut5Nkabv8e9/l2f8z/Vgek6PhWfNbbV2jjLQQgAAEIXJTA6YqlzRvgiQLhCpL74+2t/FBPjiqWtsdvfTGyVdd78Vlv36EBRDgEIAABCHyMQLdYsptJ2CSOPlnaugEeSu6Vk4h/j/l+u8+9WsnyPdTyjwn/ZPwWun49Pq/4/7GMQBEEIACB6xNoFEvPebrdikccUizJJ2v3GKcsBnRb/TFPONFwbeE/Kb78xhfvSVt4FR2iP9rm+0pbDoSVrx6BuY1kes7SPj3FVitD2r3uyiOe0G7HZO35yvsjzuXb8arHV/tnH3smmX5TDPzsyZX4JHyV/3PZ5vro9mDayP/ZF4EiP+fIOH4LCIsbVsbSNjfA2LfIUWk/Ij7z3LXvnfxa8K/FyJ5OGv835OcCPjcgAAEIQKBJYFksxc3QbsJufF7IpQbwC3dasGO7NLoR7jslakPw71P/uk3tPqI/b4RWf9Cn1IeNVfTFAsP5JZueFEziq5enBJTyxeI8Xu6Ur6HgUaJyhxf4Bj25aBC96Xs65vRqzD8b4asOExvXNvQ/Mqz6FYV7G4W5UfjCG68n+y0jS/tauoRT28534iNW1NnNK/LL2aVtKvPL+hfiKbnptNv2+L7Ceuy/8oVLCEAAAhAYEjDFUn+RDYu3Xuz9BiGLtd+4yw3ObkpBfi52atb5PiLTdBjoN33jG7eBiSy1AWcdekNytha2mWKkUNAseuJmKnrVsJf5ztamMF4zVnxX8FemuJ22KJasLt+38L/crI28+CazrbWuvLewzVfei8eaXV27x0fZXrNP3ct26fxS4+XSjUl5omIZ272cNOHG8RGx/rXnv+nIGwhAAAIQGBFQxVJY2N3jp7Q+m9GDYkVtFnnYcozfAORxW9oo1Ijmv3BayjLFmhMRNwjzGE90KPuqm1ltbONRn7c29dfFizei8a8G3+Dri6UcD7t5Zmb+SvmXWyrMpLHsn/xRj9iM/x1ZIlNOE4W5uh8uQ0Gg41PNtdI2N9jbZ1nnOC4UqVywY+SEdKl3FB+lo2afupftCjLT6VCNsWJli9EVY018lH2JV/1Ra9GTtxCAAAQgMCCgiqXYMy7oaYFPAiqbpdsgZLFXm0UaUmz2+b67iptTsWvljcb2lv6mu9YfdRm7dbuyL+tQG5L3uzhZKk2Q915WLmLktn+tbOrLdvs9lNBe4VvY5O02AJRk5V++uzytSG1l/0JX6pcuFKt0b3mR2S7bVt8pbXMDK/Y1dR0SH2V9zT51L9ulmYVYNPNTHrPJBwn3qmNd8V9ZZC97/tuevIMABCAAgRUElsWSHxRPAKQQ8vcqm7lblFOfOEYt8P6TcmpfWmM/Scd2v9DXipZ1+vNmVPgw3MyCfLNBLU2OXzCu2Rc6O5+yDRUB/lZhm7+39K/k0y2WYrGo7e/yVzyClWP/vf7yUWXpYjN+ZcfO+4Vtrm9gltj6PvkL5iLN+9yx8f34iIb4mFV9F8+3KJvXFUtlDrj37bySDws6vsqidDnyP3XkAgIQgAAEVhNoFEthvN1Ylpv54jGYbNjy6bgolMJCrh7zFO1ite0nG8hYf9jMRf59fjxUMTfczJz2WDCI/e5V26hkiK32dbThFb1NYVXRrQpPb517RFncKySGf8Uo9mvbbcfKd5a8Bv8IUT8mM/77Ax73pX1hXPCJOurxKw0o31f893ok/nK6FHU731w8tI+fjo+2T+muF0vucEyzK/KzxtbJ1/5tzs+SOe8hAAEIQGANgW6xtEYAfTIBvxl2i5ncd3lVKQaXnfa7ozb3/YSeW9K2+BzsW/UxW3GadrAJiIcABCAAgToBiqU6lzfuho3t7Vopnhq8P35k8nN+pF/IjKc4xykbGfOF9q3xOdhkX7yqUzSnzhdQje/GHWwO4iEAAQhAIBOgWMosvnx1/MmSeQxkHu982XXUewL28WV43PhT9Sx5AAEIQOCkBCiWThoYzIIABCAAAQhA4BwEKJbOEQesgAAEIAABCEDgpAQolk4aGMyCAAQgAAEIQOAcBCiWzhEHrIAABCAAAQhA4KQEKJZOGhjMggAEIAABCEDgHAQols4RB6yAAAQgAAEIQOCkBCiWThoYzIIABCAAAQhA4BwEKJbOEQesgAAEIAABCEDgpAQolk4aGMyCAAQgAAEIQOAcBCiWzhEHrIAABCAAAQhA4KQEKJZOGhjMggAEIAABCEDgHAQols4RB6yAAAQgAAEIQOCkBCiWThoYzIIABCAAAQhA4BwEKJbOEQesgAAEIAABCEDgpAQolk4aGMyCAAQgAAEIQOAcBCiWzhEHrIAABCAAAQhA4KQEKJZOGhjMggAEIAABCEDgHAQols4RB6yAAAQgAAEIQOCkBCiWThoYzIIABCAAAQhA4BwEKJbOEQesgAAEIAABCEDgpAQolk4aGMyCAAQgAAEIQOAcBCiWzhEHrIAABCAAAQhA4KQEKJZOGhjMggAEIAABCEDgHAQqxdK/+XG/zbfbfX78y0Y+p9t8m575Rrz697ir+zLWjQ//3bWQxWhuQAACEIAABCAAgXMTWBZL/x7z/f6YH9Nt1oXOuFiKhVKloDo3AqyDAAQgAAEIQAACbQKLYsmdFPki6TnNt/tjlsMle4KUBab+rsi63WZqpcyGKwhAAAIQgAAErk+gKJbC6ZAveHzxkx/F+WIpFk+pQJrn2Z04hROo5zy5R2+qwLo+HjyAAAQgAAEIQODXCdhiyRdI0xy+mRQKp/QoLp00xcdtsSjKxdI8z/F0yX9fiSOmX88t/IcABCAAAQj8CQKmWCoftenTpDkVS895uk/zdA+nTq5YWtRFrm/8gvei7U9gwwkIQAACEIAABH6FgCqWipMkR8AXPfGkSa6fk3/s5gopVwhVi6VIzxdbNzmp+hWk+AkBCEAAAhCAwF8ikIsl/QgtngqZ06H4iO4RiyRfSE0P/zMDzdMjX2Dl7z39JXD4AgEIQAACEIDAbxBIxZJ55KZ8dydH/veVUjElJ0XxC93F7zGpof7UiS98ayJcQwACEIAABCBwNQKpWDJf1NZeyOO3ufzXbvGL3lIspWIq/yAlhZIGyTUEIAABCEAAAlckkIqlKxqPzRCAAAQgAAEIQOBoAhRLRxNGPgQgAAEIQAAClyZAsXTp8GE8BCAAAQhAAAJHE6BYOpow8iEAAQhAAAIQuDQBiqVLhw/jIQABCEAAAhA4mgDF0tGEkQ8BCEAAAhCAwKUJUCxdOnwYDwEIQAACEIDA0QQolo4mjHwIQAACEIAABC5NgGLp0uHDeAhAAAIQgAAEjiZAsXQ0YeRDAAIQgAAEIHBpAhRLlw4fxkMAAhCAAAQgcDQBiqWjCSMfAhCAAAQgAIFLE6BYunT4MB4CEIAABCAAgaMJUCwdTRj5EIAABCAAAQhcmgDF0qXDh/EQgAAEIAABCBxNgGLpaMLIhwAEIAABCEDg0gQoli4dPoyHAAQgAAEIQOBoAhRLRxNGPgQgAAEIQAAClyZAsXTp8GE8BCAAAQhAAAJHE6BYOpow8iEAAQhAAAIQuDQBiqVLhw/jIQABCEAAAhA4mgDF0tGEkQ8BCEAAAhCAwKUJUCxdOnwYDwEIQAACEIDA0QQolo4mjHwIQAACEIAABC5NgGLp0uHDeAhAAAIQgAAEjiZAsXQ0YeRDAAIQgAAEIHBpAtVi6d/jPt8f/3Z27N/8uN/m6bmzWMRB4FIEwjy43aZ5NBXcPLzdH/PeM1FwWfnBrv3nvWjjNRBYH3+IQQAC5yGgiiVVzDynUNQ8px0XayX/QP/tBnCgIkT/JIHt+bV+s9yuqx8iKz/YRbHUZ7a9dX38t+tCAgQgsBcBVSwFkc/pNt9u8b+Nx0BOVl58KZZmV3yuOFHYK7iW/15Sf1uOLTCOZbHQtXP+WPm/Vyz9ufmxc34cm91Ih8C1CBxULD3nyRVc5hGCFEvyycoVZPfZPu3Tba59+ajCFHO3/FjPL/xS5JlX0SH6o22+j7TloFn5Sr9biKbnLO3TU2y1MqTdF5zG/6AjtNsxWbu7qrGzPcbv2jKMfYlv8CUXtlmD3VDn5L8U1K/W03X9Wd/87zHfdfxKht12iYkU/Cp+s8Rf6XIxTfKlvZ4f4/xSchuXVoa2LQ+wfMo5JPx7+ZNl1a7a8sscEJZZl7ffBdxvyoFxLWdqeuWe0Z/YS+s89+K/h/6gqT4/1sjv2y/MJP8so3H8y/E6R0Lb9KznpxAM9uWYyf21r8a/tD64ZemN9U+P9yIsl+UauZf/okf4Bbm1XPUxUXlo/c/7y1p+vfyd4xoka6fZ31byXW0HHXcnoIolmYxhYvhN0GwmK3XHzWyZmHkiyAbrEzMlamyXRr9u3k3BVCZ2zaJ2H9GfFxKr363Td/OdKtMeNwjnl9fhC7UgU3z1/ZX9ZrwyNo9XN9NlfSFPzaOLJv++f6XtosbbGn3y1yle0mP9qxuv8ITCS8uLjHUfI73bPsqf0G5km/we54ezZSsD74/3Qxby7GEZg5Yuf199UMgS+ld9+TqXIwsdG/HdFbJy3+dank997bHQUwFYzI9ufCP7Dfq9fYP5YTbwwr+SX2m/bdc8CzLV+Efmik+Is+RJbFcfMEv9ouXd/HDjlHo7P2Nseutfd7wYl17dOqdzZ7v/Pf02NsmIMJ+j056b5Hbusv6qm78D/1bwXW8IPY8goIqlLN4ljRQA+e74yidbcxEPyaIno/+0IsnpFyZZGERXKBxkTJCvJ5j0y6/thB/ozyLylUtgsc8nc7Av6wgyA6ty8sun5Ia9nUU7G/DaVZ9/RZbyz4+NoPXC4q4lF4L8hj8V8cNbSr/rq/XWxnbbh/kziv+oPViUY1+zcOU9lUtpRLExu/tdXa/mz1C+5PLT/0MMd4pa/i/EX89ROz/L/vb9eH504ys8zGnFK/pzsVVxzZva929k/9IWL6+mrBl/zdaZpGWuy8/E/NX8SAPVhZ6fyuacl5IzjX+CoMcrsXLCYtB4e3f03+lT+nUsdJ65673WNy3XuOvejPx7h+9CCTeOJFAtlt5TGCaO+2RmJkESNpjsKlnSkMqjk7CgxWNWKWTygM4GM9DvZMQFJh+Tqk/Ryr7qYlEb23jU581N/csFQjnz0uWI/wr/PM/nPN0n/9/zZf5hcdf8TC4kn+WYXPGt6LLuV+KnO6j45Nt6jL6OPdyYlEOj9jAmxz5ryVcD/6VjzVbPxuZCV1diaceIisXrUH7wX2Jn4haFeXtqDQtllRvJXhV7Mz8q/Asxm/SrRyAtF7ryh/aXxX7wRzZi40ot/rV7Zk5U+Jj8NRrUWrYyP9zwmo8yP5R9OS8LH3vjlXlVzkp+7qp91texR+l/T3/qu2V9y5Ytryr26U4j/1R7k6+Wx/XHCexYLEXbY8IuF4lKMqUEjp8CzKdGJ09/sirZBHnlJ+CcaPX+ZqHU+qMuY7duHyWz93vlqYuX1SoqS7tffN/kH1g2/fPjpvn57zFPj3/+lCd8L6vlU51/29qB/rgxGPuMsKCv2a7ik4fp/Bnkn9mYogQd/3irnV9Z6/CqZmslf5q63smfoXzF18tfxt3bYybQ0NPcoaI/N7orpd82pHeb9IsUb0c+TZDb7rUrf2h/LJZ8ARgLwharWvxr98z6N8pf5ck7+bF1/RuNF/McRynA5J573ez/YH3x8TtyfRvk78g/1Z7n/UCm5sf14QT2L5a8ySFx86d2d3M02eMYtcD4Y83axIpYqseePumWC/1a/XkzLnwYJnPwryzeygh6m82z+kWPypfjyz6j94Xtvnu41/TPL3bT/HhM4Uv3zt9pmqdFAZt1V/nn5uJqpD9uVh02fhFptkefm/lTxCdumjlHR/kZ3WnmV+Fu763Kpdyt4OP76JO30HOYP+LXIm4j+cF/yY8a624xIY409Rf8pb96relUzf1iRjo29UsH9xpzpVhb+v6N7Hcya+uO1huvO/HX64ePdbJxXX7ulh8lI2Wz5+Tt0jlT5Fc53rveYxRjMpi/qtk8ZpOYSv7K+zy/nfwd1rdOfvXzd+DfkG8lj7j1UQIHFUvBBzdxc/KumewxoeTTWVoosjx5TOBfi3YhFxYMOe6XBWysPyS7GvdQj2lWJXPQ0bRRyRBbl6+RQcO3Zf/2HctfipGGf7GYtYuL3awtV9vWtiK3dPnGbrbPUke/vZ8/9jHDND9dPBLncX6IJ5aD5Je0tl4ruWEeQxWPQZxdxr7Wp+9CX2cxN/4v5Af78nzNJyWyQXn28qZQm9729EuOyfx2r4l/kNCL73b9yUp/UZ0fXf8qMVT2L2w3/lXGlvGXAkP4KNnjD3vb88Paf/cfnFJ81Nrl+3nbbM50x3vzZO3Rr3r+9OZv0GXCU8yPvv7IPzFdrrN2Xi9z0ydNN7/LNbaU0fFvBV+bvbz7NIFDi6VPO4M+CEAAAl8h4DdRvfE7K8LmqAvQr9iGUghAYDMBiqXNCBEAAQj8PAF/MlAUS/EUwpyG/DwoAEDgmgQolq4ZN6yGAARORmDxGKf5L4NPZjjmQAACQwIUS0NEdIAABCAAAQhA4JcJUCz9cvTxHQIQgAAEIACBIQGKpSEiOkAAAhCAAAQg8MsEKJZ+Ofr4DgEIQAACEIDAkADF0hARHSAAAQhAAAIQ+GUCXymW3I+H8dsjfzXt5Mf3xn+TKv+43SdZiH32n3n7f8lU+Tfe3sZ0X8bmH9V7PY9FhtX/SQLf0SV+Z3bmh2XTj/3l9tfZfscztEIAAn+fwAeLpbBY+n3nOYU/tlv8Auvfx31+D7cXMLIpnrRYcpvy/TE/zK/Lx1+rTkVRjlMulqJflT6594qrhv4VI0/RZXt+NFj7YknnTPy14628T0ENIyAAgasT+GCxFFCZ3yLZuBA6WXz63DcF99gM11q00KV+8n+tjFf7OZ0+Z4pC3dtSycfUP558VLq8ZEKSV+h/ScgXO3tO6U9GvGdI9RRvUSzJn3/5tRO495gyCgIQOJbARYul5d/1EUymGEt/TDScCtQKq3Lxt+Nv4QRMhK94teP1J+U4OG666e/HlRtP [...]

2022-02-16 09:51 UTC, sundharakanth commented
> Hi @sundharakanth , as per discussion with @albertdb please find some more review comments:
> 
> This block mainly focuses on creating package repository. So this document mainly should address 3 points:
> 
> 1. User should be able to understand aim of this document- so may be 2-3 lines for giving this context
> 2. How to create image/package repo - in that we just need 3 options : Dockerhub, Azure(ACR) and Aws(ECR). This part should only focus on creating image repositories and not on pulling or pushing of images. If you add pull or push of images please restrict it to 2-3 liner.
> 3. Next part will explain format of image name. Please refer diagram below , you need to explain different part of image name and its meaning.
>    ![4ed352a6-efb6-4131-bab7-b9a53d063fe4](https://user-images.githubusercontent.com/16591200/154215104-2afdddc8-0fb5-492b-a154-efefa583d99e.jpg)
> 
> But we do not want to lose work which you have already done, so please move rest of the part to appendix document.

Hi @ssarmokadam , 
1. The context is already given there. Please clarify what extra is required.
2. Docker Hub and AWS are already available in Main Doc and Azure in Appendix as per earlier review comment. Please confirm if it is a new requirement to move Azure back to Main Doc from Appendix. 
Docker Push/Pull are integral part of container operations when talking about Creating Container Registry as well and they are already minimized. Without those, this would make no sense (only create registry command).
3. Currently, it is like this image and sure, will add Project ID and Account ID as well.
![image](https://user-images.githubusercontent.com/91184708/154239179-324e53ac-77ce-41db-bb73-6e2d7712b744.png)

2022-02-24 07:49 UTC, sundharakanth commented
> > Hi @sundharakanth , as per discussion with @albertdb please find some more review comments:
> > This block mainly focuses on creating package repository. So this document mainly should address 3 points:
> > 
> > 1. User should be able to understand aim of this document- so may be 2-3 lines for giving this context
> > 2. How to create image/package repo - in that we just need 3 options : Dockerhub, Azure(ACR) and Aws(ECR). This part should only focus on creating image repositories and not on pulling or pushing of images. If you add pull or push of images please restrict it to 2-3 liner.
> > 3. Next part will explain format of image name. Please refer diagram below , you need to explain different part of image name and its meaning.
> >    ![4ed352a6-efb6-4131-bab7-b9a53d063fe4](https://user-images.githubusercontent.com/16591200/154215104-2afdddc8-0fb5-492b-a154-efefa583d99e.jpg)
> > 
> > But we do not want to lose work which you have already done, so please move rest of the part to appendix document.
> 
> Hi @ssarmokadam and @albertdb ,
> 
> 1. The context is already given there. Please clarify what extra is required.
> 2. Docker Hub and AWS are already available in Main Doc and Azure in Appendix as per earlier review comment. Please confirm if it is a new requirement to move Azure back to Main Doc from Appendix.
>    Please refer the original requirements where it says "detailed guide" and "briefly find out the alternatives". Are we planning to change the requirement itself now? @SchettlerKoehler
>    ![image](https://user-images.githubusercontent.com/91184708/154431534-aafa9a64-fdf3-4482-b8dd-fad15fa0ae69.png)
> 
> Docker Push/Pull are integral part of container operations when talking about Creating Container Registry as well and they are already minimized. Without those, this would make no sense (only create registry command). 3. Currently, it is like this image and sure, will add Project ID and Account ID as well. ![image](https://user-images.githubusercontent.com/91184708/154239179-324e53ac-77ce-41db-bb73-6e2d7712b744.png)

@albertdb 's response from the meeting:
1. "Detailed guide" is mis-understood to be very detailed and it is not required. The goal is not to train the end users of this task/block.
2. "Briefly find out the alternatives" is not for the person who is working on this task/block and so, can be ignored.

@sundharakanth : I will proceed with the changes as per above and update here.

2022-02-24 07:58 UTC, sundharakanth commented on documentation/setup-container-repository.asciidoc
> +   aws ecr get-login-password \
This is completed now and here is the screenshot for reference. 
![image](https://user-images.githubusercontent.com/91184708/155482355-ef5d717e-11a1-4c4f-9305-3ddb92f5a041.png)

2022-02-28 10:32 UTC, albertdb commented
> @albertdb 's response from the meeting:
> 
> 1. "Detailed guide" is mis-understood to be very detailed and it is not required. The goal is not to train the end users of this task/block.
> 2. "Briefly find out the alternatives" is not for the person who is working on this task/block and so, can be ignored.
> 
> @sundharakanth : The changes as per above are updated. @albertdb , @ssarmokadam Please check and confirm and then, we can DELETE the APPENDIX File and proceed with the MERGE.

Please, let me fix some of the conclusions:

1. "Detailed guide" **is** required, but without going out of scope. The goal is not to train the end users of this task/block about managing container images, but to make them aware of what they are doing an why.
2. "Briefly find out the alternatives" is mis-understood. It **is** for the person who is working on this task/block and to propose which ones, especially if going to self host them, cover, not for giving that info to the end-user.

2022-03-14 12:02 UTC, albertdb commented
Acceptance criteria (live review meeting exact details prevail, please check recording if in doubt):

- [ ] Project general guidelines are met (available in Devon Hangar Teams group chat).
- [ ] Block is aligned with the project vision, i.e. fits on the bigger picture.
- [ ] Guide scope (goals, outcome) is provided on the introduction. What we are doing, why we are doing it (what needs within Hangar the does it fulfil), and what do we get at the end (outputs the user needs to carry with him for next guides in the use case).
- [ ] Define generic image name syntax on introduction.
- [ ] For each provider, provide how-to on creating container repository, and how the image looks like filling the gaps on generic image name, in a cohesive way.
- [ ] (Nice-to-have) Provide almost copy&paste example at the end of each provider subsection.

2022-03-16 18:24 UTC, sundharakanth commented
Here is the updated version of Intro section
![image](https://user-images.githubusercontent.com/91184708/158660820-0e1e7d1f-ba57-4451-a93a-1bde1694d009.png)

2022-03-17 12:23 UTC, sundharakanth commented
![image](https://user-images.githubusercontent.com/91184708/158807702-5acc6829-b36d-4646-a147-34481e194c7e.png)

2022-03-18 06:56 UTC, sundharakanth commented
![image](https://user-images.githubusercontent.com/91184708/158952092-a7b62c60-9d2c-4b55-bf2f-6a3d12785306.png)

2022-03-18 06:56 UTC, sundharakanth commented
![image](https://user-images.githubusercontent.com/91184708/158952144-e9db1425-fac6-4933-870e-a1817e39d55e.png)

2022-03-21 06:50 UTC, isandesh1986 commented on documentation/container-repository-appendix.asciidoc
> +== References
Please use this format for these references also.
link:https://docs.docker.com/docker-hub/[Docker Hub]

2022-03-21 06:50 UTC, isandesh1986 commented on documentation/container-repository-appendix.asciidoc
> +* 2. ^StackOverflow (https://stackoverflow.com/questions/34004076/)
Should be 
https://stackoverflow.com/questions/34004076/difference-between-docker-registry-and-repository[Difference between Docker registry and repository]

2022-03-21 06:50 UTC, isandesh1986 commented on documentation/setup-container-repository.asciidoc
> +* AWS CLI installed.
Add links here for AWS account creation and AWS CLI.
Ex format:- link:https://docs.docker.com/docker-hub/[Docker Hub]

2022-03-21 06:50 UTC, isandesh1986 commented on documentation/setup-container-repository.asciidoc
> +* Azure CLI installed.
Add respective links here
Ex format:- link:https://docs.docker.com/docker-hub/[Docker Hub]

2022-03-21 06:50 UTC, isandesh1986 commented on documentation/setup-container-repository.asciidoc
> +* Azure CLI installed.
Install Azure CLI - would be right .

2022-03-21 09:36 UTC, albertdb commented on documentation/setup-container-repository.asciidoc
> +* AWS CLI installed.
This is something that was already done in a previous guide: https://github.com/devonfw/hangar/blob/master/documentation/aws/setup-aws-account-iam-for-eks.asciidoc

2022-03-21 10:25 UTC, albertdb requested changes
Fixed some semantics, different providers provide different service.

2022-03-21 10:25 UTC, albertdb commented on documentation/setup-container-repository.asciidoc
> +For referencing an image in Docker Hub, you don't have to specify the `<registry-url>` since it is the default on Docker.
```suggestion
NOTE: For referencing an image in Docker Hub, you don't have to specify the `<registry-url>` since it is the default on Docker.
IMPORTANT: Docker Hub does not support multi-level image names.
```

2022-03-21 10:37 UTC, sundharakanth commented on documentation/setup-container-repository.asciidoc
> +* AWS CLI installed.
Yes Sandesh, since this was done in a previous guide, we are not providing links here in this section/guide

2022-03-21 10:39 UTC, sundharakanth commented on documentation/setup-container-repository.asciidoc
> +* Azure CLI installed.
Since these are pre-requisites and we expect the user to have completed those steps already, we have marked that as "Azure CLI installed." instead of "Install Azure CLI". Hope, you agree.

2022-03-21 10:40 UTC, sundharakanth commented on documentation/setup-container-repository.asciidoc
> +* Azure CLI installed.
Since this was done in a previous guide, we are not providing links here in this guide in pre-requisites section.

2022-03-21 10:51 UTC, isandesh1986 commented on documentation/setup-container-repository.asciidoc
> +* AWS CLI installed.
@albertdb . But chances are there that someone can pick this block to setup since they already have some project setup in place.

2022-03-21 11:17 UTC, albertdb commented on documentation/setup-container-repository.asciidoc
> +* AWS CLI installed.
@isandesh1986 That guide in particular covers that use case (allows user to verify everything is in place).

2022-03-21 11:57 UTC, isandesh1986 commented on documentation/setup-container-repository.asciidoc
> +* AWS CLI installed.
> @isandesh1986 That guide in particular covers that use case (allows user to verify everything is in place).

Got it. @albertdb.  In my view, every block should have a link to the setup block/guide. Just in case someone stumbled upon an intermediate block, we should redirect them to do the initial set up and then start doing the intermediate blocks. What do you say?

2022-03-21 12:09 UTC, sundharakanth commented on documentation/container-repository-appendix.asciidoc
> +== References
Sorry Sandesh, we removed this file as per the current scope

2022-03-21 12:09 UTC, sundharakanth commented on documentation/container-repository-appendix.asciidoc
> +* 2. ^StackOverflow (https://stackoverflow.com/questions/34004076/)
Sorry Sandesh, we removed this file as per the current scope

2022-03-21 12:12 UTC, sundharakanth commented on documentation/setup-container-repository.asciidoc
> +*** `devonfw/quarkus/sample/devon4quarkus-reference:2.0`
As discussed, tested this and confirmed. Now, updated Docker Hub examples accordingly.

2022-03-21 14:19 UTC, albertdb approved these changes

2022-03-21 14:23 UTC, albertdb approved these changes

2022-03-21 14:26 UTC, jbellver99 approved these changes

2022-03-21 14:27 UTC, merged