hangar #195 quarkus build - Create Build pipeline definition and assets for Google Cloud
devonfw/hangar pull request #277
Opened 2022-10-18 11:15 UTC by ultymatom

2022-10-18 11:17 UTC, ultymatom commented on scripts/pipelines/gcloud/templates/build/build-pipeline.cfg
> +    quarkus*) dockerImage="ultimatom/maven-with-docker:v1" ;;
he puesto una imagen en un repo publico mio
Pero para mantenerlo no me parece bueno, tenemos un registry para hangar, y quizás también vamos a necesitar un pipeline, no importa donde, para crear nuevas versiones de esta imagen cuando la de maven oficial estás actualizada

2022-10-18 11:19 UTC, ultymatom commented on scripts/pipelines/gcloud/templates/build/build-pipeline.cfg
> +    quarkus*) dockerImage="ultimatom/maven-with-docker:v1" ;;
un registry para take-off*

2022-10-18 11:33 UTC, abcarcol commented on scripts/pipelines/common/pipeline_generator.lib
> +    [[ "$provider" == "gcloud" ]] && echo "  -m, --machineType                      Set a machineType for your pipeline, accepted values: 'E2_HIGHCPU_8' or 'E2_HIGHCPU_32'."
Why double brackets and not single brackets like in the rest of the help function?

2022-10-18 11:36 UTC, abcarcol commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +FLAGS=$(getopt -a --options c:n:d:a:b:l:i:u:p:hm: --long "config-file:,pipeline-name:,local-directory:,artifact-path:,target-branch:,language:,build-pipeline-name:,sonar-url:,sonar-token:,image-name:
hm or h:m

2022-10-18 15:22 UTC, ultymatom commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +  echo "" >> "${localDirectory}/${pipelinePath}/${yamlFile}"
@sonatype-lift ignoreall
this is done for being more understandable

2022-10-18 15:22 UTC, ultymatom commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +  echo "" >> "${localDirectory}/${pipelinePath}/${yamlFile}"
@sonatype-lift ignore
This is done to be easier to read

2022-10-18 15:22 UTC, ultymatom commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +  echo "" >> "${localDirectory}/${pipelinePath}/${yamlFile}"
@sonatype-lift ignore

2022-10-19 07:04 UTC, albertdb requested changes
Pending documentations suggestions.

2022-10-19 07:04 UTC, albertdb commented on scripts/pipelines/gcloud/templates/build/build-pipeline.yml.template
> +    fi
Does gcloud keep state between steps? I guess by this solution that the answer is no, otherwise it would have been better to put this as a separate step.

2022-10-19 08:27 UTC, ultymatom commented on scripts/pipelines/gcloud/templates/build/build-pipeline.yml.template
> +    fi
no it does not, tried with two different steps but it was failing

2022-10-19 08:27 UTC, ultymatom commented on documentation/azure-devops/setup-build-pipeline.asciidoc
> +endifdef::[]
fixed

2022-10-19 08:41 UTC, albertdb commented on scripts/pipelines/gcloud/templates/build/build-pipeline.yml.template
> +    fi
@ultymatom I'm thinking that we always talked about yaml level being application language/framework agnostic, so we better make this generic. We can execute a script for setting up environment (if it exists), that will be filled from the pipeline definition.

2022-10-19 10:22 UTC, ultymatom commented on scripts/pipelines/gcloud/templates/build/build-pipeline.yml.template
> +    fi
Done a <language>-setup-environment.sh

2022-10-26 09:46 UTC, ultymatom commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +        -v | --version)           languageVersion="$2"; shift 2;;
@sonatype-lift ignore

2022-10-26 09:46 UTC, ultymatom commented on scripts/pipelines/common/templates/build/python-build.sh
> +. venv/bin/activate
@sonatype-lift ignore

2022-10-27 13:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw/hangar?pullRequest=277) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/devonfw/hangar?pullRequest=277) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: lpinon<br/>:white_check_mark: ultymatom<br/>:white_check_mark: jrodenasCapgemini<br/>:x: capf4bbo<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw/hangar?pullRequest=277) it.</sub>

2022-10-27 16:51 UTC, albertdb requested changes

2022-10-27 16:51 UTC, albertdb commented on documentation/src/common_templates/setup-build-pipeline.asciidoc
>  ```
Missing Python and Flutter examples.

2022-10-27 16:51 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +    echo "      --language-version      [Required, if Flutter or Python] Additional arguments for language version."
```suggestion
    echo "      --language-version      [Required, if Flutter or Python] Language or framework version."
```

2022-10-27 16:51 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +    echo "      --language-version      [Required, if Flutter or Python][Required, if Flutter or Python] Additional arguments for language version."
```suggestion
    echo "      --language-version      [Required, if Flutter or Python] Language or framework version."
```

2022-10-27 16:51 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +    echo "      --language-version      [Required, if Flutter or Python] Additional arguments for language version."
```suggestion
    echo "      --language-version      [Required, if Flutter or Python] Language or framework version."
```

2022-10-27 16:51 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +    echo "      --language-version      [Required, if Python or Flutter] Additional arguments for language version."
```suggestion
    echo "      --language-version      [Required, if Flutter or Python] Language or framework version."
```

2022-10-27 16:51 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +    echo "      --flutter-platform      [Required, if Flutter] Flutter platform to compile, accepted values: 'android' or 'web'."
```suggestion
    echo "      --flutter-platform      [Required, if Flutter] Target platform to compile. Accepted values: android, web."
```

2022-10-27 16:51 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +    echo "      --flutter-web-renderer             Flutter web renderer, default is auto, accepted values: 'canvaskit', 'html' or 'auto'."
```suggestion
    echo "      --flutter-web-renderer             Flutter web renderer. Accepted values: auto (default), canvaskit, html."
```

2022-10-27 16:51 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +function versionVerification {
```suggestion
function languageVersionVerification {
```

2022-10-27 16:51 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +        echo -e "${red}Language given is Flutter. It is required to use --version flag.${white}"
```suggestion
        echo -e "${red}Error: Language given requires --version flag.${white}" >&2
```

This way we avoid two ifs, remove the other one and adapt condition.

2022-10-27 16:51 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +        echo -ne ${white}
```suggestion
        echo -ne ${white} >&2
```

2022-10-27 16:51 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +            echo -ne ${white}
```suggestion
            echo -ne ${white} >&2
```

2022-10-27 16:51 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +        echo -ne ${white}
```suggestion
        echo -ne ${white} >&2
```

2022-10-27 16:51 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +        echo -ne ${white}
```suggestion
        echo -ne ${white} >&2
```

2022-10-27 16:51 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +        echo -ne ${white}
```suggestion
        echo -ne ${white} >&2
```

2022-10-27 16:51 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +        echo -ne ${white}
```suggestion
        echo -ne ${white} >&2
```

2022-10-27 16:51 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +    cd "${localDirectory}" || { echo -e "${red}Error: Local directory '${localDirectory}' does not exist. Check provided path (missing quotes?)."; echo -ne ${white}; exit 1; }
```suggestion
    cd "${localDirectory}" || { echo -e "${red}Error: Local directory '${localDirectory}' does not exist. Check provided path (missing quotes?)." >&2; echo -ne ${white} >&2; exit 2; }
```

2022-10-27 16:51 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +      *) echo -e "${red}Error: Specified language '${language}' is not supported." >&2; echo -ne ${white}; exit 1
```suggestion
      *) echo -e "${red}Error: Specified language '${language}' is not supported." >&2; echo -ne ${white} >&2; exit 2
```

2022-10-27 16:51 UTC, albertdb commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +      echo -e "For more info about the machineType: https://cloud.google.com/build/docs/api/reference/rest/v1/projects.builds?hl=fr#machinetype${white}"
```suggestion
      echo -e "${red}Error: Chosen machine type is not a valid one." >&2
      echo -e "${red}Use -h or --help flag to display help." >&2
      echo -e "${red} Also check official documentation: https://cloud.google.com/build/docs/api/reference/rest/v1/projects.builds?hl=en#machinetype" >&2
      echo -ne ${white} >&2
```

Let's make it more maintainable.

2022-10-27 16:51 UTC, albertdb commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +  echo -e "${green}Adding the machineType value to use a bigger VM for the execution of the pipeline.${white}"
```suggestion
  echo -e "${green}Setting machine type value on pipeline.${white}"
```

2022-10-27 16:51 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +        exit 1
```suggestion
        exit 2
```

2022-10-27 16:51 UTC, albertdb commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +      exit 1
```suggestion
      exit 2
```

2022-10-27 16:51 UTC, albertdb commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +        exit 127
```suggestion
        echo -e "${red}Error: Registry location not provided." >&2
        echo -ne ${white} >&2
        exit 2
```

2022-10-27 16:51 UTC, albertdb commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +    fi
```suggestion
```

Already checked.

2022-10-27 16:51 UTC, albertdb commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +versionVerification
```suggestion
languageVersionVerification
```

2022-10-27 16:51 UTC, albertdb commented on scripts/pipelines/gcloud/templates/build/build-pipeline.cfg
> +    *) echo -e "${red}Error: Specified language '${language}' is not supported." >&2; echo -ne ${white}; exit 1
```suggestion
    *) echo -e "${red}Error: Specified language '${language}' is not supported." >&2; echo -ne ${white} >&2; exit 1
```

2022-10-27 16:51 UTC, albertdb commented on documentation/src/common_templates/setup-build-pipeline.asciidoc
>  ```
Several missing flags.

2022-10-28 11:27 UTC, lpinon commented
Add trigger for next pipeline

2022-10-28 11:27 UTC, lpinon commented
Add trigger for next pipeline

2022-11-02 14:34 UTC, albertdb commented on documentation/src/common_templates/setup-build-pipeline.asciidoc
>  ```
@lpinon Python example should be put in docs source (here)

2022-11-02 14:37 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +        echo -e "${red}Language given is Flutter. It is required to use --version flag.${white}"
@ultymatom You just accepted suggestion, but not addressed what I commented.

2022-11-02 14:42 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +    [ "$provider" == "gcloud" ] && echo "  -m, --machine-type                     Machine type for pipeline runner. Accepted values: 'E2_HIGHCPU_8', 'E2_HIGHCPU_32', 'N1_HIGHCPU_8' or 'N1_HIGHCPU_32'
```suggestion
    [ "$provider" == "gcloud" ] && echo "  -m, --machine-type                     Machine type for pipeline runner. Accepted values: E2_HIGHCPU_8, E2_HIGHCPU_32, N1_HIGHCPU_8, N1_HIGHCPU_32."
```

2022-11-02 14:43 UTC, albertdb commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +      echo -ne ${white} >&2
```suggestion
      echo -ne "${white}" >&2
```

2022-11-02 14:46 UTC, albertdb commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +        echo -ne ${white} >&2
```suggestion
        echo -ne "${white}" >&2
```

2022-11-02 14:49 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +        echo -ne ${white} >&2
```suggestion
        echo -ne "${white}" >&2
```

2022-11-02 14:50 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +        echo -ne ${white} >&2
```suggestion
        echo -ne "${white}" >&2
```

2022-11-02 14:50 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +        echo -ne ${white} >&2
```suggestion
        echo -ne "${white}" >&2
```

2022-11-02 14:50 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +      *) echo -e "${red}Error: Specified language '${language}' is not supported." >&2; echo -ne ${white} >&2; exit 2
```suggestion
      *) echo -e "${red}Error: Specified language '${language}' is not supported." >&2; echo -ne "${white}" >&2; exit 2
```

2022-11-02 14:51 UTC, albertdb commented on scripts/pipelines/gcloud/templates/build/build-pipeline.cfg
> +    *) echo -e "${red}Error: Specified language '${language}' is not supported." >&2; echo -ne ${white} >&2; exit 2
```suggestion
    *) echo -e "${red}Error: Specified language '${language}' is not supported." >&2; echo -ne "${white}" >&2; exit 2
```

2022-11-02 16:45 UTC, albertdb commented on scripts/accounts/gcloud/create-project.sh
> +   exit 223
You will need to marge from master and increase this to 224

2022-11-07 11:33 UTC, ultymatom commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +        cd $currentPath
@sonatype-lift ignore

2022-11-07 11:34 UTC, ultymatom commented on scripts/pipelines/common/pipeline_generator.lib
> +        echo -e "${red}Language given is Flutter. It is required to use --version flag.${white}"
sorry that was a mistake

2022-11-07 16:46 UTC, mcerverc commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +FLAGS=$(getopt -a --options c:n:d:a:b:l:i:u:p:hm: --long "config-file:,pipeline-name:,local-directory:,project:,artifact-path:,target-branch:,language:,build-pipeline-name:,registry-location:,flutter
"project" flag included here but not in the switch case "$1"

2022-11-08 09:54 UTC, ultymatom commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +FLAGS=$(getopt -a --options c:n:d:a:b:l:i:u:p:hm: --long "config-file:,pipeline-name:,local-directory:,project:,artifact-path:,target-branch:,language:,build-pipeline-name:,registry-location:,flutter
deleted

2022-11-08 14:53 UTC, abcarcol commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +  export gCloudProject=$(echo "$gitOriginUrl" | cut -d'/' -f5)
```suggestion
  gCloudProject=$(echo "$gitOriginUrl" | cut -d'/' -f5)
  export gCloudProject
```

2022-11-08 15:09 UTC, abcarcol commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +  echo "" >> "${localDirectory}/${pipelinePath}/${yamlFile}"
@sonatype-lift ignore

2022-11-08 15:11 UTC, abcarcol commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +  echo "" >> "${localDirectory}/${pipelinePath}/${yamlFile}"
@sonatype-lift ignore

2022-11-09 11:41 UTC, albertdb commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +      echo -e "${red} Also check official documentation: https://cloud.google.com/build/docs/api/reference/rest/v1/projects.builds?hl=en#machinetype" >&2
```suggestion
      echo -e "${red}Also check official documentation: https://cloud.google.com/build/docs/api/reference/rest/v1/projects.builds?hl=en#machinetype" >&2
```

2022-11-09 11:45 UTC, albertdb commented on scripts/pipelines/gcloud/templates/build/build-pipeline.yml.template
> +  - |
```suggestion
  script: |
    #!/bin/bash
```

2022-11-09 11:46 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +    fi
```suggestion
```

2022-11-09 11:47 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +    if [ "$language" == "flutter" ] && [ "" == "$languageVersion" ]
Include python in condition

2022-11-09 11:56 UTC, albertdb requested changes

2022-11-09 11:56 UTC, albertdb commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +        cd $currentPath
```suggestion
        cd "$currentDirectory"
```

2022-11-09 11:56 UTC, albertdb commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +    if [[ `gcloud artifacts docker images list $imageTag --include-tags | awk '$3=="${languageVersion}" {print $3}'` == "" ]]
```suggestion
    if [[ $(gcloud artifacts docker images list "$imageTag" --include-tags | awk '$3=="${languageVersion}" {print $3}') == "" ]]
```

2022-11-09 11:56 UTC, albertdb commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +    gcloud config set project $gCloudProject
```suggestion
    gcloud config set project "$gCloudProject"
```

2022-11-09 11:56 UTC, albertdb commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +    if [[ `gcloud artifacts repositories list | awk '$1=="flutter" {print $1}'` == "" ]]
```suggestion
    if [[ $(gcloud artifacts repositories list | awk '$1=="flutter" {print $1}') == "" ]]
```

2022-11-09 12:00 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +        echo -e "${red}Error: Language given requires --version flag.${white}" >&2
```suggestion
        echo -e "${red}Error: Language given requires --language-version flag.${white}" >&2
```

2022-11-09 12:28 UTC, albertdb commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +        gcloud beta artifacts repositories create flutter --repository-format=docker --location=$registryLocation
```suggestion
        gcloud beta artifacts repositories create flutter --repository-format=docker --location="$registryLocation"
```

2022-11-09 12:31 UTC, albertdb commented on scripts/pipelines/common/templates/build/python-build.sh
> +. venv/bin/activate
```suggestion
# shellcheck source=/dev/null
. venv/bin/activate
```

2022-11-09 13:11 UTC, ultymatom commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +  } >> "${localDirectory}/${pipelinePath}/${yamlFile}"
@sonatype-lift ignore

2022-11-09 13:11 UTC, ultymatom commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +        cd "$currentDirectory"
@sonatype-lift ignore

2022-11-09 13:11 UTC, ultymatom commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +} >> "${localDirectory}/${pipelinePath}/${yamlFile}"
@sonatype-lift ignore

2022-11-09 13:23 UTC, albertdb approved these changes

2022-11-09 13:28 UTC, lpinon approved these changes

2022-11-09 13:50 UTC, merged