Gcloud quality pipeline
devonfw/hangar pull request #283
Opened 2022-10-20 12:23 UTC by jrodenasCapgemini

2022-10-20 13:56 UTC, jrodenasCapgemini commented on scripts/pipelines/gcloud/templates/quality/quality-pipeline.cfg
> +    specificEnvSubstList='${artifactsToPublish}'
```suggestion
```

2022-10-20 14:05 UTC, jrodenasCapgemini commented on scripts/pipelines/gcloud/templates/quality/quality-pipeline.cfg
> +
```suggestion
# Create a secret in Google Secret Manager. Then, it gives the sonar token as value for that token.
gcloud secrets create sonar-token \
    --replication-policy="automatic"
gcloud secrets versions add sonar-token --data-file="${sonarToken}"
```

2022-10-20 14:11 UTC, jrodenasCapgemini commented on scripts/pipelines/gcloud/templates/quality/quality-pipeline.cfg
> +    subsitutionVariable="_SONAR_URL=${sonarUrl},_SONAR_TOKEN=${sonarToken},_DOCKER_IMAGE=${dockerImage}"
```suggestion
    subsitutionVariable="_SONAR_URL=${sonarUrl},_SONAR_TOKEN=$(gcloud secrets versions access latest --secret="sonar-token" --format='get(payload.data)' | tr '_-' '/+' | base64 -d),_DOCKER_IMAGE=${dockerImage}"
```

2022-10-20 14:37 UTC, jrodenasCapgemini commented on scripts/pipelines/gcloud/templates/quality/quality-pipeline.yml.template
> +
```suggestion
secretEnv: ['SONAR_TOKEN']
availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/mySecret/versions/latest
    env: 'MYSECRET'
```

2022-10-20 14:42 UTC, jrodenasCapgemini commented on scripts/pipelines/gcloud/templates/quality/quality-pipeline.yml.template
> +
```suggestion
availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/sonar-token/versions/latest
    env: 'SONAR_TOKEN'
```

2022-10-20 14:43 UTC, jrodenasCapgemini commented on scripts/pipelines/gcloud/templates/quality/quality-pipeline.yml.template
> +  entrypoint: bash
```suggestion
  entrypoint: bash
  secretEnv: ['SONAR_TOKEN']
```

2022-10-20 14:46 UTC, jrodenasCapgemini commented on scripts/pipelines/gcloud/templates/quality/quality-pipeline.yml.template
> +    SONAR_TOKEN=${_SONAR_TOKEN}
```suggestion
```

2022-10-20 14:52 UTC, jrodenasCapgemini commented on scripts/pipelines/gcloud/templates/quality/quality-pipeline.cfg
> +    subsitutionVariable="_SONAR_URL=${sonarUrl},_SONAR_TOKEN=${sonarToken},_DOCKER_IMAGE=${dockerImage}"
```suggestion
    subsitutionVariable="_SONAR_URL=${sonarUrl},_DOCKER_IMAGE=${dockerImage}"
```

2022-10-25 13:10 UTC, jrodenasCapgemini commented on scripts/pipelines/gcloud/templates/quality/quality-pipeline.cfg
> +        --replication-policy="automatic"
```suggestion
    # Create a secret in Google Secret Manager. Then, it gives the sonar token as value for that token.
    gcloud secrets create sonar-token --replication-policy="automatic"
```

2022-10-25 13:16 UTC, jrodenasCapgemini commented on scripts/pipelines/gcloud/templates/quality/quality-pipeline.yml.template
> +# mark to insert entry in artifact for additonal artifact #
```suggestion
steps:
- name: gcr.io/cloud-builders/gsutil
  args:
    - cp
    - 'gs://${PROJECT_ID}_cloudbuild/pipelinesArtifacts/${buildPipelineName}/commit_${SHORT_SHA}/build_*.tar'
    - .
- name: ${_DOCKER_IMAGE}
  entrypoint: bash
  secretEnv: ['SONAR_TOKEN']
  env: 
    - PROJECT_PATH=./
    - SONAR_URL=${_SONAR_URL}
  args:
  - -c
  - |
    set -ex
    # In case of more than 1 tar, we extract the most recent one)
    for i in $(ls -t build_*.tar)
    do
        tar -xf $i
        break
    done
    sh .pipelines/scripts/quality.sh
availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/sonar-token/versions/latest
    env: 'SONAR_TOKEN'

# mark to insert step for additonal artifact #

# mark to insert entry in artifact for additonal artifact #```

2022-10-27 10:27 UTC, jrodenasCapgemini commented on scripts/pipelines/gcloud/templates/quality/quality-pipeline.cfg
> +     echo "${sonarToken}" | gcloud secrets versions add sonar-token --data-file=-
```suggestion
    echo "${sonarToken}" | gcloud secrets versions add sonar-token --data-file=-
```

2022-10-27 11:42 UTC, jrodenasCapgemini commented on scripts/pipelines/gcloud/templates/quality/quality-pipeline.yml.template
> +    sh .pipelines/scripts/quality.sh
```suggestion
    sh .pipelines/scripts/quality.sh
 # mark to insert trigger
```

2022-10-27 11:43 UTC, jrodenasCapgemini commented on scripts/pipelines/gcloud/templates/quality/quality-pipeline.cfg
> +
```suggestion
# Previous pipeline
previousPipelineyaml='test-pipeline.yml'
```

2022-10-27 11:47 UTC, jrodenasCapgemini commented on scripts/pipelines/gcloud/templates/quality/quality-pipeline.yml.template
> + # mark to insert trigger
```suggestion
# mark to insert trigger
```

2022-10-28 11:27 UTC, lpinon commented
Add trigger for next pipeline

2022-10-31 10:19 UTC, jrodenasCapgemini commented on scripts/pipelines/gcloud/templates/quality/quality-pipeline.cfg
> +mandatoryFlags="$pipelineName,$localDirectory,$language,"
```suggestion
mandatoryFlags="$pipelineName,$localDirectory,$language,$buildPipelineName,"
```

2022-11-02 16:35 UTC, albertdb requested changes

2022-11-02 16:35 UTC, albertdb commented on scripts/pipelines/common/templates/quality/python-quality.sh.template
> +export PATH="$PATH:/opt/sonar-scanner/bin"
Definitely not the way to go. Talk with Timothé about setup environment script.

2022-11-02 16:35 UTC, albertdb commented on scripts/pipelines/common/templates/quality/python-quality.sh.template
> +coverage xml
This seems a test thing. Do you need something form test pipeline?

2022-11-02 16:35 UTC, albertdb commented on scripts/pipelines/gcloud/templates/quality/quality-pipeline.cfg
> +    *) echo -e "${red}Error: Specified language '${language}' is not supported." >&2; echo -ne ${white}; exit 1
Missing Python and Flutter.

2022-11-02 16:40 UTC, albertdb requested changes
Missing documentation for Google Cloud.

Missing Python and Flutter examples in docs.

2022-11-02 17:30 UTC, jrodenasCapgemini commented on scripts/pipelines/gcloud/templates/quality/quality-pipeline.cfg
> +    node | angular) dockerImage="node" ;;
```suggestion
    node | angular) dockerImage="node" ;;
    python) dockerImage="python:${languageVersion}-slim" ;;
#  flutter) dockerImage="${registryLocation}-docker.pkg.dev/${gCloudRepo}/flutter/flutter:${flutterVersion}" ;;
```

2022-11-04 11:32 UTC, jrodenasCapgemini commented on scripts/pipelines/gcloud/templates/quality/quality-pipeline.cfg
> +    echo "${sonarToken}" | gcloud secrets versions add sonar-token --data-file=-
```suggestion
    # Create a secret in Google Secret Manager if is not defined. Then, it gives the sonar token as value for that token.
    if ! gcloud secrets versions access latest --secret="sonar-token" &>/dev/null; then
        gcloud secrets create sonar-token --replication-policy="automatic"  
    fi
```

2022-11-04 11:32 UTC, jrodenasCapgemini commented on scripts/pipelines/gcloud/templates/quality/quality-pipeline.yml.template
> +    set -ex
```suggestion
    set -ex
    apt-get update
    apt-get install openjdk-17-jre -y
```

2022-11-04 11:32 UTC, jrodenasCapgemini commented on scripts/pipelines/common/templates/quality/python-quality.sh.template
> +sonar-scanner -Dsonar.host.url="$SONAR_URL" -Dsonar.login="$SONAR_TOKEN" -Dsonar.projectKey=$projectKey -Dsonar.sources="." -Dsonar.python.coverage.reportPaths=coverage.xml
```suggestion
sonar-scanner -Dsonar.host.url="$SONAR_URL" -Dsonar.login="$SONAR_TOKEN" -Dsonar.projectKey=$projectKey -Dsonar.sources="." -Dsonar.python.coverage.reportPaths=coverage.xml -Dsonar.exclusions=venv/lib/python3.10/site-packages/**

```

2022-11-04 11:32 UTC, jrodenasCapgemini commented on scripts/pipelines/common/templates/quality/node-quality.sh.template
> +apt-get install -y openjdk-17-jre
It is necessary for sonar-scanner. Otherwise, it does not work at all.

2022-11-04 11:39 UTC, jrodenasCapgemini commented on scripts/pipelines/gcloud/templates/quality/quality-pipeline.cfg
> +#  flutter) dockerImage="${registryLocation}-docker.pkg.dev/${gCloudRepo}/flutter/flutter:${flutterVersion}" ;;
```suggestion
    flutter) dockerImage="${registryLocation}-docker.pkg.dev/${gCloudRepo}/flutter/flutter:${flutterVersion}" ;;
```

2022-11-04 13:09 UTC, jrodenasCapgemini commented on scripts/pipelines/gcloud/templates/quality/quality-pipeline.cfg
> +branchTrigger='.*'
```suggestion
branchTrigger='.*'
# Setup Environment script
setupScriptFile="quality-setup-environment.sh"
```

2022-11-04 13:12 UTC, jrodenasCapgemini commented on scripts/pipelines/gcloud/templates/quality/quality-pipeline.cfg
> +    cp "${hangarPath}/${commonTemplatesPipelinePath}/${language}-${scriptFile}.template" "${localDirectory}/${scriptFilePath}/${scriptFile}"
```suggestion
    cp "${hangarPath}/${commonTemplatesPipelinePath}/${language}-${scriptFile}.template" "${localDirectory}/${scriptFilePath}/${scriptFile}"
    ! [ -f "${hangarPath}/${templatesPath}/${language}-${setupScriptFile}" ] || cp "${hangarPath}/${templatesPath}/${language}-${setupScriptFile}" "${localDirectory}/${scriptFilePath}/${setupScriptFile}"

```

2022-11-04 13:42 UTC, jrodenasCapgemini commented on scripts/pipelines/common/templates/quality/angular-quality.sh.template
> +apt-get install -y openjdk-17-jre
I have solved the problem with Timothe.

2022-11-04 13:59 UTC, jrodenasCapgemini commented on scripts/pipelines/common/templates/quality/python-quality.sh.template
> +export PATH="$PATH:/opt/sonar-scanner/bin"
```suggestion
```

2022-11-04 14:01 UTC, jrodenasCapgemini commented on scripts/pipelines/common/templates/quality/python-quality.sh.template
> +export PATH="$PATH:/opt/sonar-scanner/bin"
Problem solved and setup environment script added.

2022-11-07 11:43 UTC, jrodenasCapgemini commented on scripts/pipelines/gcloud/templates/quality/angular-quality-setup-environment.sh
> +apt-get update -y
```suggestion
#!/bin/bash
apt-get update -y
```

2022-11-07 11:44 UTC, jrodenasCapgemini commented on scripts/pipelines/gcloud/templates/quality/node-quality-setup-environment.sh
> +apt-get update -y
```suggestion
#!/bin/bash
apt-get update -y
```

2022-11-07 11:46 UTC, jrodenasCapgemini commented on scripts/pipelines/gcloud/templates/quality/node-quality-setup-environment.sh
> +apt-get update -y
```suggestion
#!/bin/bash
apt-get update -y
```

2022-11-08 10:15 UTC, ultymatom commented on scripts/pipelines/common/templates/quality/python-quality.sh.template
> +coverage xml
We let them here waitng for doing the enhancement about giving the test artifact to the quality pipeline

2022-11-09 16:20 UTC, albertdb commented on documentation/src/azure-devops/setup-quality-pipeline.asciidoc
> +:openBrowserFlag: -w
Missing Extra args Python

Missing Extra args Flutter.

2022-11-09 16:22 UTC, albertdb commented on documentation/src/common_templates/setup-quality-pipeline.asciidoc
>  ```
Missing Flutter example

2022-11-09 16:22 UTC, albertdb commented on documentation/src/gcloud/setup-quality-pipeline.asciidoc
> +:no-PR-or-MR:
Missing Extra args Flutter.

2022-11-09 16:25 UTC, albertdb commented on documentation/src/github/setup-quality-pipeline.asciidoc
>  :extra_sentence_ci: Please note that this workflow, although manually triggerable, is designed to be executed as part of a CI workflow, which you can create following this xref:setup-ci-pipeline.asci
Missing empty Extra args Python

Missing empty Extra args Flutter.

2022-11-09 16:25 UTC, albertdb commented on scripts/pipelines/common/templates/quality/flutter-quality.sh.template
> +#flutter test --machine --coverage > tests.output
Remove?

2022-11-09 16:27 UTC, albertdb commented on scripts/pipelines/common/templates/quality/flutter-quality.sh.template
> +sonar-scanner -Dsonar.host.url="$SONAR_URL" -Dsonar.login="$SONAR_TOKEN" -Dsonar.projectKey=$projectKey -Dsonar.sources="lib" -Dsonar.exclusions=test/**/*_test.mocks.dart,lib/**/*.g.dart,lib/**/*.gr.
```suggestion
sonar-scanner -Dsonar.host.url="$SONAR_URL" -Dsonar.login="$SONAR_TOKEN" -Dsonar.projectKey="$projectKey" -Dsonar.sources="lib" -Dsonar.exclusions=test/**/*_test.mocks.dart,lib/**/*.g.dart,lib/**/*.gr.dart,lib/**/*.freezed.dart -Dsonar.tests=test -Dsonar.sourceEncoding=UTF-8
```

2022-11-09 16:30 UTC, albertdb commented on scripts/pipelines/gcloud/templates/quality/quality-pipeline.cfg
> +mandatoryFlags="$pipelineName,$localDirectory,$language,$buildPipelineName,"
Missing mandatory test pipeline name flag

2022-11-09 16:30 UTC, albertdb commented on scripts/pipelines/gcloud/templates/quality/quality-pipeline.cfg
> +branchTrigger='.*'
```suggestion
branchTrigger='_manual_'
```

2022-11-09 16:38 UTC, albertdb commented on scripts/pipelines/gcloud/templates/quality/quality-pipeline.yml.template
> +    done
Why do we do this differently than in test pipeline?

2022-11-09 16:47 UTC, lpinon commented on documentation/gcloud/setup-quality-pipeline.asciidoc
> +./pipeline_generator.sh -c ./templates/quality/quality-pipeline.cfg -n python-project-quality -l angular --sonar-url http://1.2.3.4:9000 --sonar-token 6ce6663b63fc02881c6ea4c7cBa6563b8247a04e -d C:/U
```suggestion
./pipeline_generator.sh -c ./templates/quality/quality-pipeline.cfg -n python-project-quality -l python--sonar-url http://1.2.3.4:9000 --sonar-token 6ce6663b63fc02881c6ea4c7cBa6563b8247a04e -d C:/Users/$USERNAME/Desktop/python-project {extra_args_python} -b develop {openBrowserFlag}
```

2022-11-09 16:48 UTC, lpinon commented on documentation/github/setup-quality-pipeline.asciidoc
> +./pipeline_generator.sh -c ./templates/quality/quality-pipeline.cfg -n python-project-quality -l angular --sonar-url http://1.2.3.4:9000 --sonar-token 6ce6663b63fc02881c6ea4c7cBa6563b8247a04e -d C:/U
```suggestion
./pipeline_generator.sh -c ./templates/quality/quality-pipeline.cfg -n python-project-quality -l python --sonar-url http://1.2.3.4:9000 --sonar-token 6ce6663b63fc02881c6ea4c7cBa6563b8247a04e -d C:/Users/$USERNAME/Desktop/python-project {extra_args_python} -b develop {openBrowserFlag}
```

2022-11-09 16:51 UTC, lpinon commented on documentation/src/azure-devops/setup-quality-pipeline.asciidoc
> +:openBrowserFlag: -w
```suggestion
:openBrowserFlag: -w
:extra_args_python: --build-pipeline-name python-project-build
```

2022-11-09 16:51 UTC, lpinon commented on documentation/src/common_templates/setup-quality-pipeline.asciidoc
> +./pipeline_generator.sh -c ./templates/quality/quality-pipeline.cfg -n python-project-quality -l angular --sonar-url http://1.2.3.4:9000 --sonar-token 6ce6663b63fc02881c6ea4c7cBa6563b8247a04e -d C:/U
```suggestion
./pipeline_generator.sh -c ./templates/quality/quality-pipeline.cfg -n python-project-quality -l python --sonar-url http://1.2.3.4:9000 --sonar-token 6ce6663b63fc02881c6ea4c7cBa6563b8247a04e -d C:/Users/$USERNAME/Desktop/python-project {extra_args_python} -b develop {openBrowserFlag}
```

2022-11-09 16:58 UTC, lpinon commented on documentation/src/github/setup-quality-pipeline.asciidoc
>  :extra_sentence_ci: Please note that this workflow, although manually triggerable, is designed to be executed as part of a CI workflow, which you can create following this xref:setup-ci-pipeline.asci
```suggestion
:extra_args_python:
:extra_args_flutter:
:extra_sentence_ci: Please note that this workflow, although manually triggerable, is designed to be executed as part of a CI workflow, which you can create following this xref:setup-ci-pipeline.asciidoc[guide].
```

2022-11-09 17:18 UTC, capf4bbo commented on documentation/src/gcloud/setup-quality-pipeline.asciidoc
> +:extra_args_python: --build-pipeline-name python-project-build
```suggestion
:extra_args_python: --build-pipeline-name python-project-build
:extra_args_flutter: --build-pipeline-name flutter-project-build
```

2022-11-09 17:39 UTC, albertdb commented on documentation/src/common_templates/setup-quality-pipeline.asciidoc
> +./pipeline_generator.sh -c ./templates/quality/quality-pipeline.cfg -n flutter-project-quality -l flutter --sonar-url http://1.2.3.4:9000 --sonar-token 6ce6663b63fc02881c6ea4c7cBa6563b8247a04e -d C:/
````suggestion
```
./pipeline_generator.sh -c ./templates/quality/quality-pipeline.cfg -n flutter-project-quality -l flutter --sonar-url http://1.2.3.4:9000 --sonar-token 6ce6663b63fc02881c6ea4c7cBa6563b8247a04e -d C:/Users/$USERNAME/Desktop/flutter-project {extra_args_flutter} -b develop {openBrowserFlag}
```
````

2022-11-09 17:43 UTC, albertdb commented on documentation/azure-devops/setup-quality-pipeline.asciidoc
> +
````suggestion
```
````

2022-11-09 17:46 UTC, albertdb commented on documentation/src/common_templates/setup-quality-pipeline.asciidoc
> +==== Flutter project
````suggestion
```

==== Flutter project
````

2022-11-09 17:48 UTC, albertdb commented on documentation/src/gcloud/setup-quality-pipeline.asciidoc
> +:extra_args_angular: --build-pipeline-name angular-project-build
```suggestion
:extra_args_quarkus: --build-pipeline-name quarkus-project-build --test-pipeline-name quarkus-project-test
:extra_args_node: --build-pipeline-name node-project-build --test-pipeline-name node-project-test
:extra_args_angular: --build-pipeline-name angular-project-build --test-pipeline-name angular-project-test
```

2022-11-09 17:49 UTC, albertdb commented on documentation/src/github/setup-quality-pipeline.asciidoc
> +:extra_args_flutter:
```suggestion
```

2022-11-09 17:49 UTC, albertdb submitted a review, later dismissed

2022-11-09 17:50 UTC, albertdb submitted a review, later dismissed

2022-11-09 17:52 UTC, albertdb approved these changes

2022-11-10 16:03 UTC, lpinon approved these changes

2022-11-10 16:23 UTC, ultymatom approved these changes

2022-11-10 16:24 UTC, merged