feature/test-pipeline-draft
devonfw/hangar pull request #285
Opened 2022-10-24 13:31 UTC by mcerverc

2022-10-28 11:26 UTC, lpinon commented
Add trigger for next pipeline

2022-11-02 14:58 UTC, albertdb requested changes

2022-11-02 14:58 UTC, albertdb commented on documentation/src/gcloud/setup-test-pipeline.asciidoc
> +:extra_args_angular: --build-pipeline-name angular-project-build
Missing openBrowserFlag and machineType. Check https://github.com/devonfw/hangar/pull/277/files#diff-d922906ac1017e0ed6268413f541beef53e5946be5a672b58024014fa0c41087

Will need to modify other providers docs to include first also.

2022-11-02 16:39 UTC, albertdb submitted a review, later dismissed
Missing Python and Flutter examples in docs.

2022-11-02 16:55 UTC, lpinon commented
> Missing Python and Flutter examples in docs.

Python done, Flutter out of scope for this sprint.

2022-11-08 08:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw/hangar?pullRequest=285) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/devonfw/hangar?pullRequest=285) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: mcerverc<br/>:white_check_mark: lpinon<br/>:x: capf4bbo<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw/hangar?pullRequest=285) it.</sub>

2022-11-08 11:12 UTC, ultymatom submitted a review, later dismissed

2022-11-09 14:36 UTC, lpinon submitted a review, later dismissed

2022-11-09 14:37 UTC, ultymatom approved these changes

2022-11-09 14:40 UTC, albertdb requested changes

2022-11-09 14:40 UTC, albertdb commented on documentation/src/azure-devops/setup-test-pipeline.asciidoc
> +:extra_args_python: --language-version 3.10
Probably missing Build pipeline name.

Missing Extra args Flutter.

2022-11-09 14:40 UTC, albertdb commented on documentation/src/common_templates/setup-test-pipeline.asciidoc
> +
```suggestion
```

2022-11-09 14:40 UTC, albertdb commented on documentation/src/common_templates/setup-test-pipeline.asciidoc
> +  [--language-version <version>]
```suggestion
  --language-version <version> \
```

2022-11-09 14:40 UTC, albertdb commented on documentation/src/common_templates/setup-test-pipeline.asciidoc
> +--language-version                     Version number of the language. Only required for python.
```suggestion
    --language-version   [Required, if Flutter or Python] Language or framework version.
```

2022-11-09 14:40 UTC, albertdb commented on documentation/src/gcloud/setup-test-pipeline.asciidoc
> +:extra_args_python: --language-version 3.10
Probably missing Build pipeline name.

Missing Extra args Flutter.

2022-11-09 14:40 UTC, albertdb commented on documentation/src/github/setup-test-pipeline.asciidoc
> +:extra_args_flutter: --language-version 3.0.4
Probably missing Build pipeline name.

2022-11-09 14:40 UTC, albertdb commented on scripts/pipelines/gcloud/templates/test/test-pipeline.cfg
> +branchTrigger='.*'
Unused?

2022-11-09 14:40 UTC, albertdb commented on scripts/pipelines/gcloud/templates/test/test-pipeline.cfg
> +    subsitutionVariable="_DOCKER_IMAGE=${dockerImage},_BUILD_PIPELINE_NAME=${buildPipelineName},_BRANCH_NAME="
Branch name empty

2022-11-09 15:08 UTC, ultymatom approved these changes

2022-11-09 15:08 UTC, ultymatom commented on documentation/src/azure-devops/setup-test-pipeline.asciidoc
> +:extra_args_python: --language-version 3.10
yes it is missing

2022-11-09 15:09 UTC, ultymatom commented on scripts/pipelines/gcloud/templates/test/test-pipeline.cfg
> +branchTrigger='.*'
it is used in the add trigger, not part of this PR but in master

2022-11-09 15:09 UTC, ultymatom commented on scripts/pipelines/gcloud/templates/test/test-pipeline.cfg
> +    subsitutionVariable="_DOCKER_IMAGE=${dockerImage},_BUILD_PIPELINE_NAME=${buildPipelineName},_BRANCH_NAME="
```suggestion
    subsitutionVariable="_DOCKER_IMAGE=${dockerImage},_BUILD_PIPELINE_NAME=${buildPipelineName},_BRANCH_NAME=\$BRANCH_NAME"
```

Better having value by default  that is the built-in var

2022-11-09 15:16 UTC, mcerverc commented on scripts/pipelines/gcloud/templates/test/test-pipeline.cfg
> +branchTrigger='.*'
Used but not .* for this pipeline. I'll fix right now

2022-11-09 15:16 UTC, mcerverc commented on scripts/pipelines/gcloud/templates/test/test-pipeline.cfg
> +branchTrigger='.*'
```suggestion
branchTrigger='manualtrigger'
```

2022-11-09 15:21 UTC, mcerverc commented on scripts/pipelines/gcloud/templates/test/test-pipeline.cfg
> +    subsitutionVariable="_DOCKER_IMAGE=${dockerImage},_BUILD_PIPELINE_NAME=${buildPipelineName},_BRANCH_NAME="
@ultymatom are you sure you can use default pipeline variables inside substitution variables?

2022-11-09 16:19 UTC, albertdb commented on scripts/pipelines/gcloud/templates/test/test-pipeline.cfg
> +branchTrigger='manualtrigger'
```suggestion
branchTrigger='_manual_'
```
Would this work?

2022-11-09 16:55 UTC, ultymatom commented on scripts/pipelines/gcloud/templates/test/test-pipeline.cfg
> +    subsitutionVariable="_DOCKER_IMAGE=${dockerImage},_BUILD_PIPELINE_NAME=${buildPipelineName},_BRANCH_NAME="
yes I did it for the deploy

2022-11-09 17:03 UTC, lpinon commented on documentation/src/gcloud/setup-test-pipeline.asciidoc
> +:extra_args_python: --language-version 3.10
```suggestion
:extra_args_python: --build-pipeline-name python-project-build --language-version 3.10
```

2022-11-09 17:04 UTC, lpinon commented on documentation/src/azure-devops/setup-test-pipeline.asciidoc
> +:extra_args_python: --language-version 3.10
```suggestion
:extra_args_python: --build-pipeline-name python-project-build --language-version 3.10
```

2022-11-09 17:07 UTC, albertdb commented on documentation/src/azure-devops/setup-test-pipeline.asciidoc
> +:extra_args_flutter: --language-version 3.3.4
Missing Build pipeline name.

2022-11-09 17:08 UTC, lpinon commented on documentation/src/azure-devops/setup-test-pipeline.asciidoc
> +:extra_args_flutter: --language-version 3.3.4
```suggestion
:extra_args_flutter: --build-pipeline-name flutter-project-build --language-version 3.3.4
```

2022-11-09 17:08 UTC, lpinon commented on documentation/src/gcloud/setup-test-pipeline.asciidoc
> +:extra_args_flutter: --language-version 3.3.4
```suggestion
:extra_args_flutter: --language-version 3.3.4 --build-pipeline-name python-project-build
```

2022-11-09 17:20 UTC, albertdb commented on documentation/src/common_templates/setup-test-pipeline.asciidoc
> +ifdef::machineType[-m, --machine-type                  Machine type for {pipeline_type} runner. Accepted values: E2_HIGHCPU_8, E2_HIGHCPU_32, N1_HIGHCPU_8, N1_HIGHCPU_32.]
```suggestion
ifndef::no-PR-or-MR[-w                                     Open the Pull Request on the web browser if it cannot be automatically merged. Requires -b flag.]
ifdef::machineType[-m, --machine-type                     Machine type for {pipeline_type} runner. Accepted values: E2_HIGHCPU_8, E2_HIGHCPU_32, N1_HIGHCPU_8, N1_HIGHCPU_32.]
```

2022-11-09 17:21 UTC, albertdb commented on documentation/src/common_templates/setup-test-pipeline.asciidoc
> +    --language-version   [Required, if Flutter or Python] Language or framework version.
```suggestion
    --language-version      [Required, if Flutter or Python] Language or framework version.
```

2022-11-09 17:25 UTC, albertdb approved these changes

2022-11-09 17:26 UTC, albertdb requested changes

2022-11-09 17:26 UTC, albertdb commented on scripts/pipelines/gcloud/templates/test/test-pipeline.yml.template
> +  args: ['sh', '.pipelines/scripts/test.sh']
```suggestion
  args: ['.pipelines/scripts/test.sh']
```

2022-11-09 17:26 UTC, albertdb commented on scripts/pipelines/common/templates/test/flutter-test.sh
> +#!/bin/bash
Make file executable

2022-11-09 17:26 UTC, albertdb commented on scripts/pipelines/common/templates/test/python-test.sh
> +#!/bin/bash
Make file executable

2022-11-09 17:33 UTC, albertdb approved these changes

2022-11-09 17:36 UTC, albertdb approved these changes

2022-11-09 17:36 UTC, lpinon approved these changes

2022-11-09 17:42 UTC, merged

2022-11-10 14:50 UTC, mcerverc commented on scripts/pipelines/gcloud/templates/test/test-pipeline.cfg
> +branchTrigger='manualtrigger'
yeah, my fault