feature/gcloud-package-pipeline
devonfw/hangar pull request #289
Opened 2022-10-25 10:45 UTC by abcarcol

2022-10-28 06:24 UTC, ultymatom commented on scripts/pipelines/common/pipeline_generator.lib
> +    echo "  -v, --version                          Additional arguments for language version."
I don't think this arg should be a commmon flag as we don't use it for deploy provisioning

2022-10-28 06:30 UTC, ultymatom commented on scripts/pipelines/common/pipeline_generator.lib
> +    echo "  -v, --version                          Additional arguments for language version."
(you can actually reove the message from the help function, in the build OPR it has been written)

2022-10-28 06:45 UTC, ultymatom commented on scripts/pipelines/gcloud/templates/package/package-pipeline.cfg
> +mandatoryFlags="$imageName,$buildPipelineName,${language}${dockerFile},$qualityPipelineName,"
you need ${pipelineName} too

2022-10-28 06:47 UTC, ultymatom commented on scripts/pipelines/common/templates/package/package-common.sh
> +    docker build -f "$dockerFile" -t "$region"-"$registry"/"$PROJECT_ID"/"$imageName":"$tag_completed" "$context"
I don't know how it works for google, but for the other, all of this is part of the imagename

2022-10-28 06:48 UTC, ultymatom commented on scripts/pipelines/common/templates/package/package-common.sh
> +    docker build -f "$dockerFile" -t "$region"-"$registry"/"$PROJECT_ID"/"$imageName":"$tag_completed" "$context"
I mean all of this : "$region"-"$registry"/"$PROJECT_ID"/

2022-10-28 07:58 UTC, ultymatom commented on scripts/pipelines/gcloud/templates/package/package-pipeline.yml.template
> +  args: ['cp', 'gs://package-test-bucket/build_1.tar', '.']
The name and path is not good
```suggestion
  args: ['cp', 'gs://${PROJECT_ID}_cloudbuild/pipelinesArtifacts/${buildPipelineName}/commit_${SHORT_SHA}', '.']
```

2022-10-28 08:02 UTC, ultymatom commented on scripts/pipelines/gcloud/templates/package/package-pipeline.yml.template
> +  args: ['tar', '-xf', 'build_1.tar', '.']
```suggestion
- name: ${_DOCKER_IMAGE}
  entrypoint: bash
  args: 
  - -c
  - |
    # In case of more than 1 tar, we extract the most recent one)
    for i in $(ls -t build_*.tar)
    do
        tar -xf $i
        break
    done
```
(not sure about the indentation)

2022-10-28 11:28 UTC, lpinon commented
Add trigger for next pipeline

2022-11-02 16:43 UTC, albertdb submitted a review, later dismissed
Missing latest changes from pipeline generator (in build PR), so nothing is touched here. (we should probably merge that PR first)

Missing documentation for Google Cloud.

Missing Python and Flutter examples in docs.

2022-11-07 08:30 UTC, abcarcol commented on scripts/pipelines/common/templates/package/package-common.sh
> +    repositoryName=$(echo $imageName | cut -d '/' 3)
```suggestion
    repositoryName=$(echo "$imageName" | cut -d '/' 3)
```

2022-11-07 08:34 UTC, abcarcol commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +        --gcloud-region)          gCloudRegion="$2"; shift 2;;
```suggestion
```

2022-11-11 10:54 UTC, abcarcol commented on scripts/pipelines/common/templates/package/flutter-package.sh
> +tag="0.0.1"
@sonatype-lift ignore

2022-11-11 10:55 UTC, abcarcol commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +            sed -e "s/# mark to insert trigger/- name: gcr.io\/cloud-builders\/gsutil\n  entrypoint: bash\n  args:\n  - -c\n  - |\n    if [[ "\$BRANCH_NAME" =~ $branchTrigger ]] || exit 0; then\n
@sonatype-lift ignore

2022-11-11 10:56 UTC, abcarcol commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +            sed -e "s/# mark to insert trigger/- name: gcr.io\/cloud-builders\/gsutil\n  entrypoint: bash\n  args:\n  - -c\n  - |\n    if [[ "\$_BRANCH_NAME" =~ $branchTrigger ]] || exit 0; then\n
@sonatype-lift ignore

2022-11-11 10:56 UTC, abcarcol commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +            sed -e "s/# mark to insert trigger/- name: gcr.io\/cloud-builders\/gsutil\n  entrypoint: bash\n  args:\n  - -c\n  - |\n    if [[ "\$BRANCH_NAME" =~ $branchTrigger ]] || exit 0; then\n
@sonatype-lift ignore

2022-11-11 10:57 UTC, abcarcol commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +  } >> "${localDirectory}/${pipelinePath}/${yamlFile}"
@sonatype-lift ignore

2022-11-14 10:26 UTC, abcarcol commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +    all_roles_array=($all_roles)
@sonatype-lift ignore

2022-11-14 10:29 UTC, abcarcol commented on scripts/pipelines/gcloud/templates/package/package-pipeline.cfg
> +mandatoryFlags="$imageName,$buildPipelineName,${language}${dockerFile},$qualityPipelineName,"
```suggestion
mandatoryFlags="${pipelineName},$imageName,$buildPipelineName,${language}${dockerFile},$qualityPipelineName,"
```

2022-11-14 10:31 UTC, abcarcol commented on scripts/pipelines/common/templates/package/flutter-package.sh
> +    tag="0.0.1"
@sonatype-lift ignore

2022-11-14 14:22 UTC, abcarcol commented on scripts/pipelines/common/templates/package/flutter-package.sh
> +red='\e[0;31m'
```suggestion
```

2022-11-14 15:35 UTC, lpinon approved these changes

2022-11-14 16:11 UTC, lpinon approved these changes

2022-11-14 16:24 UTC, lpinon submitted a review, later dismissed

2022-11-14 16:33 UTC, lpinon submitted a review, later dismissed

2022-11-15 07:36 UTC, lpinon submitted a review, later dismissed

2022-11-15 09:49 UTC, lpinon approved these changes

2022-11-15 10:15 UTC, lpinon approved these changes

2022-11-15 10:43 UTC, lpinon submitted a review, later dismissed

2022-11-15 14:52 UTC, lpinon approved these changes

2022-11-15 14:53 UTC, capf4bbo submitted a review, later dismissed

2022-11-15 14:53 UTC, lpinon submitted a review, later dismissed

2022-11-15 16:08 UTC, albertdb requested changes
Documentation not in source file, as discussed in chat.

Clearly a good case where we cannot merge to master.

I continue reviewing meanwhile.

2022-11-15 17:13 UTC, albertdb requested changes
Documentation pending.

2022-11-15 17:13 UTC, albertdb commented on scripts/pipelines/common/templates/package/flutter-package.sh
> +    gcloud storage cp build/app/outputs/flutter-apk/app-release.apk gs://"${PROJECT_ID}"-apk/app-release-"$SHORT_SHA".apk
We probably should exit after that, we don't have nor can push any docker image, right?

2022-11-15 17:13 UTC, albertdb commented on scripts/pipelines/common/templates/package/flutter-package.sh
> +    gcloud storage cp build/app/outputs/flutter-apk/app-release.apk gs://"${PROJECT_ID}"-apk/app-release-"$SHORT_SHA".apk
We probably should exit after that, we don't have and therefore cannot push any docker image, right?

2022-11-15 17:13 UTC, albertdb commented on scripts/pipelines/common/templates/package/python-package.sh
> +echo "$tag"
```suggestion
```

2022-11-15 17:13 UTC, albertdb commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +        --flutter-platform)      export flutterPlatform=$2; shift 2;;
```suggestion
        --flutter-platform)       export flutterPlatform=$2; shift 2;;
```

2022-11-15 17:13 UTC, albertdb commented on scripts/pipelines/gcloud/templates/package/flutter-package-pipeline.yml.template
> +    fi
This should be done in flutter-package.sh

2022-11-15 17:13 UTC, albertdb commented on scripts/pipelines/gcloud/templates/package/flutter-package-pipeline.yml.template
> +        .pipelines/scripts/package-extra.sh
Now I understand why you don't exit in flutter-package.sh. Better have a single yaml and manage complexity in scripts.

2022-11-15 17:13 UTC, albertdb commented on scripts/pipelines/gcloud/templates/package/package-pipeline.cfg
> +#dockerImageTagFilePaths="quarkus-jvm:pom.xml quarkus:pom.xml node:package.json angular:package.json"
Can't we remove this?

2022-11-15 17:13 UTC, albertdb commented on scripts/pipelines/gcloud/templates/package/package-pipeline.cfg
> +        quarkus*) dockerImage="toDefine" ;;
Should be defined, but basically we need a image that has docker for any language that we just have to build a docker image. Flutter is the exception.

2022-11-15 17:13 UTC, albertdb commented on scripts/pipelines/gcloud/templates/package/package-pipeline.cfg
> +            subsitutionVariable=$subsitutionVariable",_ANDROID_API_KEY=${androidApiKey}"
This is possibly a secret.

2022-11-16 11:44 UTC, albertdb commented on scripts/pipelines/common/templates/package/flutter-package.sh
> +    fi
A good reason for not doing this here is that this is Google Cloud specific code in a common script that will be consumed by pipelines for any provider.

2022-11-17 11:12 UTC, abcarcol commented on scripts/pipelines/common/templates/package/flutter-package.sh
> +    tag="0.0.1"
Right, "tag" should be obtained from project files and not hardcoded

2022-11-17 11:48 UTC, abcarcol commented on scripts/pipelines/common/templates/package/flutter-package.sh
> +    fi
@albertdb Please review the latest changes when possible.

2022-11-17 11:51 UTC, abcarcol commented on scripts/pipelines/common/templates/package/flutter-package.sh
> +    gcloud storage cp build/app/outputs/flutter-apk/app-release.apk gs://"${PROJECT_ID}"-apk/app-release-"$SHORT_SHA".apk
Removed from flutter-package.sh as it was provider dependent. And yes, in the android case, we simply store the .apk artifact in a bucket and we do not invoke deploy.

2022-11-17 11:51 UTC, abcarcol commented on scripts/pipelines/common/templates/package/flutter-package.sh
> +    gcloud storage cp build/app/outputs/flutter-apk/app-release.apk gs://"${PROJECT_ID}"-apk/app-release-"$SHORT_SHA".apk
Repeated?

2022-11-17 11:54 UTC, abcarcol commented on scripts/pipelines/common/templates/package/python-package.sh
> +echo "$tag"
Removed the "echo" line and exported "tag"

2022-11-17 12:02 UTC, abcarcol commented on scripts/pipelines/gcloud/templates/package/flutter-package-pipeline.yml.template
> +    fi
@albertdb We have to look this more in detail, call me when you have availability.

2022-11-17 12:02 UTC, abcarcol commented on scripts/pipelines/gcloud/templates/package/flutter-package-pipeline.yml.template
> +        .pipelines/scripts/package-extra.sh
Same as previous comment

2022-11-17 12:06 UTC, abcarcol commented on scripts/pipelines/gcloud/templates/package/package-pipeline.cfg
> +#dockerImageTagFilePaths="quarkus-jvm:pom.xml quarkus:pom.xml node:package.json angular:package.json"
@ultymatom What do you about this comment? Is the variable "dockerImageTagFilePaths" no longer being used? Can we safely remove it? Thanks!

2022-11-17 12:07 UTC, abcarcol commented on scripts/pipelines/gcloud/templates/package/package-pipeline.cfg
> +            subsitutionVariable=$subsitutionVariable",_ANDROID_API_KEY=${androidApiKey}"
Yes, it must be removed

2022-11-17 12:12 UTC, abcarcol commented on scripts/pipelines/common/templates/package/flutter-package.sh
> +export tag=$(grep -m 1 version pubspec.yaml | tr -s ' ' | tr -d ':' | cut -d' ' -f2 | cut -d'+' -f1)
@sonatype-lift ignore

2022-11-17 12:12 UTC, abcarcol commented on scripts/pipelines/common/templates/package/python-package.sh
> +export tag=$(grep -m 1 version "${imageTagFilePath}" | tr -s ' ' | tr -d '"' | tr -d "'" | cut -d' ' -f3)
sonatype-lift ignore

2022-11-17 15:24 UTC, abcarcol commented on scripts/pipelines/gcloud/templates/package/package-pipeline.cfg
> +        quarkus*) dockerImage="toDefine" ;;
Not really, according to the current package template, the "dockerImage" is the variable that specifies the image to be used in Cloud Build when extracting the artifact produced by the build pipeline. So, basically, any image which can execute "tar -xf" is valid. For consistency with other pipeline.cfg I set "quarkus*) dockerImage="maven:3-eclipse-temurin-11" ;;"

2022-11-22 16:50 UTC, albertdb commented on documentation/src/common_templates/setup-package-pipeline.asciidoc
> +ifdef::machineType[-m, --machine-type                  Machine type for {pipeline_type} runner. Accepted values: E2_HIGHCPU_8, E2_HIGHCPU_32, N1_HIGHCPU_8, N1_HIGHCPU_32.]
```suggestion
ifndef::no-PR-or-MR[-w                                        Open the Pull Request on the web browser if it cannot be automatically merged. Requires -b flag.]
ifdef::machineType[-m, --machine-type                        Machine type for {pipeline_type} runner. Accepted values: E2_HIGHCPU_8, E2_HIGHCPU_32, N1_HIGHCPU_8, N1_HIGHCPU_32.]
```

2022-11-22 17:08 UTC, albertdb requested changes

2022-11-22 17:08 UTC, albertdb commented on documentation/src/common_templates/setup-package-pipeline.asciidoc
> +===== Artifact Registry
```suggestion
===== Google Cloud Artifact Registry
```

2022-11-22 17:41 UTC, albertdb requested changes

2022-11-22 17:41 UTC, albertdb commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +FLAGS=$(getopt -a --options c:n:d:a:b:l:i:u:p:h:m --long "config-file:,pipeline-name:,local-directory:,artifact-path:,target-branch:,language:,build-pipeline-name:,sonar-url:,sonar-token:,image-name:
```suggestion
FLAGS=$(getopt -a --options c:n:d:a:b:l:i:u:p:m:h --long "config-file:,pipeline-name:,local-directory:,artifact-path:,target-branch:,language:,build-pipeline-name:,sonar-url:,sonar-token:,image-name:,registry-user:,registry-password:,resource-group:,storage-account:,storage-container:,cluster-name:,s3-bucket:,s3-key-path:,quality-pipeline-name:,dockerfile:,test-pipeline-name:,aws-access-key:,aws-secret-access-key:,aws-region:,ci-pipeline-name:,help,registry-location:,flutter-web-renderer:,machine-type:,language-version:,service-name:,gcloud-region:,port:,flutter-platform:" -- "$@")
```

2022-11-22 17:41 UTC, albertdb commented on documentation/src/common_templates/setup-package-pipeline.asciidoc
>  ```
Missing flags for Python and Flutter

2022-11-22 17:41 UTC, albertdb commented on documentation/src/common_templates/setup-package-pipeline.asciidoc
>  ```
Missing flags for Python and Flutter

2022-11-22 17:41 UTC, albertdb commented on documentation/src/common_templates/setup-package-pipeline.asciidoc
> +./pipeline_generator.sh -c ./templates/package/package-pipeline.cfg -n flutter-project-package -l flutter -d C:/Users/$USERNAME/Desktop/flutter-project {extra_args_flutter} {extra_args_flutter_web} -
Missing variables in other providers: {extra_args_flutter} {extra_args_flutter_web}

2022-11-22 17:41 UTC, albertdb commented on documentation/gcloud/setup-package-pipeline.asciidoc
> +Then, a Pull Request (PR) will be created in order to merge the new branch into the appropriate branch (provided in `-b` flag). The PR will be automatically merged if the repository policies are met.
Missing conditional content (to be modified in template) using :no-PR-or-MR:

2022-11-22 17:41 UTC, albertdb commented on scripts/pipelines/gcloud/templates/package/package-pipeline.cfg
> +mandatoryFlags="${pipelineName},$imageName,$buildPipelineName,${language}${dockerFile},$qualityPipelineName,"
This should be filled with additional required flags given the language (e.g. Flutter).

2022-11-22 17:41 UTC, albertdb commented on scripts/pipelines/gcloud/templates/package/package-pipeline.cfg
> +            exit 2
```suggestion
            exit 1
```

Not bad argument, right?

2022-11-23 11:32 UTC, abcarcol commented on scripts/pipelines/gcloud/templates/package/package-pipeline.cfg
> +            exit 2
you are right

2022-11-23 11:33 UTC, abcarcol commented on scripts/pipelines/gcloud/templates/package/package-pipeline.cfg
> +            echo -e "${red}Error: While creating buckeet for $gCloudProject-apk." >&2
```suggestion
            echo -e "${red}Error: While creating bucket for $gCloudProject-apk." >&2
```

2022-11-23 17:28 UTC, albertdb requested changes

2022-11-23 17:28 UTC, albertdb commented on documentation/src/common_templates/setup-package-pipeline.asciidoc
> +endif::no-PR-or-MR
Please check how should be this done in other templates:  https://github.com/devonfw/hangar/blob/master/documentation/src/common_templates/setup-build-pipeline.asciidoc

2022-11-23 17:28 UTC, albertdb commented on documentation/src/common_templates/setup-package-pipeline.asciidoc
> +ifdef:flutterWebRenderer[-m, --machine-type                        Flutter web renderer. Accepted values: auto (default), canvaskit, html.]
You forgot to rename flags.

2022-11-23 17:28 UTC, albertdb commented on documentation/src/common_templates/setup-package-pipeline.asciidoc
> +ifdef::flutterWebRenderer[  --flutter-web-renderer <auto (default), canvaskit, html> \]
I don't understand why do you make it conditional. If we only support gcloud for android builds (for example) of for python and flutter projects in general, then we  should have a variable name for the provider, not for each and every flag (that includes machine-type). But in that case, also the examples for python and flutter should only be shown in gcloud guide (but remain in this file for future support)

2022-11-24 08:23 UTC, abcarcol commented on documentation/src/common_templates/setup-package-pipeline.asciidoc
> +ifdef:flutterWebRenderer[-m, --machine-type                        Flutter web renderer. Accepted values: auto (default), canvaskit, html.]
Ups

2022-11-24 08:27 UTC, abcarcol commented on documentation/src/common_templates/setup-package-pipeline.asciidoc
> +endif::no-PR-or-MR
Done!

2022-11-25 11:35 UTC, mcerverc commented on documentation/src/common_templates/setup-package-pipeline.asciidoc
> +./pipeline_generator.sh -c ./templates/package/package-pipeline.cfg -n python-project-package -l python -d C:/Users/$USERNAME/Desktop/python-project {extra_args_python} -i eu-southwest1-docker.pkg.de
Do the same for all project types
```suggestion
./pipeline_generator.sh -c ./templates/package/package-pipeline.cfg -n python-project-package -l python -d C:/Users/$USERNAME/Desktop/python-project {extra_args_python} -i eu-southwest1-docker.pkg.dev/project/repo/imagename -b develop -w

```

2022-11-25 11:41 UTC, abcarcol commented on documentation/src/common_templates/setup-package-pipeline.asciidoc
> +./pipeline_generator.sh -c ./templates/package/package-pipeline.cfg -n python-project-package -l python -d C:/Users/$USERNAME/Desktop/python-project {extra_args_python} -i eu-southwest1-docker.pkg.de
Thanks!

2022-11-25 11:47 UTC, abcarcol commented on documentation/src/common_templates/setup-package-pipeline.asciidoc
> +./pipeline_generator.sh -c ./templates/package/package-pipeline.cfg -n python-project-package -l python -d C:/Users/$USERNAME/Desktop/python-project {extra_args_python} -i eu-southwest1-docker.pkg.de
@mcerverc applied in all examples.

2022-11-25 11:57 UTC, albertdb approved these changes

2022-11-25 12:10 UTC, ultymatom submitted a review, later dismissed

2022-11-28 11:46 UTC, ultymatom approved these changes

2022-11-28 15:38 UTC, mcerverc commented on scripts/pipelines/gcloud/templates/package/package-pipeline.yml.template
> +      echo $$registry_credentials > credentials.env
```suggestion
      echo $$REGISTRY_CREDENTIALS > credentials.env
```

2022-11-28 15:40 UTC, abcarcol commented on scripts/pipelines/gcloud/templates/package/package-pipeline.yml.template
> +      echo $$registry_credentials > credentials.env
Thank you!

2022-11-28 15:44 UTC, lpinon approved these changes

2022-11-28 15:59 UTC, lpinon approved these changes

2022-11-28 16:01 UTC, mcerverc approved these changes

2022-11-28 16:12 UTC, merged