Automate deployment in CloudRun environment#205
devonfw/hangar pull request #294
Opened 2022-11-02 16:25 UTC by ultymatom

Closes #205 
Closes #369

2022-11-02 16:55 UTC, albertdb requested changes
Not fully reviewed, but looks good overall.

2022-11-02 16:55 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +    echo "  -i, --image-name                    [Required] Name (excluding tag) for the generated container image."
Should be passed from previous pipeline as discussed.

2022-11-02 17:23 UTC, ultymatom commented on scripts/pipelines/common/pipeline_generator.lib
> +    echo "  -i, --image-name                    [Required] Name (excluding tag) for the generated container image."
Yes this has been corrected in last commit (not pushed yet)

2022-11-02 17:32 UTC, ultymatom commented on scripts/pipelines/common/templates/deploy-cloud-run/deploy-cloud-run.sh
> +. "$(dirname "$0")/package-extra.sh"
@sonatype-lift ignore

2022-11-02 17:32 UTC, ultymatom commented on scripts/pipelines/common/templates/deploy-cloud-run/deploy-cloud-run.sh
> +if ! ([[ "$registry" =~ .*docker.pkg.dev.* ]] || [[ "$registry" =~ .*gcr.io.* ]])
@sonatype-lift ignore

2022-11-02 17:52 UTC, ultymatom commented on scripts/pipelines/common/templates/deploy-cloud-run/deploy-cloud-run.sh
> +echo "$branch" | grep release && tag_completed="${tag}"
@sonatype-lift ignore

2022-11-02 18:06 UTC, ultymatom commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +        --service-name)           serviceName="$2"; shift 2;;
@sonatype-lift ignore

2022-11-07 11:45 UTC, ultymatom commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +  echo "" >> "${localDirectory}/${pipelinePath}/${yamlFile}"
done for being easier to maintain

2022-11-07 11:45 UTC, ultymatom commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +  echo "" >> "${localDirectory}/${pipelinePath}/${yamlFile}"
@sonatype-lift ignore

2022-11-08 08:41 UTC, mcerverc commented on scripts/pipelines/common/pipeline_generator.lib
> +    [ "$provider" == "azure-devops" ] && [ "$provider" == "gcloud" ] && echo "      --build-pipeline-name   [Required] Build $pipeline_type name."
```suggestion
    [ "$provider" == "azure-devops" ] || [ "$provider" == "gcloud" ] && echo "      --build-pipeline-name   [Required] Build $pipeline_type name."
```

2022-11-08 09:03 UTC, ultymatom commented on scripts/pipelines/common/pipeline_generator.lib
> +    [ "$provider" == "azure-devops" ] && [ "$provider" == "gcloud" ] && echo "      --build-pipeline-name   [Required] Build $pipeline_type name."
right, don't know what I did

2022-11-08 15:05 UTC, mcerverc commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +  echo "" >> "${localDirectory}/${pipelinePath}/${yamlFile}"
@sonatype-lift ignore

2022-11-08 15:10 UTC, mcerverc commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +            sed -e "s/# mark to insert trigger/- name: gcr.io\/cloud-builders\/gsutil\n  entrypoint: bash\n  args:\n  - -c\n  - |\n    if [[ "\$BRANCH_NAME" =~ $branchTrigger ]] || exit 0; then\n
@sonatype-lift ignore

2022-11-08 15:12 UTC, mcerverc commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +            sed -e "s/# mark to insert trigger/- name: gcr.io\/cloud-builders\/gsutil\n  entrypoint: bash\n  args:\n  - -c\n  - |\n    if [[ "\$BRANCH_NAME" =~ $branchTrigger ]] || exit 0; then\n
@sonatype-lift ignore

2022-11-08 15:12 UTC, mcerverc commented on scripts/pipelines/common/templates/deploy-cloud-run/deploy-cloud-run.sh
> +if ! {[[ "$registry" =~ .*docker.pkg.dev.* ]] || [[ "$registry" =~ .*gcr.io.* ]]}
@sonatype-lift ignore

2022-11-08 15:12 UTC, mcerverc commented on scripts/pipelines/gcloud/templates/deploy-cloud-run/deploy-cloud-run-setup-environment.sh
> +if ! {[[ "$registry" =~ .*docker.pkg.dev.* ]] || [[ "$registry" =~ .*gcr.io.* ]])}
@sonatype-lift ignore

2022-11-08 15:12 UTC, mcerverc commented on scripts/pipelines/gcloud/templates/deploy-cloud-run/deploy-cloud-run-setup-environment.sh
> +if ! {[[ "$registry" =~ .*docker.pkg.dev.* ]] || [[ "$registry" =~ .*gcr.io.* ]])}
@sonatype-lift ignore

2022-11-08 15:14 UTC, mcerverc commented on scripts/pipelines/gcloud/templates/deploy-cloud-run/deploy-cloud-run-setup-environment.sh
> +if ! {[[ "$registry" =~ .*docker.pkg.dev.* ]] || [[ "$registry" =~ .*gcr.io.* ]])}
@sonatype-lift ignore

2022-11-08 15:14 UTC, mcerverc commented on scripts/pipelines/common/templates/deploy-cloud-run/deploy-cloud-run.sh
> +if ! {[[ "$registry" =~ .*docker.pkg.dev.* ]] || [[ "$registry" =~ .*gcr.io.* ]]}
@sonatype-lift ignore

2022-11-08 15:17 UTC, mcerverc commented on scripts/pipelines/common/templates/deploy-cloud-run/deploy-cloud-run.sh
> +  [[ $(gcloud artifacts repositories list | awk  '$1=="temporaryrepo" {print $1}') != "" ]] || gcloud artifacts repositories create temporaryrepo --repository-format=docker --location=$gCloudRegion
@sonatype-lift ignore

2022-11-08 15:17 UTC, mcerverc commented on scripts/pipelines/gcloud/templates/deploy-cloud-run/deploy-cloud-run-setup-environment.sh
> +if ! ([[ "$registry" =~ .*docker.pkg.dev.* ]] || [[ "$registry" =~ .*gcr.io.* ]])
@sonatype-lift ignore

2022-11-15 21:11 UTC, abcarcol commented on scripts/pipelines/gcloud/templates/deploy-cloud-run/deploy-cloud-run-pipeline.cfg
> +previousPipelineyaml="package-pipeline.yml"
```suggestion
previousPipelineyaml="package-pipeline.yml"
[ "$language" == "flutter" ] && previousPipelineyaml="flutter-package-pipeline.yml"
```

2022-11-17 15:39 UTC, abcarcol commented on scripts/pipelines/common/templates/test/python-test.sh
> +. /venv/bin/activate
In my opinion it can be ignored or use:
```suggestion
# shellcheck source=/venv/bin/activate
. /venv/bin/activate
```

2022-11-17 15:48 UTC, abcarcol commented on scripts/pipelines/common/templates/deploy-cloud-run/deploy-cloud-run.sh
> +# If the registry is not the google cloud artifact registry, we need to push it to a tenmporary one
```suggestion
# If the registry is not the Google Cloud Artifact Registry, we need to push it to a temporary one
```

2022-11-17 15:56 UTC, abcarcol commented on scripts/pipelines/common/templates/deploy-cloud-run/deploy-cloud-run.sh
> +  # other regitries
```suggestion
  # other registries
```

2022-11-17 16:07 UTC, abcarcol commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +        "*package-pipeline.yml")
"*package-pipeline.yml" was not working for @mcerverc in yesterday's demo. He had to use:
```suggestion
        "package-pipeline.yml" || "flutter-package-pipeline.yml")
```
Still pending to discuss with @albertdb if package should use a separate pipeline definition YAML for Flutter

2022-11-18 08:19 UTC, ultymatom commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +        "*package-pipeline.yml")
Let me try it again but I tried it and it worked

2022-11-21 09:36 UTC, lpinon approved these changes

2022-11-29 17:18 UTC, capf4bbo approved these changes

2022-11-30 09:50 UTC, abcarcol submitted a review, later dismissed

2022-11-30 10:17 UTC, capf4bbo approved these changes

2022-11-30 10:30 UTC, Jorge-Dacal submitted a review, later dismissed

2022-11-30 12:06 UTC, capf4bbo approved these changes

2022-11-30 12:19 UTC, albertdb requested changes

2022-11-30 12:19 UTC, albertdb commented on documentation/src/common_templates/setup-deploy-cloud-run-pipeline.asciidoc
> +The script located at `/scripts/pipelines/{path_provider}/pipeline_generator.sh` will automatically create this new branch, create a build {pipeline_type} based on a YAML template appropriate for the
```suggestion
The script located at `/scripts/pipelines/{path_provider}/pipeline_generator.sh` will automatically create this new branch, create a deploy {pipeline_type} based on a YAML template appropriate for targeting Cloud Run, create the Pull Request and, if it is possible, merge this new branch into the specified branch.
```

2022-11-30 12:19 UTC, albertdb commented on documentation/src/common_templates/setup-deploy-cloud-run-pipeline.asciidoc
> +This script will commit and push the corresponding YAML template into your repository, so please be sure your local repository is up-to-date (i.e you have pulled latest changes with `git pull`).
```suggestion
* This script will commit and push the corresponding YAML template into your repository, so please be sure your local repository is up-to-date (i.e you have pulled latest changes with `git pull`).
```

2022-11-30 12:19 UTC, albertdb commented on documentation/src/common_templates/setup-deploy-cloud-run-pipeline.asciidoc
> +This {pipeline_type} uses variables set during the package pipeline, so be sure to have set it correctly before creating this one.
```suggestion
* This {pipeline_type} consumes variables set by the package {pipeline_type}, so be sure to correctly setup it before creating this one.
```

2022-11-30 12:19 UTC, albertdb commented on documentation/src/common_templates/setup-deploy-cloud-run-pipeline.asciidoc
> +  --gcloud-region <Gcloud region> \
```suggestion
  --gcloud-region <gcloud region> \

```

2022-11-30 12:19 UTC, albertdb commented on documentation/src/common_templates/setup-deploy-cloud-run-pipeline.asciidoc
> +NOTE: The config file for the build {pipeline_type} is located at `/scripts/pipelines/{path_provider}/templates/build/build-pipeline.cfg`.
```suggestion
NOTE: The config file for the deploy {pipeline_type} is located at `/scripts/pipelines/{path_provider}/templates/deploy-cloud-run/deploy-cloud-run-pipeline.cfg`.

```

2022-11-30 12:19 UTC, albertdb commented on documentation/src/common_templates/setup-deploy-cloud-run-pipeline.asciidoc
> +  -l <language or framework> \
```suggestion
```

2022-11-30 12:19 UTC, albertdb commented on documentation/src/common_templates/setup-deploy-cloud-run-pipeline.asciidoc
> +./pipeline_generator.sh -c ./templates/build/build-pipeline.cfg -n application -l quarkus -d C:/Users/$USERNAME/Desktop/project --service-name application --gcloud-region europe-southwest1 --port 80
```suggestion
./pipeline_generator.sh -c ./templates/deploy-cloud-run/deploy-cloud-run-pipeline.cfg -n project-deploy -d C:/Users/$USERNAME/Desktop/project --service-name application --gcloud-region europe-southwest1 --port 80 -b develop {openBrowserFlag}
```

2022-11-30 12:19 UTC, albertdb commented on documentation/src/common_templates/setup-deploy-cloud-run-pipeline.asciidoc
> +-l, --language           [Required] Language or framework of the project.
```suggestion
```

2022-11-30 12:19 UTC, albertdb commented on documentation/src/common_templates/setup-deploy-cloud-run-pipeline.asciidoc
> +    --service-name       [Required] Name for the cloud run service.
```suggestion
    --service-name       [Required] Name for the Cloud Run service.
```

2022-11-30 12:19 UTC, albertdb commented on documentation/src/common_templates/setup-deploy-cloud-run-pipeline.asciidoc
> +    --port                          Listening port of the service. (default: 8080)
```suggestion
    --port                          Listening port of the service. Default: 8080.

```

2022-11-30 12:47 UTC, ultymatom commented on documentation/src/gcloud/setup-deploy-cloud-run-pipeline.asciidoc
> +:trigger_sentence: This pipeline will be configured to be triggered after the package pipeline on branches develop or release/*
no, we don't check the state of the package pipeline actually

2022-11-30 13:03 UTC, albertdb commented on documentation/src/gcloud/setup-deploy-cloud-run-pipeline.asciidoc
> +:trigger_sentence: This pipeline will be configured to be triggered after the package pipeline on branches develop or release/*
@ultymatom So, would this be true? (changed last part)

```
This pipeline will be configured in order to be triggered every time package pipeline is executed successfully on a commit for `release/*` and `develop` branches, requiring manual launch for other branches.
```

If so, change it to that.

2022-11-30 14:54 UTC, albertdb commented on documentation/src/common_templates/setup-deploy-cloud-run-pipeline.asciidoc
> +
```suggestion
```

2022-11-30 14:56 UTC, albertdb commented on documentation/src/common_templates/setup-deploy-cloud-run-pipeline.asciidoc
> +In this section we will create a {pipeline_type} to deploy the project application as a service in Cloud Run. {trigger_sentence}.
```suggestion
In this section we will create a {pipeline_type} to deploy the project application as a service in Google Cloud Run. {trigger_sentence}.

```

2022-11-30 14:57 UTC, albertdb approved these changes

2022-11-30 14:58 UTC, merged