Added role & Enable API for Secret Manager
devonfw/hangar pull request #295
Opened 2022-11-02 16:28 UTC by lpinon

2022-11-02 16:36 UTC, albertdb requested changes

2022-11-02 16:36 UTC, albertdb commented on scripts/accounts/gcloud/predefined-roles.txt
> +roles/secretmanager.admin
```suggestion
```

Already there

2022-11-02 16:45 UTC, albertdb submitted a review, later dismissed

2022-11-02 16:56 UTC, albertdb approved these changes

2022-11-03 09:41 UTC, abcarcol approved these changes

2022-11-03 09:41 UTC, merged