Feature gcloud manage secrets
devonfw/hangar pull request #309
Opened 2022-11-08 22:18 UTC by ultymatom

2022-11-09 08:00 UTC, ultymatom commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +    secretName=$(echo "${fileName}" | sed 's/\W/_/g')
(I did not do advanced research), but it seems that that this is not possible with \W   (which means the opposite of [a-zA-Z0-9_])

2022-11-09 08:03 UTC, ultymatom commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +    echo "gcloud secrets versions add \"$secretName\" --data-file=\"${currentDirectory}/${filePath}\""
@sonatype-lift ignore

2022-11-09 08:04 UTC, ultymatom commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +    secretName=$(echo "${fileName}" | sed 's/\W/_/g')
@sonatype-lift ignore

2022-11-21 16:13 UTC, ultymatom commented on scripts/pipelines/gcloud/add-secret-file.sh
> +  cd "$currentDirectory"
@sonatype-lift ignore

2022-11-21 16:13 UTC, ultymatom commented on scripts/pipelines/gcloud/add-secret-file.sh
> +  localFilePath=${localFilePath//'\'/"/"}
@sonatype-lift ignore

2022-11-21 16:16 UTC, ultymatom commented on scripts/pipelines/gcloud/add-secret-file.sh
> +  cd $(dirname "${localFilePath}") && [ -f $(basename "${localFilePath}") ] && localFilePath="$(pwd)/$(basename "${localFilePath}")"  || { echo -e "${red}Error: The file given with the flag '-f' cann
I don't want a if else
I have here: A && B && C || D
If any of the A B or C is false, I want D to be executed

2022-11-21 16:16 UTC, ultymatom commented on scripts/pipelines/gcloud/add-secret-file.sh
> +  cd $(dirname "${localFilePath}") && [ -f $(basename "${localFilePath}") ] && localFilePath="$(pwd)/$(basename "${localFilePath}")"  || { echo -e "${red}Error: The file given with the flag '-f' cann
@sonatype-lift ignore

2022-11-21 16:20 UTC, ultymatom commented on scripts/pipelines/gcloud/add-secret-file.sh
> +    secretName=$(echo "${fileName}" | sed 's/\W/_/g')
I tried, but the \W was not working

2022-11-21 16:20 UTC, ultymatom commented on scripts/pipelines/gcloud/add-secret-file.sh
> +    secretName=$(echo "${fileName}" | sed 's/\W/_/g')
@sonatype-lift ignore

2022-11-21 16:27 UTC, ultymatom commented on scripts/pipelines/gcloud/add-secret-file.sh
> +function checkArgs {
@sonatype-lift ignore

2022-11-21 16:28 UTC, ultymatom commented on scripts/pipelines/gcloud/add-secret-file.sh
> +checkArgs
@sonatype-lift ignore

2022-11-23 14:59 UTC, albertdb requested changes
Documentation pending due to possible upgrade in functionality.

2022-11-28 11:21 UTC, ultymatom commented on scripts/pipelines/common/secret/get-gcloud-secrets.sh
> +    echo "gcloud secrets versions access latest --secret=$secretName --out-file=$downloadPath"
this is not debug lines, this is log lines, to let know the user what secret have been downloaded, becasue the whole step is silent if not this echo:
![image](https://user-images.githubusercontent.com/90399827/204265559-1ca9768d-a39b-405d-95e6-9ccf0bc95338.png)

2022-11-28 11:22 UTC, ultymatom commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +FLAGS=$(getopt -a --options c:n:d:a:b:l:i:u:p:hm: --long "config-file:,pipeline-name:,local-directory:,artifact-path:,target-branch:,language:,build-pipeline-name:,sonar-url:,sonar-token:,image-name:
True, I had to resolve conflicts as I put it inside the pipeline generator, but indeed it does not make sense anymore to have modification in this file

2022-11-28 11:28 UTC, ultymatom commented on scripts/pipelines/common/pipeline_generator.lib
> +    [[ "$provider" != "gcloud" ]] && echo "  -w                                     Open the Pull Request on the web browser if it cannot be automatically merged. Requires -b flag."
I can't remember why I changed this

2022-11-28 14:55 UTC, mcerverc approved these changes

2022-11-28 15:33 UTC, lpinon approved these changes

2022-11-29 13:20 UTC, lpinon approved these changes

2022-11-29 15:18 UTC, lpinon approved these changes

2022-11-29 15:41 UTC, lpinon approved these changes

2022-11-29 15:56 UTC, capf4bbo submitted a review, later dismissed

2022-11-29 16:51 UTC, abcarcol commented on documentation/gcloud/upload-secret-manager.asciidoc
> +-n, --secret-name           [Required if -v flag set] Name of the secret as it will appear in the secret manager. if not set, we use the name of the file given with '-f'."
```suggestion
-n, --secret-name           [Required if -v flag set] Name of the secret as it will appear in the secret manager. For the file case, we use the name of the file given with '-f'."

```

2022-11-29 17:21 UTC, abcarcol commented on scripts/pipelines/common/pipeline_generator.lib
> +    [ "$provider" == "gcloud" ] && echo "      --env-vars                     Machine type for pipeline runner. Accepted values: E2_HIGHCPU_8, E2_HIGHCPU_32, N1_HIGHCPU_8, N1_HIGHCPU_32."
```suggestion
    [ "$provider" == "gcloud" ] && echo "      --env-vars                     Environment variable needed for this pipeline. (list in the format of "var1=val1 var2=val2 ...")"
```

2022-11-29 17:35 UTC, abcarcol commented on scripts/pipelines/gcloud/add-secret.sh
> +configFilePath=".pipelines/config" # Path to the scripts.
```suggestion
configFilePath=".pipelines/config" # Path to the config files.
```

2022-11-29 17:37 UTC, abcarcol commented on scripts/pipelines/gcloud/add-secret.sh
> +  echo "Upload a file as a secret in the secret manager of Google Cloud to be used inside the choosen pipelines."
```suggestion
  echo "Upload a file or a variable as a secret in the secret manager of Google Cloud to be used inside the chosen pipelines."
```

2022-11-29 17:39 UTC, abcarcol commented on scripts/pipelines/gcloud/add-secret.sh
> +  echo "  -n, --secret-name           [Required if -v flag set] Name of the secret as it will appear in the secret manager. if not set, we use the name of the file given with '-f'. NOTE: the name has
```suggestion
  echo "  -n, --secret-name           [Required if -v flag set] Name of the secret as it will appear in the secret manager. For the file case, we use the name of the file given with '-f'. NOTE: the name has to be compliant with the regex [a-zA-Z0-9_]."
```

2022-11-29 17:45 UTC, abcarcol commented on documentation/gcloud/upload-secret-manager.asciidoc
> +NOTE: the name given with the `-n` has to be compliant with the regex [a-zA-Z0-9_]. (if flag not set and file name given with `-f` is not compliant with the regex, it will be modified to be compliant
According to this in add-secret.sh:
```
# If secret name given we check that is compliant with the regex \w
  [[ "$secretName" =~ ^[a-zA-Z0-9_]*$ ]] || { echo -e "${red}Error: The secret name is not compliant with the regex ^[a-zA-Z0-9_]\$*. (only letters number and '_' are accepted in the name)" >&2; echo -ne "${white}" >&2; exit 2; }
```
The modification to be compliant with the regex is not implement. I do not find it necessary BTW.

2022-11-29 17:53 UTC, abcarcol commented on scripts/pipelines/gcloud/add-secret.sh
> +  cd "$currentDirectory"
I do not remember where is this variable defined

2022-11-29 18:17 UTC, abcarcol commented on scripts/pipelines/gcloud/add-secret.sh
> +    echo "$secretName #$pipelinesList" >> "${localDirectory}/${configFilePath}/SecretVars.conf"
```suggestion
    [[ -f "${localDirectory}/${configFilePath}/SecretVars.conf" ]] || echo "# secretName #pipelinesList" >> "${localDirectory}/${configFilePath}/SecretVars.conf"
    echo "$secretName $pipelinesList" >> "${localDirectory}/${configFilePath}/SecretVars.conf"
```

2022-11-29 18:37 UTC, abcarcol commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +        echo "$secretName #$pipelineName" >> "${localDirectory}/${configFilePath}/SecretVars.conf"
```suggestion
        [[ -f "${localDirectory}/${configFilePath}/SecretVars.conf" ]] || echo "# secretName #pipelineList" >> "${localDirectory}/${configFilePath}/SecretVars.conf"
        echo "$secretName $pipelineName" >> "${localDirectory}/${configFilePath}/SecretVars.conf"
```

2022-11-29 18:40 UTC, abcarcol commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +}
Why are you not calling add-secret.sh N times (one for each secret) passed to the pipeline_generator.sh instead of duplicating the code? I suppose there should be a good reason behind it.

2022-11-29 19:01 UTC, abcarcol submitted a review, later dismissed

2022-11-30 08:51 UTC, ultymatom commented on scripts/pipelines/common/pipeline_generator.lib
> +    [ "$provider" == "gcloud" ] && echo "      --env-vars                     Machine type for pipeline runner. Accepted values: E2_HIGHCPU_8, E2_HIGHCPU_32, N1_HIGHCPU_8, N1_HIGHCPU_32."
wow what an error sry

2022-11-30 08:54 UTC, ultymatom commented on scripts/pipelines/gcloud/add-secret.sh
> +    secretName=$(echo "${fileName}" | sed 's/\W/_/g')
Here we don't check if it is compliant. 
It is ifwe are uploading a file and we did not give -n flag
then we need to change all the "." "-" etc...

2022-11-30 08:57 UTC, ultymatom commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +}
The add-secret.sh creates a branch and then merge it. and generates too much logs I think. so if we have a list of variable that is a bit long this would be way too much

2022-11-30 08:58 UTC, ultymatom commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +}
way too much time*, doing it that way in the pipeline generator make it go faster

2022-11-30 09:07 UTC, ultymatom commented on documentation/gcloud/upload-secret-manager.asciidoc
> +NOTE: If '-v' and '-f' are both set, '-f' is choosen.
This is a topic to discussed, but I know in the other scripts of Hangar when this can happen, we set priority between flags

2022-11-30 09:10 UTC, ultymatom commented on scripts/pipelines/common/secret/get-gcloud-secret-vars.sh
> +triggerName=$1
ALso can be discussed, but to do a more generic script, it is better do it like this I think

2022-11-30 09:27 UTC, abcarcol commented on documentation/gcloud/upload-secret-manager.asciidoc
> +NOTE: If '-v' and '-f' are both set, '-f' is choosen.
Then, it is consistent. Resolved.

2022-11-30 09:28 UTC, abcarcol commented on scripts/pipelines/gcloud/add-secret.sh
> +    secretName=$(echo "${fileName}" | sed 's/\W/_/g')
Resolved.

2022-11-30 09:29 UTC, abcarcol commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +}
Resolved.

2022-11-30 09:30 UTC, abcarcol commented on scripts/pipelines/common/secret/get-gcloud-secret-vars.sh
> +triggerName=$1
Resolved.

2022-11-30 09:30 UTC, abcarcol submitted a review, later dismissed

2022-11-30 09:36 UTC, capf4bbo submitted a review, later dismissed

2022-11-30 10:35 UTC, Jorge-Dacal submitted a review, later dismissed

2022-12-01 14:39 UTC, albertdb requested changes
Missing changes in Deploy in Cloud Run pipeline (where the variables should be consumed by gcloud run passing them to the container), otherwise part of the functionality is of no direct use (i.e. an unused nice-to-have).

This is partial review.

2022-12-09 08:21 UTC, ultymatom commented on documentation/src/common_templates/setup-build-pipeline.asciidoc
> +ifdef::envVar[  [--env-vars <env vars list>]]
I don't think it should because we might add this flag for others provider too

2022-12-09 08:21 UTC, ultymatom commented on documentation/src/common_templates/setup-build-pipeline.asciidoc
> +ifdef::envVar[    --env-vars                      Environment variable needed for this pipeline. (list in the format of "var1=val1 var2=val2 ...")]
I don't think it should because we might add this flag for others provider too

2022-12-09 08:21 UTC, ultymatom commented on documentation/src/common_templates/setup-package-pipeline.asciidoc
> +ifdef::envVar[  [--env-vars <env vars list>]]
I don't think it should because we might add this flag for others provider too

2022-12-09 08:21 UTC, ultymatom commented on documentation/src/common_templates/setup-package-pipeline.asciidoc
> +ifdef::envVar[    --env-vars                            Environment variable needed for this pipeline. (list in the format of "var1=val1 var2=val2 ...")]
I don't think it should because we might add this flag for others provider too

2022-12-09 08:21 UTC, ultymatom commented on documentation/src/common_templates/setup-quality-pipeline.asciidoc
> +ifdef::envVar[  [--env-vars <env vars list>]]
I don't think it should because we might add this flag for others provider too

2022-12-09 08:21 UTC, ultymatom commented on documentation/src/common_templates/setup-quality-pipeline.asciidoc
> +ifdef::envVar[    --env-vars                          Environment variable needed for this pipeline. (list in the format of "var1=val1 var2=val2 ...")]
I don't think it should because we might add this flag for others provider too

2022-12-09 08:21 UTC, ultymatom commented on documentation/src/common_templates/setup-test-pipeline.asciidoc
> +ifdef::envVar[    --env-vars                         Environment variable needed for this pipeline. (list in the format of "var1=val1 var2=val2 ...")]
I don't think it should because we might add this flag for others provider too

2022-12-09 08:22 UTC, ultymatom commented on documentation/src/gcloud/setup-build-pipeline.asciidoc
> +:envVar:
I don't think it should because we might add this flag for others provider too

2022-12-09 08:22 UTC, ultymatom commented on documentation/src/gcloud/setup-package-pipeline.asciidoc
> +:envVar:
I don't think it should because we might add this flag for others provider too

2022-12-09 08:22 UTC, ultymatom commented on documentation/src/gcloud/setup-quality-pipeline.asciidoc
> +:envVar:
I don't think it should because we might add this flag for others provider too

2022-12-14 13:32 UTC, albertdb requested changes
Missing changes in Deploy in Cloud Run pipeline (where the variables should be consumed by gcloud run passing them to the container), otherwise part of the functionality is of no direct use (i.e. an unused nice-to-have).

2022-12-14 13:35 UTC, albertdb commented on documentation/src/gcloud/setup-build-pipeline.asciidoc
> +:envVar:
If so, we will change it then (and we could even remove all conditionals if we add support to all providers). Keeping it just in case could be more confusing.

2022-12-15 10:40 UTC, ultymatom commented on documentation/src/gcloud/setup-build-pipeline.asciidoc
> +:envVar:
I am gonna do it but I don't really see th epoint because it will just add changes more to be done later

2022-12-15 10:51 UTC, mcerverc commented on documentation/src/gcloud/setup-build-pipeline.asciidoc
> +:envVar:
If i understanded well, we don't use this variables in gcloud. IMO it's better to remove them here and add a conditional in the general template just as albert suggested.

2022-12-16 08:03 UTC, lpinon approved these changes

2022-12-16 14:19 UTC, albertdb requested changes

2022-12-16 14:19 UTC, albertdb commented on documentation/gcloud/upload-secret-manager.asciidoc
> +add-secret.sh -d /depots/test-quarkus/ -n secretVar -v secretValue -b develop -p "test-quarkus,build-quarkus"
````suggestion
= Upload files or variables as secrets in Google Cloud Secret Manager

In this section we will create secrets in Secret Manager that will be made available in the pipelines that need them, either as files or as environment variables.

To make this happen, in addition to creating an entry in Secret Manager, it is required to create/update a configuration file in the project repository containing the information about the secrets and their scope pipeline-wise. This process will follow the project workflow, so a new branch named `feature/add-secret` will be created and the required changes will be pushed to it.

Then, the new branch will be merged into the appropriate branch (provided in `-b` flag).

The script located at `scripts/pipelines/gcloud/add-secret.sh` will assist you in this process.

== Prerequisites

This script will commit and push the corresponding shell script and configuration file into your repository, so please be sure your local repository is up-to-date (i.e you have pulled latest changes with `git pull`).

== Uploading secrets using provided script

=== Usage

```
add-secret.sh \
  -d <local directory> \
  -f <local file path> \
  [-r <remote file path>] \
  [-n <secret name>] \
  -v <value> \
  -b <target branch> \
  [-p <pipelines list>]
```

=== Flags
```
-d, --local-directory       [Required] Local directory of your project."
-f, --local-file-path       [Required, unless -v] Local path of the file to be uploaded. Takes precedence over -v.
-r, --remote-file-path      [Required, if -f] File path (in pipeline context) where the secret will be downloaded.
-n, --secret-name           [Required, if -v] Name for the secret in Secret Manager. If not specified (when optional), file name is used as default. The name must comply with the regex [a-zA-Z0-9_].
-v, --value                 [Required, unless -f] Value of the secret.
-b, --target-branch         [Required] Name of the branch to which the merge will target.
-p, --pipelines                        List of pipelines where the secret will be made available. By default, all pipelines.
```

NOTE: If `-n` flag is not provided and the file name of `-f` is not compliant with the regex, it will be modified to be so.

=== Examples

==== Adding a secret file

```
./add-secret.sh -d C:/Users/$USERNAME/Desktop/project -f ../path/to/secretFile.txt -r .pipelines/config/secretFile.txt -n secretFile -b develop -p "build-pipeline,test-pipeline"
```

==== Adding secret variable

```
./add-secret.sh -d C:/Users/$USERNAME/Desktop/project/ -n secretVar -v secretValue -b develop -p "build-pipeline,test-pipeline"
```
````

2022-12-19 09:27 UTC, closed without merging