Feature/block 6
devonfw/hangar pull request #31
Opened 2021-12-21 11:23 UTC by prathibhapadma

2021-12-22 14:41 UTC, jbellver99 requested changes
Take a look to the updates in block 5 and make it more similar.

2021-12-22 14:41 UTC, jbellver99 commented on documentation/azure-devops/setup-test-pipeline.asciidoc
> +. Clone the {url-devonfw-hangar}[devonfw/hangar] repository.
Check if we really need to create a service connection with github, because we do not want to run the tests of a github project, we want to pass test to the code that is stored in the Azure DevOps repository

2021-12-22 14:41 UTC, jbellver99 commented on documentation/azure-devops/setup-test-pipeline.asciidoc
> +. This bash script will execute in Git bash or Linux Machine.
```suggestion

```

2021-12-22 14:41 UTC, jbellver99 commented on documentation/azure-devops/setup-test-pipeline.asciidoc
> +. Clone the {url-devonfw-hangar}[devonfw/hangar] repository.
is it really necessary to have a PAT? we already created it in block 1.

2021-12-22 14:41 UTC, jbellver99 commented on documentation/azure-devops/setup-test-pipeline.asciidoc
> +-b    [Required] Branch of the repository.
-r flag is not necessary, we do not want to test the code in a github repo, we want to test the code in our Azure DevOps repo.

2021-12-22 14:41 UTC, jbellver99 commented on documentation/azure-devops/setup-test-pipeline.asciidoc
> +NOTE:  -l <language> This example is maven based. If you need to choose a different language, you have to modify the commands in `.scripts/${language}-test.sh` file.
```suggestion
```

2021-12-22 14:41 UTC, jbellver99 commented on scripts/pipelines/azure-devops/test_pipeline_generator.sh
> +pipelineFile="${pipelinesDirectory}/azure-pipelines.yml"
This pipeline needs to be block independent, so give a name such as test-pipeline.yml

2021-12-22 14:41 UTC, jbellver99 commented on scripts/pipelines/azure-devops/test_pipeline_generator.sh
> +cp -r .pipelines ${directory}
Make it more block independent, do not copy into the repo the whole folder, just the specific YAML for the test pipeline.

2021-12-22 14:41 UTC, jbellver99 commented on scripts/pipelines/azure-devops/test_pipeline_generator.sh
> +mkdir .scripts
no need to create this folder as it is already created in the build pipeline.

2021-12-22 14:41 UTC, jbellver99 commented on scripts/pipelines/azure-devops/test_pipeline_generator.sh
> +az pipelines create --name $name --repository $repository --branch $branch --yml-path ".pipelines/azure-pipelines.yml"
This creates a pipeline for the branch that is passed through the -b flag and it should be created in the new created branch (feature/test-pipeline).

2021-12-23 13:26 UTC, albertdb commented
Apart from previous review comments, we can take this block as an opportunity to create a generic pipeline generator script instead of needing one script per pipeline type. So, we can provide a config file as parameter containing all the variables that make a test (or QA, or Deploy... any type) different from a build pipeline, like the paths, filenames and such. That way, we can reuse the script for the next blocks.

2022-01-07 11:51 UTC, jbellver99 requested changes

2022-01-07 11:51 UTC, jbellver99 commented on .pipelines/test-pipeline.yml
> +        filePath: '.pipelines/.scripts/test.sh'
```suggestion
        filePath: '.pipelines/scripts/test.sh'
```

2022-01-07 11:51 UTC, jbellver99 commented on documentation/azure-devops/setup-test-pipeline.asciidoc
> +Before executing the script be sure your local repository is upto date, pull latest changes with `git pull`.
```suggestion
Before executing the script be sure your local repository is up to date, pull latest changes with `git pull`.
```

2022-01-07 11:51 UTC, jbellver99 commented on scripts/pipelines/azure-devops/script_config.cfg
> +scripts=".pipelines/.scripts/test.sh"
```suggestion
scripts=".pipelines/scripts/test.sh"
```

2022-01-07 11:51 UTC, jbellver99 commented on scripts/pipelines/azure-devops/test_pipeline_generator.sh
> +    echo "  -w               Open the Pull Request on the web browser if it cannot be automatically merged. Requires -b flag."
```suggestion
    echo "  -n    [Required] Name that will be set to the test pipeline."
    echo "  -l    [Required] Language or framework of the project."
    echo "  -d    [Required] Local directory of your project (the path should always be using '/' and not '\')."
    echo "  -c    [Required] Configuration file for parameter containing all the variables."
    echo "  -b    [Required] Name of the target branch to which the Pull Request will target. PR is not created if the flag is not provided."
    echo "  -w               Open the Pull Request on the web browser if it cannot be automatically merged. Requires -b flag." 
```

2022-01-07 11:51 UTC, jbellver99 commented on scripts/pipelines/azure-devops/test_pipeline_generator.sh
> +if test -z "$name" || test -z "$language" || test -z "$directory"
```suggestion
if test -z "$name" || test -z "$language" || test -z "$directory" || test -z "$configuration_file" || test -z "$target_branch"
```

2022-01-07 11:51 UTC, jbellver99 commented on scripts/pipelines/azure-devops/test_pipeline_generator.sh
> +    echo -e "${red}Missing parameters, all flags are mandatory."
```suggestion
    echo -e "${red}Missing parameters, some flags are mandatory."
```

2022-01-07 11:51 UTC, jbellver99 commented on scripts/pipelines/azure-devops/test_pipeline_generator.sh
> +
```suggestion
pipelinesDirectory="${directory}/${pipelines}"
scriptsDirectory="${pipelinesDirectory}/${scripts}"
```

2022-01-07 11:51 UTC, jbellver99 commented on scripts/pipelines/azure-devops/test_pipeline_generator.sh
> +
```suggestion

# Copy the corresponding YAML and script into the directory.
echo -e "${green}Copying the corresponding YAML and script into your directory..."
echo -e ${white}
cd ${hangarPath}/.pipelines
cp "test-pipeline.yml" "${pipelinesDirectory}/test-pipeline.yml"
cd ${hangarPath}/.scripts
cp "${language}-test.sh" "${scriptsDirectory}/test.sh"

```

2022-01-07 11:51 UTC, jbellver99 commented on scripts/pipelines/azure-devops/test_pipeline_generator.sh
> +git add ${pipelines} ${scripts} -f
```suggestion
git add .pipelines -f
```

2022-01-07 13:18 UTC, jbellver99 commented
Change the YAML template and the test script to the path: ./scripts/pipelines/azure-devops/templates/test

2022-01-20 11:49 UTC, jbellver99 requested changes
Make the necessary changes in the documentation in order to fit with the new script.

2022-01-20 11:49 UTC, jbellver99 commented on scripts/pipelines/azure-devops/build-pipeline-config.cfg
> +mandatoryFlags="$language,$targetBranch,"
Add the other required flags such as pipeline name and local directory

2022-01-20 11:49 UTC, jbellver99 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    exit 2
Check only check if a config file is supplied, the other flags are checked afterwards.

2022-01-20 11:49 UTC, jbellver99 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +	h) help=${OPTARG};;
Add the variable localDirectory here and not in the config file.

2022-01-20 11:49 UTC, jbellver99 commented on scripts/pipelines/azure-devops/build-pipeline-config.cfg
> +localDirectory="C:/Users/ppadma/Desktop/new_testing/quarkus-demo"
Remove this variable from here.

2022-01-24 11:29 UTC, jbellver99 requested changes
Remove the quality-pipeline-config.cfg

2022-01-24 11:29 UTC, jbellver99 commented on documentation/azure-devops/setup-test-pipeline.asciidoc
> +The script located at `/scripts/pipelines/azure-devops/pipeline_generator.sh` will automatically create a test pipeline based on a YAML template at `templates/test/test-pipeline.yml`. Configuration f
```suggestion
The script located at `/scripts/pipelines/azure-devops/pipeline_generator.sh` will automatically create a test pipeline based on a YAML template at `templates/test/test-pipeline.yml`.  The configuration file `test-pipeline-config.cfg` contains the required variables in order to create the test pipeline and should be passed by parameter in the script..
```

2022-01-24 11:29 UTC, jbellver99 commented on documentation/azure-devops/setup-test-pipeline.asciidoc
> +Please follow below instructions to execute the script:
```suggestion
```

2022-01-24 11:29 UTC, jbellver99 commented on documentation/azure-devops/setup-test-pipeline.asciidoc
> +Please follow below instructions to execute the script:
These are not instructions to follow.

2022-01-24 11:29 UTC, jbellver99 commented on documentation/azure-devops/setup-test-pipeline.asciidoc
> +*Note*: If any test pipeline failed, check the logs for the specific pipeline summary. In more actions you can download complete logs which include additional diagnostic information or you can store
```suggestion
```

2022-01-24 11:29 UTC, jbellver99 commented on documentation/azure-devops/setup-test-pipeline.asciidoc
> +*Note*: If any test pipeline failed, check the logs for the specific pipeline summary. In more actions you can download complete logs which include additional diagnostic information or you can store
Variables in the config file should not be modified by the user.

2022-01-24 11:29 UTC, jbellver99 commented on documentation/azure-devops/setup-test-pipeline.asciidoc
> +./pipeline_generator.sh -n <pipeline name> -l <language or framework> -d <project local path> -c <config file path> -b <target branch> [-w]
```suggestion
./pipeline_generator.sh -c <config file path> -n <pipeline name> -l <language or framework> -d <project local path>  -b <target branch> [-w]
```

2022-01-24 11:29 UTC, jbellver99 commented on documentation/azure-devops/setup-test-pipeline.asciidoc
> +NOTE: Pipeline parameters can be modified as needed in `test-pipeline-config.cfg` file such as pipeline name, branch name, yaml files path, etc.
```suggestion
```

2022-01-24 11:29 UTC, jbellver99 commented on documentation/azure-devops/setup-test-pipeline.asciidoc
> +NOTE: Pipeline parameters can be modified as needed in `test-pipeline-config.cfg` file such as pipeline name, branch name, yaml files path, etc.
Configuration files should not be modified.

2022-01-24 11:29 UTC, jbellver99 commented on scripts/pipelines/azure-devops/build-pipeline-config.cfg
> +mandatoryFlags="$pipelineName,$localDirectory,$language,$targetBranch,"
```suggestion
mandatoryFlags="$pipelineName,$localDirectory,$language,"
```

2022-01-24 11:29 UTC, jbellver99 commented on scripts/pipelines/azure-devops/build-pipeline-config.cfg
> +mandatoryFlags="$pipelineName,$localDirectory,$language,$targetBranch,"
Target branch is not mandatory

2022-01-24 11:29 UTC, jbellver99 commented on scripts/pipelines/azure-devops/test-pipeline-config.cfg
> +mandatoryFlags="$pipelineName,$localDirectory,$language,$targetBranch,"
```suggestion
mandatoryFlags="$pipelineName,$localDirectory,$language,"
```

2022-01-24 11:29 UTC, jbellver99 commented on scripts/pipelines/azure-devops/test-pipeline-config.cfg
> +mandatoryFlags="$pipelineName,$localDirectory,$language,$targetBranch,"
Target branch is not mandatory

2022-01-25 16:05 UTC, jbellver99 requested changes
Review suggestions and make changes in order to be more consistent with the other documentations.

2022-01-25 16:05 UTC, jbellver99 commented on documentation/azure-devops/setup-test-pipeline.asciidoc
> +
```suggestion
CAUTION: Remember to write the path to the local repository with '/' and not '\' on windows.
```

2022-01-25 16:05 UTC, jbellver99 commented on scripts/pipelines/azure-devops/test-pipeline-config.cfg
> +
Change file name to test-config.cfg in order to be more consistent with the other documentations.

2022-01-27 07:21 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/test-pipeline-config.cfg
> +
I hope this is the final review, I have incorporated all the changes and commited.

2022-01-27 07:36 UTC, jbellver99 requested changes

2022-01-27 07:36 UTC, jbellver99 commented on documentation/azure-devops/setup-test-pipeline.asciidoc
> +== Prerequisites
```suggestion

== Prerequisites
```

2022-01-27 07:36 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/test/test-config.cfg
> +yamlfilepath=".pipelines/test-pipeline.yml"
```suggestion
```

2022-01-31 11:59 UTC, albertdb requested changes
I'm missing some of the functionality that we discussed time ago. Please review comments.

2022-01-31 11:59 UTC, albertdb commented on documentation/azure-devops/setup-test-pipeline.asciidoc
> +. The config file for the test pipeline is located at `/templates/test/test-config.cfg`.
```suggestion
. The config file for the test pipeline is located at `/scripts/pipelines/azure-devops/templates/test/test-config.cfg`.
```

2022-01-31 11:59 UTC, albertdb commented on documentation/azure-devops/setup-test-pipeline.asciidoc
> +. If any test pipeline failed, check the logs for the specific pipeline summary. In more actions you can download complete logs which include additional diagnostic information or you can store applic
```suggestion
. If the test pipeline failed, check the logs for the failed test case(s) summary. In _More actions_ (three dots button) you can download complete logs which include additional diagnostic information or you can store application logs in user specified path.
```

2022-01-31 11:59 UTC, albertdb commented on documentation/azure-devops/setup-test-pipeline.asciidoc
> +. If any test pipeline failed, check the logs for the specific pipeline summary. In more actions you can download complete logs which include additional diagnostic information or you can store applic
The feature to specify a path where the application stores its logs (including but not limited to artifact creation) is not implemented.

2022-01-31 11:59 UTC, albertdb commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    echo "  -n    [Required] Name that will be set to the quality pipeline."
```suggestion
    echo "  -n    [Required] Name that will be set to the pipeline."
```

2022-02-03 08:37 UTC, jbellver99 requested changes
The idea is to add the publish artifact block in the YAML only if the -a flag is activated not always. Try to have this block in another file and concatenate it to the YAML template when the flag is activated.

2022-02-03 08:37 UTC, jbellver99 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +az pipelines variable create --name "artifactPath" --pipeline-name $pipelineName --value ${artifactPath}
```suggestion
# Check if -a flag is activated
if ! test -z "$artifactPath"
then
    # Create variables in Azure pipeline
    echo -e "${green}Creating variable in the pipeline..."
    echo -e ${white}
    az pipelines variable create --name "artifactPath" --pipeline-name $pipelineName --value ${artifactPath}
fi
```

2022-02-03 08:37 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/test/test-pipeline.yml
> +        testResultsFiles: '**/TEST-*.xml'
Add display names to the steps in the pipeline in order to make it more user friendly.

2022-02-03 08:37 UTC, jbellver99 commented on documentation/azure-devops/setup-test-pipeline.asciidoc
> +
Mention the new flag and for what it is used for so that the user is aware of this option.

2022-02-03 08:41 UTC, jbellver99 requested changes

2022-02-03 08:41 UTC, jbellver99 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +az pipelines create --name $pipelineName --yml-path "${pipelinePath}/${yamlFile}" --skip-first-run
```suggestion
az pipelines create --name $pipelineName --yml-path "${pipelinePath}/${yamlFile}" --skip-first-run true
```

2022-02-03 10:00 UTC, jbellver99 commented
The -a option should store the logs generated by the test and not the target folder generated when doing a mvn test, please review the YAML file

2022-02-03 10:55 UTC, albertdb commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +echo -e "${green}Run the pipeline..."
I think we talked about this. There's no reason to run the pipeline when we setup it.

2022-02-03 10:57 UTC, albertdb commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +az pipelines variable create --name "artifactPath" --pipeline-name $pipelineName --value ${artifactPath}
The message shown does not let the user know what variable is and why is that being done.

2022-02-03 11:02 UTC, albertdb commented on documentation/azure-devops/setup-test-pipeline.asciidoc
> +
I wouldn't add that here, it's already mentioned in usage and flags, and could also be mentioned in the note I'm going to write "HERE"

2022-02-03 11:02 UTC, albertdb commented on documentation/azure-devops/setup-test-pipeline.asciidoc
> +. If the test pipeline failed, check the logs for the failed test case(s) summary. In _More actions_ (three dots button) you can download complete logs which include additional diagnostic information
HERE

2022-02-03 12:03 UTC, prathibhapadma commented on documentation/azure-devops/setup-test-pipeline.asciidoc
> +
Yes -a flag added in NOTE.

2022-02-09 11:35 UTC, prathibhapadma commented
All the above review comments are updated.

2022-02-16 09:19 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/test/store-extra-path.yml
> +  artifact: tests
```suggestion
  artifact: additional-pipeline-output
```

2022-02-16 09:21 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/test/store-extra-path.yml
> +  artifact: tests
```suggestion
  displayName: "Publish Additional Output Artifact"
  artifact: additional-pipeline-output
```

2022-02-16 09:35 UTC, albertdb approved these changes

2022-02-16 09:38 UTC, merged