AWS EKS provisioning using Terraform
devonfw/hangar pull request #32
Opened 2021-12-28 09:23 UTC by isandesh1986

This is a intermediate commit only with the Terraform scripts so as to use these scripts for internal development purpose of other blocks. More detailed guide will be added soon.

2022-03-02 11:28 UTC, jbellver99 requested changes
Delete the eks-config.cfg file as we are using the eks-pipeline.cfg

2022-03-02 11:28 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/eks/eks-pipeline.cfg
> +    fi
```suggestion
    # Create .terraform/eks folder if it does not exist.
    mkdir -p "${localDirectory}/${terraformPath}"
```

2022-03-02 11:31 UTC, isandesh1986 commented
> Delete the eks-config.cfg file as we are using the eks-pipeline.cfg

yes its already deleted, I'm currently testing few things. Will be committed once testing is completed.

2022-03-16 15:52 UTC, isandesh1986 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --cluster-name)         clusterName=$2; shift 2;;
used in pipeline cfg file

2022-03-16 15:52 UTC, isandesh1986 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --build-pipeline-name)  buildPipelineName=$2; shift 2;;
ignore

2022-03-29 16:18 UTC, albertdb requested changes
IMPORTANT: Please put proxy script in sonarqube directory, you moved original script and that will break if the proxy script is not put there as a replacement.

2022-03-29 16:18 UTC, albertdb commented on documentation/azure-devops/setup-eks-provisioning-pipeline.asciidoc
> +Example DNS Name - https://aa9e8f0434d934c939be841f1de52a09-1657056367.eu-west-1.elb.amazonaws.com/dashboard
This is example doesn't belong here but could be in the appendix.

2022-03-29 16:18 UTC, albertdb commented on documentation/azure-devops/setup-eks-provisioning-pipeline.asciidoc
> +Rancher can be accessed at the DNS name of the nginx ingress controller. Refer the appendix to retrieve the DNS name from the nginx ingress controller.
```suggestion
```

2022-03-29 16:18 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/eks/eks-provisioning.yml
> +  displayName: 'Install ingress controller and Publish DNS'
```suggestion
  displayName: 'Install Ingress controller and publish its DNS name'
```

2022-03-29 17:02 UTC, isandesh1986 commented on scripts/environment-provisioning/aws/eks/main.tf
> +  worker_groups = [
yes, it should be because of this

2022-03-29 17:04 UTC, isandesh1986 commented on scripts/pipelines/azure-devops/templates/eks/store-extra-path.yml
> +- publish: $(Build.Repository.LocalPath)/$(artifactPath)
Yes, synced up.

2022-03-29 17:08 UTC, isandesh1986 commented on documentation/azure-devops/setup-eks-provisioning-pipeline.asciidoc
> +Example DNS Name - https://aa9e8f0434d934c939be841f1de52a09-1657056367.eu-west-1.elb.amazonaws.com/dashboard
Moved to appendix. Done.

2022-03-29 17:13 UTC, isandesh1986 commented on documentation/azure-devops/setup-eks-provisioning-pipeline.asciidoc
> +NOTE: The config file for the EKS provisioning pipeline is located at `/scripts/pipelines/azure-devops/templates/eks/eks-pipeline.cfg`.
This path is right.

2022-03-29 17:17 UTC, isandesh1986 commented on documentation/azure-devops/setup-eks-provisioning-pipeline.asciidoc
> +* The script installs Rancher on the cluster after provisioning. However before executing the script, please edit the config file `eks-pipeline.cfg` to disable rancher installation.
Done

2022-03-30 08:18 UTC, albertdb commented on documentation/azure-devops/setup-eks-provisioning-pipeline.asciidoc
> +NOTE: The config file for the EKS provisioning pipeline is located at `/scripts/pipelines/azure-devops/templates/eks/eks-pipeline.cfg`.
Sorry, my bad.

2022-03-30 09:01 UTC, albertdb commented on documentation/azure-devops/setup-eks-provisioning-pipeline.asciidoc
> +Before executing the pipeline generator, you will need to customize some input variables about the environment. Also, you may want to use existing VPC and subnets instead of creating new ones. To do
We don't mention anywhere where are those files,

2022-03-30 09:12 UTC, isandesh1986 commented on documentation/azure-devops/setup-eks-provisioning-pipeline.asciidoc
> +NOTE: The config file for the EKS provisioning pipeline is located at `/scripts/pipelines/azure-devops/templates/eks/eks-pipeline.cfg`.
No problem

2022-04-02 03:21 UTC, isandesh1986 commented
> @isandesh1986 Could you please give a quick update of the current status?

I am sick leave. Latest update is after upgrading the terraform aws module version to the latest - there are failures. Once we resolve them it should be done.

2022-04-05 14:54 UTC, albertdb commented on documentation/azure-devops/setup-eks-provisioning-pipeline.asciidoc
> +In this section we will create a pipeline which will provision AWS EKS. This pipeline will be configured to be manually triggered by the user. As part of EKS cluster provisioning, an NGINX Ingress co
```suggestion
In this section we will create a pipeline which will provision an AWS EKS cluster. This pipeline will be configured to be manually triggered by the user. As part of EKS cluster provisioning, an NGINX Ingress controller is deployed and a variable group with the name `eks-variables` is created, which contains, among others, the DNS name of the Ingress controller, that you you will need to add as CNAME record on the domains used in your application Ingress manifest files. Refer the appendix to retrieve the DNS name of the ingress controller independently. 
```

2022-04-05 15:07 UTC, albertdb commented on documentation/azure-devops/setup-eks-provisioning-pipeline.asciidoc
> +* Create a https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#create-a-service-connection[service connection] and name it `AWS-Terraform-Con
```suggestion
* Create a service connection for connecting to an AWS account (as explained in the above Terraform extension link) and name it `AWS-Terraform-Connection`. If you already have a service connection available or you need a specific connection name, please update `eks-pipeline.cfg` accordingly.
```

2022-04-05 15:39 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/eks/eks-pipeline.cfg
> +    # Add the AWS S3 Key path variable.
Review comment.

2022-04-05 15:44 UTC, albertdb commented on documentation/azure-devops/setup-eks-provisioning-pipeline.asciidoc
> +-d, --local-directory    [Required] Local directory of your project (the path should always be using '/' and not '\').
```suggestion
-d, --local-directory    [Required] Local directory of your project (the path should always be using '/' and not '\').
    --cluster-name       [Required] Name for the cluster."
    --s3-bucket          [Required] Name of the S3 bucket where the Terraform state of the cluster will be stored.
    --s3-key-path        [Required] Path within the S3 bucket where the Terraform state of the cluster will be stored.
```

2022-04-05 16:04 UTC, albertdb commented on documentation/azure-devops/setup-eks-provisioning-pipeline.asciidoc
> +Run the below command to connect to the AWS EKS cluster from your terminal
```suggestion
First, generate a kubeconfig for accessing the AWS EKS cluster:
```

2022-04-05 16:20 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/eks/eks-provisioning.yml
> +trigger:
Append `.template` to filename. Please sync changes as discussed.

2022-04-05 16:33 UTC, albertdb commented on documentation/azure-devops/setup-eks-provisioning-pipeline.asciidoc
> +To get the DNS name of the nginx ingress controller from the EKS cluster, run the below command from your terminal
```suggestion
To get the DNS name of the NGINX Ingress controller on the EKS cluster, run the below command:
```

2022-04-05 17:41 UTC, isandesh1986 commented on scripts/pipelines/azure-devops/templates/eks/eks-pipeline.cfg
> +# The AWS Service Connection name created in Azure DevOps
Done

2022-04-05 17:41 UTC, isandesh1986 commented on scripts/pipelines/azure-devops/templates/eks/eks-pipeline.cfg
> +
Done

2022-04-06 09:11 UTC, isandesh1986 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --cluster-name)         clusterName=$2; shift 2;;
ignore

2022-04-06 09:28 UTC, albertdb requested changes

2022-04-06 09:28 UTC, albertdb commented on scripts/environment-provisioning/aws/eks/setTerraformVariables.sh
> +#!/bin/bash
Rename to `set-terraform-variables.sh`

2022-04-06 09:28 UTC, albertdb commented on documentation/azure-devops/setup-eks-provisioning-pipeline.asciidoc
> +Before executing the pipeline generator, you will need to customize some input variables about the environment. Also, you may want to use existing VPC and subnets instead of creating new ones. To do
```suggestion
Before executing the pipeline generator, you will need to customize some input variables about the environment. Also, you may want to use existing VPC and subnets instead of creating new ones. To do so, you can either edit `terraform.tfvars` file or take advantage of the `set-terraform-variables.sh` script located at `/scripts/environment-provisioning/aws/eks`, which allows you to create or update values for the required variables, passing them as flags.
```

2022-04-06 09:28 UTC, albertdb commented on documentation/azure-devops/setup-eks-provisioning-pipeline.asciidoc
> +./setTerraformVariables.sh --region <region name> --instance_type <instance type> --vpc_name <vpc name> --vpc_cidr_block <vpc_cidr_block>
Rename to `set-terraform-variables.sh`

2022-04-06 09:32 UTC, isandesh1986 commented on scripts/environment-provisioning/aws/eks/setTerraformVariables.sh
> +#!/bin/bash
done

2022-04-06 10:43 UTC, isandesh1986 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        -a | --artifact-path)   artifactPath=$2; shift 2;;
ignore

2022-04-06 10:43 UTC, isandesh1986 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        -l | --language)        language=$2; shift 2;;
ignore

2022-04-06 10:43 UTC, isandesh1986 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        -p | --password)        password=$2; shift 2;;
ignore

2022-04-06 10:43 UTC, isandesh1986 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --s3-key-path)          s3KeyPath=$2; shift 2;;
ignore

2022-04-06 10:43 UTC, isandesh1986 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --sonar-token)          sonarToken=$2; shift 2;;
ignore

2022-04-06 10:44 UTC, isandesh1986 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --sonar-url)            sonarUrl=$2; shift 2;;
ignore

2022-04-06 10:44 UTC, isandesh1986 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --storage-account)      storageAccountName=$2; shift 2;;
ignore

2022-04-06 10:44 UTC, isandesh1986 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --storage-container)    storageContainerName=$2; shift 2;;
ignore

2022-04-06 10:45 UTC, isandesh1986 commented on scripts/environment-provisioning/aws/eks/main.tf
> +  worker_groups = [
Done

2022-04-06 10:45 UTC, isandesh1986 commented on scripts/environment-provisioning/aws/eks/variables.tf
> +  description = "[Optional] - Instance type of the worker node group configuration."
Done

2022-04-06 11:07 UTC, isandesh1986 commented on scripts/pipelines/azure-devops/templates/eks/eks-pipeline.cfg
> +    # Add the AWS S3 Key path variable.
Done

2022-04-06 11:17 UTC, isandesh1986 commented on scripts/environment-provisioning/aws/eks/main.tf
> +  cluster_version = "1.20"
Done, upgraded to 1.21

2022-04-12 16:27 UTC, albertdb requested changes

2022-04-12 16:27 UTC, albertdb commented on documentation/aws/setup-sonarqube-instance.asciidoc
> +Then, you may need to customize some input variables about the environment. To do so, you can either edit `terraform.tfvars` file or take advantage of the `set-terraform-variables` script located at
In the above paragraph the location is mentioned and the user should be there to execute `terraform init`, maybe we can skip saying it again

2022-04-12 16:27 UTC, albertdb commented on documentation/azure-devops/setup-eks-provisioning-pipeline.asciidoc
> +```
````suggestion
Example: creating a new VPC on cluster creation:

```
./set-terraform-variables.sh --region <region name> --instance_type <workers instance type> --vpc_name <vpc name> --vpc_cidr_block <vpc cidr block>
```
Example: reusing existing VPC and subnets:
```
./set-terraform-variables.sh --region <region name> --instance_type <workers instance type> --existing_vpc_id <vpc id> --existing_vpc_private_subnets <array of subnet ids>
```
````

2022-04-18 02:41 UTC, isandesh1986 commented on scripts/pipelines/azure-devops/templates/eks/eks-provisioning.yml.template
> +      helm upgrade --install nginx-ingress nginx-ingress-controller --set ingressClassResource.default=true --set containerSecurityContext.allowPrivilegeEscalation=false --repo https://charts.bitnami
do we really need a separate script for just a couple of lines?

2022-04-18 02:42 UTC, isandesh1986 commented on scripts/environment-provisioning/aws/eks/variables.tf
> +}
Done

2022-04-18 02:52 UTC, isandesh1986 commented on scripts/pipelines/azure-devops/templates/eks/eks-provisioning.yml.template
> +    script: 'sleep 60'
Done

2022-04-18 02:55 UTC, isandesh1986 commented on documentation/aws/setup-sonarqube-instance.asciidoc
> +Then, you may need to customize some input variables about the environment. To do so, you can either edit `terraform.tfvars` file or take advantage of the `set-terraform-variables` script located at
Done.

2022-04-20 08:41 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/eks/eks-provisioning.yml.template
> +      helm upgrade --install nginx-ingress nginx-ingress-controller --set ingressClassResource.default=true --set containerSecurityContext.allowPrivilegeEscalation=false --repo https://charts.bitnami
This bunch of lines is repeated for both provisioning pipelines and it would be the case for any other provider that we support.

2022-04-20 09:10 UTC, albertdb requested changes
Please address Sonatype Lift shellchecks.

I don't see that we are using Rancher for anything, would it be posible to retrieve and publish a kubeconfig generated with Rancher?

2022-04-22 05:18 UTC, isandesh1986 commented on scripts/environment-provisioning/aws/eks/variables.tf
> +  description = "Minimum workers"
agreed. done

2022-04-22 05:18 UTC, isandesh1986 commented on scripts/pipelines/azure-devops/templates/eks/eks-provisioning.yml.template
> +  name: 'PublishDNS'
yes, done.

2022-04-22 05:32 UTC, isandesh1986 commented
> Please address Sonatype Lift shellchecks.
> 
> I don't see that we are using Rancher for anything, would it be posible to retrieve and publish a kubeconfig generated with Rancher?

All Sonatype checks are addressed

2022-04-22 05:44 UTC, isandesh1986 commented
> > Please address Sonatype Lift shellchecks.
> > I don't see that we are using Rancher for anything, would it be posible to retrieve and publish a kubeconfig generated with Rancher?
> 
> All Sonatype checks are addressed

Dint find any such provision to do so from rancher cli.

2022-04-22 07:12 UTC, isandesh1986 commented on scripts/pipelines/azure-devops/templates/eks/eks-provisioning.yml.template
> +      helm upgrade --install nginx-ingress nginx-ingress-controller --set ingressClassResource.default=true --set containerSecurityContext.allowPrivilegeEscalation=false --repo https://charts.bitnami
Done

2022-04-22 07:19 UTC, isandesh1986 commented
@albertdb - All requested changes are addressed.

2022-04-28 10:27 UTC, albertdb requested changes
Some minor changes. Please check and if everything OK, it will be ready to go.

2022-04-28 10:27 UTC, albertdb commented on documentation/azure-devops/setup-eks-provisioning-pipeline.asciidoc
> +•	Logging - https://rancher.com/docs/rancher/v2.0-v2.4/en/cluster-admin/tools/cluster-logging/
```suggestion
* https://rancher.com/docs/rancher/v2.6/en/cluster-admin/cluster-access/kubectl/[Downloading `kubeconfig`].
* https://rancher.com/docs/rancher/v2.6/en/admin-settings/rbac/[RBAC]
* https://rancher.com/docs/rancher/v2.6/en/monitoring-alerting/[Monitoring]
* https://rancher.com/docs/rancher/v2.6/en/logging/[Logging]
```

2022-04-28 10:27 UTC, albertdb commented on scripts/environment-provisioning/aws/eks/set-terraform-variables.sh
> +"/bin/sh" "../../../set-config.sh" "$ARGS"
```suggestion
../../../set-config.sh "$ARGS"
```

The problem is with variables.

set-config.sh should be executable. Please check and fix if needed.

2022-04-28 10:27 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/eks/eks-pipeline.cfg
> +    cp "${hangarPath}/scripts/pipelines/azure-devops/templates/common/install-ingress-controller.sh" "${localDirectory}/${scriptFilePath}/install-ingress-controller.sh"
```suggestion
    cp "${hangarPath}/${commonTemplatesPath}/install-ingress-controller.sh" "${localDirectory}/${scriptFilePath}/install-ingress-controller.sh"
```

2022-04-28 10:27 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/eks/eks-provisioning.yml.template
> +      sh '$(System.DefaultWorkingDirectory)/.pipelines/scripts/install-ingress-controller.sh'
```suggestion
      $(System.DefaultWorkingDirectory)/.pipelines/scripts/install-ingress-controller.sh
```

File should be executable already. Please check.

2022-04-28 10:30 UTC, albertdb commented on scripts/sonarqube/set-terraform-variables.sh
> +/bin/sh ../set-config.sh $ARGS
```suggestion
../set-config.sh "$ARGS"
```

2022-05-02 09:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw/hangar?pullRequest=32) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/devonfw/hangar?pullRequest=32) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw/hangar?pullRequest=32) it.</sub>

2022-06-15 13:26 UTC, isandesh1986 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --cluster-operation)      clusterOperation=$2; shift 2;;
@sonatype-lift ignore

2022-06-16 08:48 UTC, albertdb commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    echo "      --cluster-operation                Operation to be performed on AWS to create or destroy the cluster."
The point was that the user is able to change the parameter on pipeline launch, as in GitHub inputs.

2022-06-16 08:50 UTC, albertdb commented on documentation/azure-devops/setup-eks-provisioning-pipeline.asciidoc
> +    --cluster-operation             Operation to be performed on EKS cluster to create or destroy it. Default is create.
```suggestion
```

2022-06-16 08:52 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/eks/eks-pipeline.cfg
> +# Set this to destroy if you are destroying the cluster and to create otherwise.
```suggestion
# Default cluster operation.
```

2022-06-16 08:52 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/eks/eks-pipeline.cfg
> +# Installs Rancher on EKS cluster if set to true
```suggestion
# Install Rancher on EKS cluster.
```

2022-06-16 08:54 UTC, albertdb submitted a review, later dismissed

2022-06-16 09:05 UTC, albertdb commented on documentation/azure-devops/setup-eks-provisioning-pipeline.asciidoc
> +CAUTION: Remember to write the path to the local repository with '/' and not '\' on Windows.
```suggestion
```

2022-06-16 09:07 UTC, merged