Feature/aws policy checker
devonfw/hangar pull request #34
Opened 2022-01-20 16:00 UTC by mcerverc

2022-01-20 16:31 UTC, mcerverc commented on scripts/accounts/aws/verify-account-policies.sh
> +        for user_custom_policy in ${user_custom_policies[@]} #Loop all groups
ignore

2022-01-27 11:56 UTC, albertdb commented on scripts/accounts/aws/verify-account-policies.sh
> +        for user_custom_policy in ${user_custom_policies[@]} #Loop all groups
The suggestion seems legit. Did you find any issue applying it?

2022-01-31 15:37 UTC, albertdb requested changes
I'm missing the file with the list of managed policies, the file with the custom policy, and a proper example using them.

2022-02-01 12:28 UTC, albertdb requested changes
Review comments and please update the managed policies list, they have changed (removed some, added other).

2022-02-01 12:28 UTC, albertdb commented on documentation/aws/setup-aws-account-iam-for-eks.asciidoc
> +NOTE: Required policies for EKS usage are located at `/scripts/accounts/aws/eks-managed-policies.txt` and `/scripts/accounts/aws/eks-custom-policies.json`
```suggestion
NOTE: Required policies for using EKS are located at `/scripts/accounts/aws/eks-managed-policies.txt` and `/scripts/accounts/aws/eks-custom-policies.json`
```

2022-02-01 12:28 UTC, albertdb commented on documentation/aws/setup-aws-account-iam-for-eks.asciidoc
> +NOTE: Required policies for EKS usage are located at `/scripts/accounts/aws/eks-managed-policies.txt` and `/scripts/accounts/aws/eks-custom-policies.json`
It would be good to include this note also in the first section example, below the existing note.

2022-02-03 10:47 UTC, albertdb requested changes
Review comments and update the list of required policies on the upper part of the guide (including `eks:*`).

2022-02-03 10:47 UTC, albertdb commented on documentation/aws/setup-aws-account-iam-for-eks.asciidoc
> +create-user.sh -u <username> -g <group> [-p <policies...>] [-f <policies file path>] [-c "<custom policies file>"] [-a "<AWS access key>"] [-s "<AWS secret key>"] [-r <region>]
```suggestion
create-user.sh \
  -u <username> \
  -g <group> \
  [-p <policies...>] \
  [-f <policies file path>] \
  [-c <custom policies file path>] \
  [-a <AWS access key>] \
  [-s <AWS secret key>] \
  [-r <region>] 
```

2022-02-03 10:47 UTC, albertdb commented on documentation/aws/setup-aws-account-iam-for-eks.asciidoc
> +-c     [Optional] Path to a json file containing the custom policies to be attached to the group.
```suggestion
-c      [Optional] Path to a json file containing the custom policies to be attached to the group.
```

2022-02-03 10:47 UTC, albertdb commented on documentation/aws/setup-aws-account-iam-for-eks.asciidoc
> +./create-user.sh -u "Bob" -g "DevOps" -f "./eks-managed-policies.txt" -c "eks-custom-policies.json" -a "myAccessKey" -s "mySecretKey" -r "eu-west-1"
```suggestion
./create-user.sh -u Bob -g DevOps -f ./eks-managed-policies.txt -c ./eks-custom-policies.json -a "myAccessKey" -s "mySecretKey" -r eu-west-1
```

2022-02-03 10:47 UTC, albertdb commented on documentation/aws/setup-aws-account-iam-for-eks.asciidoc
> +
```suggestion
```

2022-02-03 10:47 UTC, albertdb commented on documentation/aws/setup-aws-account-iam-for-eks.asciidoc
> +
```suggestion

NOTE: Required policies for EKS usage are located at `/scripts/accounts/aws/eks-managed-policies.txt` and `/scripts/accounts/aws/eks-custom-policies.json`

```

2022-02-03 10:47 UTC, albertdb commented on scripts/accounts/aws/create-user.sh
> +    custom_policies_arn=$(aws iam create-policy --policy-name "${custom_policies%.*}" --policy-document "file://${custom_policies}" --query 'Policy.[Arn]' --output text)
Could you give an example (here in the conversation) of generated name for the policy?

2022-02-03 10:47 UTC, albertdb commented on documentation/aws/setup-aws-account-iam-for-eks.asciidoc
> +verify-account-policies.sh -u <username> [-p <policies...>] [-f <policies file path>] [-c <custom policies file path>] [-a "<AWS access key>"] [-s "<AWS secret key>"] [-r <region>]
```suggestion
verify-account-policies.sh \
  -u <username> \
  [-p <policies...>] \
  [-f <policies file path>] \
  [-c <custom policies file path>] \
  [-a <AWS access key>] \
  [-s <AWS secret key>] \
  [-r <region>] 
```

2022-02-03 10:47 UTC, albertdb commented on documentation/aws/setup-aws-account-iam-for-eks.asciidoc
> +./verify-account-policies.sh -u "Bob" -f "./eks-managed-policies.txt" -c "./eks-custom-policies.json"-a "myAccessKey" -s "mySecretKey" -r "eu-west-1"
```suggestion
./verify-account-policies.sh -u Bob -f ./eks-managed-policies.txt -c ./eks-custom-policies.json-a "myAccessKey" -s "mySecretKey" -r eu-west-1
```

2022-02-03 11:00 UTC, mcerverc commented on scripts/accounts/aws/create-user.sh
> +    custom_policies_arn=$(aws iam create-policy --policy-name "${custom_policies%.*}" --policy-document "file://${custom_policies}" --query 'Policy.[Arn]' --output text)
The policy name is the policy filename without the extension. 
For example: 
File->eks-custom-policies.json
Policy name->eks-custom-policies

2022-02-03 13:41 UTC, albertdb submitted a review, later dismissed

2022-02-03 13:46 UTC, albertdb commented on documentation/aws/setup-aws-account-iam-for-eks.asciidoc
> +NOTE: Required policies for EKS usage are located at `/scripts/accounts/aws/eks-managed-policies.txt` and `/scripts/accounts/aws/eks-custom-policies.json`
```suggestion
NOTE: Required policies for using EKS are located at `/scripts/accounts/aws/eks-managed-policies.txt` and `/scripts/accounts/aws/eks-custom-policies.json`
```

2022-02-03 13:46 UTC, albertdb commented on documentation/aws/setup-aws-account-iam-for-eks.asciidoc
> +NOTE: Required policies for EKS usage are located at `/scripts/accounts/aws/eks-managed-policies.txt` and `/scripts/accounts/aws/eks-custom-policies.json`
```suggestion
NOTE: Required policies for using EKS are located at `/scripts/accounts/aws/eks-managed-policies.txt` and `/scripts/accounts/aws/eks-custom-policies.json`
```

2022-02-03 13:47 UTC, albertdb submitted a review, later dismissed

2022-02-03 14:24 UTC, jbellver99 submitted a review, later dismissed

2022-02-03 15:35 UTC, albertdb commented on documentation/aws/setup-aws-account-iam-for-eks.asciidoc
> +eks:*
```suggestion
```

2022-02-03 15:35 UTC, albertdb commented on documentation/aws/setup-aws-account-iam-for-eks.asciidoc
>  In case you do not have an account or permission to create new IAM users, request it to your AWS administrator asking for the following policies attached. Then go to <<configure-cli>>.
```suggestion
In case you do not have an account or permission to create new IAM users, request it to your AWS administrator asking for the following policies being attached. Then go to <<check-iam-user-permissions>>.

=== Required managed policies
```

2022-02-03 15:35 UTC, albertdb commented on documentation/aws/setup-aws-account-iam-for-eks.asciidoc
> +== Check user permissions
```suggestion
== Check IAM user permissions
```

2022-02-03 15:35 UTC, albertdb commented on documentation/aws/setup-aws-account-iam-for-eks.asciidoc
> +The script located at `/scripts/accounts/aws/verify-account-policies.sh` will check that policies were correctly attached to the user.
```suggestion
The script located at `/scripts/accounts/aws/verify-account-policies.sh` will check that the necessary policies were attached to the IAM user.
```

2022-02-03 15:35 UTC, albertdb commented on documentation/aws/setup-aws-account-iam-for-eks.asciidoc
```suggestion

=== Required custom policies

Find them on `/scripts/accounts/aws/eks-custom-policies.json`.

```

2022-02-03 15:35 UTC, albertdb commented on scripts/accounts/aws/eks-custom-policies.json
> +                "eks:*"
```suggestion
                "eks:*",
                "iam:AddRoleToInstanceProfile",
                "iam:AttachRolePolicy",
                "iam:CreateInstanceProfile",
                "iam:CreateOpenIDConnectProvider",
                "iam:CreateServiceLinkedRole",
                "iam:CreatePolicy",
                "iam:CreatePolicyVersion",
                "iam:CreateRole",
                "iam:DeleteInstanceProfile",
                "iam:DeleteOpenIDConnectProvider",
                "iam:DeletePolicy",
                "iam:DeletePolicyVersion",
                "iam:DeleteRole",
                "iam:DeleteRolePolicy",
                "iam:DeleteServiceLinkedRole",
                "iam:DetachRolePolicy",
                "iam:GetInstanceProfile",
                "iam:GetOpenIDConnectProvider",
                "iam:GetPolicy",
                "iam:GetPolicyVersion",
                "iam:GetRole",
                "iam:GetRolePolicy",
                "iam:List*",
                "iam:PassRole",
                "iam:PutRolePolicy",
                "iam:RemoveRoleFromInstanceProfile",
                "iam:TagOpenIDConnectProvider",
                "iam:TagRole",
                "iam:UntagRole",
                "iam:TagPolicy",
                "iam:TagInstanceProfile",
                "iam:UpdateAssumeRolePolicy"
```

2022-02-03 15:56 UTC, albertdb commented on documentation/aws/setup-aws-account-iam-for-eks.asciidoc
```suggestion

=== Alternative

```

2022-02-03 15:56 UTC, albertdb commented on documentation/aws/setup-aws-account-iam-for-eks.asciidoc
> +=== Required managed policies
```suggestion
==== Required managed policies
```

2022-02-03 15:56 UTC, albertdb commented on documentation/aws/setup-aws-account-iam-for-eks.asciidoc
> +=== Required custom policies
```suggestion
==== Required custom policies
```

2022-02-04 10:54 UTC, albertdb approved these changes

2022-02-04 10:54 UTC, merged