Feature/201 automatic setup qa engine in google cloud
devonfw/hangar pull request #341
Opened 2022-11-09 14:12 UTC by Jorge-Dacal

Closes #201

2022-11-09 14:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw/hangar?pullRequest=341) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/devonfw/hangar?pullRequest=341) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw/hangar?pullRequest=341) it.</sub>

2022-11-09 16:03 UTC, albertdb requested changes
Good overall. I will send suggestions ASAP. Blocking meanwhile.

2022-11-11 08:22 UTC, Jorge-Dacal commented on scripts/sonarqube/gcloud/set-terraform-variables.sh
> +../../set-config.sh --file_set_vars $file $*
This scripts call another second script and Sonatype is asking us to enclose with quotation marks the argument that will pass from first script to the second all the arguments with which it has been invoked. If we add this quotation which would make only one input argument, generating a bug in the second script.

2022-11-11 08:25 UTC, Jorge-Dacal commented on scripts/sonarqube/gcloud/set-terraform-variables.sh
> +../../set-config.sh --file_set_vars $file $*
Solved all but not the same four that are in the first comment, that are repeated here.

These four scripts call another second script and Sonatype is asking us to enclose with quotation marks the argument that will pass from first script to the second all the arguments with which it has been invoked. If we add this quotation which would make only one input argument, generating a bug in the second script.

2022-11-11 08:52 UTC, Jorge-Dacal commented on scripts/sonarqube/gcloud/set-terraform-variables.sh
> +../../set-config.sh --file_set_vars $file $*
@sonatype-lift ignoreall

2022-11-11 08:52 UTC, Jorge-Dacal commented on scripts/sonarqube/gcloud/set-terraform-variables.sh
> +../../set-config.sh --file_set_vars $file $*
@sonatype-lift ignoreall

2022-11-17 11:44 UTC, Jorge-Dacal commented on scripts/sonarqube/common/create_token.sh
> +green='\e[1;32m'
fixed

2022-11-17 11:44 UTC, Jorge-Dacal commented on scripts/sonarqube/common/create_token.sh
> +    setToken=$(curl -sS -H "Content-Type: application/x-www-form-urlencoded" -d "name=$tokenName" -u $user:$password $sonarUrl/api/user_tokens/generate)
fixed

2022-11-17 11:44 UTC, Jorge-Dacal commented on scripts/sonarqube/common/create_token.sh
> +    echo -e "${red}Error: Missing paramenters, -s or --sonar-url is mandatory." >&2
fixed

2022-11-17 11:45 UTC, Jorge-Dacal commented on scripts/sonarqube/common/create_token.sh
> +    if [[ ! -z "$sq_token_output" ]]; then
fixed

2022-11-17 14:06 UTC, Jorge-Dacal commented on scripts/sonarqube/common/create_token.sh
> +    health=$(curl -sS --retry 30 --max-time 10 --retry-connrefused -u $user:$password $sonarUrl/api/system/health)
fixed

2022-11-18 09:06 UTC, ultymatom submitted a review, later dismissed

2022-11-21 10:38 UTC, lpinon submitted a review, later dismissed
Working fine! Only issue needs to be inside the sonar folder in order to work.

2022-11-24 10:09 UTC, Jorge-Dacal commented on scripts/tf.sh
> +while [[ -n "${@}" ]]; do
changed the while condition to
while [[ $# -gt 0 ]]; do

2022-11-24 11:54 UTC, lpinon approved these changes

2022-11-24 15:40 UTC, ultymatom submitted a review, later dismissed

2022-11-25 08:50 UTC, Jorge-Dacal commented on scripts/tf.sh
> +    echo "                  If you want to recover only one output value add an option `--output-key \$key` where \$key is the name of the output var."
removed the $ to avoid this issue

2022-11-25 08:53 UTC, Jorge-Dacal commented on scripts/tf.sh
> +    echo "                  If you want to recover only one output value add an option `--output-key \$key` where \$key is the name of the output var."
remove $ to avoid this issue

2022-11-25 08:54 UTC, Jorge-Dacal commented on scripts/tf.sh
> +    echo "  output        Show output values from your terraform. With output command only one flag is readed `--output-key` or `-k`, all other flags are ignored."
changed `` for '' to avoid this issue

2022-11-25 08:55 UTC, Jorge-Dacal commented on scripts/tf.sh
> +    echo "  output        Show output values from your terraform. With output command only one flag is readed `--output-key` or `-k`, all other flags are ignored."
changed `` for '' to avoid this issue

2022-11-29 13:20 UTC, lpinon approved these changes

2022-11-30 09:52 UTC, ultymatom approved these changes

2022-11-30 13:14 UTC, lpinon approved these changes

2022-12-15 12:16 UTC, albertdb commented on .vscode/settings.json
> +{
Remove this file

2022-12-15 12:28 UTC, Jorge-Dacal commented on .vscode/settings.json
> +{
removed

2022-12-15 15:10 UTC, albertdb commented on documentation/src/common_templates/setup-sonarqube-instance.asciidoc
> +After having deployed sonarqube by following this guide, you will be able to access SonarQube web interface on the url provided by terraform output and the following credentials:
```suggestion
After a few minutes, you will be able to access SonarQube web interface on the public URL provided by Terraform output with the following credentials:
```

2022-12-15 15:12 UTC, albertdb commented on documentation/src/common_templates/setup-sonarqube-instance.asciidoc
> +```
```suggestion
IMPORTANT: Change the default password promptly. After that, update the password in Terraform configuration: `./set-terraform-variables.sh --sonarqube_password <new password>`.
```

2022-12-15 15:12 UTC, albertdb commented on documentation/src/common_templates/setup-sonarqube-instance.asciidoc
> +== Appendix: More information about terraform for {provider_name}
```suggestion
== Appendix: More information about Terraform for {provider_name}
```

2022-12-15 15:16 UTC, albertdb commented on documentation/src/gcloud/setup-sonarqube-instance.asciidoc
> +* Enable Compute Engine in your gcloud project. You can do it via webconsole or via glcoud cli using the following command:
```suggestion
* Enable Compute Engine in your Google Cloud project. You can do it via Web Console or with the following command:
```

2022-12-15 15:18 UTC, albertdb commented on documentation/src/gcloud/setup-sonarqube-instance.asciidoc
> +* Have a service account that is going to be used by terraform with the next roles:
```suggestion
* Have the `key.json` file of a service account with (at least) the following roles:
```

2022-12-15 15:18 UTC, albertdb commented on documentation/src/gcloud/setup-sonarqube-instance.asciidoc
> +IMPORTANT: You need the key.json file of that service account to run terraform as it.
```suggestion
```

2022-12-15 15:24 UTC, albertdb commented on documentation/src/gcloud/setup-sonarqube-instance.asciidoc
> +-- instance_type                     Machine Instance type. By dafeault: e2-medium
```suggestion
:terraform_vars: --service_account_file    [Required] JSON file of a service account with required roles. + \
--project                 [Required] Short name (ID) of the project. + \
--region                             Region where the resources will be created. Default: europe-southwest1 + \
--zone                               Zone inside the region where the resources will be created. Default: europe-southwest1-a + \
--subnet_cidr_block                  Range of internal addresses that are owned by this subnetwork. Ranges must be unique and non-overlapping within a network. Default: 10.0.1.0/29 + \
-- instance_type                     Machine Instance type. Default: e2-medium
```

2022-12-15 15:27 UTC, albertdb commented on documentation/src/common_templates/setup-sonarqube-instance.asciidoc
> +{extra_information}
```suggestion
* {extra_information}
```

2022-12-15 15:29 UTC, albertdb commented on documentation/src/aws/setup-sonarqube-instance.asciidoc
> +--keypair_name         Keypair name to connect with ssh as defined in AWS. By default: sonarqube
```suggestion
:terraform_vars: --region               Region where the resources will be created. Default: eu-west-1 + \
--vpc_cidr_block       Virtual private network IP range (CIDR). Default: 10.0.0.0/16 + \
--subnet_cidr_block    Range of internal addresses that are owned by this subnetwork. Ranges must be unique and non-overlapping within a network. Default: 10.0.1.0/24 + \
--nic_private_ip       Instance private IP within subnet range.  Default: 10.0.1.50 + \
--instance_type        Machine Instance type. Default: t3a.small + \
--keypair_name         Keypair name to connect with SSH as defined in AWS. Default: sonarqube
```

2022-12-15 15:53 UTC, Jorge-Dacal commented on scripts/tf.sh
> +#! /bin/bash
renamed

2022-12-15 16:01 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-principal-account.sh
> +        if ! gcloud iam service-accounts keys create "${key_path}" --iam-account="$service_account_email" &> /dev/null;
it's ok

2022-12-15 16:36 UTC, Jorge-Dacal commented on scripts/accounts/azure-devops/create-project.sh
> +   echo -e "${white}" >&2
```suggestion
   echo -ne "${white}" >&2
```

2022-12-15 17:04 UTC, albertdb approved these changes

2022-12-15 17:41 UTC, abcarcol requested changes

2022-12-15 17:41 UTC, abcarcol commented on .gitignore
> +**/.secrets/**
Is this file part of the PR?

2022-12-16 08:27 UTC, albertdb commented on .gitignore
> +**/.secrets/**
I don't see why not.

2022-12-16 08:31 UTC, lpinon approved these changes

2022-12-16 09:09 UTC, abcarcol approved these changes

2022-12-16 09:13 UTC, merged