feature/block8: Quality pipeline
devonfw/hangar pull request #35
Opened 2022-01-24 15:59 UTC by jbellver99

Added quality pipeline documentation, modified pipeline_generator.sh, modified build pipeline documentation and added config files.

2022-02-01 08:16 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/quality/quarkus-quality.sh
> +url=<sonarqube-url>
@sonatype-lift help

2022-02-01 08:26 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/quality/quarkus-quality.sh
> +url=<sonarqube-url>
@sonatype-lift ignore

2022-02-01 08:27 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/quality/quarkus-quality.sh
> +url=<sonarqube-url>
@sonatype-lift ignore

2022-02-04 10:06 UTC, albertdb requested changes

2022-02-10 15:32 UTC, merged