Feature/sp4 346 automate firebase resources creation
devonfw/hangar pull request #362
Opened 2022-11-15 13:04 UTC by lpinon

2022-11-21 12:24 UTC, lpinon commented
gcloud services enable apikeys.googleapis.com --project "$projectName"
gcloud alpha services api-keys create --project "$projectName" --display-name apikeymaps"$projectName"

2022-11-21 12:38 UTC, lpinon commented
firebase apps:android:sha:list --project $projectName $appId
firebase apps:android:sha:create <appId> <shaHash>

2022-11-23 08:35 UTC, mcerverc commented on documentation/src/firebase/setup-firebase.asciidoc
> +  ./setup-firebase.sh -n <project name> -o /output
Is --enable-maps flag missing here?
```suggestion
  ./setup-firebase.sh -n <project name> -o /output --enable-maps
```

2022-11-23 08:35 UTC, mcerverc commented on scripts/accounts/gcloud/create-project.sh
> +   echo -e "${red}Error: Cloud Resource Manager"
```suggestion
   echo -e "${red}Error: Cannot enable Cloud Resource Manager"
```

2022-11-23 08:35 UTC, mcerverc commented on scripts/accounts/gcloud/setup-firebase.sh
> +FLAGS=$(getopt -a --options n:r:o:h --long "help,project-name:,firestore-region:,output:,enable-maps,setup-ios,setup-android,setup-web" -- "$@")
Delete here project-name or add to the switch case and to the docs

2022-11-23 08:35 UTC, mcerverc commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -e "${red}Error while enabling api keys api." >&2
```suggestion
            echo -e "${red}Error while enabling API keys API." >&2
```

2022-11-23 08:42 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +FLAGS=$(getopt -a --options n:r:o:h --long "help,project-name:,firestore-region:,output:,enable-maps,setup-ios,setup-android,setup-web" -- "$@")
```suggestion
FLAGS=$(getopt -a --options n:r:o:h --long "help,output:,enable-maps,setup-ios,setup-android,setup-web" -- "$@")
```

2022-11-23 08:52 UTC, mcerverc approved these changes

2022-11-23 12:19 UTC, Jorge-Dacal submitted a review, later dismissed

2022-11-23 13:07 UTC, albertdb requested changes

2022-11-23 13:32 UTC, albertdb requested changes

2022-11-23 13:32 UTC, albertdb commented on scripts/accounts/gcloud/setup-firebase.sh
> +   echo "Enables Firebase on a project and required APIs"
```suggestion
   echo "Enables Firebase and required APIs on a Google Cloud project."
```

2022-11-23 13:32 UTC, albertdb commented on scripts/accounts/gcloud/setup-firebase.sh
> +   echo -e "\t--setup-web                     Enables Web APIs and creates Web App"
```suggestion
   echo -e "\t-o, --output         [Required] Output path to store credentials."
   echo -e "\t-r                              Region where to create Firestore Database."
   echo -e "\t--enable-maps                   Enables APIs related to Maps services."
   echo -e "\t--setup-ios                     Enables IOS APIs and creates IOS App."
   echo -e "\t--setup-android                 Enables Android APIs and creates Android App."
   echo -e "\t--setup-web                     Enables Web APIs and creates Web App."
```

2022-11-23 13:32 UTC, albertdb commented on scripts/accounts/gcloud/setup-firebase.sh
> +        exit 128
```suggestion
        exit 127
```

2022-11-23 13:32 UTC, albertdb commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -e "Firebase already added to $projectName"
```suggestion
        echo -e "Firebase already added to $projectName."
```

2022-11-23 16:07 UTC, lpinon commented on documentation/firebase/setup-firebase.asciidoc
> +== Creating repository using provided script
```suggestion
== Setting up Firebase Services using the provided script
```

2022-11-23 16:08 UTC, lpinon commented on documentation/firebase/setup-firebase.asciidoc
> +The script located at `/scripts/accounts/gcloud/setup-firebase.sh` allows you to either:
```suggestion
The script located at `/scripts/accounts/gcloud/setup-firebase.sh` allows you to:
```

2022-11-23 17:05 UTC, albertdb commented on documentation/firebase/setup-firebase.asciidoc
> +== Setting up Firebase Services using the provided script
```suggestion
== Setting up Firebase services using the provided script
```

2022-11-23 17:34 UTC, capf4bbo submitted a review, later dismissed

2022-11-24 10:38 UTC, Jorge-Dacal requested changes
Todo es basicamente el mismo fallo:

Los errores deben redirigirse a >&2.

Una vez estés redirigiendo a >&2 el color rojo, debes modificar a blanco en >&2 también.
echo -ne "${white}" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/create-project.sh
> +   echo -e "${red}Error: Cannot enable Cloud Resource Manager API"
Los errores deben mandarse a >&2

echo -e "${red}Error: Cannot enable Cloud Resource Manager API" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/create-project.sh
> +   echo -ne "${white}"
Una vez estés redirigiendo a >&2 el color rojo, debes modificar a blanco en >&2 también

echo -ne "${white}" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/create-project.sh
> +   echo -e "${red}Error: Cannot enable IAM Control API"
Los errores deben mandarse a >&2

echo -e "${red}Error: Cannot enable Cloud Resource Manager API" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/create-project.sh
> +   echo -ne "${white}"
Una vez estés redirigiendo a >&2 el color rojo, debes modificar a blanco en >&2 también

echo -ne "${white}" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
Si estás redirigiendo a >&2 el color rojo, debes modificar a blanco en >&2 también.

echo -ne "${white}" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
Si estás redirigiendo a >&2 el color rojo, debes modificar a blanco en >&2 también.

echo -ne "${white}" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
Si estás redirigiendo a >&2 el color rojo, debes modificar a blanco en >&2 también.

echo -ne "${white}" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
Si estás redirigiendo a >&2 el color rojo, debes modificar a blanco en >&2 también.

echo -ne "${white}" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
Si estás redirigiendo a >&2 el color rojo, debes modificar a blanco en >&2 también.

echo -ne "${white}" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -e "${red}Error: Project $projectName does not exist."
Los errores deben mandarse a >&2

echo -e "${red}Error: Project $projectName does not exist." >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
Una vez estés redirigiendo a >&2 el color rojo, debes modificar a blanco en >&2 también.

echo -ne "${white}" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -e "${red}Error: Cannot enable Firebase API"
Los errores deben mandarse a >&2

echo -e "${red}Error: Cannot enable Firebase API" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
Una vez estés redirigiendo a >&2 el color rojo, debes modificar a blanco en >&2 también.

echo -ne "${white}" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -e "${red}Error: Cannot enable Firestore API"
Los errores deben mandarse a >&2

echo -e "${red}Error: Cannot enable Firebase API" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
Una vez estés redirigiendo a >&2 el color rojo, debes modificar a blanco en >&2 también.

echo -ne "${white}" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -e "${red}Error: Cannot enable API keys"
Los errores deben mandarse a >&2

echo -e "${red}Error: Cannot enable API keys" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
Una vez estés redirigiendo a >&2 el color rojo, debes modificar a blanco en >&2 también.

echo -ne "${white}" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -e "${red}Error: Cannot enable Geocoding Backend API"
Los errores deben mandarse a >&2

echo -e "${red}Error: Cannot enable Geocoding Backend API" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
Una vez estés redirigiendo a >&2 el color rojo, debes modificar a blanco en >&2 también.

echo -ne "${white}" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -e "${red}Error: Cannot enable Maps Android Backend API"
Los errores deben mandarse a >&2

echo -e "${red}Error: Cannot enable Maps Android Backend API" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -e "${red}Error: Cannot enable Maps IOS Backend API"
Los errores deben mandarse a >&2

echo -e "${red}Error: Cannot enable Maps IOS Backend API" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -ne "${white}"
Una vez estés redirigiendo a >&2 el color rojo, debes modificar a blanco en >&2 también.

echo -ne "${white}" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -e "${red}Error: Cannot enable Maps Backend API"
Los errores deben mandarse a >&2

echo -e "${red}Error: Cannot enable Maps Backend API" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -ne "${white}"
Una vez estés redirigiendo a >&2 el color rojo, debes modificar a blanco en >&2 también.

echo -ne "${white}" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -e "${red}Error: Cannot enable Static Maps Backend API"
Los errores deben mandarse a >&2

echo -e "${red}Error: Cannot enable Static Maps Backend API" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
Una vez estés redirigiendo a >&2 el color rojo, debes modificar a blanco en >&2 también.

echo -ne "${white}" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -e "${red}Error: Cannot add Firebase to project."
Los errores deben mandarse a >&2

echo -e "${red}Error: Cannot add Firebase to project." >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -ne "${white}"
Una vez estés redirigiendo a >&2 el color rojo, debes modificar a blanco en >&2 también.

echo -ne "${white}" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -e "${red}Error: Cannot Create Firestore Database"
Los errores deben mandarse a >&2

echo -e "${red}Error: Cannot Create Firestore Database" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
Una vez estés redirigiendo a >&2 el color rojo, debes modificar a blanco en >&2 también.

echo -ne "${white}" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -e "${red}Error: Cannot create Firebase Service Account"
Los errores deben mandarse a >&2

echo -e "${red}Error: Cannot create Firebase Service Account" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
Una vez estés redirigiendo a >&2 el color rojo, debes modificar a blanco en >&2 también.

echo -ne "${white}" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -e "${red}Error: Cannot add SHA1 key."
Los errores deben mandarse a >&2

echo -e "${red}Error: Cannot add SHA1 key." >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
Una vez estés redirigiendo a >&2 el color rojo, debes modificar a blanco en >&2 también.

echo -ne "${white}" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -e "${red}Error: Cannot add SHA256 key."
Los errores deben mandarse a >&2

echo -e "${red}Error: Cannot add SHA256 key." >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
Una vez estés redirigiendo a >&2 el color rojo, debes modificar a blanco en >&2 también.

echo -ne "${white}" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -ne "${white}"
Si estás redirigiendo a >&2 el color rojo, debes modificar a blanco en >&2 también.

echo -ne "${white}" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -ne "${white}"
Si estás redirigiendo a >&2 el color rojo, debes modificar a blanco en >&2 también.

echo -ne "${white}" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -ne "${white}"
Si estás redirigiendo a >&2 el color rojo, debes modificar a blanco en >&2 también.

echo -ne "${white}" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -ne "${white}"
Si estás redirigiendo a >&2 el color rojo, debes modificar a blanco en >&2 también.

echo -ne "${white}" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -ne "${white}"
Si estás redirigiendo a >&2 el color rojo, debes modificar a blanco en >&2 también.

echo -ne "${white}" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -ne "${white}"
Si estás redirigiendo a >&2 el color rojo, debes modificar a blanco en >&2 también.

echo -ne "${white}" >&2

2022-11-24 10:38 UTC, Jorge-Dacal commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -ne "${white}"
Si estás redirigiendo a >&2 el color rojo, debes modificar a blanco en >&2 también.

echo -ne "${white}" >&2

2022-11-24 11:33 UTC, lpinon commented on scripts/accounts/gcloud/create-project.sh
> +   echo -ne "${white}"
```suggestion
   echo -ne "${white}" >&2
```

2022-11-24 11:33 UTC, lpinon commented on scripts/accounts/gcloud/create-project.sh
> +   echo -e "${red}Error: Cannot enable IAM Control API"
```suggestion
   echo -e "${red}Error: Cannot enable IAM Control API" >&2
```

2022-11-24 11:33 UTC, lpinon commented on scripts/accounts/gcloud/create-project.sh
> +   echo -ne "${white}"
```suggestion
   echo -ne "${white}" >&2
```

2022-11-24 11:34 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
```suggestion
        echo -ne "${white}" >&2
```

2022-11-24 11:34 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -ne "${white}"
```suggestion
            echo -ne "${white}" >&2
```

2022-11-24 11:34 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -ne "${white}"
```suggestion
            echo -ne "${white}" >&2
```

2022-11-24 11:35 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -ne "${white}"
```suggestion
            echo -ne "${white}" >&2
```

2022-11-24 11:35 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -ne "${white}"
```suggestion
            echo -ne "${white}" >&2
```

2022-11-24 11:35 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -ne "${white}"
```suggestion
            echo -ne "${white}" >&2
```

2022-11-24 11:36 UTC, lpinon commented on scripts/accounts/gcloud/create-project.sh
> +   echo -e "${red}Error: Cannot enable Cloud Resource Manager API"
```suggestion
   echo -e "${red}Error: Cannot enable Cloud Resource Manager API"  >&2
```

2022-11-24 11:37 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
```suggestion
        echo -ne "${white}" >&2
```

2022-11-24 11:38 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
```suggestion
        echo -ne "${white}" >&2
```

2022-11-24 11:39 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
```suggestion
        echo -ne "${white}" >&2
```

2022-11-24 11:40 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
```suggestion
        echo -ne "${white}" >&2
```

2022-11-24 11:41 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -e "${red}Error: Project $projectName does not exist."
```suggestion
        echo -e "${red}Error: Project $projectName does not exist." >&2
```

2022-11-24 11:41 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
```suggestion
        echo -ne "${white}" >&2
```

2022-11-24 11:41 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -e "${red}Error: Cannot enable Firebase API"
```suggestion
        echo -e "${red}Error: Cannot enable Firebase API" >&2
```

2022-11-24 11:44 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
```suggestion
        echo -ne "${white}" >&2
```

2022-11-24 11:44 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -e "${red}Error: Cannot enable Firestore API"
```suggestion
        echo -e "${red}Error: Cannot enable Firestore API" >&2
```

2022-11-24 11:44 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
```suggestion
        echo -ne "${white}" >&2
```

2022-11-24 11:44 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -e "${red}Error: Cannot enable API keys"
```suggestion
        echo -e "${red}Error: Cannot enable API keys" >&2
```

2022-11-24 11:44 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
```suggestion
        echo -ne "${white}" >&2
```

2022-11-24 11:44 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -e "${red}Error: Cannot enable Geocoding Backend API"
```suggestion
        echo -e "${red}Error: Cannot enable Geocoding Backend API" >&2
```

2022-11-24 11:45 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
```suggestion
        echo -ne "${white}" >&2
```

2022-11-24 11:45 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -e "${red}Error: Cannot enable Maps Android Backend API"
```suggestion
            echo -e "${red}Error: Cannot enable Maps Android Backend API" >&2
```

2022-11-24 11:45 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -ne "${white}"
```suggestion
            echo -ne "${white}" >&2
```

2022-11-24 11:45 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -e "${red}Error: Cannot enable Maps IOS Backend API"
```suggestion
            echo -e "${red}Error: Cannot enable Maps IOS Backend API" >&2
```

2022-11-24 11:45 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -ne "${white}"
```suggestion
            echo -ne "${white}" >&2
```

2022-11-24 11:45 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -e "${red}Error: Cannot enable Maps Backend API"
```suggestion
            echo -e "${red}Error: Cannot enable Maps Backend API" >&2
```

2022-11-24 11:45 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -ne "${white}"
```suggestion
            echo -ne "${white}" >&2
```

2022-11-24 11:45 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -e "${red}Error: Cannot enable Static Maps Backend API"
```suggestion
        echo -e "${red}Error: Cannot enable Static Maps Backend API" >&2
```

2022-11-24 11:46 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
```suggestion
        echo -ne "${white}" >&2
```

2022-11-24 11:46 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -e "${red}Error: Cannot add Firebase to project."
```suggestion
            echo -e "${red}Error: Cannot add Firebase to project." >&2
```

2022-11-24 11:46 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -ne "${white}"
```suggestion
            echo -ne "${white}" >&2
```

2022-11-24 11:46 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -e "${red}Error: Cannot Create Firestore Database"
```suggestion
        echo -e "${red}Error: Cannot Create Firestore Database" >&2
```

2022-11-24 11:46 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
```suggestion
        echo -ne "${white}" >&2
```

2022-11-24 11:46 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -e "${red}Error: Cannot create Firebase Service Account"
```suggestion
        echo -e "${red}Error: Cannot create Firebase Service Account" >&2
```

2022-11-24 11:46 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
```suggestion
        echo -ne "${white}" >&2
```

2022-11-24 11:47 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -e "${red}Error: Cannot add SHA1 key."
```suggestion
        echo -e "${red}Error: Cannot add SHA1 key." >&2
```

2022-11-24 11:47 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
```suggestion
        echo -ne "${white}" >&2
```

2022-11-24 11:47 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -e "${red}Error: Cannot add SHA256 key."
```suggestion
        echo -e "${red}Error: Cannot add SHA256 key." >&2
```

2022-11-24 11:47 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +        echo -ne "${white}"
```suggestion
        echo -ne "${white}" >&2
```

2022-11-24 11:47 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -ne "${white}"
```suggestion
            echo -ne "${white}" >&2
```

2022-11-24 11:47 UTC, lpinon commented on scripts/accounts/gcloud/setup-firebase.sh
> +            echo -ne "${white}"
```suggestion
            echo -ne "${white}" >&2
```

2022-11-24 11:49 UTC, capf4bbo submitted a review, later dismissed

2022-11-25 06:56 UTC, Jorge-Dacal approved these changes

2022-11-25 09:12 UTC, Jorge-Dacal submitted a review, later dismissed

2022-11-25 09:20 UTC, albertdb requested changes
Although it is not part of this PR, you half fixed the echos in create-project, please, fix the rest of them (or don't fix any and create new issue)

2022-11-25 10:25 UTC, albertdb approved these changes

2022-11-25 10:30 UTC, capf4bbo approved these changes

2022-11-25 10:31 UTC, merged