Feature/block9 Package pipeline
devonfw/hangar pull request #37
Opened 2022-02-07 15:36 UTC by ultymatom

2022-02-21 09:08 UTC, jbellver99 reviewed
Use the new pipeline_generator.sh script in the PR feature/block27_aks and modify the config file to add the necessary functions so it works with this new script.
Take into account that in the new pipeline_generator.sh script all the flags required for the package pipeline are already defined.

2022-02-21 09:08 UTC, jbellver99 commented on documentation/setup-package-pipeline.asciidoc
> +-w               Open the Pull Request on the web browser if it cannot be automatically merged. Requires -b flag.
```suggestion
-c, --config-file                      [Required] Configuration file containing pipeline definition.
-n, --pipeline-name               [Required] Name that will be set to the pipeline.
-l, --language                        [Required] Language or framework of the project.
-i, --image-name                   [Required] Name that will be given to the Docker image (It must contain the name of the registry and the name or path of the repository inside the registry).
-u, --user                               [Required] User to connect to your container registry.
-p, --password                       [Required] Password of the user to connect to your container registry.
      --build-pipeline-name     [Required] Build pipeline name.
-d, --local-directory               [Required] Local directory of your project (the path should always be using '/' and not '\').
-a, --artifact-path                                     Path to be persisted as an artifact after pipeline execution e.g. where the application stores logs or any other blob on runtime.
-b, --target-branch                                   Name of the branch to which the Pull Request will target. PR is not created if the flag is not provided.
-w                                                              Open the Pull Request on the web browser if it cannot be automatically merged. Requires -b flag.

```

2022-02-21 09:08 UTC, jbellver99 commented on documentation/setup-package-pipeline.asciidoc
> +-w               Open the Pull Request on the web browser if it cannot be automatically merged. Requires -b flag.
Check if the tabulations added are correct. It is a little bit difficult to do it through github :)

2022-02-21 09:08 UTC, jbellver99 commented on documentation/setup-package-pipeline.asciidoc
> +./pipeline_generator.sh -c ./templates/build/build-config.cfg -n quarkus-project-build -l quarkus -d C:/Users/$USERNAME/Desktop/quarkus-project -i docker.io/user/image_name -a username -p password  -
```suggestion
./pipeline_generator.sh -c ./templates/package/package-config.cfg -n quarkus-project-package -l quarkus -d C:/Users/$USERNAME/Desktop/quarkus-project -i docker.io/user/image_name -u username -p password  -b develop -w

```

2022-02-21 09:08 UTC, jbellver99 commented on scripts/pipelines/azure-devops/pipeline_generator.sh.old
> +#!/bin/bash
No need to have this file, remove it from PR.

2022-02-21 09:08 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/package/package-config.cfg
> +mandatoryFlags="$imageName,$dockerUser,$dockerPassword,$buildPipelineName,$language"
Check the variable names with and make them the same as in the script.

2022-02-21 09:08 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/package/package-pipeline.yml
> +stages:
No need to use stages or jobs, make the yaml file look similar to the other ones in the project.

2022-02-23 08:25 UTC, jbellver99 requested changes

2022-02-23 08:25 UTC, jbellver99 commented on documentation/setup-package-pipeline.asciidoc
> +  [-w]
```suggestion
pipeline_generator.sh \
  -c, --config-file <config file path> \
  -n, --pipeline-name <pipeline name> \
  -l, --language <language or framework> \
      --dockerfile <path to dockerfile> \
  -d, --local-directory <project local path> \
  -i, --image-name <image name> \
  -u, --user <user>
  -p, --password <password>
      --build-pipeline-name <build pipeline name> \
      --quality-pipeline-name <quality pipeline name> \
  [-b, --target-branch <branch>] \
  [-w]
```

2022-02-23 08:25 UTC, jbellver99 commented on documentation/setup-package-pipeline.asciidoc
> +-w                                  Open the Pull Request on the web browser if it cannot be automatically merged. Requires -b flag.
```suggestion
-c, --config-file              [Required] Configuration file containing pipeline definition.
-n, --pipeline-name            [Required] Name that will be set to the pipeline.
-l, --language                 [Required, if dockerfile not set] Language or framework of the project.
    --dockerfile               [Required, if language not set] Path to the Dockerfile, replace the one set with the language if both flags are given.
-d, --local-directory          [Required] Local directory of your project (the path should always be using '/' and not '\').
-i, --image-name               [Required] Name that will be given to the Docker image (It must contain the name of the registry and the name or path of the repository inside the registry).
-u, --user                     [Required] User that will be used to connect to the registry.
-p, --password                 [Required] Password that will be used to connect to the registry.
    --build-pipeline-name      [Required] Build pipeline name.
    --quality-pipeline-name    [Required] Quality pipeline name.
-b, --target-branch                       Name of the branch to which the Pull Request will target. PR is not created if the flag is not provided.
-w                                        Open the Pull Request on the web browser if it cannot be automatically merged. Requires -b flag.
```

2022-02-23 08:25 UTC, jbellver99 commented on documentation/setup-package-pipeline.asciidoc
> +./pipeline_generator.sh -c ./templates/package/package-config.cfg -n package-pipeline -l quarkus -d C:/path/to/project/quarkus-project -i docker.io/user/quarkus-project -u username -p password --buil
```suggestion
./pipeline_generator.sh -c ./templates/package/package-config.cfg -n quarkus-project-package -l quarkus -d C:/Users/$USERNAME/Desktop/quarkus-project -i docker.io/username/quarkus-project -u username -p password --build-pipeline-name quarkus-project-build --quality-pipeline-name quarkus-project-name  -b develop -w

```

2022-02-23 08:25 UTC, jbellver99 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +FLAGS=$(getopt -a --options c:n:d:a:b:l:i:u:p: --long "config-file:,pipeline-name:,local-directory:,artifact-path:,target-branch:,language:,build-pipeline-name:,sonar-url:,sonar-token:,image-name:,us
```suggestion
FLAGS=$(getopt -a --options c:n:d:a:b:l:i:u:p: --long "config-file:,pipeline-name:,local-directory:,artifact-path:,target-branch:,language:,build-pipeline-name:,sonar-url:,sonar-token:,image-name:,user:,password:,resource-group:,storage-account:,storage-container:,cluster-name:,s3-bucket:,s3-key-path:,quality-pipeline-name:,dockerfile:" -- "$@")

```

2022-02-23 08:25 UTC, jbellver99 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --) shift; break;;
```suggestion
        -c | --config-file)       configFile=$2; shift 2;;
        -n | --pipeline-name)     pipelineName=$2; shift 2;;
        -d | --local-directory)   localDirectory=$2; shift 2;;
        -a | --artifact-path)     artifactPath=$2; shift 2;;
        -b | --target-branch)     targetBranch=$2; shift 2;;
        -l | --language)          language=$2; shift 2;;
        --build-pipeline-name)    buildPipelineName=$2; shift 2;;
        --sonar-url)              sonarUrl=$2; shift 2;;
        --sonar-token)            sonarToken=$2; shift 2;;
        -i | --image-name)        imageName=$2; shift 2;;
        -u | --user)              dockerUser=$2; shift 2;;
        -p | --password)          dockerPassword=$2; shift 2;;
        --resource-group)         resourceGroupName=$2; shift 2;;
        --storage-account)        storageAccountName=$2; shift 2;;
        --storage-container)      storageContainerName=$2; shift 2;;
        --cluster-name)           clusterName=$2; shift 2;;
        --s3-bucket)              s3Bucket=$2; shift 2;;
        --s3-key-path)            s3KeyPath=$2; shift 2;;
        --quality-pipeline-name)  qualityPipeline=$2; shift 2;;
        --dockerfile)             dockerFile=$2; shift 2;;
        --) shift; break;;
```

2022-02-23 08:25 UTC, jbellver99 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    echo "  -l, --language              [Required] Language or framework of the project."
```suggestion
```

2022-02-23 08:25 UTC, jbellver99 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    echo "      --dockerFile            [Required, if language not set] Language or framework of the project."
```suggestion
    echo "      --dockerfile            [Required, if language not set] Path to the Dockerfile, replace the one set with the language if both flags are given."

```

2022-02-23 08:25 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/package/CheckPipelineExec.sh
> +# Init var
Add the shebang #!/bin/bash at the beginning of the script.

2022-02-23 08:25 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/package/CheckPipelineExec.sh
> +# Init var
Add comments on the script in order to let other people know what the script is doing.

2022-02-23 08:25 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/package/package-config.cfg
> +    az pipelines variable create --name "qualityPipeline" --pipeline-name $pipelineName --value $qualityPipeline
Check the script, it looks like it is setting all this commands inside "".

2022-02-23 08:25 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/package/package-pipeline.yml
> +      displayName: 'Getting the last execution of the Build pipeline to download the right artefact'
```suggestion
      displayName: 'Getting the last execution of the Build pipeline to download the right artifact'

```

2022-02-23 08:25 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/package/package.sh
> +while getopts f:c:u:p:r:i:b:t: flag
Add comments on the script.

2022-02-23 08:25 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/package/package.sh
> +		t) pomPath=${OPTARG};;
```suggestion
        f) dockerFile=${OPTARG};;
        c) context=${OPTARG};;
        u) username=${OPTARG};;
        p) password=${OPTARG};;
	r) registry=${OPTARG};;
        i) imageName=${OPTARG};;
        b) branch=${OPTARG};;
	t) pomPath=${OPTARG};;
```

2022-02-28 08:42 UTC, jbellver99 requested changes

2022-02-28 08:42 UTC, jbellver99 commented on documentation/azure-devops/setup-package-pipeline.asciidoc
> +  [-w]
```suggestion
pipeline_generator.sh \
  -c <config file path> \
  -n <pipeline name> \
  -l <language or framework> \
  --dockerfile <dockerfile path> \
  -d <project local path> \
  -i <image name>
  -u <user>
  -p <password>
  --build-pipeline-name <build pipeline name>
  --quality-pipeline-name <quality pipeline name>
  [-b, --target-branch <branch>] \
  [-w]

```

2022-02-28 08:42 UTC, jbellver99 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +
```suggestion
```

2022-02-28 08:42 UTC, jbellver99 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    cd ${localDirectory}
```suggestion
    cd "${localDirectory}"

```

2022-02-28 08:42 UTC, jbellver99 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    cp ${hangarPath}/${templatesPath}/${yamlFile} ${localDirectory}/${pipelinePath}/${yamlFile}
```suggestion
    cp "${hangarPath}/${templatesPath}/${yamlFile}" "${localDirectory}/${pipelinePath}/${yamlFile}"

```

2022-02-28 08:42 UTC, jbellver99 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    sed -i "s/<@quality-pipeline-name@>/${qualityPipelineName}/g" ${localDirectory}/${pipelinePath}/${yamlFile}
```suggestion
    sed -i "s/<@build-pipeline-name@>/${buildPipelineName}/g" "${localDirectory}/${pipelinePath}/${yamlFile}"
    sed -i "s/<@test-pipeline-name@>/${testPipelineName}/g" "${localDirectory}/${pipelinePath}/${yamlFile}"
    sed -i "s/<@quality-pipeline-name@>/${qualityPipelineName}/g" "${localDirectory}/${pipelinePath}/${yamlFile}"

```

2022-02-28 14:55 UTC, jbellver99 requested changes

2022-02-28 14:55 UTC, jbellver99 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    mkdir -p ${localDirectory}/.pipelines/scripts
```suggestion
    mkdir -p "${localDirectory}/.pipelines/scripts"

```

2022-03-15 15:13 UTC, jbellver99 requested changes

2022-03-17 12:01 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/common/CheckPipelineExec.sh
> +pipelineList=$(az pipelines runs list --pipeline-ids $id --top $number_lst)
help

2022-03-21 15:42 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/common/CheckPipelineExec.sh
> +pipelineList=$(az pipelines runs list --pipeline-ids $id --top $number_lst)
@ultymatom https://help.sonatype.com/lift/talking-to-lift

2022-03-22 16:34 UTC, albertdb requested changes
Partial review (everything but package pipeline part)

2022-03-22 16:34 UTC, albertdb commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    echo "AKS pipeline flags:"
```suggestion
    echo "Azure AKS provisioning pipeline flags:"
```

2022-03-22 16:34 UTC, albertdb commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    echo "      --s3-key-path           [Required] Path of the S3 bucket where the tfstate file of the cluster will be stored."
```suggestion
    echo "AWS EKS provisioning pipeline flags:"
    echo "      --cluster-name          [Required] Name for the cluster."
    echo "      --s3-bucket             [Required] Name of the S3 bucket where the Terraform state of the cluster will be stored."
    echo "      --s3-key-path           [Required] Path within the S3 bucket where the Terraform state of the cluster will be stored."

```

2022-03-22 16:34 UTC, albertdb commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    sed -i "s/<@quality-pipeline-name@>/${qualityPipelineName}/g" "${localDirectory}/${pipelinePath}/${yamlFile}"
Export variables and use envsubst (single `envsubst < file > file` command) instead of sed. You will need to change placeholders to bash variable notation `${var}` on all pipeline yamls

2022-03-22 16:34 UTC, albertdb commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    if test ! -z $resourceGroupName || test ! -z $clusterName
Seems like a dirty hack. If later the resource group or cluster name is used by some other pipeline it will break.

2022-03-22 16:34 UTC, albertdb commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    find .pipelines -type f -exec git update-index --chmod=+x {} \;
Too greedy. At least find only `.sh` files

2022-03-23 11:00 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/package/package-pipeline.yml
> +    source: '<@quality-pipeline-name@>'
This will be affected by the `envsubst` change.

BTW, can't you use pipeline variable?

2022-03-23 11:52 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/quality/quality-pipeline.yml
>    displayName: "Download Artifact"
```suggestion
  displayName: "Download Build pipeline artifact"
```

2022-03-23 14:45 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/common/check-pipeline-exec.sh
> +number_lst=100
You mean the limit of 100 ?
I put that value in an arbitrary way, but I think we should still put limit to not go to far, becasue if after 2 years of existence all the execution of the pipeline will be really long as the list will just grow and grow

2022-03-23 14:50 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/quality/quality-pipeline.cfg
> +    sed -i "s/<sonarqube-token>/$sonarToken/g" "${localDirectory}/${scriptFilePath}/${scriptFile}"
I will try it, but I am a bit afraid of it having to change other var that should as they are in the pipeline

2022-03-23 14:56 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/package/package.sh
> +    case "${flag}" in
As this is not a script used directly by the user, there is no need

2022-03-23 14:57 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/package/package.sh
> +    l) region=${OPTARG};;
@sonatype-lift help

2022-03-23 14:59 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/test/test-pipeline.yml
>      - '*'
no because if no triggers section are given it considers that by default it is :
trigger:
branches:
include:
- '*'
As the triggers from another pipeline is defined in resource section it think as if no triggers are set, so it used the one by default

2022-03-23 17:02 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/common/check-pipeline-exec.sh
> +number_lst=100
I mean the case that the pipeline is not within the first `<number>` pipelines executions, but exists.

Not the end of the world, the depending pipelines could be relaunched, but...

2022-03-23 17:03 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/common/check-pipeline-exec.sh
> +# Getting the list of the last execution (the lenght of the list is defined by the value of $number_lst)
@ultymatom The review comment was intended to be here, I kept the above one unconsciously.

2022-03-23 17:27 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/common/check-pipeline-exec.sh
> +number_lst=100
I've put it at 5000, if you think that is enough you can resolve the comment if not we can decide what should it be

2022-03-24 09:47 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/common/check-pipeline-exec.sh
> +number_lst=100
Better filter also by branch https://docs.microsoft.com/es-es/cli/azure/pipelines/runs?view=azure-cli-latest#az-pipelines-runs-list and keep previous 100

2022-03-24 10:08 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/common/check-pipeline-exec.sh
> +number_lst=5000
```suggestion
pipelineToFind="$1"
sourceVersion="$2"
i=0
pipelineRunsListLimit=100
```

You should be consistent with naming convention used. Mixing is not good, as with spirit drinks :)

Rename references.

2022-03-24 11:47 UTC, ultymatom commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    envsubst '${buildPipelineName} ${testPipelineName} ${qualityPipelineName}' < "${localDirectory}/${pipelinePath}/${yamlFile}.template" > "${localDirectory}/${pipelinePath}/${yamlFile}"
That is normal, this is because in envsubst we need to use simple quote specially to not interpret them

2022-03-24 12:25 UTC, ultymatom commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    find .pipelines -type f -name *.sh -exec git update-index --chmod=+x {} \;
@sonatype-lift ignore

2022-03-24 12:27 UTC, ultymatom commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    find .pipelines -type f -name *.sh -exec git update-index --chmod=+x {} \;
I need to the * to be interpreted as a wildcard, if I put quote it won't

2022-03-24 12:27 UTC, ultymatom commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    find .pipelines -type f -name *.sh -exec git update-index --chmod=+x {} \;
@sonatype-lift ignore

2022-03-24 13:50 UTC, albertdb requested changes
Only guide is left for review.

2022-03-24 13:50 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/package/package-pipeline.yml.template
> +  displayName: 'Getting the last execution of the quality pipeline for the wanted commit'
```suggestion
  displayName: 'Checking last Quality pipeline execution status'
```

2022-03-24 13:50 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/package/package-pipeline.yml.template
> +- bash: 'echo "The quality pipeline executed for this commit has failed, we cannot package your application.";exit 1'
```suggestion
- bash: 'echo "The quality pipeline executed for this commit has failed.";exit 1'
```

2022-03-24 13:50 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/package/package-pipeline.yml.template
> +- bash: 'echo "The quality pipeline executed for this commit has been canceled, we cannot package your application.";exit 1'
```suggestion
- bash: 'echo "The quality pipeline executed for this commit has been canceled.";exit 1'
```

2022-03-24 13:50 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/package/package-pipeline.yml.template
> +- bash: 'echo "We could not find any execution of the quality pipeline with this commit, we cannot package your application.";exit 1'
```suggestion
- bash: 'echo "There is no quality pipeline execution for this commit.";exit 1'
```

2022-03-24 13:50 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/package/package-pipeline.yml.template
> +- bash: 'echo "The result of the quality pipeline is not over yet";exit 1'
```suggestion
- bash: 'echo "The quality pipeline for this commit is not over yet.";exit 1'
```

2022-03-24 13:50 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/package/package-pipeline.yml.template
> +  displayName: 'Getting the last execution of the Build pipeline to download the right artifact'
```suggestion
  displayName: 'Getting last Build pipeline execution to download artifact'
```

2022-03-24 13:50 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/package/package-pipeline.yml.template
> +  displayName: 'Download last artifact from build pipeline'
```suggestion
  displayName: 'Download Build pipeline artifact'
```

2022-03-24 13:50 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/package/package-pipeline.yml.template
> +  displayName: 'Build and Push the image to the registry (Default)'
```suggestion
  displayName: 'Build and push image to registry'
```

2022-03-24 13:50 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/package/package-pipeline.yml.template
> +  displayName: 'Build and Push the image to the registry (AWS)'
```suggestion
  displayName: 'Build and push image to registry (AWS)'
```

2022-03-24 13:50 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/package/package-pipeline.yml.template
> +    pipeline: $(BuildPipeline)
```suggestion
    pipeline: $(buildPipeline)
```

2022-03-24 13:50 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/package/package-pipeline.yml.template
> +    script: '$(Build.Repository.LocalPath)/.pipelines/scripts/check-pipeline-exec.sh $(BuildPipeline) $(Build.SourceVersion)'
```suggestion
    script: '$(Build.Repository.LocalPath)/.pipelines/scripts/check-pipeline-exec.sh $(buildPipeline) $(Build.SourceVersion)'
```

2022-03-24 14:27 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/package/package.sh
> +    echo "docker login -u=$username -p=$password $registry"
the password is not printed because it is a secret variable, the pipeline hides it

2022-03-24 14:39 UTC, albertdb requested changes
Last expected review.

2022-03-24 14:39 UTC, albertdb commented on documentation/azure-devops/setup-package-pipeline.asciidoc
> +
```suggestion
In this section we will create a package pipeline to build and push a container image of the project application into the specified container registry. This pipeline will be configured in order to be triggered every time quality pipeline is executed successfully on a commit for `release/*` and `develop` branches, requiring manual launch for other branches but still enforcing that quality pipeline has passed. It consumes the artifact produced by the build pipeline.
```

2022-03-24 14:39 UTC, albertdb commented on documentation/azure-devops/setup-package-pipeline.asciidoc
> +  [-b, --target-branch <branch>] \
```suggestion
  --build-pipeline-name <build pipeline name> \
  --quality-pipeline-name <quality pipeline name> \
  -i <image name> \
  [-u <registry user>] \
  [-p <registry password>] \
  [--aws-access-key <aws access key>] \
  [--aws-secret-access-key <aws secret access key>] \
  [--aws-region <aws region>] \
  [-b <branch>] \
```

Required flags go always first.

2022-03-24 14:39 UTC, albertdb commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    echo "      --quality-pipeline-name [Required] Quality pipeline name."
```suggestion
    echo "      --build-pipeline-name   [Required] Build pipeline name."
    echo "      --quality-pipeline-name [Required] Quality pipeline name."
    echo "  -i, --image-name            [Required] Name (excluding tag) for the generated container image."
```

2022-03-24 14:39 UTC, albertdb commented on documentation/azure-devops/setup-package-pipeline.asciidoc
> +    --aws-region               [Required if --aws-access-key is used] region for your AWS account."
```suggestion
    --dockerfile               [Required, if language not set] Path from the root of the project to its Dockerfile. Takes precedence over the language/framework default one.
-d, --local-directory          [Required] Local directory of your project (the path should always be using '/' and not '\').
    --build-pipeline-name      [Required] Build pipeline name.
    --quality-pipeline-name    [Required] Quality pipeline name.
-i, --image-name               [Required] Name (excluding tag) for the generated container image.
-u, --registry-user            [Required, unless AWS] Container registry login user.
-p, --registry-password        [Required, unless AWS] Container registry login password.
    --aws-access-key           [Required, if AWS] AWS account access key ID. Takes precedence over registry credentials."
    --aws-secret-access-key    [Required, if AWS] AWS account secret access key."
    --aws-region               [Required, if AWS] AWS region for ECR."
```

2022-03-24 14:39 UTC, albertdb commented on documentation/azure-devops/setup-package-pipeline.asciidoc
> +
```suggestion
./pipeline_generator.sh -c ./templates/package/package-pipeline.cfg -n quarkus-project-package -l quarkus -d C:/Users/$USERNAME/Desktop/quarkus-project --build-pipeline-name quarkus-project-build --quality-pipeline-name quarkus-project-quality -i docker.io/username/quarkus-project -u username -p password -b develop -w
```

Do we require to put `docker.io` for DockerHub images?

2022-03-24 14:41 UTC, ultymatom commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --resource-group)         resourceGroupName=$2; shift 2;;
used for AKS

2022-03-24 14:41 UTC, ultymatom commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --cluster-name)           clusterName=$2; shift 2;;
used for AKS

2022-03-24 14:49 UTC, ultymatom commented on documentation/azure-devops/setup-package-pipeline.asciidoc
> +
yes it is important because if we want to keep the script to be used for any registry we need to get the registry with the first part before /
And I did not find a way to check if the imagename is given with a registry or not.
And we talked about this ini one of the meeting, that we should get the registry from the image name and not giving it with another flag

2022-03-24 17:26 UTC, albertdb approved these changes

2022-03-24 17:56 UTC, albertdb submitted a review, later dismissed

2022-03-25 09:33 UTC, jbellver99 submitted a review, later dismissed

2022-03-25 10:54 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/package/package-pipeline.cfg
> +# Function that copies the terraform scripts into the directory.
```suggestion
```

2022-03-25 10:56 UTC, albertdb commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    rm "${localDirectory}/${scriptFilePath}/store-extra-path.yml"
Why?

2022-03-25 10:58 UTC, albertdb commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    rm "${localDirectory}/${scriptFilePath}/store-extra-path.yml"
```suggestion
    cp "${hangarPath}/${commonTemplatesPath}"/*.sh "${localDirectory}/${scriptFilePath}"
```

2022-03-25 14:11 UTC, jbellver99 approved these changes

2022-03-25 14:14 UTC, albertdb approved these changes

2022-03-25 14:14 UTC, merged