feature/package-library
devonfw/hangar pull request #38
Opened 2022-02-15 12:20 UTC by mcerverc

2022-02-21 08:28 UTC, jbellver99 reviewed
Pull the latest changes for the pipeline generator script and add the necessary functions inside the templates folder.

2022-02-21 08:28 UTC, jbellver99 commented on documentation/azure-devops/setup-library-package.asciidoc
> +IMPORTANT: The settings.xml file must be put in `.pipelines/scripts/` folder inside the Azure DevOps repo instead of the local .m2 folder.
Change this section in order to generate automatically the settings.xml (a PAT will be created automatically and used to generate the settings.xml).

2022-02-21 08:28 UTC, jbellver99 commented on documentation/azure-devops/setup-library-package.asciidoc
> +Follow the steps from the link:setup-quality-pipeline.asciidoc[Setup build pipeline section] to create the build pipeline. Use the config file located at `scripts/pipelines/azure-devops/templates/dep
Add the create a feed into the script in order to be generated automatically and leave the other sections inside a prerequisites section.

2022-02-21 08:28 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/library-deploy/deploy-config.cfg
> +yamlFile="deploy-pipeline.yml"
Change naming of branches,scripts,.. from deploy to library-deploy

2022-02-21 08:28 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/library-deploy/deploy-pipeline.yml
> +  targetPath: target
Not necessary

2022-02-21 08:32 UTC, jbellver99 commented on documentation/azure-devops/setup-library-package.asciidoc
> +Follow the steps from the link:setup-quality-pipeline.asciidoc[Setup build pipeline section] to create the build pipeline. Use the config file located at `scripts/pipelines/azure-devops/templates/dep
Check the link to the build pipeline section, you are taking the user to the quality pipeline section.

2022-02-25 09:09 UTC, albertdb commented on documentation/azure-devops/setup-library-package.asciidoc
> +Follow the steps from the link:setup-quality-pipeline.asciidoc[Setup build pipeline section] to create the build pipeline. Use the config file located at `scripts/pipelines/azure-devops/templates/dep
In fact, we should not link another guide, this guide should have the required content for creating the pipeline.

2022-02-25 09:55 UTC, albertdb requested changes
Live review done.

2022-02-28 09:02 UTC, jbellver99 requested changes

2022-03-15 14:55 UTC, jbellver99 commented on documentation/azure-devops/setup-library-package-pipeline.asciidoc
> +The script located at /scripts/pipelines/azure-devops/pipeline_generator.sh will automatically create this new branch, create a java library package pipeline based on a YAML template appropriate for
```suggestion
The script located at `/scripts/pipelines/azure-devops/pipeline_generator.sh` will automatically create this new branch, create a java library package pipeline based on a YAML template appropriate for the project programming language or framework, create the Pull Request, and if it is possible, merge this new branch into the specified branch.
```

2022-03-23 09:50 UTC, albertdb commented
Please resolve conflicts (you are modifying files that are not part of this block)

2022-03-23 09:50 UTC, albertdb commented
Please resolve conflicts (you are modifying files that are not part of this block)

2022-03-23 15:47 UTC, albertdb requested changes
Partial review. Guide pending.

2022-03-23 15:48 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/library-package/library-package-pipeline.cfg
> +    sed -e "s/\${feed}/$feed/" -e "s/\${organization}/$organization/" -e "s/\${pat}/$patToken/" settings-template.xml | tee "${localDirectory}/${scriptFilePath}/settings.xml"
Sync with Timothé regarding this.

2022-03-23 15:48 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/library-package/library-package-pipeline.yml
> +        filePath: '$(Build.Repository.LocalPath)/.pipelines/scripts/library-package.sh'
Yo will need the latest version of the pipeline generator (package pipeline) for this to work.

2022-03-23 16:52 UTC, albertdb requested changes

2022-03-23 16:52 UTC, albertdb commented on documentation/azure-devops/setup-library-package-pipeline.asciidoc
> +The script located at `/scripts/pipelines/azure-devops/pipeline_generator.sh` will automatically create this new branch, create a java library package pipeline based on a YAML template appropriate fo
```suggestion
The script located at `/scripts/pipelines/azure-devops/pipeline_generator.sh` will automatically create this new branch, create a Java library package pipeline based on a YAML template appropriate for Maven, create the Maven feed, create a PAT token with permission to push to that feed, create the Pull Request, and if it is possible, merge this new branch into the specified branch.
```

2022-03-23 16:52 UTC, albertdb commented on documentation/azure-devops/setup-library-package-pipeline.asciidoc
> +-l, --language                 [Required, if dockerfile not set] Language or framework of the project.
```suggestion
-l, --language                 [Required] Language or framework of the project.
```

2022-03-23 16:52 UTC, albertdb commented on documentation/azure-devops/setup-library-package-pipeline.asciidoc
> +./pipeline_generator.sh -c ./templates/library-package/library-package-pipeline.cfg -n library-package-pipeline -l java -d C:/projects/libraryrepo --build-pipeline-name library-build-pipeline --quali
```suggestion
./pipeline_generator.sh -c ./templates/library-package/library-package-pipeline.cfg -n library-package-pipeline -l java -d C:/Users/$USERNAME/Desktop/java-library-project --build-pipeline-name java-library-build --quality-pipeline-name java-library-quality
```

2022-03-23 16:52 UTC, albertdb commented on documentation/azure-devops/setup-library-package-pipeline.asciidoc
> +
```suggestion
```

Redundant.

2022-03-23 16:52 UTC, albertdb commented on documentation/azure-devops/setup-library-package-pipeline.asciidoc
> +Go to Azure Artifacts and click on the artifact that you want to install. Then copy the contents of the <dependency> element and paste it inside the <dependencies> element of your pom.xml file.
```suggestion
Go to Azure Artifacts and click on the artifact of the library. Then copy the contents of the <dependency> element and paste it inside the `<dependencies>` element of your `pom.xml` file.
```

2022-03-23 16:52 UTC, albertdb commented on documentation/azure-devops/setup-library-package-pipeline.asciidoc
> +Then, follow again the link:https://docs.microsoft.com/en-us/azure/devops/artifacts/maven/pom-and-settings?view=azure-devops[Set up the Maven client] guide to connect the main project to the maven fe
```suggestion
Then, follow again the link:https://docs.microsoft.com/en-us/azure/devops/artifacts/maven/pom-and-settings?view=azure-devops[Set up the Maven client] guide to connect the main project to the Maven feed to be able to consume the library.
```

2022-03-24 09:35 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/library-package/library-package-pipeline.cfg
> +    az rest --method post --uri "https://feeds.dev.azure.com/${organization}/_apis/packaging/feeds?api-version=7.1-preview.1" --resource "https://management.core.windows.net/" --body '{ "name": "'${f
That error message is on stdout or stderr?

2022-03-24 11:09 UTC, mcerverc commented on scripts/pipelines/azure-devops/templates/library-package/library-package-pipeline.cfg
> +    az rest --method post --uri "https://feeds.dev.azure.com/${organization}/_apis/packaging/feeds?api-version=7.1-preview.1" --resource "https://management.core.windows.net/" --body '{ "name": "'${f
Both error messages are stderr. Maybe is a good idea to substitute &>/dev/null by 1>/dev/null

2022-03-24 13:19 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/library-package/library-package-pipeline.cfg
> +    az rest --method post --uri "https://feeds.dev.azure.com/${organization}/_apis/packaging/feeds?api-version=7.1-preview.1" --resource "https://management.core.windows.net/" --body '{ "name": "'${f
Definitely.

2022-03-24 15:55 UTC, mcerverc commented on scripts/pipelines/azure-devops/templates/library-package/java-library-package.sh
> +mvn deploy --settings $settings_path
Done

2022-03-28 11:47 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/library-package/library-package-pipeline.cfg
> +    fi
```suggestion
```

This is managed in piepeline generator

2022-03-28 11:49 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/library-package/library-package-pipeline.cfg
> +    envsubst < settings-template.xml > "${localDirectory}/${scriptFilePath}/settings.xml"
You will need to rename patToken variable in xml in order to avoid exporting another variable.

2022-03-28 11:50 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/library-package/library-package-pipeline.yml.template
> +    script: '$(Build.Repository.LocalPath)/.pipelines/scripts/check-pipeline-exec.sh $(qualityPipeline) $(Build.SourceVersion)'
You are missing the branch.

2022-03-28 11:50 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/library-package/library-package-pipeline.yml.template
> +    script: '$(Build.Repository.LocalPath)/.pipelines/scripts/check-pipeline-exec.sh $(buildPipeline) $(Build.SourceVersion)'
You are missing the branch.

2022-03-29 08:03 UTC, albertdb commented
Please check that shell script uses Unix-style line ending (LF).

2022-03-29 09:02 UTC, albertdb approved these changes

2022-03-29 09:05 UTC, jbellver99 approved these changes

2022-03-29 09:07 UTC, merged