feature/block27_aks
devonfw/hangar pull request #39
Opened 2022-02-18 12:43 UTC by jbellver99

2022-03-15 12:29 UTC, jbellver99 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        -a | --artifact-path)   artifactPath=$2; shift 2;;
@sonatype-lift ignore

2022-03-15 12:30 UTC, jbellver99 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --build-pipeline-name)  buildPipelineName=$2; shift 2;;
@sonatype-lift ignore

2022-03-15 12:31 UTC, jbellver99 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        -p | --password)        password=$2; shift 2;;
@sonatype-lift ignore

2022-03-15 12:32 UTC, jbellver99 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --s3-bucket)            s3Bucket=$2; shift 2;;
@sonatype-lift ignore

2022-03-15 12:32 UTC, jbellver99 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --s3-key-path)          s3KeyPath=$2; shift 2;;
@sonatype-lift ignore

2022-03-15 12:33 UTC, jbellver99 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --storage-account)      storageAccountName=$2; shift 2;;
@sonatype-lift ignore

2022-03-15 12:33 UTC, jbellver99 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --storage-container)    storageContainerName=$2; shift 2;;
@sonatype-lift ignore

2022-03-15 12:34 UTC, jbellver99 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        -u | --user)            user=$2; shift 2;;
@sonatype-lift ignore

2022-03-15 12:35 UTC, jbellver99 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        -l | --language)        language=$2; shift 2;;
@sonatype-lift ignore

2022-04-01 07:09 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/aks/obtain-dns.sh
> +ip=$(kubectl get -o json svc nginx-stable-nginx-ingress --namespace nginx-ingress --kubeconfig $1/kubeconfig | python -c "import sys, json; print(json.load(sys.stdin)['status']['loadBalancer']['ingre
@sonatype-lift ignore

2022-04-01 07:09 UTC, jbellver99 commented on scripts/environment-provisioning/azure/aks/set-config.sh
> +/bin/sh ../../../set-config.sh $ARGS
@sonatype-lift ignore

2022-04-05 16:30 UTC, albertdb requested changes

2022-04-05 16:30 UTC, albertdb commented on documentation/azure-devops/setup-aks-provisioning-pipeline.asciidoc
> +In order to interact with your cluster download the artifact `kubeconfig` generated by the pipeline and execute the following command:
```suggestion
In order to interact with your cluster you will need to download the artifact `kubeconfig` generated by the cluster provisioning pipeline on the location it is expected by default (`~/.kube/config`) or either:
```

2022-04-05 16:30 UTC, albertdb commented on documentation/azure-devops/setup-aks-provisioning-pipeline.asciidoc
> +kubectl <kubectl command> --kubeconfig <path to downloaded kubeconfig>
```suggestion
# via environment variable (you can add this on your profile)
export KUBECONFIG=<path to downloaded kubeconfig>
kubectl <command>

# via command-line flag
kubectl <command> --kubeconfig=<path to downloaded kubeconfig>
```

2022-04-05 16:30 UTC, albertdb commented on scripts/environment-provisioning/azure/aks/main.tf
> +            source = "hashicorp/azurerm"
Please set version.

2022-04-05 16:30 UTC, albertdb commented on scripts/environment-provisioning/azure/aks/variables.tf
> +    description = "Number of nodes for the cluster"
```suggestion
    description = "Number of worker nodes for the cluster"
```

2022-04-05 16:30 UTC, albertdb commented on scripts/environment-provisioning/azure/aks/variables.tf
> +    description = "DNS name prefix to use with the hosted Kubernetes API server FQDN"
Could you please explain what it this? Not totally clear for me at least given the description.

2022-04-05 16:30 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/aks/aks-pipeline.cfg
> +    fi
```suggestion
```

Not needed anymore here.

2022-04-05 16:30 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/aks/aks-provisioning.yml.template
> +      helm install nginx-stable nginx-stable/nginx-ingress --set controller.setAsDefaultIngress=true --namespace nginx-ingress --create-namespace --kubeconfig $(terraformWorkingDirectory)/kubeconfig
This is using a deprecated helm chart. Please look at EKS yaml.

2022-04-05 16:30 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/aks/aks-provisioning.yml.template
> +    script: 'sleep 60'
Use proper wait.

2022-04-05 16:30 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/aks/obtain-dns.sh
> +dnsname=${url:22:length-22-1}
Maybe this could easily break?

2022-04-06 09:32 UTC, albertdb requested changes

2022-04-06 09:32 UTC, albertdb commented on documentation/azure-devops/setup-aks-provisioning-pipeline.asciidoc
> +./set-config.sh --cluster_name <cluster name> --location <location> --resource_group_name <resource group name> --instance_type <worker instance type> --worker_node_count <number of worker nodes> --d
```suggestion
./set-terraform-variables.sh --cluster_name <cluster name> --location <location> --resource_group_name <resource group name> --instance_type <worker instance type> --worker_node_count <number of worker nodes> --dns_prefix <dns prefix>
```

2022-04-06 09:53 UTC, jbellver99 commented on scripts/environment-provisioning/azure/aks/set-terraform-variables.sh
> +/bin/sh ../../../set-config.sh $*
@sonatype-lift ignore

2022-04-06 09:53 UTC, jbellver99 commented on scripts/environment-provisioning/azure/aks/set-terraform-variables.sh
> +/bin/sh ../../../set-config.sh $*
@sonatype-lift ignore

2022-04-19 07:07 UTC, jbellver99 commented on scripts/environment-provisioning/azure/aks/set-terraform-variables.sh
> +/bin/sh ../../../set-config.sh $*
@sonatype-lift ignore

2022-04-19 07:08 UTC, jbellver99 commented on scripts/environment-provisioning/azure/aks/set-terraform-variables.sh
> +/bin/sh ../../../set-config.sh $*
@sonatype-lift ignore

2022-04-19 07:08 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/aks/obtain-dns.sh
> +ip=$(kubectl get svc nginx-ingress-nginx-ingress-controller --namespace nginx-ingress --kubeconfig $1/kubeconfig -o jsonpath='{.status.loadBalancer.ingress[0].ip}' &> /dev/null)
@sonatype-lift ignore

2022-04-19 07:09 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/aks/obtain-dns.sh
> +    ip=$(kubectl get svc nginx-ingress-nginx-ingress-controller --namespace nginx-ingress --kubeconfig $1/kubeconfig -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
@sonatype-lift ignore

2022-04-19 07:09 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/aks/obtain-dns.sh
> +az network public-ip update --resource-group $iprg --name $ipname --dns-name $dnsname
@sonatype-lift ignore

2022-04-19 07:09 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/aks/obtain-dns.sh
> +az network public-ip update --resource-group $iprg --name $ipname --dns-name $dnsname
@sonatype-lift ignore

2022-04-19 07:09 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/aks/obtain-dns.sh
> +az network public-ip update --resource-group $iprg --name $ipname --dns-name $dnsname
@sonatype-lift ignore

2022-04-19 07:10 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/aks/obtain-dns.sh
> +dns=$(az network public-ip show --resource-group $iprg --name $ipname --query "[dnsSettings.fqdn]" --output tsv)
@sonatype-lift ignore

2022-04-28 12:03 UTC, albertdb requested changes

2022-04-28 12:03 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/aks/obtain-dns.sh
> +ip="$(kubectl get svc nginx-ingress-nginx-ingress-controller --namespace nginx-ingress --kubeconfig "$1"/kubeconfig -o jsonpath='{.status.loadBalancer.ingress[0].ip}')"
```suggestion
ip="$(kubectl get svc nginx-ingress-nginx-ingress-controller --namespace nginx-ingress --kubeconfig "$1/kubeconfig" -o jsonpath='{.status.loadBalancer.ingress[0].ip}')"
```

Although better pass KUBECONFIG env variable.

2022-04-28 12:03 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/aks/obtain-dns.sh
> +    ip="$(kubectl get svc nginx-ingress-nginx-ingress-controller --namespace nginx-ingress --kubeconfig "$1"/kubeconfig -o jsonpath='{.status.loadBalancer.ingress[0].ip}')"
```suggestion
    ip="$(kubectl get svc nginx-ingress-nginx-ingress-controller --namespace nginx-ingress --kubeconfig "$1/kubeconfig" -o jsonpath='{.status.loadBalancer.ingress[0].ip}')"
```

Although better pass KUBECONFIG env variable.

2022-06-09 09:28 UTC, albertdb requested changes
Add destroy option to pipeline, in sync with EKS.

2022-06-16 09:58 UTC, albertdb approved these changes

2022-06-16 10:08 UTC, merged