feature/setup-gcloud-service-accounts
devonfw/hangar pull request #394
Opened 2022-11-20 17:31 UTC by abcarcol

2022-11-21 08:23 UTC, abcarcol commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +    if [[ ! " ${service_accounts_array[*]} " =~ " ${service_account} " ]];
@sonatype-lift ignore

2022-11-21 08:23 UTC, abcarcol commented on scripts/accounts/gcloud/setup-principal-account.sh
> +    if [[ ! " ${service_accounts_array[*]} " =~ " ${service_account} " ]];
@sonatype-lift ignore

2022-11-21 08:24 UTC, abcarcol commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +    service_accounts_array=($service_accounts)
@sonatype-lift ignore

2022-11-21 08:24 UTC, abcarcol commented on scripts/accounts/gcloud/setup-principal-account.sh
> +    service_accounts_array=($service_accounts)
@sonatype-lift ignore

2022-11-21 08:28 UTC, abcarcol commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +    if [[ ! " ${service_accounts_array[*]} " =~ " ${service_account} " ]];
```suggestion
    if [[ ! " ${service_accounts_array[*]} " =~ " ${service_account} " ]]; # Searches right literal in left array. More info: https://stackoverflow.com/a/15394738
```

2022-11-21 08:28 UTC, abcarcol commented on scripts/accounts/gcloud/setup-principal-account.sh
> +    if [[ ! " ${service_accounts_array[*]} " =~ " ${service_account} " ]];
```suggestion
    if [[ ! " ${service_accounts_array[*]} " =~ " ${service_account} " ]]; # Searches right literal in left array. More info: https://stackoverflow.com/a/15394738
```

2022-11-21 08:31 UTC, abcarcol commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +    if [[ ! " ${service_accounts_array[*]} " =~ " ${service_account} " ]]; # Searches right literal in left array. More info: https://stackoverflow.com/a/15394738
@sonatype-lift ignore

2022-11-23 15:05 UTC, albertdb requested changes
I see this as a fix to overcome a limitation that worsens user experience, that now has to know the format of a service account email to create a new one.

We can ask for Service Account name **or* email. And if the value does not contain @ we assume it is a custom service account as before.

2022-11-25 12:18 UTC, albertdb requested changes

2022-11-25 12:18 UTC, albertdb commented on scripts/accounts/gcloud/setup-principal-account.sh
>          ? ) helpFunction ;; # Print helpFunction in case parameter is non-existent.
Please replace here and across all script tabs by spaces, keeping indentation consistent.

2022-11-25 12:18 UTC, albertdb commented on scripts/accounts/gcloud/setup-principal-account.sh
> +        if [[ ! " ${service_accounts_array[*]} " =~ " ${service_account} " ]];
Does this work when is the first or last element of the array?

2022-11-25 12:18 UTC, albertdb commented on scripts/accounts/gcloud/setup-principal-account.sh
> +        if [[ ! " ${service_accounts_array[*]} " =~ " $service_account_email " ]];
Does this work when is the first or last element of the array?

2022-11-25 12:18 UTC, albertdb commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +    echo "  -s     [Required] Service Account email. Mutually exclusive with -g."
Please accept both:

````
[[ "$serviceAccount" =~ .*"@".* ]] && service_account_email="$service_account@$project_id.iam.gserviceaccount.com" || service_account_email="$serviceAccount"
````

2022-11-25 12:18 UTC, albertdb commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +    echo -e "${white}Checking if service account $service_account already exists..."
Does `gcloud iam service-accounts describe` not work for google managed service accounts?

2022-11-25 12:55 UTC, abcarcol commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +    echo -e "${white}Checking if service account $service_account already exists..."
Oops I totally forgot to fix this script. Sorry!

2022-11-28 12:47 UTC, abcarcol commented on scripts/accounts/gcloud/setup-principal-account.sh
> +        if [[ ! " ${service_accounts_array[*]} " =~ " ${service_account} " ]];
Yes, it works but I do not understand why do you ask it. Please, elaborate a little on this.

2022-11-28 12:48 UTC, abcarcol commented on scripts/accounts/gcloud/setup-principal-account.sh
> +        if [[ ! " ${service_accounts_array[*]} " =~ " ${service_account} " ]];
@sonatype-lift ignore

2022-11-28 12:48 UTC, abcarcol commented on scripts/accounts/gcloud/setup-principal-account.sh
> +        if [[ ! " ${service_accounts_array[*]} " =~ " $service_account_email " ]];
Same as previous comment

2022-11-28 12:48 UTC, abcarcol commented on scripts/accounts/gcloud/setup-principal-account.sh
> +        if [[ ! " ${service_accounts_array[*]} " =~ " $service_account_email " ]];
@sonatype-lift ignore

2022-11-28 12:56 UTC, abcarcol commented on scripts/accounts/gcloud/setup-principal-account.sh
>          ? ) helpFunction ;; # Print helpFunction in case parameter is non-existent.
Done

2022-11-28 13:10 UTC, abcarcol commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +    echo "  -s     [Required] Service Account email. Mutually exclusive with -g."
I think you meant this:
```suggestion
    [[ "$serviceAccount" =~ .*"@".* ]] && service_account_email="$serviceAccount" || service_account_email="$service_account@$project_id.iam.gserviceaccount.com"  
```

2022-11-28 13:12 UTC, abcarcol commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +    echo "  -s     [Required] Service Account email. Mutually exclusive with -g."
I forgot about this script, now it is done.

2022-11-28 13:13 UTC, abcarcol commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +    echo -e "${white}Checking if service account $service_account already exists..."
Yes, it works for any kind of service account, the code was not changed. Now it is done.

2022-11-28 13:19 UTC, lpinon submitted a review, later dismissed

2022-11-29 14:14 UTC, abcarcol commented on scripts/accounts/gcloud/verify-principal-roles-and-permissions.sh
> +    if [[ ! " ${service_accounts_array[*]} " =~ " ${service_account_email} " ]]; # Searches right literal in left array. More info: https://stackoverflow.com/a/15394738
@sonatype-lift ignore

2022-11-29 14:22 UTC, albertdb requested changes
Fixed with suggestions one script. Please fix the other, it has the same issue.

2022-11-29 14:22 UTC, albertdb commented on scripts/accounts/gcloud/setup-principal-account.sh
> +    exit 2
```suggestion
        exit 2
```

2022-11-29 14:22 UTC, albertdb commented on scripts/accounts/gcloud/setup-principal-account.sh
> +        echo -ne "${white}"
```suggestion
        then
            echo -e "${red}Error: Attaching role $role_to_check to $memberValue for project $project_id." >&2
            echo -ne "${white}"
```

2022-11-29 14:22 UTC, albertdb commented on scripts/accounts/gcloud/setup-principal-account.sh
> +    fi
```suggestion
        else
            echo -e "${green}Attached role $role_to_check to $memberValue in project $project_id."
            echo -ne "${white}"
        fi
```

2022-11-29 14:22 UTC, albertdb commented on scripts/accounts/gcloud/setup-principal-account.sh
> +    else
```suggestion
        then
            echo -e "${red}Error: Attaching role $role_to_check to $memberValue in project $project_id." >&2
            echo -ne "${white}"
            exit 2
        else
```

2022-11-29 14:22 UTC, albertdb commented on scripts/accounts/gcloud/setup-principal-account.sh
> +    exit 2
```suggestion
        exit 2
```

2022-11-29 14:22 UTC, albertdb commented on scripts/accounts/gcloud/setup-principal-account.sh
> +    echo -ne "${white}"
```suggestion
        echo -e "${green}Created custom role $custom_role_id for project $project_id successfully."
        echo -ne "${white}"
```

2022-11-29 14:22 UTC, albertdb commented on scripts/accounts/gcloud/setup-principal-account.sh
> +    exit 2
```suggestion
        exit 2
```

2022-11-29 17:06 UTC, albertdb approved these changes

2022-11-29 17:12 UTC, merged