feature/block11 deploy pipeline EKS
devonfw/hangar pull request #40
Opened 2022-02-28 14:28 UTC by prathibhapadma

2022-03-02 10:54 UTC, jbellver99 requested changes
No need to add the files inside the k8smanifests, we are not supposed to give the user the yamls files for the deployment, this are supplied by the user.

2022-03-02 10:54 UTC, jbellver99 commented on documentation/aws/setup-deploy-pipeline-aws-eks.asciidoc
> +  --k8s-namespace <k8sNamespace> \
A flag like --deploy-files should be added so that the user can specify where the yamls for the deployment are located.

2022-03-02 10:54 UTC, jbellver99 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    echo ""
Add the necessary flags for the deployment pipeline in the help function.

2022-03-02 10:54 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/deploy/deploy-pipeline.yml
> +        inline: '{ "kind": "Namespace", "apiVersion": "v1", "metadata": { "name": "$(k8sNamespace)" }}'
Not needed.

2022-03-02 10:54 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/deploy/deploy-pipeline.yml
> +        dockerRegistryEndpoint: '$(container_reg_connection)'
No need to add so many options, it can be done like this:

- task: Kubernetes@1
  inputs:
    displayName: "kubectl apply"
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: '$(k8sServiceConnection)'
    command: 'apply'
    arguments: '-f $(deployFiles)'

2022-03-02 10:54 UTC, jbellver99 commented on documentation/aws/setup-deploy-pipeline-aws-eks.asciidoc
> +* Create a service connection to container registry to pull `Image` from registry (Name this service connection `Container-Reg-Connection`).
Not actually needed so it can de deleted.

2022-03-02 11:51 UTC, prathibhapadma commented
@jbellver99 most of the review comments I've got from Sandesh. I'm already working on those.

2022-03-07 05:13 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/deploy-pipeline.yml
> +        inline: '{ "kind": "Namespace", "apiVersion": "v1", "metadata": { "name": "$(k8sNamespace)" }}'
while deploying application in to kubernetes we need to maintain one specific namespace, we should not go with default.

2022-03-07 05:13 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/deploy-pipeline.yml
> +
done

2022-03-07 05:15 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/deploy-pipeline.yml
> +        dockerRegistryEndpoint: '$(container_reg_connection)'
we need container service connection to pull image.

2022-03-07 05:24 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/deploy-config.cfg
> +    az pipelines variable create --name "k8sNamespace" --pipeline-name $pipelineName --value ${k8sNamespace}
we need to create variables for k8s service connections to connect cluster for deployment, and container registry service connection to pull image.

2022-03-22 04:51 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --build-pipeline-name)       buildPipelineName=$2; shift 2;;
@sonatype-lift ignore

2022-03-22 04:51 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --deploy-files)              deployFiles=$2; shift 2;;
@sonatype-lift ignore

2022-03-22 04:51 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        -l | --language)             language=$2; shift 2;;
@sonatype-lift ignore

2022-03-22 04:51 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --package-pipeline-name)     packagePipelineName=$2; shift 2;;
@sonatype-lift ignore

2022-03-22 04:51 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        -p | --password)             password=$2; shift 2;;
@sonatype-lift ignore

2022-03-22 04:51 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --s3-bucket)                 s3Bucket=$2; shift 2;;
@sonatype-lift ignore

2022-03-22 04:51 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --s3-key-path)               s3KeyPath=$2; shift 2;;
@sonatype-lift ignore

2022-03-22 04:52 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --sonar-token)               sonarToken=$2; shift 2;;
@sonatype-lift ignore

2022-03-22 04:52 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --sonar-url)                 sonarUrl=$2; shift 2;;
@sonatype-lift ignore

2022-03-22 04:52 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --storage-account)           storageAccountName=$2; shift 2;;
@sonatype-lift ignore

2022-03-22 04:52 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --storage-container)         storageContainerName=$2; shift 2;;
@sonatype-lift ignore

2022-03-22 04:52 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        -u | --user)                 user=$2; shift 2;;
@sonatype-lift ignore

2022-03-22 04:52 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +yq e '.spec.template.spec.imagePullSecrets[0].name = "'$secrets'"' -i $(Build.Repository.LocalPath)/$(deployFiles)/*-deployment.yaml
@sonatype-lift ignore

2022-03-22 04:52 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/ecr-secrets.sh
> +export secrets=$(secretsName)
@sonatype-lift ignore

2022-03-22 04:53 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/ecr-secrets.sh
> +yq e '.spec.template.spec.imagePullSecrets[0].name = "'$secrets'"' -i $(Build.Repository.LocalPath)/$(deployFiles)/*-deployment.yaml
@sonatype-lift ignore

2022-03-22 04:53 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/ecr-secrets.sh
> +kubectl apply -f $(Build.Repository.LocalPath)/$(deployFiles)/*-deployment.yaml --namespace=$(k8sNamespace)
@sonatype-lift ignore

2022-03-28 11:21 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    [ $? != "0" ] && echo -e "${red}The local directory: '${localDirectory}' cannot be found, please check the path." && exit 1
@sonatype-lift ignore

2022-03-28 13:36 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    envsubst '${buildPipelineName} ${testPipelineName} ${qualityPipelineName} ${packagePipelineName}' < "${localDirectory}/${pipelinePath}/${yamlFile}.template" > "${localDirectory}/${pipelinePath}/$
@sonatype-lift ignore

2022-03-28 13:36 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --aws-access-key)         awsAccessKey="$2"; shift 2;;
@sonatype-lift ignore

2022-03-28 13:36 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --aws-region)             awsRegion="$2"; shift 2;;
@sonatype-lift ignore

2022-03-28 13:36 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --aws-secret-access-key)  awsSecretAccessKey="$2"; shift 2;;
@sonatype-lift ignore

2022-03-28 13:36 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        -p | --registry-password) dockerPassword=$2; shift 2;;
@sonatype-lift ignore

2022-03-28 13:36 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        -u | --registry-user)     dockerUser=$2; shift 2;;
@sonatype-lift ignore

2022-03-28 13:37 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --resource-group)         resourceGroupName=$2; shift 2;;
@sonatype-lift ignore

2022-03-30 14:04 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +# Apply manifest files.
@sonatype-lift ignore

2022-04-08 07:20 UTC, jbellver99 requested changes

2022-04-08 07:20 UTC, jbellver99 commented on documentation/azure-devops/setup-deploy-pipeline.asciidoc
> +The script located at `/scripts/pipelines/azure-devops/pipeline_generator.sh` will automatically create new branch,create a deploy pipeline based on a YAML template appropriate for the project manife
```suggestion
The script located at `/scripts/pipelines/azure-devops/pipeline_generator.sh` will automatically this create new branch, create a deploy pipeline based on a YAML template appropriate for the project manifests files, create the Pull Request, and if it is possible, merge this new branch into the specified branch.
```
```suggestion
The script located at `/scripts/pipelines/azure-devops/pipeline_generator.sh` will automatically create new branch,create a deploy pipeline based on a YAML template appropriate for the project manifests files, create the Pull Request, and if it is possible, merge this new branch into the specified branch.
```

2022-04-08 07:20 UTC, jbellver99 commented on documentation/azure-devops/setup-deploy-pipeline.asciidoc
> +./pipeline_generator.sh -c ./templates/deploy/deploy-pipeline.cfg -n quarkus-project-deploy -d C:/Users/$USERNAME/Desktop/quarkus-project --deploy-files manifest-path --deploy-cluster deploy-cluster-
```suggestion
./pipeline_generator.sh -c ./templates/deploy/deploy-pipeline.cfg -n quarkus-project-deploy -d C:/Users/$USERNAME/Desktop/quarkus-project --deploy-files k8s-files --deploy-cluster EKS --package-pipeline-name quarkus-project-package -b develop -w
```
```suggestion
./pipeline_generator.sh -c ./templates/deploy/deploy-pipeline.cfg -n quarkus-project-deploy -d C:/Users/$USERNAME/Desktop/quarkus-project --deploy-files manifest-path --deploy-cluster deploy-cluster-name --package-pipeline-name package-pipeline-name -b develop -w
```

2022-04-08 07:20 UTC, jbellver99 commented on documentation/azure-devops/setup-deploy-pipeline.asciidoc
> +./pipeline_generator.sh -c ./templates/deploy/deploy-pipeline.cfg -n quarkus-project-deploy -d C:/Users/$USERNAME/Desktop/quarkus-project --deploy-files manifest-path --deploy-cluster deploy-cluster-
```suggestion
./pipeline_generator.sh -c ./templates/deploy/deploy-pipeline.cfg -n quarkus-project-deploy -d C:/Users/$USERNAME/Desktop/quarkus-project --deploy-files k8s-files --deploy-cluster EKS --package-pipeline-name quarkus-project-package -b develop -w
```
```suggestion
./pipeline_generator.sh -c ./templates/deploy/deploy-pipeline.cfg -n quarkus-project-deploy -d C:/Users/$USERNAME/Desktop/quarkus-project --deploy-files manifest-path --deploy-cluster deploy-cluster-name --package-pipeline-name package-pipeline-name -b develop -w
```

2022-04-08 07:20 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/deploy/deploy-pipeline.cfg
> +k8sNamespace="hangar"
This two variables, should not be hardcoded, they should go as flags so that the user is able to specify them.

2022-04-08 07:20 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/deploy/deploy-pipeline.cfg
> +k8sNamespace="hangar"
This two variables, should not be hardcoded, they should go as flags so that the user is able to specify them.

2022-04-08 07:20 UTC, jbellver99 commented on documentation/azure-devops/setup-deploy-pipeline.asciidoc
> +    --deploy-cluster          [Required] Name of the kubernetes cluster, AKS or EKS.
Not exactly the name of the cluster but the environment, change the description of the flag.

2022-04-08 07:20 UTC, jbellver99 commented on documentation/azure-devops/setup-deploy-pipeline.asciidoc
> +    --deploy-cluster          [Required] Name of the kubernetes cluster, AKS or EKS.
Not exactly the name of the cluster but the environment, change the description of the flag.

2022-04-08 11:38 UTC, prathibhapadma commented on documentation/azure-devops/setup-deploy-pipeline.asciidoc
> +    --deploy-cluster          [Required] Name of the kubernetes cluster, AKS or EKS.
done

2022-04-08 11:39 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/deploy-pipeline.cfg
> +k8sNamespace="hangar"
Done, now user can pass both values as flags

2022-04-11 07:10 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --deploy-cluster)             deployCluster=$2; shift 2;;
@sonatype-lift ignore

2022-04-11 07:11 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        -a | --artifact-path)        artifactPath=$2; shift 2;;
@sonatype-lift ignore

2022-04-11 07:11 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --aks-provision-pipeline)    aksProvisionPipeline=$2; shift 2;;
@sonatype-lift ignore

2022-04-11 07:13 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +export secrets=$(secretsValue)
@sonatype-lift ignore

2022-04-11 07:13 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl apply -f $(Build.Repository.LocalPath)/$(deployFiles)/*-deployment.yaml --namespace=$(k8sNamespace) --kubeconfig $(Pipeline.Workspace)/kubeconfig/kubeconfig
@sonatype-lift ignore

2022-04-11 07:13 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --aks-provision-pipeline)    aksProvisionPipelineName=$2; shift 2;;
@sonatype-lift ignore

2022-04-11 07:13 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --k8s-namespace)             k8sNamespace=$2; shift 2;;
@sonatype-lift ignore

2022-04-11 07:13 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --secrets-value)             secretsValue=$2; shift 2;;
@sonatype-lift ignore

2022-04-11 07:19 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --secrets-name)             secretsName=$2; shift 2;;
@sonatype-lift ignore

2022-04-11 07:21 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --container-reg-connection)  container-reg-connection=$2; shift 2;;
@sonatype-lift ignore

2022-04-18 02:50 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --k8s-namespace)                k8sNamespace="$2"; shift 2;;
@sonatype-lift ignore

2022-04-18 02:50 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +kubectl apply -f $6 --namespace=$1
@sonatype-lift ignore

2022-04-18 02:50 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +kubectl apply -f $6 --namespace=$1
@sonatype-lift ignore

2022-04-18 02:50 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +kubectl create namespace $1
@sonatype-lift ignore

2022-04-18 02:50 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +yq eval '.spec.rules[0].host = "'$dns'"' -i $5
@sonatype-lift ignore

2022-04-18 02:51 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +yq eval '.spec.rules[0].host = "'$dns'"' -i $5
@sonatype-lift ignore

2022-04-18 02:51 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +yq eval '.spec.template.spec.containers[0].image = "'$image'"' -i $4
@sonatype-lift ignore

2022-04-18 02:51 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +yq eval '.spec.template.spec.containers[0].image = "'$image'"' -i $4
@sonatype-lift ignore

2022-04-18 02:51 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +# Apply manifest files.
@sonatype-lift ignore

2022-04-18 02:51 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +kubectl create namespace $6 --kubeconfig $7
@sonatype-lift ignore

2022-04-18 02:52 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +# Create namespace in AKS cluster.
@sonatype-lift ignore

2022-04-18 02:52 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +yq eval '.spec.rules[0].host = "'$dns'"' -i $4
@sonatype-lift ignore

2022-04-18 02:52 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +yq eval '.spec.template.spec.containers[0].image = "'$image'"' -i $3
@sonatype-lift ignore

2022-04-18 02:52 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +export image=$1 dns=$2
@sonatype-lift ignore

2022-04-18 02:52 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +# Add image name and ingress DNS name.
@sonatype-lift ignore

2022-04-18 02:52 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +#!/bin/bash
@sonatype-lift ignore

2022-04-18 02:53 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl apply -f $6 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-18 02:53 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl apply -f $6 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-18 02:53 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl apply -f $6 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-18 02:53 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +yq e '.spec.template.spec.imagePullSecrets[0].name = "'$secrets'"' -i $6
@sonatype-lift ignore

2022-04-18 02:53 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +yq e '.spec.template.spec.imagePullSecrets[0].name = "'$secrets'"' -i $6
@sonatype-lift ignore

2022-04-18 02:53 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +yq e '.spec.template.spec."imagePullSecrets"=[{"name":"secrets"}]' -i $6
@sonatype-lift ignore

2022-04-18 02:53 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl create secret docker-registry $2 --docker-server=$5 --docker-username=$3 --docker-password=$4 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-18 02:54 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl create secret docker-registry $2 --docker-server=$5 --docker-username=$3 --docker-password=$4 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-18 02:54 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl create secret docker-registry $2 --docker-server=$5 --docker-username=$3 --docker-password=$4 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-18 02:54 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl create secret docker-registry $2 --docker-server=$5 --docker-username=$3 --docker-password=$4 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-18 02:54 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl create secret docker-registry $2 --docker-server=$5 --docker-username=$3 --docker-password=$4 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-18 02:54 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl create secret docker-registry $2 --docker-server=$5 --docker-username=$3 --docker-password=$4 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-18 02:54 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl delete secret $2 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-18 02:54 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl delete secret $2 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-18 02:54 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl delete secret $2 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-18 02:54 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +kubectl apply -f $5 --namespace=$6 --kubeconfig $7
@sonatype-lift ignore

2022-04-18 02:54 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +kubectl apply -f $5 --namespace=$6 --kubeconfig $7
@sonatype-lift ignore

2022-04-18 02:54 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +kubectl apply -f $5 --namespace=$6 --kubeconfig $7
@sonatype-lift ignore

2022-04-18 02:55 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +kubectl create namespace $6 --kubeconfig $7
@sonatype-lift ignore

2022-04-18 02:55 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +kubectl create namespace $6 --kubeconfig $7
@sonatype-lift ignore

2022-04-18 02:55 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +yq eval '.spec.rules[0].host = "'$dns'"' -i $4
@sonatype-lift ignore

2022-04-18 02:55 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +yq eval '.spec.rules[0].host = "'$dns'"' -i $4
@sonatype-lift ignore

2022-04-18 02:55 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +yq eval '.spec.template.spec.containers[0].image = "'$image'"' -i $3
@sonatype-lift ignore

2022-04-18 02:55 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +yq eval '.spec.template.spec.containers[0].image = "'$image'"' -i $3
@sonatype-lift ignore

2022-04-18 02:59 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --container-reg-connection)  container-reg-connection=$2; shift 2;;
@sonatype-lift ignore

2022-04-18 03:00 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --aks-provision-pipeline)    aksProvisionPipeline=$2; shift 2;;
@sonatype-lift ignore

2022-04-18 03:00 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        -a | --artifact-path)        artifactPath=$2; shift 2;;
@sonatype-lift ignore

2022-04-21 05:06 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +yq eval '.spec.template.spec.containers[0].image = "'$image'"' -i $3
@sonatype-lift ignore

2022-04-21 05:06 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +yq eval '.spec.template.spec.containers[0].image = "'$image'"' -i $3
@sonatype-lift ignore

2022-04-21 05:06 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +yq eval '.spec.rules[0].host = "'$dns'"' -i $4
@sonatype-lift ignore

2022-04-26 05:26 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +yq eval '.spec.rules[0].host = "'$dns'"' -i $4
@sonatype-lift ignore

2022-04-26 05:27 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +kubectl create namespace $6 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:28 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +kubectl create namespace $6 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:28 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +kubectl apply -f $5 --namespace=$6 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:28 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +kubectl apply -f $5 --namespace=$6 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:29 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +kubectl apply -f $5 --namespace=$6 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:29 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl delete secret $2 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:29 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl delete secret $2 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:29 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl delete secret $2 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:29 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl create secret docker-registry $2 --docker-server=$5 --docker-username=$3 --docker-password=$4 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:29 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl create secret docker-registry $2 --docker-server=$5 --docker-username=$3 --docker-password=$4 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:30 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl create secret docker-registry $2 --docker-server=$5 --docker-username=$3 --docker-password=$4 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:30 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl create secret docker-registry $2 --docker-server=$5 --docker-username=$3 --docker-password=$4 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:30 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl create secret docker-registry $2 --docker-server=$5 --docker-username=$3 --docker-password=$4 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:30 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl create secret docker-registry $2 --docker-server=$5 --docker-username=$3 --docker-password=$4 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:31 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +yq e '.spec.template.spec."imagePullSecrets"=[{"name":"secrets"}]' -i $6
@sonatype-lift ignore

2022-04-26 05:31 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +yq e '.spec.template.spec.imagePullSecrets[0].name = "'$secrets'"' -i $6
@sonatype-lift ignore

2022-04-26 05:36 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +yq e '.spec.template.spec.imagePullSecrets[0].name = "'$secrets'"' -i $6
@sonatype-lift ignore

2022-04-26 05:36 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl apply -f $6 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:36 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl apply -f $6 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:36 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl apply -f $6 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:36 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +#!/bin/bash
@sonatype-lift ignore

2022-04-26 05:37 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +# Add image name and ingress DNS name.
@sonatype-lift ignore

2022-04-26 05:37 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +export image=$1 dns=$2
@sonatype-lift ignore

2022-04-26 05:39 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +yq eval '.spec.template.spec.containers[0].image = "'$image'"' -i $3
@sonatype-lift ignore

2022-04-26 05:39 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +yq eval '.spec.rules[0].host = "'$dns'"' -i $4
@sonatype-lift ignore

2022-04-26 05:39 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +# Create namespace in AKS cluster.
@sonatype-lift ignore

2022-04-26 05:40 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --k8s-namespace)                k8sNamespace="$2"; shift 2;;
@sonatype-lift ignore

2022-04-26 05:41 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +kubectl apply -f $6 --namespace=$1
@sonatype-lift ignore

2022-04-26 05:41 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +kubectl apply -f $6 --namespace=$1
@sonatype-lift ignore

2022-04-26 05:41 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +kubectl create namespace $1
@sonatype-lift ignore

2022-04-26 05:41 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +yq eval '.spec.rules[0].host = "'$dns'"' -i $5
@sonatype-lift ignore

2022-04-26 05:41 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +yq eval '.spec.rules[0].host = "'$dns'"' -i $5
@sonatype-lift ignore

2022-04-26 05:41 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +yq eval '.spec.template.spec.containers[0].image = "'$image'"' -i $4
@sonatype-lift ignore

2022-04-26 05:41 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +yq eval '.spec.template.spec.containers[0].image = "'$image'"' -i $4
@sonatype-lift ignore

2022-04-26 05:41 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +# Apply manifest files.
@sonatype-lift ignore

2022-04-26 05:41 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +kubectl create namespace $6 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:54 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --k8s-namespace)                k8sNamespace="$2"; shift 2;;
@sonatype-lift ignore

2022-04-26 05:54 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +kubectl create namespace $1
@sonatype-lift ignore

2022-04-26 05:54 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +yq eval '.spec.rules[0].host = "'$dns'"' -i $5
@sonatype-lift ignore

2022-04-26 05:54 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +yq eval '.spec.rules[0].host = "'$dns'"' -i $5
@sonatype-lift ignore

2022-04-26 05:54 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +yq eval '.spec.template.spec.containers[0].image = "'$image'"' -i $4
@sonatype-lift ignore

2022-04-26 05:54 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +yq eval '.spec.template.spec.containers[0].image = "'$image'"' -i $4
@sonatype-lift ignore

2022-04-26 05:54 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +kubectl apply -f $6 --namespace=$1
@sonatype-lift ignore

2022-04-26 05:54 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +kubectl apply -f $6 --namespace=$1
@sonatype-lift ignore

2022-04-26 05:55 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +# Apply manifest files.
@sonatype-lift ignore

2022-04-26 05:55 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +kubectl create namespace $6 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:55 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +# Create namespace in AKS cluster.
@sonatype-lift ignore

2022-04-26 05:55 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +yq eval '.spec.rules[0].host = "'$dns'"' -i $4
@sonatype-lift ignore

2022-04-26 05:55 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +yq eval '.spec.template.spec.containers[0].image = "'$image'"' -i $3
@sonatype-lift ignore

2022-04-26 05:55 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +export image=$1 dns=$2
@sonatype-lift ignore

2022-04-26 05:55 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +# Add image name and ingress DNS name.
@sonatype-lift ignore

2022-04-26 05:55 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +#!/bin/bash
@sonatype-lift ignore

2022-04-26 05:55 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl apply -f $6 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:56 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl apply -f $6 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:56 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl apply -f $6 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:56 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +yq e '.spec.template.spec.imagePullSecrets[0].name = "'$secrets'"' -i $6
@sonatype-lift ignore

2022-04-26 05:56 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +yq e '.spec.template.spec.imagePullSecrets[0].name = "'$secrets'"' -i $6
@sonatype-lift ignore

2022-04-26 05:56 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +yq e '.spec.template.spec."imagePullSecrets"=[{"name":"secrets"}]' -i $6
@sonatype-lift ignore

2022-04-26 05:56 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl create secret docker-registry $2 --docker-server=$5 --docker-username=$3 --docker-password=$4 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:56 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl create secret docker-registry $2 --docker-server=$5 --docker-username=$3 --docker-password=$4 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:56 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl create secret docker-registry $2 --docker-server=$5 --docker-username=$3 --docker-password=$4 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:56 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl create secret docker-registry $2 --docker-server=$5 --docker-username=$3 --docker-password=$4 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:56 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl create secret docker-registry $2 --docker-server=$5 --docker-username=$3 --docker-password=$4 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:57 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl create secret docker-registry $2 --docker-server=$5 --docker-username=$3 --docker-password=$4 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:57 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl delete secret $2 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:57 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl delete secret $2 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:57 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl delete secret $2 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:57 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +kubectl apply -f $5 --namespace=$6 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:57 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +kubectl apply -f $5 --namespace=$6 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:57 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +kubectl apply -f $5 --namespace=$6 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:57 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +kubectl create namespace $6 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:57 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +kubectl create namespace $6 --kubeconfig $7
@sonatype-lift ignore

2022-04-26 05:57 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +yq eval '.spec.rules[0].host = "'$dns'"' -i $4
@sonatype-lift ignore

2022-04-26 05:57 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +yq eval '.spec.rules[0].host = "'$dns'"' -i $4
@sonatype-lift ignore

2022-04-26 05:58 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +yq eval '.spec.template.spec.containers[0].image = "'$image'"' -i $3
@sonatype-lift ignore

2022-04-26 05:58 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +yq eval '.spec.template.spec.containers[0].image = "'$image'"' -i $3
@sonatype-lift ignore

2022-05-05 11:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw/hangar?pullRequest=40) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/devonfw/hangar?pullRequest=40) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw/hangar?pullRequest=40) it.</sub>

2022-05-05 13:12 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +# Add image name and ingress DNS name.
@sonatype-lift ignore

2022-05-05 13:12 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +yq eval '.spec.template.spec.containers[0].image = "'$image'"' -i $4
@sonatype-lift ignore

2022-05-05 13:12 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +yq eval '.spec.rules[0].host = "'$dns'"' -i $5
@sonatype-lift ignore

2022-05-05 13:13 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +# Create namespace in EKS cluster.
@sonatype-lift ignore

2022-05-05 13:13 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +#!/bin/bash
@sonatype-lift ignore

2022-05-05 13:13 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +export image=$2 dns=$3
@sonatype-lift ignore

2022-05-05 13:13 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +yq eval '.spec.template.spec.containers[0].image = "'$image'"' -i $4
@sonatype-lift ignore

2022-05-05 13:14 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +yq eval '.spec.rules[0].host = "'$dns'"' -i $5
@sonatype-lift ignore

2022-05-05 13:14 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +kubectl create namespace $1
@sonatype-lift ignore

2022-05-05 13:15 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +kubectl apply -f $6 --namespace=$1
@sonatype-lift ignore

2022-05-05 13:15 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/ecr-secrets.sh
> +kubectl create secret docker-registry $2 --docker-server=$5 --docker-username=$3 --docker-password=$4 --namespace=$1
@sonatype-lift ignore

2022-05-05 13:15 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/ecr-secrets.sh
> +kubectl create secret docker-registry $2 --docker-server=$5 --docker-username=$3 --docker-password=$4 --namespace=$1
@sonatype-lift ignore

2022-05-05 13:15 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/ecr-secrets.sh
> +yq e '.spec.template.spec."imagePullSecrets"=[{"name":"secrets"}]' -i $6
@sonatype-lift ignore

2022-05-05 13:15 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/ecr-secrets.sh
> +kubectl apply -f $6 --namespace=$1
@sonatype-lift ignore

2022-05-05 13:15 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +kubectl create namespace $1
@sonatype-lift ignore

2022-05-05 13:15 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +kubectl apply -f $6 --namespace=$1
@sonatype-lift ignore

2022-05-05 13:16 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/ecr-secrets.sh
> +kubectl delete secret $2 --namespace=$1
@sonatype-lift ignore

2022-05-05 13:16 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/ecr-secrets.sh
> +kubectl create secret docker-registry $2 --docker-server=$5 --docker-username=$3 --docker-password=$4 --namespace=$1
@sonatype-lift ignore

2022-05-05 13:16 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/ecr-secrets.sh
> +kubectl create secret docker-registry $2 --docker-server=$5 --docker-username=$3 --docker-password=$4 --namespace=$1
@sonatype-lift ignore

2022-05-05 13:16 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/ecr-secrets.sh
> +kubectl create secret docker-registry $2 --docker-server=$5 --docker-username=$3 --docker-password=$4 --namespace=$1
@sonatype-lift ignore

2022-05-05 13:16 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/ecr-secrets.sh
> +yq e '.spec.template.spec.imagePullSecrets[0].name = "'$secrets'"' -i $6
@sonatype-lift ignore

2022-05-05 13:16 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +#!/bin/bash
@sonatype-lift ignore

2022-05-05 13:16 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +export image=$1 dns=$2
@sonatype-lift ignore

2022-05-05 13:17 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +yq eval '.spec.template.spec.containers[0].image = "'$image'"' -i $3
@sonatype-lift ignore

2022-05-05 13:17 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +yq eval '.spec.rules[0].host = "'$dns'"' -i $4
@sonatype-lift ignore

2022-05-05 13:17 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +yq eval '.spec.rules[0].host = "'$dns'"' -i $4
@sonatype-lift ignore

2022-05-05 13:17 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +kubectl create namespace $6 --kubeconfig $7
@sonatype-lift ignore

2022-05-05 13:17 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +kubectl create namespace $6 --kubeconfig $7
@sonatype-lift ignore

2022-05-05 13:18 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +# Add image name and ingress DNS name.
@sonatype-lift ignore

2022-05-05 13:28 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +yq eval '.spec.template.spec.containers[0].image = "'$image'"' -i $3
@sonatype-lift ignore

2022-05-05 13:28 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +yq eval '.spec.template.spec.containers[0].image = "'$image'"' -i $3
@sonatype-lift ignore

2022-05-05 13:28 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +yq eval '.spec.rules[0].host = "'$dns'"' -i $4
@sonatype-lift ignore

2022-05-05 13:28 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +# Create namespace in AKS cluster.
@sonatype-lift ignore

2022-05-05 13:28 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +kubectl create namespace $6 --kubeconfig $7
@sonatype-lift ignore

2022-05-05 14:37 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl delete secret $2 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-05-05 14:37 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl delete secret $2 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-05-05 14:38 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl create secret docker-registry $2 --docker-server=$5 --docker-username=$3 --docker-password=$4 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-05-05 14:38 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +yq e '.spec.template.spec.imagePullSecrets[0].name = "'$secrets'"' -i $6
@sonatype-lift ignore

2022-05-05 14:38 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl apply -f $6 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-05-05 14:38 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl create secret docker-registry $2 --docker-server=$5 --docker-username=$3 --docker-password=$4 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-05-05 14:38 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +kubectl create secret docker-registry $2 --docker-server=$5 --docker-username=$3 --docker-password=$4 --namespace=$1 --kubeconfig $7
@sonatype-lift ignore

2022-05-05 14:38 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +yq e '.spec.template.spec."imagePullSecrets"=[{"name":"secrets"}]' -i $6
@sonatype-lift ignore

2022-05-05 14:38 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +yq e '.spec.template.spec.imagePullSecrets[0].name = "'$secrets'"' -i $6
@sonatype-lift ignore

2022-05-05 14:39 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --aks-provision-pipeline-name)  aksProvisionPipelineName="$2"; shift 2;;
@sonatype-lift ignore

2022-05-05 14:39 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    	--deploy-files)                 deployFiles=$2; shift 2;;
@sonatype-lift ignore

2022-05-24 11:25 UTC, jbellver99 requested changes

2022-05-24 11:25 UTC, jbellver99 commented on documentation/azure-devops/setup-deploy-pipeline.asciidoc
> +NOTE: The deploy pipeline will fail if the package pipeline executed on the same commit has failed.
```suggestion
NOTE: The deploy pipeline will fail if the package pipeline executed on the same commit has failed.

NOTE: The deploy pipeline will fail if the provisioning pipeline failed or does not exist.
```

2022-05-24 11:25 UTC, jbellver99 commented on documentation/azure-devops/setup-deploy-pipeline.asciidoc
> +* If it is private container registry, create secret for container registry to pull image from private repository.
```suggestion
* If the images are stored in a private container registry, create the corresponding secrets to pull images from it.
```

2022-05-24 11:25 UTC, jbellver99 commented on documentation/azure-devops/setup-deploy-pipeline.asciidoc
> +NOTE: Use `--secrets-name` flag to add extra secrets script to pull image from private container registry .
```suggestion
NOTE: Use `--secrets-name` flag to add extra secrets script to pull images from private container registry .
```

2022-05-24 11:25 UTC, jbellver99 commented on documentation/azure-devops/setup-deploy-pipeline.asciidoc
> +  --aks-provision-pipeline-name \
```suggestion
  [--aks-provision-pipeline-name <aks provisionig pipeline name>] \
```

2022-05-24 11:25 UTC, jbellver99 commented on documentation/azure-devops/setup-deploy-pipeline.asciidoc
> +  --k8s-namespace \
```suggestion
  --k8s-namespace <namespace> \
```

2022-05-24 11:25 UTC, jbellver99 commented on documentation/azure-devops/setup-deploy-pipeline.asciidoc
> +  --secrets-name <secretsValue> \
```suggestion
  [--secrets-name <secretsValue>] \
```

2022-05-24 11:25 UTC, jbellver99 commented on documentation/azure-devops/setup-deploy-pipeline.asciidoc
> +CAUTION: Remember to write the path to the local repository with '/' and not '\' on Windows.
```suggestion
```

2022-05-24 11:25 UTC, jbellver99 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
>          --) shift; break;;
```suggestion
        -c | --config-file)             configFile=$2; shift 2;;
        -n | --pipeline-name)           pipelineName=$2; shift 2;;
        -d | --local-directory)         localDirectory=$2; shift 2;;
        -a | --artifact-path)           artifactPath=$2; shift 2;;
        -b | --target-branch)           targetBranch=$2; shift 2;;
        -l | --language)                language=$2; shift 2;;
        --build-pipeline-name)          export buildPipelineName=$2; shift 2;;
        --sonar-url)                    sonarUrl=$2; shift 2;;
        --sonar-token)                  sonarToken=$2; shift 2;;
        -i | --image-name)              imageName=$2; shift 2;;
        -u | --registry-user)           dockerUser=$2; shift 2;;
        -p | --registry-password)       dockerPassword=$2; shift 2;;
        --resource-group)               resourceGroupName=$2; shift 2;;
        --storage-account)              storageAccountName=$2; shift 2;;
        --storage-container)            storageContainerName=$2; shift 2;;
        --cluster-name)                 clusterName=$2; shift 2;;
        --s3-bucket)                    s3Bucket=$2; shift 2;;
        --s3-key-path)                  s3KeyPath=$2; shift 2;;
        --quality-pipeline-name)        export qualityPipelineName=$2; shift 2;;
        --test-pipeline-name)           export testPipelineName=$2; shift 2;;
        --dockerfile)                   dockerFile=$2; shift 2;;
        --aws-access-key)               awsAccessKey="$2"; shift 2;;
        --aws-secret-access-key)        awsSecretAccessKey="$2"; shift 2;;
        --aws-region)                   awsRegion="$2"; shift 2;;
        --aks-provision-pipeline-name)  aksProvisionPipelineName="$2"; shift 2;;
        --k8s-namespace)                k8sNamespace="$2"; shift 2;;
    	--deploy-files)                 deployFiles=$2; shift 2;; 
	--deploy-cluster)               deployCluster=$2; shift 2;; 
        --secrets-name)                 secretsName=$2; shift 2;; 
	--package-pipeline-name)        export packagePipelineName=$2; shift 2;;
        -h | --help)                    help="true"; shift 1;;
        -w)                             webBrowser="true"; shift 1;;
        --) shift; break;;
```

2022-05-24 11:25 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/common/store-extra-path.yml
> -
Do not delete this blank line, it is needed.

2022-05-24 11:25 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +#!/bin/bash
```suggestion
#!/bin/bash
set -e
```

2022-05-24 11:25 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +#!/bin/bash
```suggestion
#!/bin/bash
set -e
```

2022-05-24 11:25 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/deploy/deploy-pipeline.cfg
> +    az pipelines variable create --name "secretsName" --pipeline-name $pipelineName --value $secretsName
Add a check to see if the flag is activated and add the variable only if the flag is activated, if not it fails.

2022-05-24 11:25 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/deploy/deploy-pipeline.cfg
> +    az pipelines variable create --name "aksProvisionPipelineName" --pipeline-name $pipelineName --value $aksProvisionPipelineName
Add a check to see if the flag is activated and add the variable only if the flag is activated, if not it fails.

2022-05-24 11:25 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/deploy/deploy-pipeline.yml.template
> +  - group: AWS_Credentials
This breaks if the variable group does not exist, add a check to see if the variable group is going to be used or not.

2022-05-24 11:25 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/deploy/deploy-pipeline.yml.template
> +    value: "$(Build.Repository.LocalPath)/$(deployFiles)/*-deployment.yaml"
the * breaks the execution of aks-deploy.sh and eks-deploy.sh, it would be better to add the name of the file.

2022-05-24 11:25 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/deploy/ecr-secrets.sh
> +#!/bin/bash
```suggestion
#!/bin/bash
set -e
```

2022-05-24 11:25 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +#!/bin/bash
```suggestion
#!/bin/bash
set -e
```

2022-05-24 11:25 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/deploy/deploy-pipeline.yml.template
> +
Add a step that checks if the provisioning pipeline has succeeded.

2022-05-24 11:25 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/deploy/deploy-pipeline.yml.template
> +    displayName: 'create secrets for AKS'
```suggestion
    displayName: 'Create secrets for AKS'
```

2022-05-24 11:25 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/deploy/deploy-pipeline.yml.template
> +    displayName: 'create secrets for EKS'
```suggestion
    displayName: 'Create secrets for EKS'
```

2022-05-24 11:25 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/deploy/deploy-pipeline.cfg
> +    cp *-deploy.sh "${localDirectory}/${scriptFilePath}"
```suggestion
    cp "${hangarPath}/${templatesPath}"/*-deploy.sh "${localDirectory}/${scriptFilePath}"
```

2022-05-24 11:25 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/deploy/deploy-pipeline.cfg
> +        cp *-secrets.sh "${localDirectory}/${scriptFilePath}"
```suggestion
        cp "${hangarPath}/${templatesPath}"/*-secrets.sh "${localDirectory}/${scriptFilePath}"
```

2022-05-24 14:16 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/deploy/deploy-pipeline.yml.template
> +  - group: eks_variables # DNS available for this job
There should be a conditional here to check if this variable group exists.

2022-05-24 14:16 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/deploy/deploy-pipeline.yml.template
> +  - group: aks-variables # DNS available for this job
There should be a conditional here to check if this variable group exists.

2022-05-25 10:17 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/deploy-pipeline.cfg
> +    az pipelines variable create --name "aksProvisionPipelineName" --pipeline-name $pipelineName --value $aksProvisionPipelineName
Instead of adding check to this variable, modified aksProvisionPipeline to ProvisionPipeline to make common for both EKS and AKS provision pipeline.

2022-05-25 10:19 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/eks-deploy.sh
> +yq eval '.spec.template.spec.containers[0].image = "'$image'"' -i "$4"
@sonatype-lift ignore

2022-05-25 10:19 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/ecr-secrets.sh
> +yq e '.spec.template.spec.imagePullSecrets[0].name = "'$secrets'"' -i "$6"
@sonatype-lift ignore

2022-05-25 10:19 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +yq eval '.spec.rules[0].host = "'$dns'"' -i "$4"
@sonatype-lift ignore

2022-05-25 10:20 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/aks-deploy.sh
> +yq eval '.spec.template.spec.containers[0].image = "'$image'"' -i "$3"
@sonatype-lift ignore

2022-05-25 10:20 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/templates/deploy/acr-secrets.sh
> +yq e '.spec.template.spec.imagePullSecrets[0].name = "'$secrets'"' -i "$6"
@sonatype-lift ignore

2022-05-25 10:20 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --k8s-namespace)                k8sNamespace="$2"; shift 2;;
@sonatype-lift ignore

2022-05-25 10:20 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --aks-provision-pipeline-name)  aksProvisionPipelineName="$2"; shift 2;;
@sonatype-lift ignore

2022-05-25 10:20 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    	--deploy-files)                 deployFiles=$2; shift 2;;
@sonatype-lift ignore

2022-05-25 10:20 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --secrets-name)                 secretsName=$2; shift 2;;
@sonatype-lift ignore

2022-05-25 10:20 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +	    --deploy-cluster)               deployCluster=$2; shift 2;;
@sonatype-lift ignore

2022-05-25 10:41 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --provision-pipeline-name)      ProvisionPipelineName="$2"; shift 2;;
@sonatype-lift ignore

2022-05-27 06:17 UTC, prathibhapadma commented
Incorporated all the changes and commited.

2022-06-16 10:25 UTC, albertdb requested changes
Please address relevant issues https://lift.sonatype.com/results/github.com/devonfw/hangar/01G5NYVQJMQVVXZ54VYN50ATJN

2022-06-22 10:02 UTC, prathibhapadma commented
Fixed all sonatype lift issues(Double quote to prevent globbing and word splitting).

2022-07-01 15:05 UTC, albertdb requested changes
Please retest after changes

2022-07-04 03:18 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --k8s-image-pull-secret-name)  k8sImagePullSecret=$2; shift 2;;
@sonatype-lift ignore

2022-07-04 03:18 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +      	--k8s-provider)             k8sProvider=$2; shift 2;;
@sonatype-lift ignore

2022-07-04 03:18 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --env-provision-pipeline-name)  envProvisionPipelineName="$2"; shift 2;;
@sonatype-lift ignore

2022-07-04 03:18 UTC, prathibhapadma commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +      	--k8s-deploy-files-path)    k8sDeployFiles=$2; shift 2;;
@sonatype-lift ignore

2022-07-04 08:11 UTC, prathibhapadma commented
@albertdb Tested with all changes, successfully deployed app to AKS cluster.

2022-07-06 08:33 UTC, merged