FEATURE:  GCLOUD DEPLOY IN GKE
devonfw/hangar pull request #406
Opened 2022-11-22 12:26 UTC by ultymatom

2022-11-22 12:31 UTC, ultymatom commented on scripts/pipelines/common/templates/deploy/deploy.sh
> +echo "tag_completed: $8" | grep release && tag_completed="${tag}"
@sonatype-lift ignore

2022-11-22 12:34 UTC, ultymatom commented on scripts/pipelines/gcloud/templates/deploy/deploy-setup-environment.sh
> +echo "$firstPartImage" | grep "\." > /dev/null && REGISTRY="$firstPartImage" || REGISTRY="docker.io"
@sonatype-lift ignore

2022-11-28 10:09 UTC, mcerverc commented on scripts/accounts/gcloud/create-project.sh
> +   exit 226
```suggestion
echo "Enabling Compute API..."
if ! gcloud services enable compute.googleapis.com --project "$projectName"; then
   echo -e "${red}Error: Cannot enable Compute API"
   echo -ne "${white}"
   exit 225
fi

echo "Enabling Container API..."
if ! gcloud services enable container.googleapis.com --project "$projectName"; then
   echo -e "${red}Error: Cannot enable Container API"
   echo -ne "${white}"
   exit 226
```

2022-11-29 15:47 UTC, capf4bbo approved these changes

2022-12-05 12:52 UTC, abcarcol commented on documentation/azure-devops/setup-deploy-pipeline.asciidoc
> +    --k8s-image-pull-secret-name    Name for the generated secret containing registry credentials. Required when using a private registry to host images.
```suggestion
   --k8s-image-pull-secret-name               Name for the generated secret containing registry credentials. Required when using a private registry to host images.
```
Why did you delete the spaces for identation?

2022-12-05 14:07 UTC, abcarcol commented on documentation/src/common_templates/setup-deploy-pipeline.asciidoc
> +ifdef::machineType[  [-m <machine type for {pipeline_type} runner>]]
```suggestion
ifeval::["{provider}" == "Google Cloud"]
machineType[  [-m <machine type for {pipeline_type} runner>]]
endif::[]
```

2022-12-05 14:08 UTC, abcarcol commented on documentation/src/common_templates/setup-deploy-pipeline.asciidoc
> +ifdef::machineType[-m, --machine-type                             Machine type for {pipeline_type} runner. Accepted values: E2_HIGHCPU_8, E2_HIGHCPU_32, N1_HIGHCPU_8, N1_HIGHCPU_32.]
```suggestion
ifeval::["{provider}" == "Google Cloud"]
machineType[-m, --machine-type                             Machine type for {pipeline_type} runner. Accepted values: E2_HIGHCPU_8, E2_HIGHCPU_32, N1_HIGHCPU_8, N1_HIGHCPU_32.]
endif::[]
```

2022-12-05 14:10 UTC, abcarcol commented on documentation/src/common_templates/setup-deploy-pipeline.asciidoc
> +kubectl get ingress -n <namespace>
Where is 'kubectl' supposed to be installed? local, remote?

2022-12-05 14:11 UTC, abcarcol commented on documentation/src/gcloud/setup-deploy-pipeline.asciidoc
> +:machineType:
```suggestion
```

2022-12-05 14:32 UTC, abcarcol commented on scripts/pipelines/common/templates/deploy/secrets.sh
> +kubectl get namespace | grep -q "^$1" || kubectl create namespace "$1"
Variable names instead of positional arguments

2022-12-05 14:34 UTC, abcarcol commented on scripts/pipelines/gcloud/templates/deploy/deploy-pipeline.cfg
> +previousPipelineyaml="*package-pipeline.yml"
```suggestion
previousPipelineyaml="package-pipeline.yml"
```
Now there is only one package-pipeline for every case, wildcard no longer needed.

2022-12-05 14:38 UTC, abcarcol commented on scripts/pipelines/gcloud/templates/deploy/deploy-pipeline.yml.template
> +  name: gcr.io/cloud-builders/gsutil
```suggestion
- name: gcr.io/cloud-builders/gsutil
   id: "Download artifact from provisioning pipeline"
```

2022-12-05 14:42 UTC, abcarcol commented on scripts/pipelines/gcloud/templates/deploy/deploy-pipeline.yml.template
> +    - '_ENV_PROVISIONING_PIPELINE_NAME=${_ENV_PROVISIONING_PIPELINE_NAME}'
```suggestion
    - 'ENV_PROVISIONING_PIPELINE_NAME=${_ENV_PROVISIONING_PIPELINE_NAME}'
```

2022-12-05 14:47 UTC, abcarcol commented on scripts/pipelines/gcloud/templates/deploy/deploy-setup-environment.sh
> +firstPartImage=$(echo $_IMAGE_NAME | cut -d'/' -f1)
```suggestion
firstPartImage=$(echo "$_IMAGE_NAME" | cut -d'/' -f1)
```

2022-12-16 10:42 UTC, ultymatom commented on documentation/azure-devops/setup-deploy-pipeline.asciidoc
> +    --k8s-image-pull-secret-name    Name for the generated secret containing registry credentials. Required when using a private registry to host images.
oops not on purpose

2022-12-16 10:43 UTC, ultymatom commented on scripts/pipelines/common/templates/deploy/deploy.sh
> +. "$7"
For this part this is legacy code sadly

2022-12-16 10:57 UTC, ultymatom commented on documentation/src/common_templates/setup-deploy-pipeline.asciidoc
> +kubectl get ingress -n <namespace>
Local machine, but this is just an appendix to get the hostname, do we need to explained that kubec

2022-12-16 11:00 UTC, ultymatom commented on scripts/pipelines/common/templates/deploy/secrets.sh
> +kubectl get namespace | grep -q "^$1" || kubectl create namespace "$1"
legacy code

2022-12-19 11:55 UTC, mcerverc approved these changes

2022-12-19 13:47 UTC, albertdb requested changes

2022-12-19 13:47 UTC, albertdb commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +FLAGS=$(getopt -a --options c:n:d:a:b:l:i:u:p:hm: --long "config-file:,pipeline-name:,local-directory:,artifact-path:,target-branch:,language:,build-pipeline-name:,registry-location:,flutter-web-rend
```suggestion
FLAGS=$(getopt -a --options c:n:d:a:b:l:i:u:p:m:h --long "config-file:,pipeline-name:,local-directory:,artifact-path:,target-branch:,language:,build-pipeline-name:,sonar-url:,sonar-token:,image-name:,registry-user:,registry-password:,resource-group:,storage-account:,storage-container:,cluster-name:,s3-bucket:,s3-key-path:,quality-pipeline-name:,dockerfile:,test-pipeline-name:,aws-access-key:,aws-secret-access-key:,aws-region:,ci-pipeline-name:,help,registry-location:,flutter-web-renderer:,machine-type:,language-version:,service-name:,gcloud-region:,port:,flutter-platform:,package-pipeline-name:,env-provision-pipeline-name:,k8s-provider:,k8s-namespace:,k8s-deploy-files-path:,k8s-image-pull-secret-name:" -- "$@")
```

2022-12-19 14:33 UTC, albertdb requested changes

2022-12-19 14:33 UTC, albertdb commented on documentation/src/common_templates/setup-deploy-pipeline.asciidoc
> +The script located at `/scripts/pipelines/{path_provider}/pipeline_generator.sh` will automatically create the new branch, create a deploy pipeline based on a YAML template appropriate for the projec
```suggestion
The script located at `/scripts/pipelines/{path_provider}/pipeline_generator.sh` will automatically create the new branch, create a deploy {pipeline_type} based on a YAML template appropriate for the project manifests files, create the Pull Request, and if it is possible, merge this new branch into the specified branch.

```

2022-12-19 14:33 UTC, albertdb commented on documentation/src/common_templates/setup-deploy-pipeline.asciidoc
> +  -n <pipeline name> \
```suggestion
  -n <{pipeline_type} name> \
```

2022-12-19 14:33 UTC, albertdb commented on documentation/src/common_templates/setup-deploy-pipeline.asciidoc
> +  --env-provision-pipeline-name <pipeline name> \
```suggestion
  --package-pipeline-name <{pipeline_type} name> \
  --env-provision-pipeline-name <{pipeline_type} name> \
```

2022-12-19 14:33 UTC, albertdb commented on documentation/src/common_templates/setup-deploy-pipeline.asciidoc
> +NOTE:  The config file for the deploy pipeline is located at `/scripts/pipelines/{path_provider}/templates/deploy/deploy-pipeline.cfg`.
```suggestion
NOTE:  The config file for the deploy {pipeline_type} is located at `/scripts/pipelines/{path_provider}/templates/deploy/deploy-pipeline.cfg`.
```

2022-12-19 14:33 UTC, albertdb commented on documentation/src/common_templates/setup-deploy-pipeline.asciidoc
> +-n  --pipeline-name                 [Required] Name that will be set to the pipeline.
```suggestion
-c  --config-file                   [Required] Configuration file containing {pipeline_type} definition.
-n  --pipeline-name                 [Required] Name that will be set to the {pipeline_type}.
```

2022-12-19 14:33 UTC, albertdb commented on documentation/src/common_templates/setup-deploy-pipeline.asciidoc
> +    --package-pipeline-name         [Required] Package pipeline name.
```suggestion
    --package-pipeline-name         [Required] Package {pipeline_type} name.
```

2022-12-19 14:33 UTC, albertdb commented on documentation/src/common_templates/setup-deploy-pipeline.asciidoc
> +    --env-provision-pipeline-name   [Required] Environment provisioning pipeline name.
```suggestion
    --env-provision-pipeline-name   [Required] Environment provisioning {pipeline_type} name.
```

2022-12-19 14:33 UTC, albertdb commented on documentation/src/common_templates/setup-deploy-pipeline.asciidoc
> +Once the {pipeline_type} is executed and your application is deployed, you can list the hostname to access it with: (from your local machine)
```suggestion
Once the {pipeline_type} is executed and your application is deployed, you can list the hostname to access it by running locally:
```

2022-12-19 14:33 UTC, albertdb commented on documentation/src/azure-devops/setup-deploy-pipeline.asciidoc
> +:pipeline_type: Pipeline
```suggestion
:pipeline_type: pipeline
```

2022-12-19 14:33 UTC, albertdb commented on documentation/src/azure-devops/setup-deploy-pipeline.asciidoc
> +:provider: Azure Devops
```suggestion
:provider: Azure DevOps

```

2022-12-19 14:33 UTC, albertdb commented on documentation/src/azure-devops/setup-deploy-pipeline.asciidoc
> +:trigger_sentence: This pipeline will be configured to be triggered after the package pipeline
```suggestion
:trigger_sentence: This pipeline will be configured in order to be triggered every time package pipeline is executed successfully on a commit for `release/*` and `develop` branches, requiring manual launch for other branches but still enforcing that package pipeline has passed
```

2022-12-19 14:33 UTC, albertdb commented on documentation/src/gcloud/setup-deploy-pipeline.asciidoc
> +:trigger_sentence: This pipeline will be configured to be triggered after the package pipeline
```suggestion
:trigger_sentence: This pipeline will be configured in order to be triggered every time package pipeline is executed successfully on a commit for `release/*` and `develop` branches, requiring manual launch for other branches
```

Hope this is true. Otherwise, fix pipeline definition accordingly.

2022-12-19 14:33 UTC, albertdb commented on scripts/pipelines/gcloud/templates/deploy/deploy-setup-environment.sh
> +apt-get install zip -y
```suggestion
apt-get install -y sudo wget curl zip 
```

2022-12-19 14:33 UTC, albertdb commented on scripts/pipelines/gcloud/templates/deploy/deploy-pipeline.yml.template
> +    - echo $$registry_credentials > credentials.env
```suggestion
- name: gcr.io/cloud-builders/gcloud
  id: Get credentials
  entrypoint: bash
  secretEnv: ['registry_credentials']
  args:
    - -c
    - echo $$registry_credentials > credentials.env
```

Better use already used image

2022-12-19 14:33 UTC, albertdb commented on scripts/pipelines/gcloud/templates/deploy/deploy-pipeline.yml.template
> +  id: get kubeconfig
```suggestion
  id: Get Kubeconfig
```

2022-12-19 14:33 UTC, albertdb commented on scripts/pipelines/gcloud/templates/deploy/deploy-pipeline.yml.template
> +  id: deploy
```suggestion
  id: Deploy
```

2022-12-19 14:33 UTC, albertdb commented on scripts/pipelines/gcloud/templates/deploy/deploy-pipeline.cfg
> +#!/bin/bash
```suggestion
#!/bin/false
```

2022-12-19 14:33 UTC, albertdb commented on scripts/pipelines/gcloud/templates/deploy/deploy-pipeline.cfg
> +branchTrigger='.*'
Wrong :(

2022-12-19 14:33 UTC, albertdb commented on documentation/src/common_templates/setup-deploy-pipeline.asciidoc
> +    --k8s-image-pull-secret-name    Name for the generated secret containing registry credentials. Required when using a private registry to host images.
```suggestion
    --k8s-image-pull-secret-name               Name for the generated secret containing registry credentials. Required when using a private registry to host images.

```

2022-12-19 17:29 UTC, albertdb approved these changes

2022-12-20 08:20 UTC, abcarcol approved these changes

2022-12-20 08:37 UTC, merged