Feature/sp5 365 connect frontend with backend when deploying services on gcp
devonfw/hangar pull request #411
Opened 2022-11-23 08:50 UTC by lpinon

2022-11-23 08:55 UTC, lpinon commented on scripts/quickstart/gcloud/init-cloud-run.sh
> +    serviceUrl=$(gcloud run services describe $serviceName --format 'value(status.url)' --project "$projectName" --region "$region")
```suggestion
    serviceUrl=$(gcloud run services describe "$serviceName" --format 'value(status.url)' --project "$projectName" --region "$region")
```

2022-11-23 11:58 UTC, capf4bbo submitted a review, later dismissed

2022-11-23 12:09 UTC, mcerverc commented on documentation/gcloud/quickstart-init-cloud-run.asciidoc
> +By the end of this guide, a Cloud Run on {provider_name} will be created in an automated way using a script and the public URL will be returned or written into an output file.
```suggestion
By the end of this guide, a Cloud Run service on {provider_name} will be created in an automated way using a script and the public URL will be returned or written into an output file.

```

2022-11-23 12:09 UTC, mcerverc commented on scripts/quickstart/gcloud/init-cloud-run.sh
> +   echo "Inits Cloud Run Instance and Returns Public URL"
```suggestion
   echo "Inits Cloud Run Instance and returns public URL"
```

2022-11-23 12:12 UTC, Jorge-Dacal commented on scripts/quickstart/gcloud/init-cloud-run.sh
> +   echo "Inits Cloud Run Instance and Returns Public URL"
Por mi parte, no me queda claro sí la documentación debe ir a la carpeta src y autogenerarse, por lo demás, conforme.

Como mucho pondría en minusculas lo que ya te ha sugerido miguel.

2022-11-23 12:13 UTC, Jorge-Dacal commented
Por mi parte, no me queda claro sí la documentación debe ir a la carpeta src y autogenerarse, por lo demás, conforme.

Como mucho pondría en minusculas lo que ya te ha sugerido miguel.

2022-11-23 12:16 UTC, Jorge-Dacal commented on documentation/gcloud/quickstart-init-cloud-run.asciidoc
> +:provider_name: Google Cloud
Por mi parte, no me queda claro sí la documentación debe ir a la carpeta src y autogenerarse, por lo demás, conforme.

Como mucho pondría en minusculas lo que ya te ha sugerido miguel.

2022-11-23 12:42 UTC, Jorge-Dacal commented on documentation/gcloud/quickstart-init-cloud-run.asciidoc
> +:provider_name: Google Cloud
Aclarado por ALbert, pueden haber ficheros no autogenerados.

2022-11-23 12:43 UTC, Jorge-Dacal submitted a review, later dismissed

2022-11-23 12:44 UTC, albertdb requested changes

2022-11-23 12:44 UTC, albertdb commented on documentation/gcloud/quickstart-init-cloud-run.asciidoc
> +By the end of this guide, a Cloud Run service on {provider_name} will be created in an automated way using a script and the public URL will be returned or written into an output file.
But why do we need it? Not explained.

2022-11-23 12:44 UTC, albertdb commented on documentation/gcloud/quickstart-init-cloud-run.asciidoc
> += Setting up Cloud Run service in {provider_name}
```suggestion
= Setting up a Google Cloud Run service
```

No other option.

2022-11-23 12:53 UTC, albertdb requested changes

2022-11-23 12:53 UTC, albertdb commented on documentation/gcloud/quickstart-init-cloud-run.asciidoc
> +-p, --project                [Required] Id of the project.
```suggestion
-p, --project                [Required] Short name (ID) of the project.
```

To be consistent with other doc.

2022-11-23 12:53 UTC, albertdb commented on documentation/gcloud/quickstart-init-cloud-run.asciidoc
> +-n, --name                   [Required] Name that will be set to the Cloud Run Service endpoint.
```suggestion
-n, --name                   [Required] Name for the Cloud Run service endpoint.
```

2022-11-23 12:53 UTC, albertdb commented on documentation/gcloud/quickstart-init-cloud-run.asciidoc
> +-r, --region                            Region to create the Cloud Run service on.
```suggestion
-r, --region                            Region where the Cloud Run service will be created.
```

For consistency.

2022-11-23 12:53 UTC, albertdb commented on documentation/gcloud/quickstart-init-cloud-run.asciidoc
> +-o, --output                            Output File to store the created service public URL.
```suggestion
-o, --output                            Output file path to store the created service public URL.
```

2022-11-23 12:53 UTC, albertdb commented on scripts/quickstart/gcloud/init-cloud-run.sh
> +   echo "Inits Cloud Run Instance and returns public URL"
```suggestion
   echo "Creates a new Cloud Run service with a predefined HelloWorld image deployed and retrieves the public URL."
```

2022-11-23 12:53 UTC, albertdb commented on scripts/quickstart/gcloud/init-cloud-run.sh
> +   echo -e "\t-o, --output                    Output file path to store the service URL."
```suggestion
   echo "Flags:"
   echo -e "\t-p, --project        [Required] Short name (ID) of the project.."
   echo -e "\t-n, --name           [Required] Name for the Cloud Run service endpoint."
   echo -e "\t-r, --region                    Region where the Cloud Run service will be created."
   echo -e "\t-o, --output                    Output file path to store the created service public URL."
```

2022-11-23 13:34 UTC, ultymatom submitted a review, later dismissed

2022-11-23 16:10 UTC, lpinon commented on documentation/gcloud/quickstart-init-cloud-run.asciidoc
> +By the end of this guide, a Cloud Run service on {provider_name} will be created in an automated way using a script and the public URL will be returned or written into an output file.
```suggestion
By the end of this guide, a Cloud Run service on {provider_name} will be created in an automated way using a script and the public URL will be returned or written into an output file. The purpose of this script is to create a Cloud Run endpoint quickly in order to retrieve the URL of the service before the execution of a Deployment pipeline.

```

2022-11-24 10:15 UTC, Jorge-Dacal approved these changes

2022-11-24 10:20 UTC, Jorge-Dacal requested changes

2022-11-24 10:20 UTC, Jorge-Dacal commented on scripts/quickstart/gcloud/init-cloud-run.sh
> +        echo -ne "${white}"
echo -ne "${white}" >&2

2022-11-24 10:20 UTC, Jorge-Dacal commented on scripts/quickstart/gcloud/init-cloud-run.sh
> +        echo -ne "${white}"
echo -ne "${white}" >&2

2022-11-24 11:31 UTC, lpinon commented on scripts/quickstart/gcloud/init-cloud-run.sh
> +        echo -ne "${white}"
```suggestion
        echo -ne "${white}" >&2
```

2022-11-24 11:31 UTC, lpinon commented on scripts/quickstart/gcloud/init-cloud-run.sh
> +        echo -ne "${white}"
```suggestion
        echo -ne "${white}" >&2
```

2022-11-24 11:31 UTC, lpinon commented on scripts/quickstart/gcloud/init-cloud-run.sh
> +        echo -ne "${white}"
```suggestion
        echo -ne "${white}" >&2
```

2022-11-24 11:31 UTC, lpinon commented on scripts/quickstart/gcloud/init-cloud-run.sh
> +        echo -ne "${white}"
```suggestion
        echo -ne "${white}" >&2
```

2022-11-24 11:32 UTC, lpinon commented on scripts/quickstart/gcloud/init-cloud-run.sh
> +        echo -ne "${white}"
```suggestion
        echo -ne "${white}" >&2
```

2022-11-25 06:53 UTC, Jorge-Dacal requested changes

2022-11-25 06:53 UTC, Jorge-Dacal commented on scripts/quickstart/gcloud/init-cloud-run.sh
> +        echo -e "${red}Error: Cannot create Cloud Run Instance"
```suggestion
        echo -e "${red}Error: Cannot create Cloud Run Instance" >&2
```

2022-11-25 07:30 UTC, lpinon commented on scripts/quickstart/gcloud/init-cloud-run.sh
> +        echo -e "${red}Error: Project $projectName does not exist."
```suggestion
        echo -e "${red}Error: Project $projectName does not exist." >&2
```

2022-11-25 07:59 UTC, lpinon commented on documentation/gcloud/quickstart-init-cloud-run.asciidoc
> +init-cloud-run.sh.sh \
```suggestion
init-cloud-run.sh \

```

2022-11-25 08:00 UTC, lpinon commented on documentation/gcloud/quickstart-init-cloud-run.asciidoc
> +
```suggestion
```

2022-11-25 08:52 UTC, Jorge-Dacal approved these changes

2022-11-25 09:24 UTC, albertdb commented on documentation/gcloud/quickstart-init-cloud-run.asciidoc
> +
```suggestion
```

2022-11-25 09:24 UTC, albertdb commented on documentation/gcloud/quickstart-init-cloud-run.asciidoc
> +
```suggestion
```

2022-11-25 09:25 UTC, albertdb commented on scripts/quickstart/gcloud/init-cloud-run.sh
> +        exit 200
```suggestion
        exit 1
```

2022-11-25 09:26 UTC, albertdb commented on scripts/quickstart/gcloud/init-cloud-run.sh
> +        exit 240
```suggestion
        exit 1
```

2022-11-25 09:29 UTC, albertdb submitted a review, later dismissed

2022-11-25 10:36 UTC, capf4bbo approved these changes

2022-11-28 11:36 UTC, ultymatom approved these changes

2022-11-28 13:04 UTC, ultymatom approved these changes

2022-11-28 15:54 UTC, abcarcol approved these changes

2022-11-28 15:58 UTC, merged