Feature: Add steps for getting ACR credentials
devonfw/hangar pull request #43
Opened 2022-03-23 14:56 UTC by albertdb

@sundharakanth please review and test.

2022-03-25 12:12 UTC, sundharakanth commented
To resolve the errors from spellcheck, we need to add the 6 valid words (ECR, ecr, dkr, aws, amazonaws, azurecr) in the dictionary - https://github.com/devonfw/.github/blob/master/en-devonfw.dict
![image](https://user-images.githubusercontent.com/91184708/160118489-3a012beb-9d4a-4c5b-8deb-0be4423c087d.png)

There is one word mis-spelt as "accesing" instead of "accessing" which is to be corrected.

2022-03-28 06:15 UTC, sundharakanth requested changes
Please change line#83 from 
** `<registry-url>`: <aws-account-id>.dkr.ecr.<region>.amazonaws.com
to
** `<registry-url>`: Format is `<aws-account-id>.dkr.ecr.<region>.amazonaws.com`

We can add only new technical words into dictionary and to avoid adding words like "dkr" and "ecr", we will have to show the above line as code.

2022-03-28 06:15 UTC, sundharakanth commented on documentation/setup-container-image-registry.asciidoc
>  ** `<registry-url>`: <registry-name>.azurecr.io
** `<registry-url>`: Format is `<registry-name>.azurecr.io`

2022-03-28 06:23 UTC, sundharakanth commented
Hi @albertdb - Opened a PR https://github.com/devonfw/.github/pull/126 to add new words ECR and ACR in Dictionary and got it reviewed and merged. For all other words failing, we need to use backticks (as code) since those are not new technical words rather those are specific words from each providers as per Devon Core Team review.

2022-03-28 10:57 UTC, albertdb commented
@sundharakanth Thanks. Apart from that, do the commands work as expected?

2022-03-28 11:08 UTC, sundharakanth commented
> @sundharakanth Thanks. Apart from that, do the commands work as expected?

Thanks for the updates @albertdb . Yes, all the commands are working as expected and once we merge the current file, we can check if it resolves SpellCheck issues.

2022-03-29 06:25 UTC, sundharakanth commented
Hi @albertdb , right now, only the 3 words (imagesdir, partnums, sectnums) are failing in SpellCheck. 

<img width="656" alt="image" src="https://user-images.githubusercontent.com/91184708/160545853-b4916f07-033b-4e96-8453-f99e1c18bb01.png">

There are a couple of options to fix this issue:
1. We can check with Jan @SchettlerKoehler if we are going to use the below format in all the documentation folders as template in all devonfw github projects and if not, we can remove this part.

![image](https://user-images.githubusercontent.com/91184708/160546408-36653420-4eeb-44fd-8f5c-6ebe712d94ad.png)

2. If this format is required, then, we can check with Malte @maybeec and add regex to escape words starting with colon and ending with colon to escape words like 
          (a) :imagesdir:
          (b) :partnums:
          (c) :sectnums:

![image](https://user-images.githubusercontent.com/91184708/160546851-53dbe080-388a-493e-82e0-b63d7336e59f.png)

2022-03-30 07:08 UTC, sundharakanth commented
> @sundharakanth Please go ahead preparing the solution mentioned in the second option while we get more opinions on this matter. Not much work to throw away in case a different decision is finally taken.

@albertdb - The following regex takes care of escaping the single words (not the ones with hyphen in between like :toc-title: ). Please confirm. 
<img width="221" alt="image" src="https://user-images.githubusercontent.com/91184708/160772239-1c4ee886-e174-4fb0-8038-0bb5541f5f39.png">

2022-03-30 07:27 UTC, sundharakanth commented
Hi All ( @maybeec , @SchettlerKoehler , @ssarmokadam , @isandesh1986 , @sujith-mn ),
I can see the following templated related non-standard words in dictionary.

148   doctype
614   toc
249   idprefix
250   idseparator
516   reproducable [Looks like mis-spelling of reproducible]

If we have the above words, then, I think, it is okay to add the following few more words. Please confirm. 
(a) :imagesdir:
(b) :partnums:
(c) :sectnums:

![image](https://user-images.githubusercontent.com/91184708/160775563-2f89ebbc-9b38-4d49-9308-5a3bd0550a9f.png)

[ FYI - @albertdb ]

2022-03-30 08:11 UTC, albertdb commented
> Hi All ( @maybeec , @SchettlerKoehler , @ssarmokadam , @isandesh1986 , @sujith-mn ), I can see the following templated related non-standard words in dictionary.
> 
> 148 doctype 614 toc 249 idprefix 250 idseparator 516 reproducable [Looks like mis-spelling of reproducible]
> 
> If we have the above words, then, I think, it is okay to add the following few more words. Please confirm. (a) :imagesdir: (b) :partnums: (c) :sectnums:
> 
> ![image](https://user-images.githubusercontent.com/91184708/160775563-2f89ebbc-9b38-4d49-9308-5a3bd0550a9f.png)
> 
> [ FYI - @albertdb ]

That is kicking the can down the road, because we can have arbitrary attributes in a document: https://asciidoctor.org/docs/asciidoc-recommended-practices/#document-attributes-i-e-variables



> > @sundharakanth Please go ahead preparing the solution mentioned in the second option while we get more opinions on this matter. Not much work to throw away in case a different decision is finally taken.
> 
> @albertdb - The following regex takes care of escaping the single words like _:sectnums:_ , _:partnums:_ , _:imagesdir:_ , etc. Please confirm. [ FYI - @ssarmokadam , @isandesh1986 , @sujith-mn ]
> 
> <img alt="image" width="221" src="https://user-images.githubusercontent.com/91184708/160772239-1c4ee886-e174-4fb0-8038-0bb5541f5f39.png">
> 
> **Note:** The above one does not take care of the words with hyphen in between like _:toc-title:_ , _:chapter-label:_ , etc. But, those are not having any spellcheck issues as of now.

Please try to make it work for cases with hyphens also.

2022-03-30 08:13 UTC, maybeec commented
Just one question, why do we need all this properties here?
Normally we generate the website / pdf with a central tool and not configuring asciidoc in each document. Is it really needed?

2022-03-30 08:32 UTC, sundharakanth commented
> > Hi All ( @maybeec , @SchettlerKoehler , @ssarmokadam , @isandesh1986 , @sujith-mn ), I can see the following templated related non-standard words in dictionary.
> > 148 doctype 614 toc 249 idprefix 250 idseparator 516 reproducable [Looks like mis-spelling of reproducible]
> > If we have the above words, then, I think, it is okay to add the following few more words. Please confirm. (a) :imagesdir: (b) :partnums: (c) :sectnums:
> > ![image](https://user-images.githubusercontent.com/91184708/160775563-2f89ebbc-9b38-4d49-9308-5a3bd0550a9f.png)
> > [ FYI - @albertdb ]
> 
> That is kicking the can down the road, because we can have arbitrary attributes in a document: https://asciidoctor.org/docs/asciidoc-recommended-practices/#document-attributes-i-e-variables
> 
> > > @sundharakanth Please go ahead preparing the solution mentioned in the second option while we get more opinions on this matter. Not much work to throw away in case a different decision is finally taken.
> > 
> > 
> > @albertdb - The following regex takes care of escaping the single words like _:sectnums:_ , _:partnums:_ , _:imagesdir:_ , etc. Please confirm. [ FYI - @ssarmokadam , @isandesh1986 , @sujith-mn ]
> > <img alt="image" width="221" src="https://user-images.githubusercontent.com/91184708/160772239-1c4ee886-e174-4fb0-8038-0bb5541f5f39.png">
> > **Note:** The above one does not take care of the words with hyphen in between like _:toc-title:_ , _:chapter-label:_ , etc. But, those are not having any spellcheck issues as of now.
> 
> Please try to make it work for cases with hyphens also.

![image](https://user-images.githubusercontent.com/91184708/160787816-a9b79d8d-4693-46cd-a535-fe025589961f.png)

2022-03-30 08:44 UTC, albertdb commented
> Just one question, why do we need all this properties here? Normally we generate the website / pdf with a central tool and not configuring asciidoc in each document. Is it really needed?

I think the problem is more general. If we want to create a variable for a URL, the spellchecker will complain. For me is the same as running it against source code, completely absurd.

2022-03-30 11:19 UTC, sundharakanth commented
Raised the PR https://github.com/devonfw/.github/pull/127 for change in spellcheck.yml

2022-03-31 15:02 UTC, albertdb commented
@sundharakanth Any advances on this?

2022-04-01 04:50 UTC, sundharakanth commented
> @sundharakanth Any advances on this?

@albertdb Tested the regex changes in my fork and it is working fine. Need to test negative scenarios as well. Same changes are already added to this PR in Hangar repo.

2022-04-01 04:55 UTC, sundharakanth commented
> Hi All ( @maybeec , @SchettlerKoehler , @ssarmokadam , @isandesh1986 , @sujith-mn ), I can see the following templated related non-standard words in dictionary.
> 
> 148 doctype 614 toc 249 idprefix 250 idseparator 516 reproducable [Looks like mis-spelling of reproducible]
> 
> If we have the above words, then, I think, it is okay to add the following few more words. Please confirm. (a) :imagesdir: (b) :partnums: (c) :sectnums:
> 
> ![image](https://user-images.githubusercontent.com/91184708/160775563-2f89ebbc-9b38-4d49-9308-5a3bd0550a9f.png)
> 
> [ FYI - @albertdb ]

@ssarmokadam and @sujith-mn - Shall we go ahead with this option? Please confirm.

2022-04-01 08:11 UTC, sundharakanth approved these changes

2022-04-01 09:25 UTC, sundharakanth commented
> @sundharakanth You have force pushed and removed changes in spellcheck.yaml
> 
> Please check.

@albertdb - Yes, thats right. To fix the issue temporarily, I added the 3 new words in dictionary and get it merged. So, removed all the .spellcheck.yml file changes. 

Now, you can merge this PR#43 which will make spellcheck workflow to execute successfully in Hangar repo.

Currently Spellcheck is passing in the branch feature/acr-credentials and failing in master. 

<img width="959" alt="image" src="https://user-images.githubusercontent.com/91184708/161235690-e37188e3-b5f7-4b29-b8c1-2842f3b712a0.png">

2022-04-01 09:44 UTC, albertdb commented
@sundharakanth As I commented before about adding new attributes to dictionary:

> That is kicking the can down the road, because we can have arbitrary attributes in a document: https://asciidoctor.org/docs/asciidoc-recommended-practices/#document-attributes-i-e-variables

Please reintroduce spellcheck change if that is valid for any `:watheverVariable-with-hyphens:`

2022-04-04 06:03 UTC, sundharakanth commented
> @sundharakanth As I commented before about adding new attributes to dictionary:
> 
> > That is kicking the can down the road, because we can have arbitrary attributes in a document: https://asciidoctor.org/docs/asciidoc-recommended-practices/#document-attributes-i-e-variables
> 
> Please reintroduce spellcheck change if that is valid for any `:watheverVariable-with-hyphens:`

@albertdb - I will discuss with Devon Core team ( @ssarmokadam , @sujith-mn , @isandesh1986 ) and get back.

2022-04-06 10:50 UTC, sundharakanth commented
> Devon Core team ( @ssarmokadam , @sujith-mn , @isandesh1986 ) and get back

@albertdb - A JIRA Ticket is created for this requirement and Devon Core team ( @ssarmokadam , @sujith-mn , @isandesh1986 ) would get back to you on the timelines of the same.

2022-04-12 15:06 UTC, merged