Quickstart Scripts Backend Wayat
devonfw/hangar pull request #461
Opened 2022-11-30 17:27 UTC by lpinon

Closes #416

2022-12-01 11:11 UTC, ultymatom approved these changes

2022-12-16 14:25 UTC, albertdb requested changes

2022-12-16 14:25 UTC, albertdb commented on documentation/gcloud/quickstart-wayat-backend.asciidoc
> +== Initializing a Cloud Run service using provided script
Not really

2022-12-16 14:30 UTC, lpinon commented on documentation/gcloud/quickstart-wayat-backend.asciidoc
> +== Initializing a Cloud Run service using provided script
```suggestion
== Initializing Wayat Backend using provided script
```

2022-12-19 09:37 UTC, closed without merging