Quickstart Frontend Wayat
devonfw/hangar pull request #462
Opened 2022-11-30 17:28 UTC by lpinon

2022-12-01 11:13 UTC, ultymatom submitted a review, later dismissed

2022-12-16 14:26 UTC, albertdb requested changes

2022-12-16 14:26 UTC, albertdb commented on documentation/gcloud/quickstart-wayat-frontend.asciidoc
> +== Initializing a Cloud Run service using provided script
Not really

2022-12-19 08:16 UTC, lpinon commented on documentation/gcloud/quickstart-wayat-frontend.asciidoc
> +== Initializing a Cloud Run service using provided script
```suggestion
== Initializing Wayat Frontend using provided script

```

2022-12-19 09:33 UTC, closed without merging