324 access resources gui
devonfw/hangar pull request #482
Opened 2022-12-12 08:51 UTC by serhiibets

2022-12-12 08:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw/hangar?pullRequest=482) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/devonfw/hangar?pullRequest=482) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw/hangar?pullRequest=482) it.</sub>

2022-12-12 09:20 UTC, airherna requested changes
url_launcher is a package for Flutter. the lib is not flutter, is just pure Dart, because it has to work with both the CLI and the GUI.

The getResource methods in the façage should just return URL, so that the CLI or the GUI
are the ones that open it using their available methods (For the GUI the url_launcher package and the CLI our own open URL method).

Right now, this will work when called from the GUI, but if we tried to call it from the CLI it will not, because url_launcher depends on flutter packages.

2022-12-12 09:20 UTC, airherna commented on takeoff/takeoff_lib/lib/src/utils/url_launcher/gcloud_url.dart
> +class GCloudResourceUrl {
Replace this with an enum with a String value

2022-12-12 09:22 UTC, airherna requested changes

2022-12-12 09:22 UTC, airherna commented on takeoff/takeoff_gui/lib/features/details/pages/resource_details.dart
> +          }),
all of this calls can be replaced with:

onTap: controller.openIDE,

2022-12-12 11:14 UTC, serhiibets commented on takeoff/takeoff_lib/lib/src/utils/url_launcher/gcloud_url.dart
> +class GCloudResourceUrl {
Change to enum which return rawValue - baseUrl links

2022-12-12 11:33 UTC, serhiibets commented on takeoff/takeoff_gui/lib/features/details/pages/resource_details.dart
> +          }),
I change all comments, but here I can't because I need to put ResourceType arg in the func like this controller.openResource(ResourceType.ide)

Check please.

2022-12-12 14:50 UTC, airherna requested changes

2022-12-12 14:50 UTC, airherna commented on takeoff/takeoff_gui/lib/features/details/pages/resource_details.dart
> +        GestureDetector(
All the buttons can be extracted as a single widget with link and  name as parameters. Also take into account the mouse pointer when hovering over it. And change the styling to fit Material Design guidelines

2022-12-12 14:50 UTC, airherna commented on takeoff/takeoff_gui/lib/features/details/pages/resource_details.dart
> +          child: Observer(
This Observer is useless

2022-12-12 14:50 UTC, airherna commented on takeoff/takeoff_gui/lib/features/details/pages/resource_details.dart
> +          child: Observer(
This Observer is also useless. Check the rest of the code because there are more ocurrences

2022-12-12 14:50 UTC, airherna commented on takeoff/takeoff_lib/lib/src/takeoff_facade.dart
> +  Uri getGCloudResourceUrl(String project, ResourceType resourceType) {
The facade should ideally only contain public methods. This should be moved to the GCloudController

2022-12-12 14:51 UTC, airherna commented on takeoff/takeoff_gui/lib/features/details/pages/resource_details.dart
> +          }),
Then use an arrow function () => method(args)

2022-12-12 14:52 UTC, airherna commented on takeoff/takeoff_gui/lib/features/details/pages/resource_details.dart
> +          }),
And this openIDE does not require any arguments. I don't understand this response

2022-12-12 15:08 UTC, serhiibets commented on takeoff/takeoff_gui/lib/features/details/pages/resource_details.dart
> +          child: Observer(
Fixed

2022-12-12 15:08 UTC, serhiibets commented on takeoff/takeoff_gui/lib/features/details/pages/resource_details.dart
> +          child: Observer(
Fixed

2022-12-12 15:35 UTC, serhiibets commented on takeoff/takeoff_gui/lib/features/details/pages/resource_details.dart
> +        GestureDetector(
Fixed

2022-12-13 07:51 UTC, airherna requested changes

2022-12-13 08:20 UTC, serhiibets commented on takeoff/takeoff_lib/pubspec.yaml
> +  url_launcher: ^6.1.7
Fixed

2022-12-13 08:21 UTC, serhiibets commented on takeoff/takeoff_gui/lib/features/home/controllers/projects_controller.dart
> +      await launchUrl(url);
Fixed

2022-12-13 08:23 UTC, serhiibets commented on takeoff/takeoff_lib/lib/src/controllers/cloud/gcloud/gcloud_controller_impl.dart
> +        String url = "${GCloudResourceUrl.baseSourcePath}/$project/backend/";
Fixed

2022-12-13 08:24 UTC, serhiibets commented on takeoff/takeoff_lib/lib/src/controllers/cloud/gcloud/gcloud_controller.dart
> +import 'dart:html';
Fixed

2022-12-13 16:12 UTC, airherna requested changes
The app crashes with this error when trying to access a project page

![image](https://user-images.githubusercontent.com/101186485/207385157-a4def033-9a84-4e3c-9fe4-16277c0e184f.png)

2022-12-14 10:14 UTC, airherna approved these changes

2022-12-14 10:14 UTC, merged