Feature/package pipeline bug for flutter platforms
devonfw/hangar pull request #489
Opened 2022-12-13 08:07 UTC by capf4bbo

2022-12-14 12:17 UTC, lpinon approved these changes

2022-12-14 12:29 UTC, ultymatom commented on scripts/pipelines/gcloud/pipeline_generator.sh
> +FLAGS=$(getopt -a --options c:n:d:a:b:l:i:u:p:m:h --long "config-file:,pipeline-name:,local-directory:,artifact-path:,target-branch:,language:,build-pipeline-name:,sonar-url:,sonar-token:,image-name:
ypu deleted rancher, be careful as an argument

2022-12-14 12:35 UTC, lpinon submitted a review, later dismissed

2022-12-14 12:37 UTC, ultymatom approved these changes

2022-12-14 12:43 UTC, albertdb requested changes

2022-12-14 12:43 UTC, albertdb commented on documentation/src/common_templates/setup-package-pipeline.asciidoc
> +--flutter-android-platform     [Required, if Flutter] Android platform to compile.
```suggestion
--flutter-web-platform         [Required, if Flutter] Compile Web platform.
--flutter-android-platform     [Required, if Flutter] Compile Android platform.
```

2022-12-14 12:43 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +    echo "      --flutter-android-platform  [Required, if Flutter] Android platform to compile."
```suggestion
    echo "      --flutter-web-platform  [Required, if Flutter] Compile Web platform to ."
    echo "      --flutter-android-platform  [Required, if Flutter] Compile Android platform."
```

2022-12-15 09:59 UTC, albertdb commented on scripts/pipelines/common/pipeline_generator.lib
> +    echo "      --flutter-web-platform  [Required, if Flutter] Compile Web platform to ."
```suggestion
    echo "      --flutter-web-platform  [Required, if Flutter] Compile Web platform."
```

2022-12-15 10:05 UTC, albertdb commented on scripts/pipelines/gcloud/templates/package/package-pipeline.cfg
> +[ "$language" == "flutter" ] && mandatoryFlags=$mandatoryFlags"${registryLocation},${languageVersion},${flutterPlatformDefined},"
```suggestion
[ "$language" == "flutter" ] && mandatoryFlags=$mandatoryFlags"${registryLocation},${languageVersion},${webPlatform}${androidPlatform},"
```

Shouldm't this be like this? Ask @ultymatom in case of doubt.

2022-12-15 10:14 UTC, ultymatom approved these changes

2022-12-15 10:17 UTC, ultymatom commented on scripts/pipelines/gcloud/templates/package/package-pipeline.cfg
> +[ "$language" == "flutter" ] && mandatoryFlags=$mandatoryFlags"${registryLocation},${languageVersion},${flutterPlatformDefined},"
yes that would work too
that would mean, if webPlatform AND androidP?latform are empty it will fail
but if one (or two) of them is not empty it will pass

2022-12-15 10:24 UTC, abcarcol approved these changes

2022-12-15 10:27 UTC, albertdb approved these changes

2022-12-15 10:30 UTC, merged