Enhancement/test-pipeline-artifact-usage
devonfw/hangar pull request #49
Opened 2022-03-30 14:26 UTC by mcerverc

2022-03-31 13:58 UTC, albertdb requested changes

2022-03-31 14:11 UTC, mcerverc commented on scripts/pipelines/azure-devops/templates/library-package/library-package-pipeline.yml.template
> +    pipeline: $(buildPipelineName)
Yes, the name of the variable in the library-package template was incorrect

2022-03-31 15:15 UTC, mcerverc commented on scripts/pipelines/azure-devops/templates/library-package/library-package-pipeline.yml.template
> +    pipeline: $(buildPipelineName)
I think in the older version of pipeline_generator the var name was buildPipeline. Because that the script worked when i did it. Now is buildPipelineName

2022-03-31 15:21 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/library-package/library-package-pipeline.yml.template
> +    pipeline: $(buildPipelineName)
Have you tested this change? I'm sure it breaks. The pipeline variable is defined in package pipeline definition as buildPipeline.

2022-04-04 09:26 UTC, albertdb submitted a review, later dismissed

2022-04-05 06:31 UTC, jbellver99 approved these changes

2022-04-05 07:58 UTC, jbellver99 requested changes
In library-package-pipeline.yml.template change the trigger to trigger: none like in other ymls

2022-04-05 08:08 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/test/test-pipeline.cfg
> +    az pipelines variable create --name "buildPipeline" --pipeline-name $pipelineName --value ${buildPipelineName}
I think for more consistency we should keep the name as buildPipelineName
I made the mistake in my package pipeline, I'm going to correct it also

2022-04-05 08:09 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/library-package/library-package-pipeline.cfg
> +    az pipelines variable create --name "qualityPipeline" --pipeline-name $pipelineName --value ${qualityPipelineName}
Same as for the test pipeline, for more consistency we should have qualityPipelineName

2022-04-05 08:09 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/library-package/library-package-pipeline.cfg
>      az pipelines variable create --name "buildPipeline" --pipeline-name $pipelineName --value ${buildPipelineName}
for more consistency we should have buildPipelineName

2022-04-05 10:58 UTC, albertdb approved these changes

2022-04-05 11:04 UTC, jbellver99 approved these changes

2022-04-05 13:24 UTC, merged