Feature/372 compress build artifact
devonfw/hangar pull request #496
Opened 2022-12-14 11:35 UTC by Jorge-Dacal

2022-12-14 13:16 UTC, albertdb requested changes

2022-12-14 13:16 UTC, albertdb commented on scripts/pipelines/gcloud/templates/build/build-pipeline.yml.template
> +    tar --zstd -cf zstd_artifacts/build_${BUILD_ID}.tar.zst --exclude=./zstd_artifacts ${_TARGET_DIRECTORY}
Better exclude tar, no need to create a directory.

2022-12-14 13:16 UTC, albertdb commented on scripts/pipelines/gcloud/templates/quality/quality-pipeline.yml.template
> +- id: "Run Sonarqube"
```suggestion
- id: "Run SonarQube scanner"
```

2022-12-15 09:56 UTC, albertdb commented
For closing #483, this should address last item in that issue.

Review comments not addressed.

2022-12-15 10:32 UTC, Jorge-Dacal commented on scripts/pipelines/gcloud/templates/build/build-pipeline.yml.template
> +    tar --zstd -cf zstd_artifacts/build_${BUILD_ID}.tar.zst --exclude=./zstd_artifacts ${_TARGET_DIRECTORY}
Is not possible, when you exclude a file, the file must be exist, if not, the command fail because the file appear after the execution and is not excluded.

![image](https://user-images.githubusercontent.com/32701664/207836614-1bff0d64-10cb-4fd1-a658-a73c575b1033.png)

In the image you can see that the execution cannot be done without create a directory and exclude it.

2022-12-15 10:35 UTC, Jorge-Dacal commented on scripts/pipelines/gcloud/templates/quality/quality-pipeline.yml.template
> +- id: "Run Sonarqube"
Now this is not the name of the id

2022-12-15 10:38 UTC, Jorge-Dacal commented on .vscode/settings.json
> +{
removed

2022-12-15 11:53 UTC, albertdb commented on scripts/pipelines/gcloud/templates/deploy-cloud-run/deploy-cloud-run-pipeline.yml.template
> +- id: "Run deploy script for cloud run"
```suggestion
- id: "Run deploy to Cloud Run script"
```

2022-12-15 11:57 UTC, albertdb requested changes

2022-12-15 11:57 UTC, albertdb commented on scripts/pipelines/gcloud/templates/build/build-pipeline.yml.template
> +- id: "Run build script"
```suggestion
- id: "Run Build script"
```

2022-12-15 11:57 UTC, albertdb commented on scripts/pipelines/gcloud/templates/deploy-cloud-run/deploy-cloud-run-pipeline.yml.template
> +- id: "Run deploy to Cloud Run script"
```suggestion
- id: "Run Deploy to Cloud Run script"
```

2022-12-15 11:57 UTC, albertdb commented on scripts/pipelines/gcloud/templates/gke/gke-provisioning.yml.template
> +- id: "Run terraform"
```suggestion
- id: "Run Terraform"
```

2022-12-15 11:57 UTC, albertdb commented on scripts/pipelines/gcloud/templates/package/package-pipeline.yml.template
> +- id: "Run package script"
```suggestion
- id: "Run Package script"
```

2022-12-15 11:57 UTC, albertdb commented on scripts/pipelines/gcloud/templates/quality/quality-pipeline.yml.template
> +- id: "Run quality script"
```suggestion
- id: "Run Quality script"
```

2022-12-15 11:57 UTC, albertdb commented on scripts/pipelines/gcloud/templates/security/security-pipeline.yml.template
> +- id: "checkov analysis"
```suggestion
- id: "Run Checkov analysis"
```

2022-12-15 11:57 UTC, albertdb commented on scripts/pipelines/gcloud/templates/test/test-pipeline.yml.template
> +- id: "Run test script"
```suggestion
- id: "Run Test script"
```

2022-12-15 12:01 UTC, Jorge-Dacal commented on scripts/pipelines/gcloud/templates/build/build-pipeline.yml.template
> +    tar --zstd -cf zstd_artifacts/build_${BUILD_ID}.tar.zst --exclude=./zstd_artifacts ${_TARGET_DIRECTORY}
Replaced by touch

2022-12-15 12:04 UTC, Jorge-Dacal commented on scripts/pipelines/gcloud/templates/build/build-pipeline.yml.template
> +- id: "Run build script"
For me, this should be in lowercase, only first letter in a phrase should be on uppercase

2022-12-15 12:10 UTC, albertdb approved these changes

2022-12-15 12:13 UTC, albertdb approved these changes

2022-12-15 12:21 UTC, abcarcol approved these changes

2022-12-15 12:34 UTC, merged