Add QuickStart get URLs for fe-repo and be-repo (Not tested for now)
devonfw/hangar pull request #523
Opened 2022-12-21 14:41 UTC by serhiibets

2022-12-21 14:52 UTC, capf4bbo requested changes

2022-12-21 14:52 UTC, capf4bbo commented on takeoff/takeoff_lib/lib/src/controllers/cloud/gcloud/gcloud_controller_impl.dart
> +  bool _isQuickStartProject(String project) {
Instead of _ use @visibleForTesting and add unit testing for it, with this cases:
1- wayat-takeoff-1-2-1-2-2000
2- wayat-takeoff-1-12-1-12-2000
3- wayat-takeoff-11-12-11-12-2000

2022-12-21 14:52 UTC, capf4bbo commented on takeoff/takeoff_lib/lib/src/controllers/cloud/gcloud/gcloud_controller_impl.dart
> +    return rule.hasMatch(project) ? true : false;
Just leave return rule.hasMatch(project), no need for conditional statement

2022-12-21 14:56 UTC, serhiibets commented on takeoff/takeoff_lib/lib/src/controllers/cloud/gcloud/gcloud_controller_impl.dart
> +    return rule.hasMatch(project) ? true : false;
Agree. 
Fixed

2022-12-21 18:29 UTC, serhiibets commented on takeoff/takeoff_lib/lib/src/controllers/cloud/gcloud/gcloud_controller_impl.dart
> +  bool _isQuickStartProject(String project) {
Fixed and tested

2022-12-22 07:46 UTC, capf4bbo requested changes

2022-12-22 07:46 UTC, capf4bbo commented on takeoff/takeoff_lib/test/src/controllers/cloud_providers/gcloud_controller_test.dart
> +  test("RegExp match projectId", () {
In this test, please do not use a random number, use cases that I wrote you in previous changes

2022-12-22 07:46 UTC, capf4bbo commented on takeoff/takeoff_lib/test/src/controllers/cloud_providers/gcloud_controller_test.dart
> +    int random = Random().nextInt(99);
In this test, please do not use a random number, use one correct case that I wrote you in previous changes

2022-12-22 07:46 UTC, capf4bbo commented on takeoff/takeoff_lib/test/src/controllers/cloud_providers/gcloud_controller_test.dart
> +    RegExp rule = RegExp(
Do not rewrite the isQuickStartProject method, just call isQuickStartProject and check with cases that it returns true or false

2022-12-22 08:02 UTC, serhiibets commented on takeoff/takeoff_lib/test/src/controllers/cloud_providers/gcloud_controller_test.dart
> +  test("RegExp match projectId", () {
Ok. 
Fixed.

2022-12-22 08:06 UTC, serhiibets commented on takeoff/takeoff_lib/test/src/controllers/cloud_providers/gcloud_controller_test.dart
> +    RegExp rule = RegExp(
Fixed

2022-12-22 08:06 UTC, serhiibets commented on takeoff/takeoff_lib/test/src/controllers/cloud_providers/gcloud_controller_test.dart
> +    int random = Random().nextInt(99);
Fixed

2022-12-22 08:11 UTC, capf4bbo requested changes

2022-12-22 08:11 UTC, capf4bbo commented on takeoff/takeoff_lib/test/src/controllers/cloud_providers/gcloud_controller_test.dart
> +
Add false cases too

2022-12-22 08:11 UTC, capf4bbo commented on takeoff/takeoff_lib/test/src/controllers/cloud_providers/gcloud_controller_test.dart
> +    int random = Random().nextInt(99);
It is not fixed, please read it again

2022-12-22 08:17 UTC, serhiibets commented on takeoff/takeoff_lib/test/src/controllers/cloud_providers/gcloud_controller_test.dart
> +
Fixed

2022-12-22 08:32 UTC, serhiibets commented on takeoff/takeoff_lib/test/src/controllers/cloud_providers/gcloud_controller_test.dart
> +    int random = Random().nextInt(99);
Fixed

2022-12-22 08:50 UTC, capf4bbo approved these changes

2022-12-22 08:51 UTC, merged