implemented functional test pipeline
devonfw/hangar pull request #68
Opened 2022-04-21 09:03 UTC by zichriste

Implemented functional build & testing pipelines.
Build pipeline will be fitted to corresponding task as soon as it's done.

2022-04-21 09:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw/hangar?pullRequest=68) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/devonfw/hangar?pullRequest=68) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw/hangar?pullRequest=68) it.</sub>

2022-04-28 07:06 UTC, zichriste commented
For the current (jest-junit) solution we need to install jest-junit to the project and add something like this to the package.json:
"jest-junit": {
    "suiteName": "jest tests",
    "outputDirectory": ".",
    "outputName": "TEST-jest.xml",
    "uniqueOutputName": "false",
    "classNameTemplate": "{classname}-{title}",
    "titleTemplate": "{classname}-{title}",
    "ancestorSeparator": " › ",
    "usePathForSuiteName": "true"
  }

2022-05-17 10:39 UTC, ultymatom submitted a review, later dismissed

2022-05-17 10:39 UTC, jbellver99 approved these changes

2022-05-31 07:22 UTC, jbellver99 requested changes

2022-05-31 07:22 UTC, jbellver99 commented on documentation/azure-devops/setup-test-pipeline.asciidoc
> +==== Node project
```suggestion
==== Node.js project
```

2022-06-09 11:50 UTC, jbellver99 approved these changes

2022-06-09 11:50 UTC, albertdb approved these changes

2022-06-09 11:50 UTC, merged