Feature/node library package pipeline
devonfw/hangar pull request #71
Opened 2022-04-21 15:42 UTC by shiftwolf

2022-04-21 15:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw/hangar?pullRequest=71) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/devonfw/hangar?pullRequest=71) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw/hangar?pullRequest=71) it.</sub>

2022-05-13 17:49 UTC, shiftwolf commented on scripts/pipelines/azure-devops/templates/library-package/library-package-pipeline.cfg
> +        envsubst < settings-template.xml > "${localDirectory}/${scriptFilePath}/settings.xml"
This was pre-existing but I'll change it accordingly.

2022-05-13 18:04 UTC, shiftwolf commented on documentation/azure-devops/setup-library-package-pipeline.asciidoc
> +
Ok, in retrospective this seems very obvious. If you have any suggestions for naming conventions that would be helpful, as I would need 2 different ".npmrc.template" files. In the meantime I'll go with ".npmrc.project.template" for this one and ".npmrc.user.template" for the user-level npmrc.

2022-05-16 08:15 UTC, mcerverc commented on documentation/azure-devops/setup-library-package-pipeline.asciidoc
> +
The naming convention you chose seems proper for me :)

2022-05-16 08:16 UTC, mcerverc approved these changes

2022-05-19 10:31 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/library-package/library-package-pipeline.cfg
> +        envsubst < .npmrc.project.template > "${localDirectory}/.npmrc"
Be careful this file is not being commited

2022-05-19 10:58 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/library-package/.npmrc.user.template
> +; end auth token
$email and $encodedPatToken are not being replaced when I execute it, when seeing your code I don't see anything wrong because you export corectly the values before the envsubst, was this working when you fully tested the script ?

2022-05-19 11:06 UTC, shiftwolf commented on scripts/pipelines/azure-devops/templates/library-package/.npmrc.user.template
> +; end auth token
I'll look into it.

2022-05-19 12:19 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/library-package/.npmrc.user.template
> +//pkgs.dev.azure.com/${organization}/_packaging/${organization}/npm/:email=$email
```suggestion
//pkgs.dev.azure.com/${organization}/_packaging/${feed}/npm/registry/:username=$organization
//pkgs.dev.azure.com/${organization}/_packaging/${feed}/npm/registry/:_password=$encodedPatToken
//pkgs.dev.azure.com/${organization}/_packaging/${feed}/npm/registry/:email=$email
//pkgs.dev.azure.com/${organization}/_packaging/${feed}/npm/:username=$organization
//pkgs.dev.azure.com/${organization}/_packaging/${feed}/npm/:_password=$encodedPatToken
//pkgs.dev.azure.com/${organization}/_packaging/${feed}/npm/:email=$email
```

The URL to access the feed was not correct

2022-05-19 13:15 UTC, shiftwolf commented on scripts/pipelines/azure-devops/templates/library-package/.npmrc.user.template
> +//pkgs.dev.azure.com/${organization}/_packaging/${organization}/npm/:email=$email
Just to confirm, this fixes the issue with the $email and $patToken not being replaced?

2022-05-19 13:16 UTC, ultymatom commented on documentation/azure-devops/setup-library-package-pipeline.asciidoc
> +./pipeline_generator.sh -c ./templates/library-package/library-package-pipeline.cfg -n library-package-pipeline -l node -d C:/Users/$USERNAME/Desktop/node-library-project --build-pipeline-name node-l
in the pipeline-generator.sh some of the argument are not written in the help function (I think it is an error that comes from before, but better adding them)

2022-05-19 13:17 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/library-package/.npmrc.user.template
> +; end auth token
forget about it, now without any changed from it is working correctly^^

2022-05-19 13:18 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/library-package/library-package-pipeline.cfg
> +    echo -e "${green}Creating a ${feedType} feed..."
```suggestion
    echo -e "${green}Creating a ${feedType} feed...${white}"
```

Without changing back to white all the next lines are green

2022-05-19 13:23 UTC, ultymatom commented on documentation/azure-devops/setup-library-package-pipeline.asciidoc
> +./pipeline_generator.sh -c ./templates/library-package/library-package-pipeline.cfg -n library-package-pipeline -l node -d C:/Users/$USERNAME/Desktop/node-library-project --build-pipeline-name node-l
If I am not wrong I am not sure you need to have the build pipeline as an argument. Because we use the --build-pipeline-name in case of a java library so that we can download the application that have been built before, in the node case I am not sure this is needed. (in that case the yml.template needs to be updated with conditional step)

2022-05-19 13:25 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/library-package/library-package-pipeline.cfg
>  # Path to the scripts.
(I put a comment here but this is related to the line with mandatory flags but github does not let me comment on that line)

if as said on another comment we don't need the --build-pipeline-name flag, you will probably need to set the variable mandatoryFlags conditionally

2022-05-19 13:26 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/library-package/.npmrc.user.template
> +//pkgs.dev.azure.com/${organization}/_packaging/${organization}/npm/:email=$email
Actually after I did these changes in local it was working but I don't know how ^^
but I put the comment about the two variables not being replaced a resolved

2022-05-19 13:30 UTC, shiftwolf commented on scripts/pipelines/azure-devops/templates/library-package/.npmrc.user.template
> +//pkgs.dev.azure.com/${organization}/_packaging/${organization}/npm/:email=$email
Also, I'm not sure how this could happen. At some point I was able to make it work (or it appeared so at least) but I don't know what went wrong from there. I'll definitely do much more (regression) testing in the future. Thanks for the help in finding this issue though.

2022-05-20 06:22 UTC, shiftwolf commented on scripts/pipelines/azure-devops/templates/library-package/library-package-pipeline.cfg
> +        envsubst < .npmrc.project.template > "${localDirectory}/.npmrc"
As far as I have tested now this is not a problem, at least from the npm side of things, git may be different. But to be absolutely sure I will try to add a line to both the .npmignore and .git/info/exclude files to explicitly ignore .npmrc files.

2022-05-20 06:22 UTC, shiftwolf commented on scripts/pipelines/azure-devops/templates/library-package/library-package-pipeline.cfg
> +        envsubst < .npmrc.project.template > "${localDirectory}/.npmrc"
As far as I have tested now this is not a problem, at least from the npm side of things, git may be different. But to be absolutely sure I will try to add a line to both the .npmignore and .git/info/exclude files to explicitly ignore .npmrc files.

2022-05-20 07:39 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/library-package/library-package-pipeline.cfg
> +        envsubst < .npmrc.project.template > "${localDirectory}/.npmrc"
it will work in local but your pipeline won't be working because you won't have teh .npmrc at the root of your repo so the URL that npm publish will use is not the righ one

2022-06-02 11:40 UTC, shiftwolf commented
I have tested also on Azure DevOps but I will continue to test this because there may be some edge cases that are not working.

The main problem currently is that once this uploaded to Azure DevOps, it will break both the build and the quality pipeline, as they can't handle the `.npmrc` that is generated here. So far the only solutions I was able to find were changes to the build and quality pipelines themselves, like adding an additional parameter to use the npm public registry:  `--registry=https://registry.npmjs.org/` which causes the `.npmrc` contents to be ignored. Would that be a viable solution?

2022-06-06 09:47 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/library-package/library-package-pipeline.cfg
> -mandatoryFlags="$pipelineName,$localDirectory,$language,$buildPipelineName,$qualityPipelineName,"
Be careful, here you you removed the mandatory flag variable,
you still need tha var, I meant define it conditionally as in the package pipeline:
https://github.com/devonfw/hangar/blob/master/scripts/pipelines/azure-devops/templates/package/package-pipeline.cfg

In that file we defined conditionally the mandatory flags depending on if we use AWS to store the image or another registry.

(don't hesitate to contact me on teams if anything in unclear , (I'm Timothé Paty for info))

2022-06-08 13:42 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/library-package/library-package-pipeline.cfg
> -mandatoryFlags="$pipelineName,$localDirectory,$language,$buildPipelineName,$qualityPipelineName,"
Indeed as you said me, the flags are defined lower in the file so my commentary makes no sense

2022-06-08 14:54 UTC, ultymatom commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    echo "      --build-pipeline-name   [Required, if Java / Maven] Build pipeline name."
I'm writting here because I can't put it on the line of the docs, but you have to write in the docs that it is not mandatory the build pipeline name (in the two lines it gives info about it)

2022-06-09 14:51 UTC, shiftwolf commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    echo "      --build-pipeline-name   [Required, if Java / Maven] Build pipeline name."
I hope my latest change resolved this.

2022-06-23 15:24 UTC, ultymatom approved these changes

2022-06-27 15:29 UTC, albertdb requested changes

2022-06-27 15:29 UTC, albertdb commented on documentation/azure-devops/setup-library-package-pipeline.asciidoc
> += Setting up a library package pipeline using Azure DevOps
```suggestion
= Setting up a library package pipeline on Azure DevOps
```

2022-06-27 15:29 UTC, albertdb commented on documentation/azure-devops/setup-library-package-pipeline.asciidoc
> +In this section we will create a package pipeline to generate a distributable of a library and push it to a feed in Azure DevOps. This pipeline will be configured in order to be triggered every time
```suggestion
In this section we will create a package pipeline to generate a distributable of a library and push it to a feed in Azure DevOps. This pipeline will be configured in order to be triggered every time quality pipeline is executed successfully on a commit for `release/*` and `develop` branches, requiring manual launch for other branches but still enforcing that quality pipeline has passed. Depending on the language, it consumes the artifact produced by the build pipeline.
```

2022-06-27 15:32 UTC, albertdb approved these changes

2022-06-27 15:33 UTC, merged