Node build
devonfw/hangar pull request #74
Opened 2022-04-22 14:05 UTC by BenjaminE98

Added a target-directory flag. If the user does not enter a target-directory we assume a default value. The default value is based on the target language. For node the directory is defaulted to "./" and for java the directory is defaulted to "./target"

2022-05-03 13:16 UTC, jbellver99 requested changes

2022-05-03 13:16 UTC, jbellver99 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    fi
No need to add this on this script. This should go in the build pipeline config file.

2022-05-03 13:16 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/build/build-pipeline.cfg
> +    az pipelines variable create --name "targetPath" --pipeline-name "${buildPipelineName}" --value "${targetDirectory}"
Create a new function called AddPipelineVariables and insert this part in this function.

2022-05-03 13:16 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/build/build-pipeline.cfg
> +    az pipelines variable create --name "targetPath" --pipeline-name "${buildPipelineName}" --value "${targetDirectory}"
Create a new function called AddPipelineVariables and insert this part in this function.

2022-05-03 13:16 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/build/build-pipeline.cfg
> +            java) targetDirectory="./target/" ;;
Delete the java case and add quarkus and quarkus-jvm cases.

2022-05-03 13:16 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/build/build-pipeline.cfg
> +            java) targetDirectory="./target/" ;;
Delete the java case and add quarkus and quarkus-jvm cases.

2022-05-03 13:16 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/build/build-pipeline.cfg
> +mandatoryFlags="$pipelineName,$localDirectory,$language"
Do not delete the last ",", if not the script does not work correctly.

2022-05-03 13:16 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/build/build-pipeline.cfg
> +mandatoryFlags="$pipelineName,$localDirectory,$language"
Do not delete the last ",", if not the script does not work correctly.

2022-05-03 13:16 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/build/build-pipeline.yml.template
> +  artifact: target
```suggestion
  artifact: $(targetPath)
```

2022-05-03 13:16 UTC, jbellver99 commented on scripts/pipelines/azure-devops/templates/build/build-pipeline.yml.template
> +  artifact: target
```suggestion
  artifact: $(targetPath)
```

2022-05-04 08:06 UTC, BenjaminE98 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    fi
Moved out of the pipeline generator into the cfg

2022-05-04 08:07 UTC, BenjaminE98 commented on scripts/pipelines/azure-devops/templates/build/build-pipeline.cfg
> +    az pipelines variable create --name "targetPath" --pipeline-name "${buildPipelineName}" --value "${targetDirectory}"
added the function and moved the section into that

2022-05-04 08:08 UTC, BenjaminE98 commented on scripts/pipelines/azure-devops/templates/build/build-pipeline.cfg
> +            java) targetDirectory="./target/" ;;
added the cases for quarkus

2022-05-04 08:08 UTC, BenjaminE98 commented on scripts/pipelines/azure-devops/templates/build/build-pipeline.cfg
> +mandatoryFlags="$pipelineName,$localDirectory,$language"
reverted the change and included the ,

2022-05-04 08:08 UTC, BenjaminE98 commented on scripts/pipelines/azure-devops/templates/build/build-pipeline.yml.template
> +  artifact: target
Applied the change accordingly

2022-05-06 12:56 UTC, jbellver99 requested changes

2022-05-06 12:59 UTC, BenjaminE98 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    fi
Updated in a more recent commit

2022-05-09 06:53 UTC, jbellver99 approved these changes

2022-05-09 09:02 UTC, albertdb commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +
```suggestion

```

2022-05-09 09:04 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/build/build-pipeline.cfg
> +            quarkus-jvm) targetDirectory="./target/";;
```suggestion
            quarkus*) targetDirectory="./target/" ;;
```

Would this work? Try before accepting the suggestion.

2022-05-09 09:05 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/build/build-pipeline.yml.template
> +
```suggestion
```

2022-05-12 13:40 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/build/build-pipeline.cfg
> +    az pipelines variable create --name "targetPath" --pipeline-name "${buildPipelineName}" --value "${targetDirectory}"
```suggestion
    az pipelines variable create --name "targetPath" --pipeline-name "${pipelineName}" --value "${targetDirectory}"
```

2022-05-16 07:30 UTC, jbellver99 submitted a review, later dismissed

2022-05-17 10:26 UTC, jbellver99 reviewed
Add the explanation of the -t flag (--target directory) in the documentation, just like in the help function of the pipeline generator.

2022-05-18 10:12 UTC, jbellver99 approved these changes

2022-05-18 10:37 UTC, ultymatom submitted a review, later dismissed

2022-05-27 09:50 UTC, shiftwolf commented
When running this pipeline in this in Azure DevOps I get the following error message: `Artifact name is not valid: ./. It cannot contain '\', /', "', ':', '<', '>', '|', '*', and '?'`. This me be a setup problem on my end, but could also be a problem relating to this change. Just wanted to know what you think.

2022-05-27 13:53 UTC, shiftwolf commented on scripts/pipelines/azure-devops/templates/build/build-pipeline.yml.template
> +  artifact: $(targetPath)
From my (limited) understanding, I'd argue that this change should be reverted back to `artifact: target`. `artifact:` really only refers to an artifactName in this case and artifact names can't have special characters like slashes so this won't work with paths. If I revert this, the pipeline works just fine. Could be that I'm totally wrong though. @jbellver99

2022-05-31 09:47 UTC, shiftwolf commented on scripts/pipelines/azure-devops/templates/build/build-pipeline.yml.template
> +  artifact: $(targetPath)
But the issue is that we can't store paths in the artifact name, as certain special characters are not permitted like '/', which we need for paths. Or at least that's the error message I'm getting, when running the pipeline in its current state.

2022-06-01 07:55 UTC, BenjaminE98 commented on scripts/pipelines/azure-devops/templates/build/build-pipeline.yml.template
> +  artifact: $(targetPath)
![image](https://user-images.githubusercontent.com/51031065/171355172-18e55e3a-e15d-4525-9ca1-4be5af027533.png)
I was able to reproduce the error Timo was mentioning. 

Would it be a good idea to set the the artifact to the language name? Or maybe a mix of the language and the project-name so it can be clearly distinguishable?

2022-06-09 09:51 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/build/build-pipeline.yml.template
> +    script: echo '$(targetPath)'
```suggestion
```

2022-06-09 09:56 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/build/build-pipeline.cfg
> +    az pipelines variable create --name "artifactName" --pipeline-name "${pipelineName}" --value "BuildOutput"
```suggestion
```

2022-06-09 09:58 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/build/build-pipeline.yml.template
> +  artifact: $(artifactName)
```suggestion
  artifact: BuildOutput
```

2022-06-09 11:44 UTC, albertdb approved these changes

2022-06-09 11:45 UTC, jbellver99 approved these changes

2022-06-09 11:46 UTC, merged