adding subpath option for the create repo script
devonfw/hangar pull request #75
Opened 2022-04-26 11:13 UTC by ultymatom

2022-04-26 14:35 UTC, albertdb requested changes

2022-04-26 14:35 UTC, albertdb commented on documentation/azure-devops/setup-repository-script.asciidoc
>  -r, --remove-other-branches            When combined with -b (and possibly -s), removes any other remaining branch.
```suggestion
-r, --remove-other-branches            Removes branches other than the one specified in -b (or default one).

```

2022-04-26 14:35 UTC, albertdb commented on documentation/azure-devops/setup-repository-script.asciidoc
> +    --subpath                          When importing from an URL, will initialize the repo with the subpath set. (ignored if -g, -b or -r not set)
```suggestion
    --subpath                          When combined with -g and -r, imports only the specified subpath of the source Git repository.

```

2022-04-26 14:35 UTC, albertdb commented on scripts/repositories/azure-devops/create-repo.sh
> +        echo "test $(pwd)"
Do we need to do that much given that we are using sparse checkout? I think we can make it simpler: sparse clone to `$name.tmp`, `mv $name.tmp/$subpath $name`, and `rm -r $name.tmp`, isn't it?

2022-04-26 14:51 UTC, ultymatom commented on scripts/repositories/azure-devops/create-repo.sh
> +        echo "test $(pwd)"
true

2022-04-28 15:48 UTC, ultymatom commented on scripts/repositories/azure-devops/create-repo.sh
> +      [ "$?" != "0" ] && exit 1
Not relevant as this is not a single command but a subshell before

2022-04-28 15:54 UTC, ultymatom commented on scripts/repositories/azure-devops/create-repo.sh
> +      cd "$name.tmp"
not relevant I have MSG error right after

2022-05-02 09:30 UTC, albertdb requested changes

2022-05-02 09:30 UTC, albertdb commented on scripts/repositories/azure-devops/create-repo.sh
>          git clone "$giturl_argument" "$name"
Why is this case different than the one in line 414?

2022-05-02 09:44 UTC, ultymatom commented on scripts/repositories/azure-devops/create-repo.sh
> + # Remove branches (other that master if -b flag and other than reference if no)
other than master if -b flag is set,
other than reference if no

2022-05-02 09:45 UTC, ultymatom commented on scripts/repositories/azure-devops/create-repo.sh
> +      (echo "The combination of the flags '-r' and '--subpath' has been detected, then we clone only the subpath: $subpath from the branch given or the default one."
Recomandation of the bot, because at the end I was doing cd ..

2022-05-02 09:57 UTC, ultymatom commented on scripts/repositories/azure-devops/create-repo.sh
>          git clone "$giturl_argument" "$name"
This is not the same case,

line 414: we import into azure the repo directly by giving to azure the URL of the original repo, and then we clone it in local (we clone from the azure URL)

444: we clone it (with the original repo URL), and then line 456 we execute push_existing_repo that will remove any branch except the default one and change the URl for pushing

2022-05-02 10:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw/hangar?pullRequest=75) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/devonfw/hangar?pullRequest=75) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: ultymatom<br/>:x: albertdb<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw/hangar?pullRequest=75) it.</sub>

2022-05-02 10:30 UTC, albertdb approved these changes

2022-05-02 10:43 UTC, mcerverc approved these changes

2022-05-02 10:58 UTC, merged