setup package pipeline for node app
devonfw/hangar pull request #76
Opened 2022-04-27 13:01 UTC by patricpoba

Block: modify "Setup Package pipeline" for devon4node

Issue: https://app.zenhub.com/workspaces/hangar-611f41e52d0d6b001dffb302/issues/devonfw/hangar/56

2022-04-27 13:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw/hangar?pullRequest=76) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/devonfw/hangar?pullRequest=76) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw/hangar?pullRequest=76) it.</sub>

2022-04-29 10:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw/hangar?pullRequest=76) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/devonfw/hangar?pullRequest=76) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw/hangar?pullRequest=76) it.</sub>

2022-05-02 12:28 UTC, patricpoba commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +    case "${flag}" in
duplicate

2022-05-02 12:29 UTC, patricpoba commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +    case "${flag}" in
@sonatype-lift help

2022-05-02 12:37 UTC, patricpoba commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +    case "${flag}" in
@CLAassistant help

2022-05-02 12:51 UTC, patricpoba commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +    case "${flag}" in
@albertdb This issue has been fixed but has not been marked as "outdated" by @sonatype-lift

2022-05-09 07:03 UTC, jbellver99 submitted a review, later dismissed

2022-05-12 06:35 UTC, mustafaokyay approved these changes

2022-05-13 12:12 UTC, albertdb requested changes
Please also take the improvements (changes requested by sonatype) to the quarkus-package script. Should be easy to do.

2022-05-13 12:12 UTC, albertdb commented on documentation/azure-devops/setup-package-pipeline.asciidoc
> +==== Node project
```suggestion
==== Node.js project
```

2022-05-13 12:12 UTC, albertdb commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +        *) echo "usage: $0 [f] [c] [u] [p] [r] [i] [b] [t] [a] [s] [l]" >&2
```suggestion
        *) echo "Error: Unexpected parameter." >&2
```

2022-05-17 14:03 UTC, jbellver99 approved these changes

2022-05-17 14:06 UTC, ultymatom approved these changes

2022-06-02 10:18 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +        t) packageDotJsonPath=${OPTARG};;
Be careful, we just noticed that here the -t tag, will the path to the pom.xml from the quarkus application because in the yml.template it has been hardcoded

2022-06-02 10:18 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +        t) packageDotJsonPath=${OPTARG};;
Be careful, we just noticed that here the -t tag, will the path to the pom.xml from the quarkus application because in the yml.template it has been hardcoded

2022-06-02 10:19 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +        t) packageDotJsonPath=${OPTARG};;
it has to be different depending on node or quarkus

2022-06-02 10:19 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +        t) packageDotJsonPath=${OPTARG};;
it has to be different depending on node or quarkus

2022-06-02 10:20 UTC, ultymatom submitted a review, later dismissed
See comment for the -t flag of the <lamguage>-package.sh

2022-06-09 13:59 UTC, albertdb commented
@patricpoba Any progress on this?

2022-06-17 09:51 UTC, patricpoba commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +        t) packageDotJsonPath=${OPTARG};;
@ultymatom please do you mean I should use a different alphabet as the flag for packageDotJsonPath whilst maintaining the -t flag for the path to the pom.xml ?

2022-06-20 08:01 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +        t) packageDotJsonPath=${OPTARG};;
no, I mean that in the package-pipeline.yml we called the package.sh, and as we had at first only for quarkyus we give hardcoded the pompath, but now as you added node, the pipeline needs to have a different value depending on node or quarkus, but I don't see any change into the yml template

2022-06-20 16:59 UTC, patricpoba commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +        t) packageDotJsonPath=${OPTARG};;
duplicate comment. :-)

2022-06-21 09:09 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/package/package-pipeline.cfg
> +        break
```suggestion
        echo $i | grep $language > /dev/null && imageTagFile=$(echo $i | cut -d':' -f2) && break
```
I noticed I made an error because the break was getting executed on the first path even if it was not the right one

2022-06-21 09:12 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/package/package-pipeline.cfg
> +        echo $i | grep $language > /dev/null && dockerFile=$(echo $i | cut -d':' -f2) && break
I put a comment so you can be aware of a change I made, just mark it as resolved when you saw it

When I did the first package pipeline I made a mistake here, the break was getting executed in any case which is not what we want, I also applied it to imageTagFile

2022-06-21 09:14 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +        t) packageDotJsonPath=${OPTARG};;
@patricpoba 

Everything seems correct for me :)

I just could not test it because I don't have a project devon4node with a Dockerfile, but seing your commits everything should be working

2022-06-21 13:01 UTC, patricpoba commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +        t) packageDotJsonPath=${OPTARG};;
all right. thanks :-)

2022-06-21 22:16 UTC, patricpoba commented
@ultymatom  I thought of doing some refactoring to remove the code duplication in node-package.sh and quarkus-package.sh.  could you please check if its necessary and complete? if not should I rollback the refactoring I did ?

2022-06-22 11:27 UTC, albertdb commented on documentation/azure-devops/setup-package-pipeline.asciidoc
> +  -v <image tag file> \
this should be removed also, right?

2022-06-22 17:59 UTC, ultymatom submitted a review, later dismissed

2022-06-23 11:38 UTC, albertdb commented on documentation/azure-devops/setup-package-pipeline.asciidoc
> +  -v <image tag file> \
```suggestion
```

2022-06-23 11:39 UTC, albertdb approved these changes

2022-06-23 11:39 UTC, merged