Feature/enhancement77 Accept relative paths on pipeline generator user input
devonfw/hangar pull request #86
Opened 2022-04-29 16:14 UTC by shiftwolf

This code was tested and should work.

Closes #77

2022-04-29 16:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw/hangar?pullRequest=86) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/devonfw/hangar?pullRequest=86) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw/hangar?pullRequest=86) it.</sub>

2022-05-11 10:02 UTC, jbellver99 requested changes

2022-05-11 10:02 UTC, jbellver99 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    localDirectory=$(python -c "from pathlib import Path; print(Path('${localDirectory}').resolve().as_posix());")
The current solution is not working, try to use an existing function from bash to convert the path.

2022-05-11 10:11 UTC, shiftwolf commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    localDirectory=$(python -c "from pathlib import Path; print(Path('${localDirectory}').resolve().as_posix());")
Do you have an example so I could reproduce? It seemed to be working for me.

2022-05-11 11:12 UTC, shiftwolf commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    localDirectory=$(python -c "from pathlib import Path; print(Path('${localDirectory}').resolve().as_posix());")
It had to do with the execution order. I must've missed this issue. I have fixed it, and it is working now as expected.

2022-05-12 16:23 UTC, shiftwolf commented
I added the backslash functionality that @jbellver99 asked for. I kept the Python (for now) because I still think it's much cleaner when accounting for all edge cases and we're using it in the pipeline-generator anyway (let me know if you want to have it replaced with pure bash anyway). It's worth mentioning that sonatype-lift has identified a bug in my code (which I have overruled by setting it to ignore) but as I have explained in the resolved conversation, I think this is a rare case where the bot is clearly wrong. Other than that, I hope I didn't miss anything.

2022-05-12 16:50 UTC, shiftwolf commented
I also think the issue needs to be updated as it's clearly not just about absolute and relative paths. And we're also going to need a change in the documentation, saying that the local directory should be passed in quotation marks, otherwise paths using backslashes won't work in bash.

2022-05-13 07:27 UTC, shiftwolf commented
> Everything looks pretty good, the only use case that is missing is to accept unix style paths like /c/Users/jbellver/Desktop/Hangar Because if you input a path like this the current outout is C:/c/Users/jbellver/Dekstop/Hangar

Ok, then I must've misunderstood you again. I thought I should not consider a path like "/c/Users/..", but you meant the opposite, like that it was not supported before, but should be supported now.

2022-05-13 09:17 UTC, shiftwolf commented
I have now refactored my solution. Initially I didn't want to use make use of "cd" given that it may be problematic when the directory doesn't exist. To address this, I have also included a guard-clause to catch this issue when it happens.

2022-05-13 09:43 UTC, jbellver99 reviewed
There is no need to check if the path exists, this is already done in the function createNewBranch.

The current solution is not changing the relative paths to absolute paths as it was doing before

2022-05-13 11:48 UTC, albertdb requested changes

2022-05-13 11:48 UTC, albertdb commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    [ $? != "0" ] && echo -e "${red}The local directory: '${localDirectory}' cannot be found, please check the path." && exit 1
```suggestion
    cd "${localDirectory}" || (echo -e "${red}Error: Local directory '${localDirectory}' does not exist. Check provided path." && exit 1)
```

Haven't tested, but this looks cleaner.

2022-05-13 11:56 UTC, albertdb requested changes
You should remove all the "CAUTION: Remember to write the path to the local repository with '/' and not '\' on Windows." on the guides using the pipeline generator as part of this PR.

Having to quote paths using backward slashes is a shell thing. If properly passed, with this we support all the path formats, and that's all we can do. Also, the new error message already suggests the quotes thing.

2022-05-13 13:11 UTC, shiftwolf commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    [ $? != "0" ] && echo -e "${red}The local directory: '${localDirectory}' cannot be found, please check the path." && exit 1
This is suggestion is not working (Parentheses create a subshell, therefore the "exit" is effectively ignored) but I have changed it slightly so that the behavior is the same as before. 
`cd "${localDirectory}" || { echo -e "${red}Error: Local directory '${localDirectory}' does not exist. Check provided path (missing quotes?)."; exit 1; }`

2022-05-16 07:45 UTC, jbellver99 submitted a review, later dismissed

2022-05-17 10:35 UTC, ultymatom approved these changes

2022-05-25 07:25 UTC, ultymatom commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    cd $currentDirectory
Be careful, you need to put double quote, because if there is a space in the variable it will fail

2022-05-25 13:37 UTC, shiftwolf commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +    localDirectory=${localDirectory//'\'/"/"}
I have elaborated on this issue earlier.

2022-05-30 10:01 UTC, ultymatom approved these changes
I've copied the changes to my branch for the pipeline generator for github and until now I have not meet any eror

2022-05-30 10:02 UTC, jbellver99 submitted a review, later dismissed

2022-06-02 09:16 UTC, albertdb approved these changes

2022-06-02 09:17 UTC, ultymatom approved these changes

2022-06-02 09:17 UTC, merged