Feature/rancher support aks
devonfw/hangar pull request #87
Opened 2022-05-02 07:07 UTC by jbellver99

2022-05-02 07:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw/hangar?pullRequest=87) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/devonfw/hangar?pullRequest=87) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw/hangar?pullRequest=87) it.</sub>

2022-05-02 07:10 UTC, jbellver99 commented on scripts/pipelines/azure-devops/pipeline_generator.sh
> +        --rancher)                installRancher="true"; shift 1;;
@sonatype-lift ignore

2022-06-16 10:00 UTC, albertdb requested changes
Add destroy option to pipeline, to keep in sync with EKS one.

2022-06-27 14:05 UTC, albertdb requested changes
I'm missing this part "Refer to the appendix to retrieve the DNS name of the Ingress controller independently.", which will make straightforward for the user to access Rancher, such as in https://github.com/devonfw/hangar/blob/master/documentation/azure-devops/setup-eks-provisioning-pipeline.asciidoc#appendix-interacting-with-the-cluster

Also please backport `--rancher` flag to EKS, and Rancher initial password retrieval to EKS guide.

2022-06-29 16:11 UTC, albertdb approved these changes

2022-06-29 16:11 UTC, merged