AWS examples for the package library pipeline
devonfw/hangar pull request #89
Opened 2022-05-04 14:01 UTC by shiftwolf

2022-05-11 09:35 UTC, jbellver99 approved these changes

2022-05-17 10:38 UTC, jbellver99 requested changes

2022-05-17 10:38 UTC, jbellver99 commented on documentation/azure-devops/setup-package-pipeline.asciidoc
> +CAUTION: Remember to write the path to the local repository with '/' and not '\' on Windows.
```suggestion
```

2022-05-17 10:38 UTC, jbellver99 commented on documentation/azure-devops/setup-package-pipeline.asciidoc
>  CAUTION: Remember to write the path to the local repository with '/' and not '\' on Windows.
```suggestion

```

2022-05-18 10:11 UTC, jbellver99 approved these changes

2022-05-18 10:37 UTC, ultymatom approved these changes

2022-06-09 14:06 UTC, albertdb requested changes

2022-06-09 14:06 UTC, albertdb commented on documentation/azure-devops/setup-package-pipeline.asciidoc
> +
```suggestion
```

2022-06-09 14:06 UTC, albertdb commented on documentation/azure-devops/setup-package-pipeline.asciidoc
> +
```suggestion
```

2022-06-09 14:06 UTC, albertdb commented on documentation/azure-devops/setup-package-pipeline.asciidoc
> +==== Node project
```suggestion
==== Node.js project

```

2022-06-09 14:06 UTC, albertdb commented on documentation/azure-devops/setup-package-pipeline.asciidoc
> +===== Non-AWS
```suggestion
===== Generic container registry
```

2022-06-09 14:06 UTC, albertdb commented on documentation/azure-devops/setup-package-pipeline.asciidoc
> +===== AWS
```suggestion
===== AWS ECR
```

2022-06-09 14:06 UTC, albertdb commented on documentation/azure-devops/setup-package-pipeline.asciidoc
> +===== Non-AWS
```suggestion
===== Generic container registry
```

2022-06-09 14:06 UTC, albertdb commented on documentation/azure-devops/setup-package-pipeline.asciidoc
> +===== AWS
```suggestion
===== AWS ECR

```

2022-06-09 14:07 UTC, albertdb commented on documentation/azure-devops/setup-package-pipeline.asciidoc
> +
```suggestion
```

2022-06-09 14:07 UTC, albertdb commented on documentation/azure-devops/setup-package-pipeline.asciidoc
> +
```suggestion
```

2022-06-23 15:49 UTC, albertdb approved these changes

2022-06-23 15:51 UTC, merged