refactored package pipeline to have generic and language specific part
devonfw/hangar pull request #92
Opened 2022-05-09 08:11 UTC by zichriste

2022-05-09 08:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw/hangar?pullRequest=92) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/devonfw/hangar?pullRequest=92) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw/hangar?pullRequest=92) it.</sub>

2022-05-09 09:52 UTC, zichriste commented
Added .shellcheck.rc file to handle external file sources.
Shellcheck in language specific package scripts required this to integrate package-common script.
Not entirely sure, however, if unexceptional acceptance of external files brings security issues?

2022-05-11 08:20 UTC, patricpoba commented
@zichriste  @albertdb 
[ FYI ]
This pull request is related to [#76](https://github.com/devonfw/hangar/pull/76).  If this pull request gets merged before ([#76](https://github.com/devonfw/hangar/pull/76)) then  some changes would have to be made on [#76](https://github.com/devonfw/hangar/pull/76) and vice versa.

2022-05-18 10:54 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/package/package-pipeline.cfg
> +    cp "${hangarPath}/${templatesPath}/${generic}-${scriptFile}" "${localDirectory}/${scriptFilePath}/${generic}-${scriptFile}"
this line tries to copy the file that is called "generic-package.sh" but it does not exists, I guess this should be the file package-common.sh ?

in that case or the file name needs to be change or this line needs to be change

2022-05-18 11:39 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/package/package-pipeline.cfg
> +    cp "${hangarPath}/${templatesPath}/${generic}-${scriptFile}" "${localDirectory}/${scriptFilePath}/${generic}-${scriptFile}"
I see that in the node and quarkus package sh it is package-common that is used so it also needs to be taken into consideration

2022-05-18 14:46 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +SCRIPT_PATH="./package-common.sh"
to change the current directory, see the documentation for the bash@3 task of azure (if you did not choose the solution to change the SCRIPT_PATH var)

2022-05-18 15:28 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/package/quarkus-package.sh
> +source "$SCRIPT_PATH" "$@" -q "$tag"
be careful in the $@ there is still the -t flag

2022-05-19 07:39 UTC, zichriste commented on scripts/pipelines/azure-devops/templates/package/quarkus-package.sh
> +        *) echo "flag ${flag} not specified"
> I see that the flags has been modified but the package-pipeline.yml.template has not been modified in this PR so issue will occured with the flag definition

The quarkus-package script calls the package-common script, which still contains the flag definitions included in the package-pipeline.yml.template. Is this still an issue? Do I need to include all flags in the language specific scripts, even if they're not used in there?

2022-05-19 07:42 UTC, zichriste commented on scripts/pipelines/azure-devops/templates/package/quarkus-package.sh
> +source "$SCRIPT_PATH" "$@" -q "$tag"
> be careful in the $@ there is still the -t flag

Is this going to be a problem in the long run? Is there a clean way to extract the -t tag? Does this mean I have to explicitly list all tags except for -t?
Or do I have to add the -t tag back into package-common.sh?

2022-05-19 13:35 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/package/quarkus-package.sh
> +        *) echo "flag ${flag} not specified"
yes it is an issue because in the line of while getopts of the package-common.sh, you don't define the "t:" flag, so when the function will see the -t flag it will exit the while getopts loop and the others arguments won't be treated.

A simpler solution is to have two tags into the quarkus-package.sh  (same for the node-package.sh)

the t flag as it already exists and another one (for example -a) that will contains all the others flag that you need for the package-common.sh, like this you will have a variable with the flagsthat you needs only

2022-05-19 13:42 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +SCRIPT_PATH="./templates/package/package-common.sh"
this is the path inside the repo where the package pipeline will be executed that needs to be set, not the path inside the hangar repo

2022-05-23 08:36 UTC, zichriste commented on scripts/pipelines/azure-devops/templates/package/quarkus-package.sh
> +        *) echo "flag ${flag} not specified"
I readded all flags to the language specific scripts, since they all would spam the console with unnecessary warnings. If there is a cleaner way to do this, please let me know.

I also filtered the -t tag and argument from the arguments, which are passed to the package-common.sh.

Thank you for the clarification!

2022-05-23 08:41 UTC, zichriste commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +SCRIPT_PATH="./templates/package/package-common.sh"
I changed the path to the relative path from the node/quarkus project source folder.
This however leads to the sonatype-bot not being able to find the script in this path and throwing an error.

Is it legitimate to ignore this warning by setting an exception, since it will not be possible to find this file as long as I'm not in the future project repo?

2022-06-02 09:27 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +SCRIPT_PATH="./templates/package/package-common.sh"
Yes this is because the bot is trying to find the script inside the curent repo (so hangar repo) but when the pipeline will be executing the script it will be another path

You can ignore the warning indeed

2022-06-02 09:28 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +source "$SCRIPT_PATH" "${args[@]}" -q "$tag"
(you can ignor this warning indeed)

2022-06-02 09:29 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/package/quarkus-package.sh
> +source "$SCRIPT_PATH" "${args[@]}" -q "$tag"
same than the other comment

2022-06-02 11:08 UTC, zichriste commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +source "$SCRIPT_PATH" "${args[@]}" -q "$tag"
@sonatype-lift ignore

2022-06-02 11:08 UTC, zichriste commented on scripts/pipelines/azure-devops/templates/package/quarkus-package.sh
> +source "$SCRIPT_PATH" "${args[@]}" -q "$tag"
@sonatype-lift ignore

2022-06-02 12:02 UTC, ultymatom requested changes
The definition of argument is a bit tricky, let's have a teams call this afternoon to fix it and to explain it better

2022-06-02 12:02 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/package/quarkus-package.sh
> +        f) ;; c) ;; u) ;; p) ;; r) ;; i) ;; b) ;; a) ;; s) ;; l) ;;
```suggestion
        f) dockerFile=${OPTARG};;
        c) context=${OPTARG};;
        u) username=${OPTARG};;
        p) password=${OPTARG};;
        r) registry=${OPTARG};;
        i) imageName=${OPTARG};;
        b) branch=${OPTARG};;
        a) aws_access_key=${OPTARG};;
        s) aws_secret_access_key=${OPTARG};;
        l) region=${OPTARG};;
        t) pomPath=${OPTARG};;
```
see comment for the node package script

this solution finally does not work (sorry for that)
better define the variable in the parent script than in the common that is called inside

2022-06-02 13:49 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +done
With the new solution this part is not needed anymore
```suggestion
```

2022-06-02 13:51 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/package/quarkus-package.sh
> +filter="-t"
```suggestion
```
with new solution, not needed

2022-06-02 13:52 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/package/quarkus-package.sh
> +done
with new solution not needed 
```suggestion
```

2022-06-02 13:52 UTC, ultymatom commented on scripts/pipelines/azure-devops/templates/package/quarkus-package.sh
> +source "$SCRIPT_PATH" "${args[@]}" -q "$tag"
```suggestion
source "$SCRIPT_PATH" -q "$tag"
```

2022-06-09 13:59 UTC, albertdb commented
@zichriste Any progress on this?

2022-06-13 06:53 UTC, zichriste commented
> @zichriste Any progress on this?

The call on the suggested solution is still pending, since I have questions about this as well.
I'll try to wrap this up as quickly as possible.

2022-06-20 09:21 UTC, zichriste commented on scripts/pipelines/azure-devops/templates/package/quarkus-package.sh
>          a) aws_access_key=${OPTARG};;
@sonatype-lift ignore

2022-06-20 09:21 UTC, zichriste commented on scripts/pipelines/azure-devops/templates/package/quarkus-package.sh
>          l) region=${OPTARG};;
@sonatype-lift ignore

2022-06-20 09:21 UTC, zichriste commented on scripts/pipelines/azure-devops/templates/package/package-common.sh
> +branch_short=$(echo "$branch" | awk -F '/' '{ print $NF }')
@sonatype-lift ignore

2022-06-20 09:22 UTC, zichriste commented on scripts/pipelines/azure-devops/templates/package/package-common.sh
> +echo "docker build -f $dockerFile -t $imageName:$tag_completed $context"
@sonatype-lift ignore

2022-06-20 09:22 UTC, zichriste commented on scripts/pipelines/azure-devops/templates/package/package-common.sh
> +if test -z "$aws_access_key"
@sonatype-lift ignore

2022-06-20 09:22 UTC, zichriste commented on scripts/pipelines/azure-devops/templates/package/package-common.sh
> +echo "docker build -f $dockerFile -t $imageName:$tag_completed $context"
@sonatype-lift ignore

2022-06-20 09:22 UTC, zichriste commented on scripts/pipelines/azure-devops/templates/package/package-common.sh
> +    echo "docker login -u=**** -p=**** $registry"
@sonatype-lift ignore

2022-06-20 09:22 UTC, zichriste commented on scripts/pipelines/azure-devops/templates/package/package-common.sh
> +    docker login -u="$username" -p="$password" "$registry"
@sonatype-lift ignore

2022-06-20 09:22 UTC, zichriste commented on scripts/pipelines/azure-devops/templates/package/package-common.sh
> +    docker login -u="$username" -p="$password" "$registry"
@sonatype-lift ignore

2022-06-20 09:22 UTC, zichriste commented on scripts/pipelines/azure-devops/templates/package/package-common.sh
> +    aws configure set aws_secret_access_key "$aws_secret_access_key"
@sonatype-lift ignore

2022-06-20 09:23 UTC, zichriste commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +        f) dockerFile=${OPTARG};;
@sonatype-lift ignore

2022-06-20 09:23 UTC, zichriste commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +        p) password=${OPTARG};;
@sonatype-lift ignore

2022-06-20 09:23 UTC, zichriste commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +        i) imageName=${OPTARG};;
@sonatype-lift ignoreall

2022-06-20 09:23 UTC, zichriste commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +        u) username=${OPTARG};;
@sonatype-lift ignoreall

2022-06-20 09:24 UTC, zichriste commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +        r) registry=${OPTARG};;
@sonatype-lift ignoreall

2022-06-20 09:24 UTC, zichriste commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +        b) branch=${OPTARG};;
@sonatype-lift ignoreall

2022-06-20 09:24 UTC, zichriste commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +        s) aws_secret_access_key=${OPTARG};;
@sonatype-lift ignoreall

2022-06-20 09:24 UTC, zichriste commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +        a) aws_access_key=${OPTARG};;
@sonatype-lift ignore

2022-06-20 09:24 UTC, zichriste commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +        l) region=${OPTARG};;
@sonatype-lift ignore

2022-06-20 09:55 UTC, zichriste commented
I tested the pipeline in Azure though the quarkus project, though I skipped the quality pipeline to make testing the package pipeline easier.
![Pipeline Test](https://user-images.githubusercontent.com/103071518/174576570-a62cda34-a7cc-4972-8e75-3457f2b1d837.png)

With this I made all suggested changes to the scripts, though I'm somehow not able to resolve the last pending request.

2022-06-22 09:24 UTC, zichriste commented on scripts/pipelines/azure-devops/templates/package/node-package.sh
> +tag=$(grep version "${packagePath}" | sed 's/.*"version": "\(.*\)".*/\1/')
Seems like my colleagues recently discovered this issue as well.
Patrick implemented and is refining his solution in [this ticket](https://github.com/devonfw/hangar/pull/76).

2022-06-23 11:41 UTC, albertdb commented
Closed in favor of (unexpected) solution part of https://github.com/devonfw/hangar/pull/76

2022-06-23 11:41 UTC, closed without merging